### ISSUE TITLE
Jump back from definition

### ISSUE THREAD

**Issue by afonso360** [autozimu/LanguageClient-neovim#1]
Hi, great plugin, I have been waiting for a semi functional LSP plugin for vim.

Is there a way to jump back after using `LanguageClient_textDocument_definition`?

It doesen't appear to register anything in the tag stack, so I can't use the usual Ctrl-T

**Comment by autozimu** [comment]
Try CTRL-o

**Comment by balta2ar** [comment]
In my case, CTRL-o is less preferable because I also use mc (midnight commander). If I run nvim in the console of mc and press CTRL-o, instead of jumping back in nvim, mc intercepts it and brings up the file panel. Maybe you could optionally populate tag stack as well?

**Comment by autozimu** [comment]
It is almost impossible to populate the tag stack as the language server only return the definition location, thus the process is not tag based at all. Besides I didn't find any documentation to manipulate the tag stack manually. I might be wrong and would like to implement it if pointed out the right direction.

For your case though, you can try some workaround like
```
nnoremap <Leader>go <C-O>
```
to use the jump stack.

**Comment by balta2ar** [comment]
Maybe this could be helpful:
https://github.com/davidhalter/jedi-vim/blob/master/doc/jedi-vim.txt#L511
https://github.com/davidhalter/jedi-vim/blob/0844b14866beea3308d615a4d3206a836fee106f/jedi_vim.py#L262

**Comment by autozimu** [comment]
Thanks for pointing it out.

To be frank, I don't like the hacky way that much. I will put it in TODO list though.
