### ISSUE TITLE
make LanguageClient#statusLine returning diagnostics summary

### ISSUE THREAD

**Issue by Kotaro7750** [autozimu/LanguageClient-neovim#1005]
## Is your feature request related to a problem? Please describe.

`LanguageClient#statusLine()` sounds like returning error count, but returns `g:LanguageClient_serverStatusMessage` which represent rust's build status. I think this behavior is contradicted to function name and this function should return error count like ALE's similar function `ale#statusline#Count`.

## Describe the solution you'd like

I would like to make `LanguageClient#statusLine` returning current buffer's diagnostics in dictionary type or string type.

Ex1. returns "Error:10 Warning:3 Info:2". Users can set directly to statusline message.
Ex2. returns 
```
{
   Error:10,
   Warning:3,
   info:2
}
```
Users can parse this dict and manually set to their statusline.

## Describe alternatives you've considered

For compatibility reasons, this function might as well stay that way. However, I think that functions with features such as  mentioned above would be beneficial to many users, so new function is still needed.

## Additional context

If you'd like, I will implement and make a pull request.

**Comment by autozimu** [comment]
Make sense.

For backwards compatibility, I'd suggest create a new function and deprecate the original one.

**Comment by Kotaro7750** [comment]
Thank you, I'll try it.
