### ISSUE TITLE
Diagnostic signs not cleared from gutter after fixing all errors

### ISSUE THREAD

**Issue by theimpostor** [autozimu/LanguageClient-neovim#1008]
## Describe the bug

The gutter signs for diagnostic errors are not cleared after the error is fixed and the file is saved for a simple project.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-91328-t7qw5t/neovim-0.4.3/build/config -I/tmp/neovim-20191107-91328-t7qw5t/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-91328-t7qw5t/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20191107-91328-t7qw5t/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-91328-t7qw5t/neovim-0.4.3/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- This plugin version (`git rev-parse --short HEAD`):
`ce7e2c8`
- This plugin's binary version (`bin/languageclient --version`):
`languageclient 0.1.156 90e49e587fc700c81cd21529e773b7f863dfc958`
- Minimal vimrc content :
https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim
- Language server link and version:
`rls 1.41.0 (b27e117 2020-01-13)`

## To Reproduce

- Create/Fetch example project ...
Running the sample code from rust lang book: https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html
`cargo new variables`
- Start vim, `nvim -u min-vimrc.vim src/main.rs`
- Fix the error by adding `mut` before `x` on line 2 and save
- See errors go away but diagnostic 'x' in gutter remains

## Expected behavior

'x' in gutter should clear after error is fixed.

## Screenshots

![Apr-09-2020 10-39-05](https://user-images.githubusercontent.com/1310766/78913266-60e6d600-7a4e-11ea-89fb-d3ef573d3147.gif)

## Additional context

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/4457189/LanguageClient.log)
LanguageServer.log is empty.

**Comment by autozimu** [comment]
Sorry, but I cannot reproduce this locally. I also checked the log and this plugin fed rls with correct updates notification.Not sure why rls still returns those 3 errors.

Can you please try out https://github.com/rust-analyzer/rust-analyzer?

**Comment by theimpostor** [comment]
With `rls` the issue appears to be intermittent - maybe depending on how quickly I type `mut` the signs will clear. So perhaps there is some timing issue.

I tried out `rust-analyzer`. I got different results but there appear to still be some signs left over.

![rep](https://user-images.githubusercontent.com/1310766/79237979-69ffea80-7e34-11ea-92eb-e8b6699443d4.gif)

```
~/projects/variables rust-analyzer --version
rust-analyzer c388130
```

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/4475939/LanguageClient.log)
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/4475942/LanguageServer.log)

**Comment by autozimu** [comment]
Thanks for reporting.

It seems the root cause is that for some reason FileType autocmd was triggered twice and results in the same sign being placed twice. While for cleaning, it only deletes the sign for once.
