### ISSUE TITLE
Bad error message, reporting the wrong problem

### ISSUE THREAD

**Issue by ranfdev** [autozimu/LanguageClient-neovim#1011]
In the install.sh file, you can find this code

```bash
download() {
    echo "Downloading bin/${name} ${version}..."
    url=https://github.com/autozimu/LanguageClient-neovim/releases/download/$version/${1}
    if (try_curl "$url" || try_wget "$url"); then
        chmod a+x bin/$name
        return
    else
        try_build || echo "Prebuilt binary might not be ready yet. Please check minutes later."
    fi
}
```

While i was trying to install this, i got the message "Prebuilt binary might not be ready yet. Please check minutes later.". I waited for some time. Then i tried again. Same problem.

The installer wasn't working because i don't have curl, wget or cargo. So there's no way to download this. I could keep waiting forever, but nothing would change...

After checking if curl and wget are present, you should print a message like "Can't find curl or wget. Falling back to cargo". And then if cargo is not found: "Can't find cargo. Aborting installation".

At least i know i can try to do something, and not just "wait some minutes".

This is a little thing, but can be really frustrating. I like this project and i hope this bug report will make it even better.

**Comment by autozimu** [comment]
Makes perfect sense. Thanks for reporting.

**Comment by autozimu** [comment]
Resolved in https://github.com/autozimu/LanguageClient-neovim/commit/f9c2ef50be1cf448cdca8e0a7858ad929520cc05

Feel free to follow up if there is any further suggestion.
