### ISSUE TITLE
Redudant parenthesis with Rust Analyzer

### ISSUE THREAD

**Issue by ANtlord** [autozimu/LanguageClient-neovim#1012]
- Did you upgrade to latest plugin version?
Yes, I did
- Did you upgrade to/compile latest binary? Run shell command
0.1.156 cf43a9feffeb479821dd3c6b6724ec7119c84bfa
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
  - OK: binary found: ~/.local/share/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.156 cf43a9feffeb479821dd3c6b6724ec7119c84bfa
  - INFO: Floating window is not supported. Preview window will be used for hover
```
- Did you check [troubleshooting]?
[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting
Yes, I did

## Describe the bug

I use LanguageClient for Rust development. I switched from RLS to rust-analyzer. When I pick a method which expects arguments it inserts parenthesis and three points inside them.

## Environment

- neovim version 
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-Bljd1N/neovim-0.3.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-Bljd1N/neovim-0.3.8/build/config -I/build/neovim-Bljd1N/neovim-0.3.8/src -I/usr/include -I/build/neovim-Bljd1N/neovim-0.3.8/build/src/nvim/auto -I/build/neovim-Bljd1N/neovim-0.3.8/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- This plugin version (`git rev-parse --short HEAD`): `0.1.156 cf43a9feffeb479821dd3c6b6724ec7119c84bfa`
- This plugin's binary version (`bin/languageclient --version`): `0.1.156 cf43a9feffeb479821dd3c6b6724ec7119c84bfa`
- Minimal vimrc content: [min-vimrc.vim](https://github.com/ANtlord/langclient-test/blob/master/min-vimrc.nvim):
```
set termguicolors

call plug#begin('~/.local/share/nvim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
			\ 'branch': 'next',
			\ 'do': 'bash install.sh',
			\ }
Plug 'https://github.com/cocopon/iceberg.vim/'

Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
call plug#end()
colorscheme iceberg
let g:LanguageClient_serverCommands = {
			\ 'rust': ['rust-analyzer'],
			\ }
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
let g:LanguageClient_useVirtualText = 'No'
```
- Language server link and version:
https://github.com/rust-analyzer/rust-analyzer
Tested with two versions
    Commit: d075f49e6d342737c8eb81bd5448503bdc33bd79 (Release 2020-04-13)
    Commit: 7a59cd49ff2bb47fa0844fcf5f1ec44f32523b1b

## To Reproduce

- Fetch example project https://github.com/ANtlord/langclient-test
- Start vim, `nvim -u min-vimrc.vim`
- Insert `Ok` in the `main` function

## Current behavior

It inserts `Ok(…)`

## Expected behavior

It inserts `Ok`

## Screenshots

![Screenshot from 2020-04-18 22-54-41](https://user-images.githubusercontent.com/2972483/79669978-3fad8480-81c8-11ea-9924-7c3e7a4cb6d7.png)

**Comment by jiahaowu** [comment]
I also encountered this issue, which requires me to delete twice (  "...)" two redundant symbols) for each function completion that has arguments.

**Comment by ANtlord** [comment]
@jiahaowu did you try the new version of Rust Analyzer? Looks like it fixed from that side. At least for me

**Comment by jiahaowu** [comment]
@ANtlord Thanks for letting me know the change on the end of RA.  I tried the new version of RA and the issue is resolved for me.

**Comment by ANtlord** [comment]
Ok, I think it can be closed.
