### ISSUE TITLE
Rust mod auto-completion not working

### ISSUE THREAD

**Issue by xiaopengli89** [autozimu/LanguageClient-neovim#1014]
/
foo.rs
   mod.rs

in file `mod.rs`
```rust
mod foo; // auto-completion not working here
```

**Comment by pickfire** [comment]
Are you using rust-analyzer? What is your LanguageClient-neovim version? Or is this even supported in the language server?

**Comment by xiaopengli89** [comment]
Yeah,  I'm using rust-analyzer. The language server probably doesn't support this feature.
