### ISSUE TITLE
Code actions for ranges

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#1016]
## Is your feature request related to a problem? Please describe.

The code action request supports a range, however currently as far as I can tell LanguageClient-neovim can only send code action requests where the range is set to the current cursor position, and not where the range is set according to the whole current selection.

## Describe the solution you'd like

Code action sends selection range properly.

## Additional context

An example range code action is this introduce variable from rust-analyzer: https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/assists.md#introduce_variable

**Comment by runiq** [comment]
Triage: This should have been closed by #1022, no?

**Comment by martskins** [comment]
Yep, it will be closed when it gets merged to branch `next`.

**Comment by runiq** [comment]
Right, sorry, I forgot.

**Comment by martskins** [comment]
Closing this one, as #1022 is now merged in `next`.
