### ISSUE TITLE
Event on Quickfix changes

### ISSUE THREAD

**Issue by jan-xyz** [autozimu/LanguageClient-neovim#1017]
## Is your feature request related to a problem? Please describe.

I would like to open the Quickfix list whenever a new entry is added or something changes. Right now I have set it to `autocmd BufWritePost * :cw` which is already a great help. However, I would like to also get diagnostics in the list even if I don't safe.

## Describe the solution you'd like

An autocmd event that gets triggered whenever something in the Quickfix list gets added or removed.

## Describe alternatives you've considered

I cannot think of an alternative. Maybe this is also too much and it's better to only do it on safe.

**Comment by martskins** [comment]
You should be able to do this with the event `LanguageClientDiagnosticsChanged`.

So `autocmd User LanguageClientDiagnosticsChanged :cw` is what I think you're looking for.
