### ISSUE TITLE
Make `explainErrorAtPoint()` behave similar to `textDocument_hover()`

### ISSUE THREAD

**Issue by runiq** [autozimu/LanguageClient-neovim#1025]
## Is your feature request related to a problem? Please describe.

With Rust, `explainErrorAtPoint()` is amazingly useful for viewing error messages without having to compile my sources and losing focus by switching to another terminal window. However, Rust's error messages can get surprisingly long.

## Describe the solution you'd like

The `textDocument_hover()` function has this amazing functionality to switch *into* the floating window on a second call. It would be awesome if `explainErrorAtPoint()` had that as well.

**Comment by martskins** [comment]
I know it's not exactly what you're looking for but you should be able to move into it by pressing `<c-w><c-w>`.

**Comment by martskins** [comment]
@runiq Just opened #1134 to add this feature

**Comment by martskins** [comment]
Closing via #1134
