### ISSUE TITLE
can't jump to the method implementation when working with clangd

### ISSUE THREAD

**Issue by framlog** [autozimu/LanguageClient-neovim#1035]
## Describe the bug

Clangd returns "method not found" when I try to jump to a function's implementation.
logs are here:
```
V[09:15:40.485] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/implementation","params":{"bufnr":1,"filename":"/root/shareless/main.cc","gotoCmd":null,"handle":true,"languageId":"cpp","method":"textDocument/implementation","position":{"character":46,"line":25},"textDocument":{"uri":"file:///root/shareless/main.cc"}}}

I[09:15:40.485] <-- textDocument/implementation(3)
I[09:15:40.485] --> reply:textDocument/implementation(3) 0 ms, error: -32601: method not found
V[09:15:40.485] >>> {"error":{"code":-32601,"message":"method not found"},"id":3,"jsonrpc":"2.0"}
```
No idea on whether it's caused by clangd or this plugin.

## Environment
sys: fedora
neovim: 0.3.8
plugin version: 0.1.157
clangd: 10.0.0
g++: 8

## To Reproduce

Saying that we have a `test.cc`:
```
#include <iostream>

void foo() {
        std::cout << "A" << std::endl;
}

int main() {
        foo();
        return 0;
}
```
And the `compile_commands.json`'s content is the following:
```
[
{
  "directory": "/root/",
  "command": "/usr/bin/c++ -I/usr/include/clang/10.0.0/include -I/usr/include/p11-kit-1 -std=gnu++17  -o test.cc.o -c test.cc",
  "file": "/root/test.cc"
}
]
```
Then, Moving the cursor to `foo()` and calling `languageClient_textDocument_implementation()` will get an error.

**Comment by martskins** [comment]
clangd does not seem to implement `textDocument/implementation`. Ccls apparently implements it, so I suggest you either try that server out or open an issue in clangd's repo to request support for this.
