### ISSUE TITLE
Code actions broken on newest rust-analyzer

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#1037]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. Yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes
- Did you check [troubleshooting]? Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

Starting from [2020-05-25](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-25), rust-analyzer returns no code actions to LanguageClient-neovim.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): v0.4.3
- This plugin version (`git rev-parse --short HEAD`): 7c741d0
- This plugin's binary version (`bin/languageclient --version`): 0.1.156
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rust-analyzer'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```
- Language server link and version: https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-05-25/rust-analyzer-linux

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- `cargo new temp`
- `nvim -u min-vimrc.vim temp/src/main.rs`
- `:call LanguageClient_textDocument_codeAction()`

## Current behavior

Code actions shown on [2020-05-18](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-18) but not on [2020-05-25](https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-05-25) or nightly.

## Expected behavior

Code actions shown.

## Screenshots

![image](https://user-images.githubusercontent.com/1794388/83036592-78504180-a043-11ea-9606-a97563956fc4.png)

## Additional context

Log files for calling code action on 2020-05-18 and 2020-05-25:
[LanguageClient-old.log](https://github.com/autozimu/LanguageClient-neovim/files/4689521/LanguageClient-old.log)
[LanguageClient-new.log](https://github.com/autozimu/LanguageClient-neovim/files/4689520/LanguageClient-new.log)

**Comment by martskins** [comment]
Possibly related to the changes introduced here: https://github.com/rust-analyzer/rust-analyzer/pull/4494

**Comment by YaLTeR** [comment]
I'm looking into this, I think it's just that LanguageClient-neovim doesn't advertise code action support.

**Comment by TheZoq2** [comment]
I *think* I tested this fix by switching my branch in `vim-plug` to `dev` and rerunning plugin update. I sitll experience the same issue (0/0) actions supported. Checking out R-A 2020-05-18 works fine

**Comment by martskins** [comment]
@TheZoq2 I assume you have `"bash ./install.sh"` as a post install step there? Try changing `"bash ./install.sh"` to `"make release"`, so it rebuilds from source instead of downloading the latest released binary (which is behind dev).

**Comment by TheZoq2** [comment]
Thanks. Adding `make release` to the vimrc didn't work, but going into the plugin folder and manually running it seems to have done the trick :)

**Comment by martskins** [comment]
@YaLTeR I think your fix for this is already in `next`, so I'll close this one, but feel free to re-open if this is still an issue.
