### ISSUE TITLE
[Suggestion] support SortText field on CompletionItem

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#104]
Strangely, I cannot make language client work if I add `sorted` function call in `handleCompletionResult`.

**Comment by autozimu** [comment]
Could you specify what language server are you using for this and the modification you made?

**Comment by HerringtonDarkholme** [comment]
I'm using https://github.com/vuejs/vetur/tree/master/server.

More specifically, [this field](https://github.com/vuejs/vetur/blob/master/server/src/modes/template/services/htmlCompletion.ts#L61)

https://github.com/autozimu/LanguageClient-neovim/blob/96de427a3e2c05a98db9d622fb53020f8b5f294c/rplugin/python3/deoplete/sources/LanguageClientSource.py#L39

I changed 

`self.__results[contextid] = items`

to 

`self.__results[contextid] = sorted(item, key=lambda t: t.get('sortText'))`

**Comment by autozimu** [comment]
in this case, items at line 39 is an object, not a list.

You can check the value using logger.

**Comment by HerringtonDarkholme** [comment]
Why close this?
This issue isn't solved.
