### ISSUE TITLE
Issue with semantic highlighting

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#1040]
Hi, I have configured my Language-client neovim to use clangd and semantic highlighting as follows:

``` vim
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
\ 'cpp': ['clangd'],
\ }

let g:LanguageClient_semanticHighlightMaps['cpp'] = {
\ 'entity.name.namespace.cpp': 'CppNameSpace',
\ 'variable.other.field.cpp': 'CppMemberVariable',
\ 'variable.other.enummember.cpp': 'EnumConstant',
\ 'entity.name.function...cpp': 'Function',
\ 'entity.name.type...cpp': 'Type',
\ }

hi! CppNamespace ctermfg=Yellow guifg=#BBBB00 cterm=none gui=none
hi! CppMemberVariable ctermfg=White guifg=White
```

And although the plugin appears to be working in general, I get the error "E121: Undefined variable: g:LanguageClient_semanticHighlightMaps" when I try to use the LanguageClient_semanticHighlightMaps.

Am i missing anything?

thanks.

**Comment by martskins** [comment]
It seems like by the time that config is loaded, the variable is not defined, so it causes that issue, but you can easily get around that by just declaring it before. Try adding `let g:LanguageClient_semanticHighlightMaps = {}` before your `let g:LanguageClient_semanticHighlightMaps['cpp']` line.

**Comment by ghost** [comment]
Hi,  thanks a lot, adding let g:LanguageClient_semanticHighlightMaps = {} fixed the issue.

However I to use LanguageClient_semanticHighlightMaps I found that  I need to define it using the '^' symbol like so:

```vim
let g:LanguageClient_semanticHighlightMaps['cpp'] = {
      \ '^entity.name.function.cpp': 'Function',
      \ '^entity.name.function.method.cpp': 'Function',
      \ '^entity.name.function.preprocessor.cpp': 'PreProc',
      \ '^entity.name.namespace.cpp': 'Type',
      \ '^entity.name.type.class.cpp': 'Type',
      \ '^entity.name.type.enum.cpp': 'Type',
      \ '^entity.name.type.template.cpp': 'Type',
      \ '^meta.disabled': 'Comment',
      \ '^variable.other.cpp': 'Variable',
      \ '^variable.other.enummember.cpp': 'Constant',
      \ '^variable.other.field.cpp': 'Variable',
      \ }
```

Since the original definition doesn't work.

Thanks again
