### ISSUE TITLE
Install.sh downloads a unuseable binary on aarch64 musl systems

### ISSUE THREAD

**Issue by ArenM** [autozimu/LanguageClient-neovim#1044]
## Describe the bug

When install.sh in run on a aarch64 system with musl instead of glibc, such as alpine, it downloads a binary that is linked against glibc which doesn't run.

## Environment

- neovim version: NVIM v0.4.3
- This plugin version (`git rev-parse --short HEAD`): 4b35f5d6859ab3d42546192cbede9add59a7435a
- This plugin's binary version (`bin/languageclient --version`): NA, doesn't run
- Minimal vimrc content: `empty`

## To Reproduce

- Run a aarch64 + musl system, this is the hard part, possibly qemu + alpine?
- Clone `next` branch
- run `install.sh`
- run `$ ./bin/languageclient`
- See the error

## Current behavior

The languageclient binary installed by install.sh doesn't run, when run in a shell it returns `no such file or directory: ./languageclient`, which seems to be propagated from
```
$ ldd languageclient
	/lib/ld-linux-aarch64.so.1 (0xffffb342b000)
	libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffffb342b000)
	libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffffb342b000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffffb2fe9000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffffb342b000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by languageclient)
Error relocating languageclient: __snprintf_chk: symbol not found
Error relocating languageclient: __res_init: symbol not found
```

## Expected behavior

`languageclient` binary starts and does something

**Comment by autozimu** [comment]
This project is relying on https://github.com/japaric/rust-cross cross compiling to create prebuilt binaries.

Unfortunately, only `aarch64-unknown-linux-gnu` is supported by rust-cross. Binaries produced this way would require libc to be present.

Basically, there are two workarounds,
1. Install glibc
2. build this plugin yourself, i.e., replace `./install.sh` post install action with `make release`.

**Comment by ArenM** [comment]
`install.sh` looks like it's intended to run `make release` (in an ideal world) if there isn't a binary version, right? If so would a check such as `uname -o | grep -i -q gnu`, or perhaps checking for a file matching `/lib/ld-linux-$(uname -m | sed 's/_/-/g').so*` make sense?

Also the `rust-cross` you linked to is a cross compiling tutorial, I did you mean this one https://github.com/japaric/cross? If that's the case it does support aarch64-unknown-linux-musl see https://github.com/rust-embedded/cross#supported-targets.

I'd be happy to open a PR with either of these solutions if they make sense.

**Comment by autozimu** [comment]
Ahh, you're right. I was looking at the slighted outdated tutorial.

In that case, we should be able to just switch aarch64 build from gnu to musl.
https://github.com/autozimu/LanguageClient-neovim/blob/4b35f5d6859ab3d42546192cbede9add59a7435a/.travis.yml#L17

PR is always wecome! :)
