### ISSUE TITLE
Unusual completion description

### ISSUE THREAD

**Issue by vivoconunxino** [autozimu/LanguageClient-neovim#105]
I'm getting the return type of the function instead of the description or the method signature (with params). Is it configurable or anything? I don't know why does it happen, all the screenshots i've seen look better than min.
I'm using PhpLanguage Server, nvim-completion-manager and this plugin. Sorry if LanguageClient-neovim isn't the source of this problem.

<a href="https://ibb.co/fzwTz5"><img src="https://preview.ibb.co/dRMve5/Screenshot_20170822_100457.png" alt="Screenshot_20170822_100457" border="0"></a><br /><a target='_blank' href='https://es.imgbb.com/'>programa para compartir fotos</a><br />

**Comment by DeltaEvo** [comment]
LanguageClient use detail field from the Language Server to show info on the menu, PHP Language Server fill the detail field with the return type https://github.com/felixfbecker/php-language-server/blob/35f33c8c91222b8409006cc68738e4000e33a4a3/src/CompletionProvider.php#L185
Full signature support seems to be for the moment WIP https://github.com/felixfbecker/php-language-server/pull/438

The documentation is stored in a info field https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L48
This can be used by other plugins like https://github.com/Shougo/echodoc.vim to show documentation

**Comment by vivoconunxino** [comment]
Thanks a lot for the explanation, so, if there were some way to tell echodoc which field is needed the problem would be solved, right?

**Comment by DeltaEvo** [comment]
echodoc show the documentation for the last completion but this do not affect the display of the menu, if you want the full signature in the menu you need to wait https://github.com/felixfbecker/php-language-server/pull/438

**Comment by vivoconunxino** [comment]
Oh ok, thanks

**Comment by autozimu** [comment]
Closing as issue shall go to php language server, as DeltaEvo explained.
