### ISSUE TITLE
rust-analyzer textDocument_rename renames in the wrong position

### ISSUE THREAD

**Issue by TheZoq2** [autozimu/LanguageClient-neovim#1055]
## Describe the bug

When running `:call LanguageClient#textDocument_rename` using rust-analyzer, the replacement happens in the wrong place. For demonstration purposes, here is a gifv of the behaviour

![Peek 2020-06-15 22-37](https://user-images.githubusercontent.com/5312813/84703630-ddb79400-af58-11ea-87fe-6d87a9d90a76.gif)

To me, it looks like the replacement happens where the value would have been before the replacement, i.e. if it renames `abc` to `abc___`, the result is
```
(abc, abc)
(abc__abc___)`
```
or something similar
## Environment

- neovim/vim version (`nvim --version` or `vim --version`):

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- This plugin version (`git rev-parse --short HEAD`):
`4b35f5d`
- This plugin's binary version (`bin/languageclient --version`):
`languageclient 0.1.157`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

Example vimrc with rls replaced with rust-analyzer

```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

" \ 'rust': ['rustup', 'run', 'stable', 'rls'],
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rust-analyzer'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```

- Language server link and version:
rust-analyzer built today: `rust-analyzer f4f5117`

## To Reproduce

- Create an empty project using `cargo init`
- Start vim opening the main file, `nvim -u min-vimrc.vim src/main.rs` ...
- Set the content to
```rust
struct Identifier;

#[derive(Clone, Debug, PartialEq, Serialize)]
pub enum Value {
    IntConst(u64),
    Ident(Identifier),
}

type A = (Value, Value);

struct HasValue {
    a: Value,
}


fn some_fn(some_name: i32) -> (i32, i32) {
    (some_name, some_name)
}
```
- Execute
`:call LanguageClient#textDocument_rename` on `Value` or `some_name`

## Current behavior

The replacement is done incorrectly, replacing things in what looks to be the wrong position

## Expected behavior

Correct renaming

## Screenshots

See gif above

## Additional context

This does not happen in vscode with the official rust-analyzer extension. It
also does not occur with `rls` which looks to be because it does the whole
replacement in one go, whereas RA replaces one occurence at a time, as can be
seen when undoing the change.

**Comment by martskins** [comment]
This is because of how rust-analyzer reports the changes. The textDocument/rename response returns a list of N documents with M changes to be applied to them, rust-analyzer sends back a list of 4 `TextDocumentEdit`s with a single edit in them, whereas other servers send a single `TextDocumentEdit` with N edits in them.

I made a quick comparison of two different servers with a similar rename situation to illustrate the difference:

gopls:
```
[
  TextDocumentEdit { text_document: VersionedTextDocumentIdentifier { uri: "file:///home/martin/go/src/github.com/financiarme/api/cmd/api/main.go", version: Some(0) }, edits: [TextEdit { range: Range { start: Position { line: 21, character: 5 }, end: Position { line: 21, character: 10 } }, new_text: "Val" }, TextEdit { range: Range { start: Position { line: 23, character: 15 }, end: Position { line: 23, character: 20 } }, new_text: "Val" }, TextEdit { range: Range { start: Position { line: 23, character: 26 }, end: Position { line: 23, character: 31 } }, new_text: "Val" }] },
]
```

rust-analyzer:
```
[
  TextDocumentEdit { text_document: VersionedTextDocumentIdentifier { uri: "file:///home/martin/dev/learn/rust/overflow/src/main.rs", version: None }, edits: [TextEdit { range: Range { start: Position { line: 3, character: 9 }, end: Position { line: 3, character: 14 } }, new_text: "Val" }] },
  TextDocumentEdit { text_document: VersionedTextDocumentIdentifier { uri: "file:///home/martin/dev/learn/rust/overflow/src/main.rs", version: None }, edits: [TextEdit { range: Range { start: Position { line: 8, character: 10 }, end: Position { line: 8, character: 15 } }, new_text: "Val" }] },
  TextDocumentEdit { text_document: VersionedTextDocumentIdentifier { uri: "file:///home/martin/dev/learn/rust/overflow/src/main.rs", version: None }, edits: [TextEdit { range: Range { start: Position { line: 8, character: 17 }, end: Position { line: 8, character: 22 } }, new_text: "Val" }] },
  TextDocumentEdit { text_document: VersionedTextDocumentIdentifier { uri: "file:///home/martin/dev/learn/rust/overflow/src/main.rs", version: None }, edits: [TextEdit { range: Range { start: Position { line: 11, character: 7 }, end: Position { line: 11, character: 12 } }, new_text: "Val" }] },
]
```

I know that might be a little hard to look at, but notice that the gopls version only sends one item in the changes array, with more than one change to be applied to a single document. Whereas rust-analyzer sends 4 items, with a single change in each of them.

This doesn't feel right to me, but maybe there's a reason they do it that way, I'll try and find out what that reason could be, if there's a legitimate reason we could group the changes by text_document_uri before applying them, that should be enough to solve this.

This is also the reason why if you undo the rename (with vim, `u`), in the rust-analyzer case you have to undo each occurrence, whereas in the RLS case you only undo once and it rolls back all changes.

**EDIT**: To expand on why I believe this is not correct:

> A TextDocumentEdit describes all changes on a version Si and after they are applied move the document to version Si+1. So the creator of a TextDocumentEdit doesn’t need to sort the array of edits or do any kind of ordering

That's from the LSP specification, applying a TextDocumentEdit essentially changes the version of the document, but the changes we have listed there are all for the same version, so applying them without going back to the server to get the new edits is in my opinion incorrect.

**Comment by Veykril** [comment]
This issue should be fixed in the server now, would be great if you can test this on the next nightly(tomorrow) or stable(next monday) release and report back if its fixed for you 👍

**Comment by martskins** [comment]
Yeah nightly seems to fix this! Thanks to everyone involved in fixing this in rust-analyzer 🙇‍♂️
