### ISSUE TITLE
How to pass option usePlaceholders to gopls ?

### ISSUE THREAD

**Issue by butterflyfish** [autozimu/LanguageClient-neovim#1082]
https://github.com/golang/tools/blob/master/gopls/doc/settings.md

I read LanguageClient-neovim help document, then create .vim/settings.json under project root dir.
```sh
cat .vim/settings.json
{
    "go.usePlaceholders": true
}

```
configuration:
```
let g:LanguageClient_hasSnippetSupport=1
let g:LanguageClient_completionPreferTextEdit=1
let g:LanguageClient_settingsPath=".vim/settings.json"
```

If so, ncm2 can not help complete "(" and function parameter. It works well with Rust at the same environment.

**Comment by martskins** [comment]
You need to drop the `go.` prefix and move all that to an `initializationOptions` key. 

```json
{
  "initializationOptions": {
    "usePlaceholders": true
  }
}
```

Note that you may need to play around with your completion/snippet plugins to have those work correctly, but I just checked and this works as expected.

**Comment by autozimu** [comment]
Closing as I believe the question has already been answered. Feel free to reopen if that's not the case.
