### ISSUE TITLE
Syntax highlighting for hover popup

### ISSUE THREAD

**Issue by rottencandy** [autozimu/LanguageClient-neovim#1085]
## Is your feature request related to a problem? Please describe.

I'm trying to migrate from another plugin. I use LSP only for typescript and after configuring the `typescript-language-server`, noticed that the hover popup window looks a bit off:
![scr1](https://user-images.githubusercontent.com/20013884/89750994-f2914d80-daeb-11ea-8ac9-b2f7d40ed31d.png)
The previous plugin I used(`coc.nvim`) was able to add syntax highlighting to the code section in the popup, this is how it looked:
![scr0](https://user-images.githubusercontent.com/20013884/89751114-6fbcc280-daec-11ea-81e9-ff4c1b623b85.png)

## Describe the solution you'd like

I'd love to know if it would be possible to implement syntax highlighting for hover popups, or if this isn't within the scope of the plugin and may be better off handled elsewhere, please point me in the right direction.

**Comment by martskins** [comment]
Something like `plasticboy/vim-markdown` (with the appropiate config) + `set conceallevel=2` should do it. I'm seeing a weird issue were the syntax doesn't get updated until I move inside the window though, but I'm not sure if that's only me or if it's a common issue.

**Comment by martskins** [comment]
Fixed in #1139

**Comment by carbolymer** [comment]
This markdown rendering never worked for me. I'm on
```
NVIM v0.8.0-dev-nightly-12-g977790746
languageclient 0.1.161
```
Do I need to configure something extra? I've tried installing `plasticboy/vim-markdown` additionally, but no difference.

**Comment by rottencandy** [comment]
Try changing vim-markdown options to trigger formatting
```vim
let g:vim_markdown_frontmatter = 1
let g:vim_markdown_conceal = 1
let g:vim_markdown_conceal_code_blocks = 1
```
You might also want to set `conceallevel` if you haven't already https://github.com/preservim/vim-markdown#syntax-concealing

**Comment by carbolymer** [comment]
@rottencandy awesome, it works in hover now, thanks. I think this should be in some FAQ of the languageclient. But concealing doesn't seem to be working in autocompletion popup from deoplete (at least for urls).
