### ISSUE TITLE
Quickfix content overwritten

### ISSUE THREAD

**Issue by asdf8601** [autozimu/LanguageClient-neovim#1086]
Hi there,

Thank you very much for this awesome plugin. I love it.

## Describe the bug

Here is my issue, when I get the output of a command which is wrote  on a quickfix window, the content will be overwritten by LanguageClient with the linter output after a few seconds.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):

```
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- This plugin version (`git rev-parse --short HEAD`): 

```
$ git rev-parse --short HEAD
0e5c954

```

- This plugin's binary version (`bin/languageclient --version`):

```
$ bin/languageclient --version
languageclient 0.1.158
```

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]:

https://github.com/mmngreco/lsp-neovim-issue/blob/master/init.vim

- Language server link and version:

```
$ pip list | grep language
python-language-server 0.31.9

```

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- Clone project `git clone https://github.com/mmngreco/lsp-neovim-issue`
- Start vim, `nvim -u init.vim`
- Execute `:Grepper` then write `foo` and press enter, open one result of the list.
- See error, after a few seconds the output will disappear.

## Current behavior

the quickfix content (opened by other command) disappears while editing a python script.

## Expected behavior

I'm wondering if t here is a way to control this. I'm not sure what should be the expected behavior but the actual behavior is very annoying. This happens on every quickfix, is not `Grepper` specifically problem.

## Screenshots

![imagen](https://user-images.githubusercontent.com/6231413/90130333-94be6900-dd6a-11ea-8394-191599491dfb.png)
![imagen](https://user-images.githubusercontent.com/6231413/90130354-a0aa2b00-dd6a-11ea-8312-a259ee1f93f1.png)
![imagen](https://user-images.githubusercontent.com/6231413/90130377-a869cf80-dd6a-11ea-942a-24cda79c2aa6.png)
![imagen](https://user-images.githubusercontent.com/6231413/90130394-af90dd80-dd6a-11ea-98bd-5bd5855ba1b0.png)
![imagen](https://user-images.githubusercontent.com/6231413/90130418-b91a4580-dd6a-11ea-8c97-835b11b4bf62.png)

**Comment by rraks** [comment]
I had to fix it by creating a mapping to disable this plugin before executing a command which would populate quick fix.
https://github.com/rraks/configs/blob/b0c8da80ce27daa5a94d894eba8b7c27f2e3cda8/config/nvim/init.vim.old#L165

**Comment by martskins** [comment]
I changed the diagnostics list to `location` instead precisely for this reason. You can do that by adding this to your vimrc:

`let g:LanguageClient_diagnosticsList = 'Location'`

**Comment by asdf8601** [comment]
Thank you both! For now, I prefer the @martskins solution, it's what I'm looking for.
