### ISSUE TITLE
Client commands

### ISSUE THREAD

**Issue by qmmp123** [autozimu/LanguageClient-neovim#1087]
I have a few questions about usage of this plugin

1)How to manual show popup with completion list?
2) How to manual show popup with parameters of function?

**Comment by autozimu** [comment]
To trigger completion manually, see 
https://github.com/vim/vim/blob/37addecc422c3b62a622b371246dc4ef0a2fa157/runtime/doc/insert.txt#L986

There is no way to manually display parameter at the moment. Feel free to create feature request.
