### ISSUE TITLE
php intelephense can't work well

### ISSUE THREAD

**Issue by likelxl** [autozimu/LanguageClient-neovim#1088]
- Did you upgrade to latest plugin version? yes
- Did you upgrade to/compile latest binary? Run shell command yes
  `bin/languageclient --version` to get its version number. 0.1.158
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yes
- Did you check [troubleshooting]? yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug
it can't works on complete,but is works well on diagnostics

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):latest
- This plugin version (`git rev-parse --short HEAD`):latest
- This plugin's binary version (`bin/languageclient --version`):0.1.158
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version:

## Screenshots
![截图录屏_选择区域_20200821235905](https://user-images.githubusercontent.com/12811070/90911569-c3dc7680-e40b-11ea-88f8-9217eed64fbd.png)

![image](https://user-images.githubusercontent.com/12811070/90911451-955e9b80-e40b-11ea-9fb2-a253bee89b10.png)

**Comment by martskins** [comment]
I don't really understand the issue you are having. Could you provide a more detailed explanation of what you expected to see and what you saw instead?

I don't see anything wrong in your screenshots.

**Comment by martskins** [comment]
Closing as stale
