### ISSUE TITLE
Use github wiki to provide some configuration steps for some language servers

### ISSUE THREAD

**Issue by DeltaEvo** [autozimu/LanguageClient-neovim#109]
I think we should use the wiki to provide some configurations and some troubleshooting steps specifics to some language servers

**Comment by autozimu** [comment]
The INSTALL has a small section for troubleshooting, <https://github.com/autozimu/LanguageClient-neovim/blob/master/INSTALL.md#troubleshooting>

But I agree the wiki is a better place for such collaboration work.

One thought though is that the wiki in this project should not overlap with language servers setup instructions, which might become obsolete quite frequently.

**Comment by autozimu** [comment]
Wiki has been there. Anyone can edit/update it.

**Comment by DeltaEvo** [comment]
I can't edit or update it :cry:

**Comment by autozimu** [comment]
Sorry about that. Need to tweak a setting. Should be good now.

**Comment by DeltaEvo** [comment]
Yes, thanks :smile:
