### ISSUE TITLE
data did not match any variant of untagged enum TextDocumentSyncCapability

### ISSUE THREAD

**Issue by filmil** [autozimu/LanguageClient-neovim#1098]
- Did you upgrade to latest plugin version? **Yes.**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. **0.1.158**
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **All green and OK**
- Did you check [troubleshooting]? **Yes**

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

When trying to use LanguageClient with clangd for a custom build of clang 12.0.0 the following error is printed and the completion seems confused:

`[LC] data did not match any variant of untagged enum TextDocumentSyncCapability`

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):

```
╰─>$ nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 #(redacted)
Compiled by (redacted)

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "(redacted)"

Run :checkhealth for more info
```

- This plugin version (`git rev-parse --short HEAD`): **0e5c954**
- This plugin's binary version (`bin/languageclient --version`): **0.1.158**
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): **Does not depend on vimrc**
- Language server link and version:
** Fuchsia clangd version 12.0.0 (https://llvm.googlesource.com/a/llvm-project 7a34dca0f3918ab1c0397e56dd64a3c04164c8b6)**

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

See attached file.  It contains a prettyprinted JSON content that triggered the message.

## Current behavior

The completion gets very confused.

## Expected behavior

The completion should work.

## Screenshots

N/A

## Additional context

N/A

[foo.txt](https://github.com/autozimu/LanguageClient-neovim/files/5329376/foo.txt)

**Comment by filmil** [comment]
Looks like clangd has a type mismatch for `save` (have: bool, should be SaveOptions: https://docs.rs/languageserver-types/0.36.0/src/languageserver_types/lib.rs.html#1024).  Now, neither of the two is part of the LSP specification 3.15 nor 3.16 it seems.

```
...
"textDocumentSync": {                                                                                                                                                                                                                                                           
  "change": 2,                                                                                
  "openClose": true,                                                                          
  "save": true                                                                                
},
```

**Comment by filmil** [comment]
Similar issue here: https://github.com/neovim/neovim/issues/12449
And seems like lsp_types has this fix already: https://sourcegraph.com/github.com/gluon-lang/lsp-types@20d125f4828d97cf17fa31c6a39527df7acc2744/-/blob/src/lib.rs#L1239:10

**Comment by martskins** [comment]
@filmil Try building `LanguageClient-neovim` from source. The version you are running is using `lsp-types` 0.74.2, which doesn't have that fix you found. The dev branch has an unreleased dependecy update (which will be included in the next release of LanguageClient-neovim) which brings `lsp-types` to 0.78, so building from source (`make release`) should do the trick.

**Comment by filmil** [comment]
@martskins Done, and this is fixed.  However, I think a new release of LC may be in order.

**Comment by martskins** [comment]
Indeed. I think we are in decent grounds for a release. Only thing bugging me is a flaky test that sometimes fails and sometimes passes. I'll try to solve that one and issue a release soon.

I'll close your issue meanwhile, but feel free to re-open if anything else comes up.
