### ISSUE TITLE
pluggable language server and auto discover

### ISSUE THREAD

**Issue by roxma** [autozimu/LanguageClient-neovim#11]
I think setup language server manually and then update `g:LanguageClient_serverCommands` is kind of tedious, is there a way to do that automatically?

FYI, I wrote an experimental language server plugin that works with NCM, https://github.com/roxma/nvim-cm-php-language-server, backed by [php-language-server](https://github.com/felixfbecker/php-language-server). The installation is simple:

```
Plug 'roxma/nvim-cm-php-language-server',  {'do': 'composer install && composer run-script parse-stubs'}
```

**Comment by autozimu** [comment]
I agree the current setup process is not streamlined.

The main problem is that, different language have different toolchains and
ecosystems, like python has pypi/pip, js has npm and yarn. It is almost
impossible to cover all cases.

Besides, many language server are still actively developed. Like python's
and js's, they are not available on PyPi or npmjs yet.

I felt it is more appropriate to left the language server installion
process to the  user as he is one most famililar with the lanuage that
needs support, e.g., I don't use ocaml, as plugin author, I don't want to
learn how to setup its dev env, and as plugin user, I don't want to have
ocaml toolchain or language server installed for me automatically.

**Comment by autozimu** [comment]
Also, there might be multiple language server implementation for one language, for example, python. In which case, the current one time manual explicit way of declaration in init.vim is more flexible.

**Comment by roxma** [comment]
I mean, it would still be nice to have an api like `LanguageClient#register_server()`

Then a language server plugin package could register it self, instead of letting the user tweak the definition of global dictionary `g:LanguageClient_serverCommands`, which could be terrible for users like me working on different machines and systems, and may need to handle different installation paths.

A language server plugin could have a small plugin.vim that register itself, and handle the relative path expansion nicely.

```vim
let s:path = globpath(&rtp,'some_server/bin/server')
call LanguageClient#register_server(['some cmd',s:path])
```

Then the install for a vim user could be as easily as:

```vim
Plug 'some_server',  {'do': 'npm, composer install, or whatever'}
```

**Comment by autozimu** [comment]
Ok, I see what you mean. It is definitely possible.
