### ISSUE TITLE
RustFMT

### ISSUE THREAD

**Issue by chrisduerr** [autozimu/LanguageClient-neovim#110]
I've recently seen that the RLS for Rust has support for formatting with RustFMT. Is there currently any plan to make this work?

From what I've seen when looking at the python code it should be pretty simple to extend the LanguageClient and I'd be down to give it a shot thin weekend.

**Comment by autozimu** [comment]
It's already supported by this plugin <https://github.com/autozimu/LanguageClient-neovim/blob/2a34802b4792cf2133feef30322977d054fcca45/doc/LanguageClient.txt#L223-L232>

**Comment by chrisduerr** [comment]
Oh wow I totally derped there. Might be nice to put it into #35 so even blind people like me can see it in action.

**Comment by autozimu** [comment]
Good catch! Will make it when I got some time.
