### ISSUE TITLE
Not handling Windows file:/// URI correctly (specifically file:///C:/path/to/file)

### ISSUE THREAD

**Issue by cormacrelf** [autozimu/LanguageClient-neovim#111]
- neovim version 0.2.0
- Plugin version (git SHA) `2a34802`
- Minimal vimrc ✔️ 
- Content of `:CheckHealth` https://pastebin.com/ratfxwqy
- Content of `~/.local/share/nvim/rplugin.vim`. (actually in appdata\local: https://pastebin.com/pxs2M5MM)
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`.

Here's what happens when you do a go-to-definition for an identifier in the same file using [javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver) on Windows 10.

```
06:29:54 INFO     Begin textDocument/definition
06:29:54 INFO     textDocument/didChange
06:29:54 DEBUG     => {"method":"textDocument/definition","jsonrpc":"2.0","id":1,"params":{"position":{"character":11,"line":39},"textDocument":{"uri":"file:///C:/Users/blah/app.component.ts"}}}
06:30:00 DEBUG     <= {"jsonrpc":"2.0","id":1,"result":[{"uri":"file:///C:/Users/blah/app.component.ts","range":{"start":{"line":60,"character":2},"end":{"line":60,"character":6}}}]}
06:30:00 INFO     End textDocument/definition
06:30:01 DEBUG     <= {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Users/blah/app.component.ts","diagnostics":[]}}
```

As you can see, the JSON RPC response has a URI in it, with the windows path normalized according to the requirements laid out here: https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

However (and this doesn't show up in the logs) it throws this error:

![capture2](https://user-images.githubusercontent.com/378760/29637145-930cc2d6-8896-11e7-9932-d75e293865de.PNG)

The path from the server is `file:///C:/Users/blah/...`. I'm not sure what LanguageClient-neovim is expecting, but it's not prepared for that input. It then takes Neovim to that 'file', which doesn't exist.

**Comment by autozimu** [comment]
I don't have a Windows machine around. Could you provide the file path nvim opened after executing the definition action?

As far as I know, nvim/vim itself have strange behaviour when taking paths on Windows, might be tricky to make it happy.

**Comment by cormacrelf** [comment]
For `file:///C:/path/to/file`, it takes you to `/C:/path/to/file`. Strip the leading slash and you're good, I think.

**Comment by autozimu** [comment]
Please try latest change and see if it works.

**Comment by cormacrelf** [comment]
Perfect. Thanks!
