### ISSUE TITLE
Disable CompleteDone for some language / Enable only for some

### ISSUE THREAD

**Issue by entropitor** [autozimu/LanguageClient-neovim#1135]
- Did you upgrade to latest plugin version? YES
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? YES
- Did you check [troubleshooting]? YES

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

I get the following error when completing an item using Neovim 0.5 builtin LSP and completion-nvim. I still need to install this plugin for https://github.com/ionide/Ionide-vim but that's only for fsharp. I don't want to break my setup for other languages
```
Error detected while processing function LanguageClient#handleCompleteDone:
line    2:
E691: Can only compare List with List
Error detected while processing function LanguageClient#handleCompleteDone:
line    2:
E15: Invalid expression: user_data ==# ''
```

It would be nice if this could be disabled.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): neovim 0.5 HEAD
- This plugin version (`git rev-parse --short HEAD`): d6d6d08

**Comment by martskins** [comment]
Ah I think this was a bad merge. Can you confirm whether you are using the dev branch? I'll push a fix for this asap.

**Comment by martskins** [comment]
Could you provide a log of the server responses? Setting `LanguageClient_loggingLevel` to `DEBUG` should given enough info. Also, a minimal reproducible example would help a lot (including .vimrc please).

And I'm not sure if it will have anything at that point, but if you could paste the output of `:echo v:completed_item` that'd be great!

**Comment by martskins** [comment]
If you feel like trying something out though, I think you won't have this issue in the dev branch, which has unreleased changes. As that branch has a commit that basically disables the autocmds for filetypes that you don't have a configured server for, so handleCompleteDone would be called only for fsharp. If you want to try that out you'll have to build from source though.

**Comment by entropitor** [comment]
Right now, I'm only installing this plugin for fsharp (using vim-plug `for` argument) and then doing the following to disable the CompleteDone
 
```vim
autocmd BufEnter *.fs,*.fsx,*.fsi autocmd! languageClient CompleteDone
```

It works for me but it's a bit annoying

This is `:echo v:completed_item`
```
{'word': 'string', 'menu': 'Microsoft.FSharp.Core.Operators.string', 'user_data': {'lsp': {'complet
ion_item': {'label': 'string', 'commitCharacters': [], 'data': {'FullName': 'Microsoft.FSharp.Core.
Operators.string'}, 'additionalTextEdits': [], 'insertText': 'string', 'kind': 2, 'detail': 'Micros
oft.FSharp.Core.Operators.string'}}}, 'info': ' ', 'kind': 'Method', 'abbr': 'string'}
```

**Comment by martskins** [comment]
Yeah I think this shouldn't be a problem for you in the `dev` branch. If you are happy to try that out it would be great. Otherwise, your fix seems like a reasonable approach until we cut the next release.

**Comment by martskins** [comment]
I'm actually a little surprised about the `v:completed_item` you get. The docs say this

```
All of these except "icase", "equal", "dup" and "empty" must be a string.  If
an item does not meet these requirements then an error message is given and
further items in the list are not used.  You can mix string and Dictionary
items in the returned list.
```

So theoretically `user_data` should be a string, not a dictionary. If it was a string, this wouldn't be a problem for you. So maybe it's worth opening an issue in completion-nvim. I'll see to do that later today.

**Comment by martskins** [comment]
Ok, turns out that that documentation is outdated, `user_data` can now be anything. I just merged a slightly related PR and included a fix for this. So it should work just fine for you in the `dev` branch now.

**Comment by entropitor** [comment]
Seems to work indeed!
