### ISSUE TITLE
invalid value: integer `-2`, expected u64, breaks syntax error report

### ISSUE THREAD

**Issue by sim590** [autozimu/LanguageClient-neovim#1147]
- Did you upgrade to latest plugin version? **Yes**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. **Yes**
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **N/A**
- Did you check [troubleshooting]? **Yes**

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

Error on certain instances of valid code with Haskell files which breaks the syntax error report in Vim:

```
Error: invalid value: integer `-2`, expected u64
```

This happens when editing the following file:

```hs
module Tata (
) where

import System.Random

toto :: [a] -> IO [a]
toto as = do
  let (before, (a:after)) = splitAt 0 as
  return before
```

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): Vi IMproved 8.2
- This plugin version (`git rev-parse --short HEAD`): d6d6d08
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.160
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): the suggested `min-vimrc.vim` file was used with the following appended:

      let g:LanguageClient_serverCommands = { 'haskell': ['hie-wrapper', '--lsp', '-l', '/tmp/hie-wrapper.log'] }

- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## Steps to Reproduce and current behaviour

1. Create a directory with the [Cabal file][toto.cabal.txt] (attached to this post) and the Haskell code snippet given above.
2. Configure Vim to use the [min-vimrc.vim][] configuration file (with the addition of Haskell configuration as mentioned before).
3. Edit the `Tata.hs` file with Vim.
4. Notice no errors in the file is reported (compile the code by yourself if you want to make sure).
5. Have a look at the LanguageClient log file for the client and notice the following:

        Message: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"Redundant bracket","message":"Redundant bracket\nFound:\n  (before, (a : after))\nWhy not:\n  (before, a : after)\n","range":{"end":{"character":-2,"line":-2},"start":{"character":-2,"line":-2}},"severity":4,"source":"hlint"}],"uri":"file:///tmp/toto/Tata.hs"}}

        Error: invalid value: integer `-2`, expected u64

   The full log file is attached [here][languageclient.log].

While the error by itself doesn't indicate a bad behaviour, notice that when triggering an error by changing the following line:

```hs
toto :: [a] -> IO [a]
```

to for instance:

```hs
oto :: [a] -> IO [a]
```

will show the syntax error on the right. However, if when undoing the change with the `u` key (and saving the file), one can clearly see that the syntax error message doesn't go away on the right no matter how many times we write the file on the disk. Actually, the whole syntax error report is not listed in the location list (or quickfix list, depending on configuration), i.e. the syntax error report is not updated in Vim since the plugin seems to have abandoned to do so even though a syntax warning message was available according to the client log.

```
Message: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"Redundant bracket","message":"Redundant bracket\nFound:\n  (before, (a : after))\nWhy not:\n  (before, a : after)\n","range":{"end":{"character":-2,"line":-2},"start":{"character":-2,"line":-2}},"severity":4,"source":"hlint"}],"uri":"file:///tmp/toto/Tata.hs"}}
```

## Expected behavior

The error message about the invalid integer should not happen and syntax errors should disappear when resolved in the file.

## Additional context

The strange thing is that changing the source file to the following does go around the issue ...

```hs
toto :: [a] -> IO [a]
toto as = do
  let (before, (a)) = splitAt 0 as
  return before
```

It seems like the `:list` part of the expression is not liked by some linter. May be the issue is with the server, but I can't tell.

**EDIT**: Actually, it seems like simply removing the parentheses does the trick... i.e.:

```hs
toto :: [a] -> IO [a]
toto as = do
  let (before, a:after) = splitAt 0 as
  return before
```

[toto.cabal.txt]: https://github.com/autozimu/LanguageClient-neovim/files/5551460/toto.cabal.txt
[languageclient.log]: https://github.com/autozimu/LanguageClient-neovim/files/5551477/languageclient.log

**Comment by martskins** [comment]
I think this may be an issue with the server. The publishDiagnostics notification is sent from the server and the character and line values you get there should be greater or equal to zero, as it doesn't make sense for them to be anything else.

The spec even says that there are no special values like -1 to denote EOL or anything like that.
> Position in a text document expressed as zero-based line and zero-based character offset. A position is between two characters like an ‘insert’ cursor in a editor. Special values like for example -1 to denote the end of a line are not supported.

**Comment by martskins** [comment]
Closing this as it seems to be stale and a server issue. Feel free to re-open if that's not the case.
