### ISSUE TITLE
PEP8 formatting

### ISSUE THREAD

**Issue by purpleP** [autozimu/LanguageClient-neovim#115]
I wanted to add ability to open quickfix window when diagnostics change and close it when there's no errors, but I noticed that you're not following PEP8 (you're using camel case in function names and stuff like that inconsistently). I once done it too coming from java. But then I learned ""When in Rome, do as the Romans do" and now I use camelCase in Haskell and Java, and snake case in python and whatever common rules exists in community.
This doesn't make your code bad, but it's making every pythonista wanted to working on your code wanting to puke =) (you're not a python programmer, right?) 

There are also some refactorings that can be made. Like using list comprehensions instead of creating empty lists and appending to them.

If you would allow me to reformat the code I would gladly help with refactoring, tests and adding new features.

**Comment by autozimu** [comment]
Do you ever notice there is a similar issue open?

Do you ever take look into all the *_test.py files?
