### ISSUE TITLE
Rust: [LC] sending on a disconnected channel

### ISSUE THREAD

**Issue by alopatindev** [autozimu/LanguageClient-neovim#1157]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. Yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes
- Did you check [troubleshooting]? Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

I often get these error messages when trying to use go to definition in a rust project.

## Environment

- neovim version (`nvim --version`): 0.4.4
- This plugin version (`git rev-parse --short HEAD`): d6d6d08
- This plugin's binary version (`bin/languageclient --version`): 0.1.160
- Minimal vimrc content:

```
call plug#begin('~/.config/nvim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
call plug#end()

let g:LanguageClient_serverCommands = {
\ 'rust': ['rust-analyzer'],
\ }
autocmd BufEnter *.rs map <C-\> :tab call LanguageClient#textDocument_definition({'gotoCmd': 'tab drop'})<CR>
```

## To Reproduce

- Open a middle size project, structured as workspace with crates
- Work with it, sometimes use go to definition
- Encounter a big

## Additional context

```
13:10:58 INFO reader-None src/rpcclient.rs:191 <= None {"id": 13, "jsonrpc": "2.0", "method": "languageClient/findLocations", "params": {"bufnr": 6, "handle": true, "languageId": "rust", "gotoCmd": "tab drop", "method": "textDocument/definition", "position": {"character": 11, "line": 105}, "filename": "/some/project/file.rs"}}
13:10:58 INFO unnamed src/language_server_protocol.rs:2259 Begin textDocument/didChange
13:10:58 INFO writer-None src/rpcclient.rs:238 => None {"jsonrpc":"2.0","method":"LSP#text","params":["/some/project/file.rs"],"id":10246}
13:10:58 INFO reader-None src/rpcclient.rs:191 <= None {"id": 10246, "jsonrpc": "2.0", "result": ["some changes"]}
13:10:58 INFO unnamed src/language_server_protocol.rs:2279 Texts equal. Skipping didChange.
13:10:58 INFO unnamed src/language_server_protocol.rs:1363 Begin textDocument/definition
13:10:58 INFO writer-None src/rpcclient.rs:238 => None {"jsonrpc":"2.0","method":"eval","params":["expand('<cword>')"],"id":10247}
13:10:58 INFO reader-None src/rpcclient.rs:191 <= None {"id": 10247, "jsonrpc": "2.0", "result": "SomeIdentifier"}
13:10:58 ERROR unnamed src/rpchandler.rs:27 Error handling message: sending on a disconnected channel

Message: {"jsonrpc":"2.0","method":"languageClient/findLocations","params":{"bufnr":11,"filename":"/some/project/file.rs","gotoCmd":"tab drop","handle":true,"languageId":"rust","method":"textDocument/definition","position":{"character":47,"line":113}},"id":10}

Error: sending on a disconnected channel
13:10:58 INFO writer-None src/rpcclient.rs:238 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"sending on a disconnected channel"},"id":10}
```

rustc 1.48.0 (7eac88abb 2020-11-16)
rust-analyzer cadf0e9

**Comment by martskins** [comment]
Can you share some more of the log? Also, have you tried updating rust-analyzer? I found a similar issue a few days ago but it was a specific commit that was broken and was fixed on the nightly release of the next day.

**Comment by alopatindev** [comment]
Thanks, it seems that updating rust-analyzer to ac30710 2020-11-30 solved the issue for me.
