### ISSUE TITLE
Yank the result of hovering

### ISSUE THREAD

**Issue by roddyyaga** [autozimu/LanguageClient-neovim#1159]
Is there an easy way to yank the result of hovering? I have something hacky that waits until the preview window is open and jumps there but would prefer something more legitimate.

**Comment by martskins** [comment]
The `dev` branch uses specific names for the windows we use, so if you switch to the `dev` branch (have to build from source) you could do something like this:

```
function! YankHover(...)
  let @t = join(getbufline('__LCNHover__', 1, '$'),"\n")
endfunction

nmap <silent> <leader>K :call LanguageClient#textDocument_hover({ 'handle': v:true }, 'YankHover')<CR>
```
Where `@t` is the register t, so you'd paste with `"tp`. You can change that to the unnamed register or whatever you prefer though.

A release is due soon though, so in a few days that should also work in the `next` branch.

**Comment by martskins** [comment]
@roddyyaga I'm assuming this worked for you so I'm closing the issue. Feel free to re-open if it didn't though.
