### ISSUE TITLE
Idea: have option to put hover info into temp buffer

### ISSUE THREAD

**Issue by Alok** [autozimu/LanguageClient-neovim#118]
Sometimes when I'm writing numeric Python code, I run `hover` and get a full buffer worth of output (lots of optional arguments for numpy functions). In that case, it'd be nice if I had the option to put that output into a buffer by default, since vim's mini-pager *sucks* (you can't even search in it).

**Comment by autozimu** [comment]
If you really have this need, you can make your own extension in a few lines.

```py
def customizedHandleHoverResponse():
    # do customized work with response

@nvim.function("CustomizedHover")
def customized_hover():
    cbs = [customizedHoverResponse, LanguageClient._instance.handleError]
    LanguageClient._instance.textDocument_hover(cbs=cbs)
```

I'm aware the API is not that great, but at least it should work. Let me know if you need more help.
