### ISSUE TITLE
initializationOptions are not passed to rust-analyzer

### ISSUE THREAD

**Issue by ta3pks** [autozimu/LanguageClient-neovim#1182]
- Did you upgrade to latest plugin version? :heavy_check_mark: 
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.  `languageclient 0.1.161`
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? :heavy_check_mark: 
- Did you check [troubleshooting]? :heavy_check_mark: 

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

Initialization options described in [rust analyzer manual](https://rust-analyzer.github.io/manual.html) has no effect on the language client.
I enabled procmacros but still i get proc macro errors I also cannot seem to disable those diagnostics for the same reason
usage of the options are clearly documented so either LanguageClient-neovim uses non-standard way of defining things or simply this is not implemented
```
let g:LanguageClient_serverCommands = {
			\ 'rust': {
			\"name":"rust-analyzer",
			\ "command":['rust-analyzer'],
			\ "initializationOptions":{
			\"rust-analyzer.procMacro.enable": v:true,
			\"rust-analyzer.cargo.loadOutDirsFromCheck": v:true,
			\},
			\ },
			\ }

```

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): `NVIM v0.4.4`
- This plugin version (`git rev-parse --short HEAD`): `next branch`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.161`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
`Not relevant`
- Language server link and version: `rust-analyzer 60c501f`

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- add client config 
```
let g:LanguageClient_serverCommands = {
			\ 'rust': {
			\"name":"rust-analyzer",
			\ "command":['rust-analyzer'],
			\ "initializationOptions":{
			\"rust-analyzer.procMacro.enable": v:true,
			\"rust-analyzer.cargo.loadOutDirsFromCheck": v:true,
			\},
			\ },
			\ }

```
- open a rust file which uses some proc macro such as `Serialize` derive macro
- watch the errors despite the initOptions

## Current behavior

Described above and the title multiple times.

## Expected behavior

Init options to take effect

## Screenshots

![image](https://user-images.githubusercontent.com/9097437/104828790-0cdf0c80-587e-11eb-9b92-2d76452a878c.png)
![image](https://user-images.githubusercontent.com/9097437/104828807-21230980-587e-11eb-9c54-b905d7d2279c.png)

**Comment by ta3pks** [comment]
options are supposed to be specified as nested maps one key at a time I guess this has nothing to do with LanguageClient-neovim afterall

**Comment by martskins** [comment]
I think the issue you are/were having is that the `rust-analyzer.` prefix on your options should not be included in this config section. The idea behind that not being necessary was that it was already clear that the initialization options were for `rust-analyzer` (or whatever server you were configuring), but maybe that's not clear or correct enough and it's worth changing it to require the full option name.

Essentially, what you want to have there is something like this instead:

```
...
"initializationOptions": {
  "procMacro.enable": v:true,
  "cargo.loadOutDirsFromCheck": v:true,
},
...
```

**Comment by ta3pks** [comment]
@martskins  that doesnt work either 
```
"initializatinonOptions":{
  "procMacro":{
    "enable":v:true
  }
}
```
dos work however
