### ISSUE TITLE
How can I cancel completion item documentation?

### ISSUE THREAD

**Issue by ta3pks** [autozimu/LanguageClient-neovim#1183]
How can I cancel completion item documentation?

**Comment by martskins** [comment]
If by cancel you mean hide them, not show them at all, then you can do that by adding this to your vimrc:

`let g:LanguageClient_showCompletionDocs = 0`

Note that this is documented in `doc/LanguageClient.txt`

**Comment by ta3pks** [comment]
thanks I searched the docs but couldnt find initially
