### ISSUE TITLE
Invert order of diagnostic messages

### ISSUE THREAD

**Issue by TheZoq2** [autozimu/LanguageClient-neovim#1184]
## Describe the bug

As of a few versions back, I have started seeing hint messages from rust-analyzer being shown in the language client. While this change is very good, the way they are displayed is a bit annoying as the hints shadow errors and warnings.

For example:

![image](https://user-images.githubusercontent.com/5312813/104898929-82300780-597a-11eb-9963-39c3a5d9ff0a.png)

The underlying errors here are "missmatched return type" and "this function takes 3 arguments but one was supplied". The last one in particular hides a lot of important information.

In my opinion, it would be much better of the errors and warnings were displayed first if present, and then hints.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- This plugin version (`git rev-parse --short HEAD`):
`8cba87e`
- This plugin's binary version (`bin/languageclient --version`):
`rust-analyzer fde4a86`
- Minimal vimrc content
[min-vimrc.vim] with rls subsituted for rust-analyzer

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

Open a rust project, cause an error

## Current behavior

If bot hints and errors are present, hint text is displayed inline, rather than the error

## Expected behavior

It would make more sense to me to show diagnostics in severity order

## Additional context

For now, I can set `let g:LanguageClient_diagnosticsMaxSeverity = 'Warning'` to achieve roughly what I want, but then hints are never shown

**Comment by martskins** [comment]
That has actually been fixed in #1172 but it hasn't been released yet. If you use the dev branch (and build from source) you can get that change into your workflow now, otherwise you'll have to use your workaround until a new release is cut. Shouldn't be too long until a new release, but some important changes have taken place lately and I want to make sure nothing breaks for a few more days.

**Comment by TheZoq2** [comment]
Ah awesome, though I think I'm already on the dev branch and it looks like 8cba87e is the latest commit ID on that branch. Maybe I'm missing something though

**Comment by martskins** [comment]
Have you built the binary from source? `make release` ?

**Comment by TheZoq2** [comment]
Ah, I completely missed having to do that. Looks like it works now :)
