### ISSUE TITLE
macOS / Apple Silicon Not Supported

### ISSUE THREAD

**Issue by stack** [autozimu/LanguageClient-neovim#1201]
This plugin fails to install on Apple Silicon Macs. A manual compilation is possible, with two changes:

1. Because the plugin tries to build the binary, it must you the Makefile. The `date` command is incorrect for macOS, and the `--utc` option must be changed to `-u`. I imagine this affects all BSDs.
2. The current `rust-toolchain` file points to version 1.46.0. Apple Silicon support was not added until 1.49.0. Removing the `rust-toolchain` file results in a working build. My current machine is running 1.50.0.

**Comment by martskins** [comment]
Fixed this in #1203 which is now in dev. If you can confirm this is fixed in that branch that would be great.

**Comment by stack** [comment]
That seems to have fixed it. Thank you!

**Comment by martskins** [comment]
Closing this in that case :+1:
