### ISSUE TITLE
exit() triggers resumeOnCrash

### ISSUE THREAD

**Issue by ryan0270** [autozimu/LanguageClient-neovim#1206]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? 0.1.161
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Everything is OK
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#troubleshooting

## Describe the bug

When I explicitly call `LanguageClient#exit()` with a file open, there's a message saying `[LC] Server crashed, restarting client`. If I set `let g:LanguageClient_restartOnCrash = 0` this no longer happens.

## Environment

- neovim/vim version (`nvim --version` or `vim --version`): 0.4.4
- This plugin version (`git rev-parse --short HEAD`): a42594c
- This plugin's binary version (`bin/languageclient --version`): 0.1.161
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- Open file (preferably one with lots of popup warnings which is why I tell LC to exit)
- call `LanguageClient#exit()`

## Current behavior

Message appears saying LC has crashed and is being restarted.

## Expected behavior

Explicitly choosing to exit LC should not trigger a restart.

**Comment by martskins** [comment]
That is expected, an exit call without a previous shutdown call will exit with code 1, as per the specification:

```
A notification to ask the server to exit its process. The server should exit with success code 0 if the shutdown request has been received before; otherwise with error code 1.
```

If you want to stop the server gracefully you can run the command `:LanguageClientStop`, which will call `LanguageClient#shutdown()` and will not trigger the restart.

**Comment by martskins** [comment]
Closing this for lack of response, but feel free to re-open if you think this doesn't solve your issue.
