### ISSUE TITLE
Java Language Server fails to start

### ISSUE THREAD

**Issue by tepf** [autozimu/LanguageClient-neovim#123]
I managed to setup the Python LS but the Java LS stops at "Starting Init ...". How do setup the Java LS?

NeoVim Version: 0.2

Here is my "init.vim":

        call plug#begin('~/.config/nvim/plugged')
        Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
        " (Optional) Multi-entry selection UI.
        Plug 'junegunn/fzf'
        " (Optional) Multi-entry selection UI.
        Plug 'Shougo/denite.nvim'
        " (Optional) Completion integration with deoplete.
        Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
        " (Optional) Completion integration with nvim-completion-manager.
        Plug 'roxma/nvim-completion-manager'
        " (Optional) Showing function signature and inline doc.
        Plug 'Shougo/echodoc.vim'
        call plug#end()

        " for echodoc
        set noshowmode

        " Required for operations modifying multiple buffers like rename.
        set hidden

        let g:LanguageClient_serverCommands = {
            \ 'python': ['pyls'],
            \ 'java': ['java',
            \   '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044',
            \   '-Declipse.application=org.eclipse.jdt.ls.core.id1',
            \   '-Dosgi.bundles.defaultStartLevel=4',
            \   '-Declipse.product=org.eclipse.jdt.ls.core.product',
            \   '-Dlog.protocol=true',
            \   '-Dlog.level=ALL',
            \   '-noverify',
            \   '-Xmx1G',
            \   '-jar', '/Users/me/Downloads/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar',
            \   '-configuration', '/Users/me/Downloads/jdt-language-server-latest/config_mac',
            \   '-data', '/Users/me/Desktop/testjava'],
            \ }

        let g:LanguageClient_autoStart = 0

        nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
        nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
        nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>

Here is the log

        19:33:08 DEBUG   [MainThread] state.serverCommands.java: None -> ['java', '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.protocol=true', '-Dlog.level=ALL', '-noverify', '-Xmx1G', '-jar', '/Users/me/Downloads/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-configuration', '/Users/me/Downloads/jdt-language-server-latest/config_mac', '-data', '/Users/me/Desktop/testjava']
        19:33:08 DEBUG   [MainThread] state.serverCommands.python: None -> ['pyls']
        19:33:08 DEBUG   [MainThread] state.selectionUI: None -> fzf
        19:33:08 INFO    [MainThread] Begin LanguageClientStart
        19:33:08 DEBUG   [MainThread] state.servers.java: None -> <subprocess.Popen object at 0x109f32eb8>
        19:33:08 DEBUG   [MainThread] state.rpcs.java: None -> <LanguageClient.RPC.RPC object at 0x10a4ece48>
        19:33:08 INFO    [MainThread] End LanguageClientStart
        19:33:08 WARNING [MainThread] Unknown parameter key: rootPath
        19:33:08 INFO    [MainThread] Begin initialize
        19:33:08 WARNING [MainThread] Unknown project type. Fallback to use dir as project root.
        19:33:08 INFO    [MainThread] rootPath: /Users/me/Desktop/testjava/src/main/java
        19:33:08 DEBUG   [MainThread] state.rootUris.java: None -> file:///Users/me/Desktop/testjava/src/main/java
        19:33:08 DEBUG   [MainThread] => {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":2594,"rootPath":"/Users/me/Desktop/testjava/src/main/java","rootUri":"file:///Users/me/Desktop/testjava/src/main/java","capabilities":{},"trace":"off"}}
        19:33:09 DEBUG   [RPC-java  ] <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Sep 4, 2017 3:33:09 PM \u003e\u003e initialize"}}
        19:33:09 DEBUG   [RPC-java  ] <= {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Sep 4, 2017 3:33:09 PM Initializing Java Language Server 0.4.0.201709010539"}}
        19:33:09 DEBUG   [RPC-java  ] <= {"jsonrpc":"2.0","method":"language/status","params":{"type":"Starting","message":"Init..."}}
        19:33:09 ERROR   [RPC-java  ] Exception in handle request and notify.
        Traceback (most recent call last):
          File "/Users/me/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 1219, in handle_request_and_notify
            getattr(self, method)(message.get("params"))
          File "/Users/me/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 1213, in language_status
            echomsg(msg)
          File "/Users/me/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/state.py", line 121, in echomsg
            execute_command("echomsg '{}'".format(message))
          File "/Users/me/.config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient/state.py", line 109, in execute_command
            state["nvim"].command(command)
          File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 218, in command
            return self.request('nvim_command', string, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
            res = self._session.request(name, *args, **kwargs)
          File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 89, in request
            v = self._yielding_request(method, args)
          File "/usr/local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 154, in _yielding_request
            return parent.switch()
        AttributeError: 'NoneType' object has no attribute 'switch'

And here :CheckHealth

        health#deoplete#check
        ========================================================================
        ## deoplete.nvim
          - SUCCESS: has("nvim") was successful
          - SUCCESS: has("python3") was successful
          - INFO: If you're still having problems, try the following commands:
            $ export NVIM_PYTHON_LOG_FILE=/tmp/log
            $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
            $ nvim
            $ cat /tmp/log_{PID}
            and then create an issue on github

        health#nvim#check
        ========================================================================
        ## Configuration
          - SUCCESS: no issues found

        ## Performance
          - SUCCESS: Build type: Release

        ## Remote Plugins
          - SUCCESS: Up to date

        ## terminal
          - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
          - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

        health#provider#check
        ========================================================================
        ## Clipboard (optional)
          - SUCCESS: Clipboard tool found: pbcopy

        ## Python 2 provider (optional)
          - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
          - WARNING: provider/pythonx: Could not load Python 2:
            python2 not found in search path or not executable.
            /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
            /usr/bin/python2.6 does not have the "neovim" module. :help provider-python
            /usr/bin/python does not have the "neovim" module. :help provider-python
          - ERROR: Python provider error
            - SUGGESTIONS:
              - provider/pythonx: Could not load Python 2:
                  python2 not found in search path or not executable.
                  /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
                  /usr/bin/python2.6 does not have the "neovim" module. :help provider-python
                  /usr/bin/python does not have the "neovim" module. :help provider-python
          - INFO: Executable: Not found

        ## Python 3 provider (optional)
          - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
          - INFO: Executable: /usr/local/bin/python3
          - INFO: Python3 version: 3.6.1
          - INFO: python3-neovim version: 0.1.13
          - SUCCESS: Latest python3-neovim is installed: 0.1.13

        ## Ruby provider (optional)
          - INFO: Ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
          - WARNING: Missing "neovim" gem.
            - SUGGESTIONS:
              - Run in shell: gem install neovim
              - Is the gem bin directory in $PATH? Check `gem environment`.
              - If you are using rvm/rbenv/chruby, try "rehashing".

**Comment by autozimu** [comment]
Thanks for reporting.

Please try the latest fix 14ade7895eab878997fdb2c877f776f13d2fdc27.

**Comment by tepf** [comment]
The server now starts and connects.

Since I am already here. I think I have found some kind of parser error.

This code should throw an error message: `Could not find symbol abc`. Instead it only shows messages in the bottom when I am with my cursor on spot 1 and 2.

	public class Library {

		public static void main(String[] args) {
                       // 1
			Box box = new Box(abc);
                       // 2
		}

	}

	class Box {
		String content;
		public Box(String content) {
			this.content = content;
		}
	}

1 -> [E]1610612976 Syntax error, insert "}" to complete ClassBody
2 -> [E]1610612967 Syntax error on token ")", { expected after this token

**Comment by autozimu** [comment]
I didn't see the same results as you described. Might because I got a warning of "classpath is incomplete.".

Nevertheless, the messages are directly from language servers. If you feel they are not accurate enough, you will need to file ticket on their side.

**Comment by tepf** [comment]
I don't think that this is the language server as Red Hats VS Code Extension uses the same language server.

What does it show to you with this code?

    public class Main {
        public static void main(String[] args) {
           abc.def();
        }
    }

It reports the Syntax Error from above for me.

**Comment by autozimu** [comment]
This time I did see the "abc cannot be resolved to a variable."

Maybe the error message is generated before you terminating the statement with ";". After you typing ";", the language server still needs some time to process and update the error message.

**Comment by tepf** [comment]
I just replicated that on a different setup. This time a Linux machine. There must be something wrong with the way I set it up.

How does your setup look like? init.vim, java project structure (just a file or maven/gradle project) etc.
How did you install the language server? Did you just download the tar.gz and extract it?

**Comment by autozimu** [comment]
I build the jar from repo directly.

And I use a wrapper named java-language-server to start the server process
```sh
#!/usr/bin/env bash

/usr/lib/jvm/default/bin/java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -noverify \
    -Xms1G \
    -jar <YourBuildPathHere>/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar \
    -configuration <YourBuildPathHere>/config_mac \
    -data ~/IdeaProjects
```
(I am using a different machine now, so I can only give a sketch.)

The files I'm opening are files of projects created by Intellij IDEA, which is within `~/IdeaProjects`.

I'm not that familiar with the java language server, but it seems do have a specific requirements on project layouts.

Or you can try the redhat provided vscode extension, and copy the same setup from there.
