### ISSUE TITLE
No LC completions at all.

### ISSUE THREAD

**Issue by jinks** [autozimu/LanguageClient-neovim#124]
I'm trying to get the LanguageClient working with the rust RLS.

When I type a "completable" line, I get no completion options at all. I tried with deoplete as well as NCM.

For example, neither the input `use std::` nor `use std::coll` present me with a popup at all. If I force completion at that point I only get presented options from the local file.

doc lookup (`K`) and go-to-definition work fine, so LC-RLS seems to be active.

If I enable vim-racer, I **do** get racer-supplied completions from the above inputs, so deoplete and/or NCM seem to be working fine, too.  (Only one of them active at a time, obviously.)

`rplugin.vim` and the LC debug log are attached. The log *looks* like RLS does return possible completions in line 141, but the pum never gets populated with them.

[rplugin.vim.txt](https://github.com/autozimu/LanguageClient-neovim/files/1275395/rplugin.vim.txt)
[lc.log.txt](https://github.com/autozimu/LanguageClient-neovim/files/1275392/lc.log.txt)

**Comment by DeltaEvo** [comment]
First, have you defined RUST_SRC_PATH ?
And there is another log file /tmp/LanguageServer.log can you send it please ?

**Comment by jinks** [comment]
1. Yes, I have. And it is also correct since I first got it wrong which broke racer until I fixed that. Since RLS seems to ignore that variable anyways, I have also symlinked `/checkout/src` in a way that RLS is happy (i.e. go-to-definition works for std code), see rust-lang-nursery/rls#227

2. This one is rather short, so I'll inline it.
```
error: expected identifier, found keyword `const`
 --> bogofile:3:1
  |
3 | const OAUTH: &'static str = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
  | ^^^^^

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', /checkout/src/libstd/io/stdio.rs:692:8
```
The error in that log goes away when I "finish" the `use std::...` line with a `;`

**Comment by autozimu** [comment]
Does it work with barebone examples like this https://github.com/autozimu/LanguageClient-neovim/tree/master/rplugin/python3/tests/sample-rs?

As far as I know, rls is still beta software. It sometimes cannot provide completions from std lib, also crash occasionally like the one you see.

**Comment by autozimu** [comment]
Also, rls is already known for being incapabile handling large projects with complex setup.

**Comment by jinks** [comment]
Barebones example has same behavior. Only working completion source is racer.

**Comment by autozimu** [comment]
Does it complete the `greet` function?

**Comment by jinks** [comment]
I opened a new line in main and typed `let f = gre`.

If I turn off racer it get a completion item for `greet [~] A`, which I **think** is just deoplete completing from the local file.

_With_ racer I get a second option `greet f [racer] greet() -> i32`.

I get no entry tagged with `[LC]` which I would expect here.

**Comment by autozimu** [comment]
I cannot reproduce the described issue locally.

Yes, when it works, it should have a `[LC]` tag.

Could you attach /tmp/LanguageClient.log and /tmp/LanguageServer.log? (with one session please.)

**Comment by autozimu** [comment]
One more thing I don't know if relevant, but I am not using latest nightly rls, I am using nightly-2017-08-22 toolchain.

Latest nightly rls doesn't work at all on my side. Not sure if it is my fault or rls broken at some point.

Also I'd suggest you try with rls-vscode extension to verify that rls are actually working.

**Comment by jinks** [comment]
Huh, apparently that was the culprit.

I was **not** using the latest nightly, last updated 5-7 days ago. A fresh `rustup update` and now it works. Sorry for the noise.

Before I close this: Is there any way to diagnose something like this more concretely. I saw no indication anywhere that rls might be the problem.

Also, yes, vscode and vim with YCM (does YCM even query rls?) both were working fine. I embarked on the whole nvim journey because I wanted to cut down on the bloat. :)

Also the mouse-heavy vscode interface is just annoying, I only used that for browsing.

**Comment by autozimu** [comment]
Glad it finally works.

For me, if I am running latest rls, I can see errors in /tmp/LanguageServer.log. Other than that, the server does not emit any error information explicitly to client. This is definitely somewhere to improve though.
