### ISSUE TITLE
None-Error introduced in refactoring a few days ago.

### ISSUE THREAD

**Issue by Drezil** [autozimu/LanguageClient-neovim#128]
with Commit https://github.com/autozimu/LanguageClient-neovim/commit/023ba139a86434205b3fd1c33bafa874e04404dd

an error was introduced:

https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L957

`items` is `None` when the server answers:

```
16:52:52 ERROR   [MainThread] {'error': {'code': -32603, 'message': 'IdeError {ideCode = PluginError, ideMessage = "getCompletions: \\"module not loaded\\"", ideInfo = Null}'}, 'id': 6, 'jsonrpc': '2.0'}
```

This is a valid error the server can throw, as i have not loaded all modules in the server.

The error originates from [this line](https://github.com/autozimu/LanguageClient-neovim/commit/023ba139a86434205b3fd1c33bafa874e04404dd#diff-b6663fb29f9a1b14fa76ec23f1b6237dR956)
where the RPC of textDocument_completion() fails with the above error.

Sadly i have no time now to fix this and issue a PR, but a `git checkout e02754224ce8740a7f6b893ce414fbfc01c64ff5` to get a working version as a fix works.

HTH

**Comment by autozimu** [comment]
Thanks for reporting.
