### ISSUE TITLE
Option to disable diagnostics

### ISSUE THREAD

**Issue by haringsrob** [autozimu/LanguageClient-neovim#13]
Hi,

This plugin seems to work fine, however:

I like the idea of validations but I think it should either:
1. Only happen on save
2. Display in a different way.

Currently every time I perform an "action" it flickers my screen because its adding an icon to the number bar.

I tried:
```
"" Php autocomplete
" Disable diagnostics
let g:LanguageClient_diagnosticsDisplay = {}
``` 

but that does not seem to help.

**Comment by autozimu** [comment]
That action is actually used to customize the display of diagnostics, so it won't work.

I am considering adding two little enhancements
- add option to keep the gutter open, even if there is no diagnostics, so that remove the annoying flicker
- add option to toggle diagnostics display

**Comment by haringsrob** [comment]
I used 
```
"" Git gutter.
let g:gitgutter_sign_column_always = 1
``` 

as a temporary workaround.

**Comment by autozimu** [comment]
Well, that's what I did too./

**Comment by PetrusZ** [comment]
so, there is any option to disable diagnostics now?

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L140

**Comment by PetrusZ** [comment]
@autozimu Thank you! Somehow I skipped that line……
