### ISSUE TITLE
KeyError: `scss` 

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#133]
I'm experimenting with using the vscode css language server binaries from npm with LanguageClient-neovim, and I'm running into an error that I originally presumed was due to the language server and not this neovim language client plugin, but looking at the logs it doesn't seem like there's anything wrong from the server's end.

* NVIM v0.2.1-870-g1551f7132
* LanguageClient 025be7becfaa3da8d7129a211ec4d8f288ee3453
* deoplete 821d375307183ac5c0936a8d4e4ae872dba76a8e

```vim

let $RUST_SRC_PATH = glob("$HOME/.rustup/toolchains/nightly*/lib/rustlib/src/rust/src/")
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'javascript': ['/usr/local/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js'],
    \ 'typescript': ['/usr/local/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js'],
    \ 'html': ['html-languageserver', '--stdio'],
    \ 'json': ['json-languageserver', '--stdio'],
    \ 'css': ['css-languageserver', '--stdio'],
    \ }
                               
```

```


 health#deoplete#check
 ========================================================================
 ## deoplete.nvim
   - SUCCESS: has("nvim") was successful
   - SUCCESS: has("python
") was successful
   - INFO: If you're still having problems, try the following commands:
     $ export NVIM_PYTHON_LOG_FILE=/tmp/log
     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
     $ nvim
     $ cat /tmp/log_{PID}
     and then create an issue on github

 health#nvim#check
 ========================================================================
 ## Configuration
   - SUCCESS: no issues found

 ## Performance
   - SUCCESS: Build type: RelWithDebInfo

 ## Remote Plugins
   - SUCCESS: Up to date

 health#provider#check
 ========================================================================
 ## Clipboard (optional)
   - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
     - SUGGESTIONS:
       - :help clipboard

 ## Python
 provider (optional)
   - INFO: Disabled. g:loaded_python_provider=


 ## Python
 provider (optional)
   - INFO: Using: g:python
_host_prog = "python
"
   - INFO: Executable: /usr/local/bin/python

   - INFO: Python
 version:
.
.

   - INFO: python
-neovim version:
.
.

   - SUCCESS: Latest python
-neovim is installed:
.
.


 ## Ruby provider (optional)
   - WARNING: `ruby` and `gem` must be in $PATH.
     - SUGGESTIONS:
       - Install Ruby and verify that `ruby` and `gem` commands work.
                                                                                                                                                                                          ~       
                                                                        
```

Attempting to type in a particular document (and many but not all) using this language server returns a slew of errors in neovim/deoplete:

```
"style.css" 2855L, 48369C
remote/host: python3 host registered plugins ['deoplete', 'LanguageClient']
remote/host: generated rplugin manifest: /usr/home/mqudsi/.local/share/nvim/rplugin.vim
[deoplete] Traceback (most recent call last):
[deoplete]   File "/usr/home/mqudsi/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 123, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 68, in gather_candidates
[deoplete]     languageId=languageId, line=line, character=character)
[deoplete]   File "/usr/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 40, in wrappedf
[deoplete]     return f(*final_args)
[deoplete]   File "/usr/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/LanguageClient/LanguageClient.py", line 943, in textDocument_completion

[deoplete]     result = state["rpcs"][languageId].call("textDocument/completion", {
[deoplete] KeyError: 'scss'
[deoplete] Could not get completions from: LanguageClient.  Use :messages for error details.
```

The LanguageClient.log file is attached: [LanguageClient.txt](https://github.com/autozimu/LanguageClient-neovim/files/1323360/LanguageClient.txt)

**Comment by DeltaEvo** [comment]
The  vscode css language server binaries on npm are not official binaries and are not usable yet, I need to work on them. However I will try to reproduce your issue :smile:

**Comment by autozimu** [comment]
The issue looks like LanguageClient-nevim thought the file is of type `css`, while deoplete thought it is `scss`.

The min vimrc is the minimal vimrc to reproduce issue, not an excerpt from your vimrc in use. Not going to investigate without valid vimrc and reproduction steps.

**Comment by mqudsi** [comment]
> The min vimrc is the minimal vimrc to reproduce issue, not an excerpt from your vimrc in use. Not going to investigate without valid vimrc and reproduction steps.

Whatever you like.

**Comment by autozimu** [comment]
> Whatever you like.

It's not whatever "I" like.

I've already pointed out one possible cause of the problem, which is possibly because of the configuration issue, and the fact this ticket lacks necessary vimrc and concrete reproduction steps.

**Comment by mqudsi** [comment]
Sorry, I somehow missed this reply.

I'm a maintainer of several popular open source repos on github and I know what it's like to deal with a huge number of support issues that may or may not be bugs and not being able to diagnose them without some sort of reproduction steps. However, I also know the importance of not being pedantic and to take into account the context of the bug report when evaluating the provided evidences.

In this particular example, I was not having any issues with LanguageClient not loading, I don't have a generic "it doesn't work for me" issue, etc. Clearly LanguageClient is configured correctly and is running OK, but something about _this particular provider_ is not playing nicely and I figured I'd report that to you for whatever it is worth.

Just as the developer's time is valuable and should not be wantonly wasted, so should the time of users filing reports for the mutual good be respected. I'm an extremely thorough individual and have provided the "full reproduction steps" in as-minimal as possible a format in other bug reports both here and elsewhere, but it takes me a good half hour to strip everything down to the bare essentials and make sure I'm presenting everything that would work "as-is" starting with a clean slate in a fresh environment. But sometimes, that effort is not necessarily indicated.

You said:

> The issue looks like LanguageClient-nevim thought the file is of type css, while deoplete thought it is scss.

Which is exactly the kind of feedback I was looking for in creating this post. I'm a developer myself, and sometimes just a hint in the right direction from someone intimately familiar with how things work is exactly what is required.

But then you followed it up with an extremely unhelpful and not very polite bit:

> The min vimrc is the minimal vimrc to reproduce issue, not an excerpt from your vimrc in use. Not going to investigate without valid vimrc and reproduction steps.

and proceeded to close the report outright, rather than acknowledging that perhaps something was going on and requesting more information and full reproduction steps in order to decide how to proceed, which was rather insulting and really quite unnecessary given that I'm only here to try to help. This attitude is not how one engenders support from the community or encourages contributions back to the project.

I'm sure you've seen my @mentions of your github name recommending that several projects include links to your LanguageClient and giving you props for developing a wonderful plugin. This is exactly the kind of user-hostile behavior that makes sure that doesn't happen going forward.

Anyway, if I could make a suggestion that would probably spare you some pain and save you a lot of effort and frustration going forward: you should consider adding all potentially useful information in debugging cases like this to the language client log so that if LC is up-and-running the vimrc file becomes less important and all the relevant information can be found in the log (which I attached in my first post, of course).

**Comment by autozimu** [comment]
I do appreciate your effort to make the project getting better know by people.

But that doesn't mean I should lower issue quality especially for anyone.

The bug report template states explicitly that minimal vimrc and reproduction steps are required. If you don't know how to create a minimal vimrc, there is already a [default one](https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim) provided. Or you could ask in the issue explicitly you need help setting up minimal vimrc. Also this bug report literally has zero reproduction steps.

You're not satisfied with my attitude to bug report, which you probably can find the reason why in some of the issues. I explicitly setup the bug report template to increase bug report quality and do welcome quality bug reports. But someone simply ignore my effort and provide only "minimal" information.

If you feel the need to pursue this issue furthermore, feel free to fill out the necessary information and reopen it.
