### ISSUE TITLE
Static methods sugestion

### ISSUE THREAD

**Issue by vivoconunxino** [autozimu/LanguageClient-neovim#138]
It doesn't suggest any method when I try with static methods. 
For instance, 
```
<?php

public class Myclass {
    public function myMethod();
    public static function mySMethod();
}

$m = new Myclass();

$m->myMethod(); //works code intelisense after ->

Myclass:: //does not sugest anything after ::

```

**Comment by DeltaEvo** [comment]
> If you are reporting a bug, please read following FAQ first.

# Not editor command: LanguageClientStart?
Have you followed the instructions at
[INSTALL.md](https://github.com/autozimu/LanguageClient-neovim/blob/master/INSTALL.md)?

If not, please try follow the instructions there first.

# If you are still seeing an error or other types of error, please create ticket with
- neovim version
- Plugin version (git SHA)
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim>).
- Content of `:CheckHealth`.
- Content of `~/.local/share/nvim/rplugin.vim`.
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`.

(Please understand the more detailed information provided, the sooner a issue
can be resolved.)

**Comment by vivoconunxino** [comment]
I understand perfectly, my apologies, I'm quite newbie reporting issues. Will extend as info as possible once I have more time. Thanks

**Comment by autozimu** [comment]
@vivoconunxino were you able to reproduce the issue and provide reproduction steps?

I'd like to close the issue if it is no longer reproducible. Plus it looks highly possible of a language server issue.

**Comment by autozimu** [comment]
Closing as incomplete bug report and no further response.

**Comment by fcojavierdomenech** [comment]
It's currently working
