### ISSUE TITLE
Settings file support

### ISSUE THREAD

**Issue by hatzel** [autozimu/LanguageClient-neovim#139]
Am I correct in assuming that settings files like this: https://github.com/rust-lang-nursery/rls#configuration are not supported in LanguageClient-neovim? If so could you give me a few pointers as to what it would take to implement this.

**Comment by DeltaEvo** [comment]
LanguageClient-neovim support sending notifications to language server with https://github.com/autozimu/LanguageClient-neovim/blob/master/doc/LanguageClient.txt#L233, so you are wrong :smile:

**Comment by hatzel** [comment]
Technically correct :D but the interesting part would be having a file in the project root that is used for this.
I am not to sure about security implications though.

**Comment by autozimu** [comment]
Currently the notification is not sent by default.

Should be relatively easy to implement though.
- refer to this to create a wrapper to send `workspace/didChangeConfiguration` notification  <https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L474> 
- call the wrapper after initialize at <https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L372>

**Comment by DeltaEvo** [comment]
I don't think this must be added to LanguageClient-neovim, because not everyone want to send config the same way, if you want to use a settings.json like VSCode you can implement it with vim script like
```vim
function! LoadConfig()
        let config = json_decode(system("cat settings.json"))
        call LanguageClient_notify('json/schemaAssociations', { 'settings': config })
endfunction

augroup JSON_Config
        autocmd!
        autocmd User LanguageClientStarted call LoadConfig()
augroup END
```
(I don't tested it)

**Comment by hatzel** [comment]
I would be in favor of having an auto-discovery option in LanguageClient-neovim for this. That way we are doing it like other plugins (YCM for example). This would mean that I build a function to load a specific file and a function to find the project root.

Seeing that VSCode does it this way I think the option should even be enabled by default but I am not sure if that really is the "sane default" here.

**Comment by autozimu** [comment]
I'm fine with adding support in this plugin.

We could implement behind a settings, with default to not send settings file.

**Comment by juancampa** [comment]
@hatzel If I understand correctly this would add support for "workspaces", right?. i.e. when the server start it should scan all the files in the workspace as opposed to just the current file.
