### ISSUE TITLE
How to switch language server on the fly?

### ISSUE THREAD

**Issue by TxHawks** [autozimu/LanguageClient-neovim#140]
Is there a way to switch the language server that is being used on the fly?

When editing javascript files, I find myself mostly wanting to use `javascript-typescript-stdio`, but switch to `flow-language-server` in projects where I use Flow.

Is that possible? Couldn't find anything relevant in the documentation or issues other than a reference to `LanguageClient_registerServerCommands` in [#136 (comment)](136#issuecomment-332003784), but not sure how to use it, or if it is even the right solution.

**Comment by autozimu** [comment]
You can put settings like this in a local vimrc file
```vim
call LanguageClient_registerServerCommands({'javascript':['path-to-server']})
```

And use a plugin to load load vimrc file.

Obviously you can do this manually without a plugin, just run the command before executing `:LanguageClientStart`.

**Comment by TxHawks** [comment]
@autozimu 
I get `Ambiguous use of user-defined command` when trying to run   
`:call LanguageClient_registerServerCommands({'javascript':['path-to-server']})`

and indeed, `:commands` lists only `LanguageClientStop` and `LanguageClientStart`

**Comment by autozimu** [comment]
`LanguageClient_registerServerCommands` is a function, not a command.

Not sure what happened on your side, but I tried the steps and see no errors. If you believe you found an issue, please create new bug report. Cannot help much without detail information.
