### ISSUE TITLE
Some diagnostics sent by HIE, but not shown in gutter

### ISSUE THREAD

**Issue by Anrock** [autozimu/LanguageClient-neovim#144]
- neovim version `v0.2.1-6-g9b1cad7c`, full `:version` output: https://bpaste.net/show/65b6250bd39d
- Plugin version: b315e05656856b8ea1a69e5cdda8b667c7693cb7
- Minimal vimrc: https://bpaste.net/show/0f90433e3e6c
- Content of `:CheckHealth`: https://bpaste.net/show/cc534c8ac3f2
- Content of `%LOCALAPPDATA%/nvim/rplugin.vim`: https://bpaste.net/show/9740999af597
- Content of `%TMP%/LanguageClient.log`: https://bpaste.net/show/7167cfae47bd

For some diagnostics from server there is no reaction from LanguageClient.

Repro:
1. Install [HIE](https://github.com/haskell/haskell-ide-engine) using instructions from README, commit i've used `e3f921df897e7a5f4fe33da000b0eb70664c8c47`
2. Open test.hs with following content:
```
data D = A | B

f :: String -> String
f = undefined
```
3. Replace `String` with `Sring`
3a. Add some garbage like `fa;sldjf;laslf` in any empty line
Expected: error added to gutter
Actual: gutter is clean

However, if you change `data` to `dta` or `dsata` - error will be displayed.

p.s. help file claims that `g:LanguageClient_diagnosticsDisplay` have default value, however it's not declared at all. Looks like python plugin checks variable and uses mentioned default value on it's level, but doesn't declare it back to vim level.

**Comment by autozimu** [comment]
Thanks for reporting.

From the log file, the issue is because HIE is not using correct file uri, check https://en.wikipedia.org/wiki/File_URI_scheme#Windows and https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/.

Please file ticket on HIE side. (Even I'd like to help, I don't have a Windows machine around.)

To answer your PS. Both the setting and its default value are kept in python side. As this setting is only used by python, it doesn't report back to vim side.

**Comment by Anrock** [comment]
@autozimu thanks for quick answer.

Regarding PS: my use case was in changing gutter symbols, because i have issues with displaying double-width chars, so it would've been very convenient for me to write just `let g:LanguageClient_diagnosticsDisplay.1signText = "E"` instead of copypasting documented default value.

**Comment by autozimu** [comment]
It is already possible to achieve what you desribed right now (though I didn't make it intentionally XD). You could have
```vim
let g:LanguageClient_diagnosticsDisplay = { 1: { "signText": "E" } }
```
