### ISSUE TITLE
Ever interested in  vim 8 support?

### ISSUE THREAD

**Issue by roxma** [autozimu/LanguageClient-neovim#146]
As [vim-hug-neovim-rpc](https://github.com/roxma/vim-hug-neovim-rpc) is gettng more power. It seems possible to port  LanguageClient-neovim to vim 8, with the help of [nvim-yarp](https://github.com/roxma/nvim-yarp)

There's a small example, and a full demo in the README.

It doesn't require modification of existing code, it just needs to add some code to bind functions/commands manually.

**Comment by autozimu** [comment]
Thanks for the suggestion. Will experiment a bit and see how it goes.

**Comment by autozimu** [comment]
Work will be tracked at https://github.com/autozimu/LanguageClient-neovim/pull/151

**Comment by autozimu** [comment]
#151 merged in.
