### ISSUE TITLE
Question regarding NodeJS completion

### ISSUE THREAD

**Issue by asilvadesigns** [autozimu/LanguageClient-neovim#147]
This may be more of a feature request or an ask for help etc I'm not sure, I have this plugin installed with deoplete and it works amazingly. I was curious how to achieve completion for NodeJS modules, that's not something I'm seeing the language client provide.

Any help greatly appreciated, thank you.

**Comment by autozimu** [comment]
Have you tried <https://github.com/sourcegraph/javascript-typescript-langserver>?

I personally only use it for frontend JS/TS, but it should support nodejs as well.

**Comment by asilvadesigns** [comment]
Yes I'm currently using that, works great for front end, but is not pulling in methods for node modules. Maybe my setup is wrong, I have the following in my init.vim
```
"   ~defaults for language servers
let g:LanguageClient_serverCommands = {
      \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
      \ 'javascript': ['/usr/local/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js'],
      \ 'javascript.jsx': ['/usr/local/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js'],
      \ 'typescript': ['/usr/local/lib/node_modules/javascript-typescript-langserver/lib/language-server-stdio.js'],
      \ 'html': ['html-languageserver', '--stdio'],
      \ 'liquid': ['html-languageserver', '--stdio'],
      \ 'css': ['css-languageserver', '--stdio'],
      \ 'sass': ['css-languageserver', '--stdio'],
      \ 'scss': ['css-languageserver', '--stdio'],
      \ }
```

I found this: https://github.com/Microsoft/vscode-languageserver-node, but I think it is only supported in VS code for now.

**Comment by asilvadesigns** [comment]
@autozimu nevermind, I got this answer here:
https://github.com/sourcegraph/javascript-typescript-langserver/issues/375#issuecomment-337981090

**Comment by autozimu** [comment]
I believe <https://github.com/Microsoft/vscode-languageserver-node> is a framework for implementing language servers/clients, not an actual language server.

The settings looks good to me.

Might get better answers from language server repo.
