### ISSUE TITLE
PHP language server issues

### ISSUE THREAD

**Issue by phil-nelson** [autozimu/LanguageClient-neovim#15]
I've come across a couple more issues while testing compatibility with the php language server:

1. Using nvim-completion-manager, completion shows `null` in the list instead of the correct variable name, in `completionManager_refresh` doing the following gives me a better menu:
```
-                e['abbr'] = item.get('insertText', "")
+                if 'insertText' in item and item['insertText']:
+                    e['abbr'] = item.get('insertText', "")
```

Though when I select an item from the popup menu, it repeats the `$`, so if I type `$` and then select `$foo` from the menu, I get `$$foo`

2. in `showDiagnosticMessage()`, `entry["code"]` is an int, not a string, so `msg += code` fails, `msg += str(code)` works

3. In `LanguageClientStart()`, because `textDocument_didOpen` is being called straight after `self.initialize([])`, the `textDocument_didOpen` request is being sent before the InitializeResponse is received. The [specification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize) says:

> Until the server has responded to the initialize request with an InitializeResult the client must not sent any additional requests or notifications to the server.

This is causing completion to not work until I open a file after php-language-server has initialized.

Again, thanks for your work, this is really cool

**Comment by autozimu** [comment]
Thanks for your helpful investigation!

I will make updates when I got some time.

**Comment by autozimu** [comment]
@roxma when you have a second, can you take a look at the part1?

**Comment by roxma** [comment]
I will. I’m watching

**Comment by roxma** [comment]
The null issue could be fixed.

> Though when I select an item from the popup menu, it repeats the $, so if I type $ and then select $foo from the menu, I get $$foo

This relates to the word pattern and the proper calculation of startcol. which has been talked about before. https://github.com/autozimu/LanguageClient-neovim/pull/10#issuecomment-282200470

I'll do some more digging on how to deal with this issue.

**Comment by roxma** [comment]
https://github.com/Microsoft/vscode/blob/54b410174f2616dfbd0d2fe11c36993b06bc02d2/extensions/php/src/phpMain.ts#L29

@autozimu 
I think Language-client needs  some extra configurations for language server, to pass a word_pattern to NCM.

Just for a quick fix, I'll make the default pattern for php in NCM, do some tunning on LanguageClient, and send a PR.
