### ISSUE TITLE
echodoc is overshadowed by diagnostics

### ISSUE THREAD

**Issue by tepf** [autozimu/LanguageClient-neovim#157]
The diagnostics messages are triggered very frequently. They prevent echodoc from being able to display the function signature. I am not quite sure how to solve this best. Maybe preventing diagnostics from showing while still in insert mode?

**Comment by autozimu** [comment]
This latest commit will mitigate some cases of conflict between line diagnostic and echodoc.

But not all of them. There is plan to replicate echodoc functionality in this plugin, to resolve this issue and some other annoying issues fundamentally.

**Comment by tepf** [comment]
Can you put the signature on top of the completion popup menu while being non selectable? And whenever you're in the parameter space with your cursor it will the show parameters.

**Comment by DerWeh** [comment]
Maybe you can have a look at [jedi-vim](https://github.com/davidhalter/jedi-vim). It has the most awesome signature help I have ever seen in vim:
![grafik](https://user-images.githubusercontent.com/22542812/32799320-a5d7f954-c977-11e7-9de6-c33f99207bce.png)

The only problem was, that it was terrible slow to load. With Neovim this problem might be solved if it can be done asynchronous.

Sadly I have no idea of `vimscript` else I would look into it myself.

**Comment by autozimu** [comment]
That's probably would require hook up into completion framework, which I haven't dive deep yet.

Maybe there could be some collaboration work with @roxma.

**Comment by DerWeh** [comment]
I think the solution of `jedi-vim` worked with concealing instead of occupying the popup menu.
I think this solution should be preferable if it is feasible. If I remember correctly, the only issue was that it extremely slowed down startup. If it is possible to load it in the background with Neovim, it wouldn't been an issue anymore. I think everyone could live with signature help being not available the first 2s after starting Neovim.

**Comment by Shougo** [comment]
> Can you put the signature on top of the completion popup menu while being non selectable? And whenever you're in the parameter space with your cursor it will the show parameters.

It needs Vim/neovim support.

gonvim implements the feature, but it seems buggy.

https://github.com/dzhou121/gonvim#autocomplete-menu-and-function-signature
