### ISSUE TITLE
Allow restricting the display of messages based on type (warning, error)

### ISSUE THREAD

**Issue by hunter-** [autozimu/LanguageClient-neovim#159]
Sometimes I don't want a linter — sometimes I just want a language smartness provider :)

Let me turn off warning messages!

**Comment by autozimu** [comment]
Not in scope.

Language servers should support customization of diagnostic messages.

**Comment by hunter-** [comment]
Well, you made me happy by adding in `g:LanguageClient_diagnosticsEnable`!
