### ISSUE TITLE
Renaming of class truncates import path in Java

### ISSUE THREAD

**Issue by tepf** [autozimu/LanguageClient-neovim#161]
`SomeClass` is located in the directory`src/main/java/com/mycompany/app/nestedpack/SomeClass.java`. And renaming it inside `src/main/java/com/mycompany/app/Main.java`, a file located a directory higher like this

    import com.mycompany.app.nestedpack.SomeClass;
    public class Main {
        SomeClass sc = new SomeClass(); // <-- rename to OtherClass
    }

to `OtherClass` will result in a truncated and invalid import

    import OtherClass; // <-- path lost during renaming
    public class Main {
        OtherClass sc = new OtherClass();
    }

**Comment by autozimu** [comment]
Not an issue of this repo. You will need to file issue for jdt to get it fixed.

**Comment by tepf** [comment]
The renaming works in VS Code's LSP plugin. I don't think the issue is with jdt. Maybe this plugin loses the full path somewhere.

**Comment by autozimu** [comment]
Hmm, I tried with vscode before closing this issue as it didn't work for vscode either.

Which version of jdt server and client are you using in vscode?

**Comment by tepf** [comment]
Sorry. I was wrong. I thought that I remembered it working. VS Code has the same problem.
