### ISSUE TITLE
Support for alternative completion plugins.

### ISSUE THREAD

**Issue by jordwalke** [autozimu/LanguageClient-neovim#162]
It's unfortunate that `LanguageClient-neovim` requires python3 to achieve autocompletion in Vim (non-NeoVim). Would you consider adding support for other lighter weight completion plugins such as [mucomplete](https://github.com/lifepillar/vim-mucomplete)?

**Comment by chenglou** [comment]
Afaik this is the only part of this project that requires python3. Unfortunately some folks are still on 2, either because it's the macOS default or because of corporate constraints. Would be nice to see this happen =)

**Comment by autozimu** [comment]
Thanks for the suggestion.

I've used neovim for so long such that forgot the pain of using python3 plugin with vim.

**Comment by jordwalke** [comment]
For something as (imho) important as a LSP bridge from Vim, it would be great if Vim (at least Vim8) had a great experience. I have had good experiences with mucomplete (it's not async though - does that matter?)

**Comment by autozimu** [comment]
Being sync is not an blocker for supporting mucomplete.

In fact, the completion API can be used with vim `omnifunc`, which is a sync call, https://github.com/autozimu/LanguageClient-neovim/blob/master/doc/LanguageClient.txt#L40

**Comment by jordwalke** [comment]
So how much work is it to allow LanguageClient-neovim to work with mucomplete?

**Comment by autozimu** [comment]
Support mucomplete could be easily done.

Support vim + python2 will require some amount of work, especially since the dependency https://github.com/roxma/vim-hug-neovim-rpc is still not stable enough.

**Comment by jordwalke** [comment]
Sorry, could you catch me up - how is `vim-hug-neovim` relevant?

**Comment by jordwalke** [comment]
are there parts of `LanguageClient-neovim` that depend on `python3` specifically?

**Comment by jordwalke** [comment]
> I made a mistake taking this issue as request for support of vim + python2 specially

That is the case actually - I merely thought that the autocomplete plugin was the only issue blocking that.

**Comment by autozimu** [comment]
I'm not even sure if it is feasible of authoring plugin for both neovim and vim, and for both python2 and python3. If it is possible to support both neovim and vim, it probably requires a rehaul of this plugin, which might be better to reconsider the choice of python.

**Comment by autozimu** [comment]
Closing. See https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-350525383
