### ISSUE TITLE
codeAction command split, LSP Protocol, Haskell IDE Engine

### ISSUE THREAD

**Issue by meck** [autozimu/LanguageClient-neovim#166]
I'm trying to get codeAction to work with [Haskell ide engine](https://github.com/haskell/haskell-ide-engine) and noticed its splitting the commands on ":"  where as the protocol calls for ": " colon space.

HIE has the command applyrefact:applyOne so that breaks. I've tried changing the split and that works, however the codeAction itself is still not working, but I've not yet had time to look any more in depth at that yet.

**Comment by meck** [comment]
Seems HIE works fine with codeAction when I do this:
``    def fzfSinkTextDocumentCodeAction(self, lines: str) -> None:
        command, title = lines[0].split(": ")
``
in LanguageClient.py, I could do a PR if you want it, I'm not sure how other Language Servers would work in this regard...

**Comment by autozimu** [comment]
PR is welcome.
