### ISSUE TITLE
when call function which is not in current repo get errors.

### ISSUE THREAD

**Issue by wsdjeg** [autozimu/LanguageClient-neovim#168]
I get unknown function error when using this plugin in Vim.

I thinking it should surrounded by try catch when using function not in current repo.

**Comment by autozimu** [comment]
Which function is generating errors? What errors do you get?

**Comment by wsdjeg** [comment]
here is where the error is，https://github.com/autozimu/LanguageClient-neovim/blob/master/plugin/LanguageClient.vim#L8

**Comment by wsdjeg** [comment]
@autozimu sorry, this is fix by install yarp.
