### ISSUE TITLE
Get errors when edit markdown or vim file.

### ISSUE THREAD

**Issue by wsdjeg** [autozimu/LanguageClient-neovim#169]
> If you are reporting a bug, please read following FAQ first.

# Not editor command: LanguageClientStart?
Have you followed the instructions at
[INSTALL.md](https://github.com/autozimu/LanguageClient-neovim/blob/master/INSTALL.md)?

If not, please try follow the instructions there first.

# If you are still seeing an error or other types of issue, please create ticket with
- neovim version latest
- Plugin version (git SHA) master
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim>).
- Content of `:CheckHealth`.  both python and python3 are supported.
- Content of `~/.local/share/nvim/rplugin.vim`.
- Language server name and version.
- Reproduction steps (from clean state).
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach contents of
  `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.

(Please understand the more detailed information provided, the sooner a issue
can be resolved. Low quality bug reports might be closed directly.)

I can not understand why this sources is called when edit file which is not listed in `keys(g:LanguageClient_serverCommands)`?

````log
[deoplete] Traceback (most recent call last):                                                                                                          
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 137, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/SpaceVim/LanguageClient-neovi/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 68, in gather_candidates
[deoplete] Traceback (most recent call last):
[deoplete]     result = LanguageClient._instance.textDocument_completion(
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugi/python3/deoplete/deoplete.py", line 137, in gather_results
[deoplete] Too many errors from "LanguageClient". This source is disabled until Neovim is restarted.
[deoplete] AttributeError: 'NoneType' object has no attribute 'textDocument_completion'
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete] Could not get completions from: LanguageClient.  Use :messages for error details.
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/SpaceVim/LanguageClient-neovi/rplugin/python3/deoplete/sources/LanguageClientSource.py", line 68, in gather_candidates
[deoplete]     result = LanguageClient._instance.textDocument_completion(
[deoplete] AttributeError: 'NoneType' object has no attribute 'textDocument_completion'
[deoplete] Could not get completions from: LanguageClient.  Use :messages for error details.
```

**Comment by autozimu** [comment]
It is that this plugin was never initialized in your case. Probably because the special layout of how plugins are structured.

deoplete will try invoke all suitable sources by default. But you can customize the behaviour. Check it's documentation.
