### ISSUE TITLE
Problem with jumping

### ISSUE THREAD

**Issue by cryptomaniac512** [autozimu/LanguageClient-neovim#171]
I have a problem with jumping back - if I go to definition and then press C-o, I may be not in previous place.
I have this problem with pyls and not test it with another language servers.

For example, I navigate to class signature, set cursor at class parent, then go to definition and then press C-o. I expect to be at class signature, but often it is first line (of file where I start working) or another file edited previously.

Sorry for bad English

**Comment by autozimu** [comment]
It is not English. I'm not native English speaker as well. But could you please follow issue template?

**Comment by tepf** [comment]
You can only go back to searches, substitutes and marks with <C-o>. For [more info](http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations).

You could create a go to definition shortcut and automatically add a mark to your call position like this:

    nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>:normal! m`<CR>

**Comment by cryptomaniac512** [comment]
@tepf, thank you!
