### ISSUE TITLE
Disable Completion

### ISSUE THREAD

**Issue by still-dreaming-1** [autozimu/LanguageClient-neovim#172]
Is there a way to disable completion? Go to definition is now the only feature that is helping me that is not causing too many issues.

**Comment by tepf** [comment]
Will disabling your preferred completion plugin (e.g. deoplete) do?

**Comment by still-dreaming-1** [comment]
Not exactly, but I did disable the language client as a completion source in Deoplete, although I would rather have disabled it at the source. For me it doesn't really matter anymore since I have that deoplete option and I stopped using language servers.

**Comment by autozimu** [comment]
Not going to support (at least from me).

Generally, completion plugins, like deopelte or NCM, supports disable source individually.
