### ISSUE TITLE
Feature request: automatically open/close the diagnostics list

### ISSUE THREAD

**Issue by euclio** [autozimu/LanguageClient-neovim#173]
It would be nice if there were an option to automatically open or close the diagnostics list, depending on whether there are any errors or not.

**Comment by davidosomething** [comment]
would be nice to disable it completely, especially, since it tends to clear/break neomake's lint loclist

**Comment by autozimu** [comment]
@davidosomething It is already possible to disable diagnostics  https://github.com/autozimu/LanguageClient-neovim/blob/master/doc/LanguageClient.txt#L140

**Comment by davidosomething** [comment]
i mean disable toggling the auto-open of the qf list

**Comment by autozimu** [comment]
The problem could be solved by exposing autocmd events. Blindly auto-open/close quickfix window seems such an intrusive UX.
