### ISSUE TITLE
triggerCharacters is optional, so NCM shouldn't skip registering if it doesn't exists

### ISSUE THREAD

**Issue by prabirshrestha** [autozimu/LanguageClient-neovim#18]
//cc @roxma 

```typescript
export interface CompletionOptions {
    /**
     * The server provides support to resolve additional
     * information for a completion item.
     */
    resolveProvider?: boolean;

    /**
     * The characters that trigger completion automatically.
     */
    triggerCharacters?: string[];
}
```

`triggerCharacters` is optional, so if `completionProvider` exists in capabilities but `triggerCharacters` doesn't it should continue to register the source instead of `pass`.

```python
    def registerCMSource(self, result: Dict) -> None:
        trigger_patterns = []
        try:
            for c in result['capabilities']['completionProvider']['triggerCharacters']:  # noqa E501
                trigger_patterns.append(re.escape(c)+'$')
        except:
            pass


    ....register ncm source...
```

**Comment by autozimu** [comment]
In described situation, current code does continue to register ncm source with trigger_patterns of [].

Can you specify more explicitly about the issue?

**Comment by prabirshrestha** [comment]
Now that I look careful you are right. I'm not used to python code.

I think there is still another bug. If the `completionProvider` doesn't exist it shouldn't register the source. For example if I have a linter as language server it will most likely not support completion capabilities.

**Comment by autozimu** [comment]
Yeah, you are right.

I will fix that shortly.
