### ISSUE TITLE
LanguageClient does not send didChange on LanguageServerStart if buffer is dirty

### ISSUE THREAD

**Issue by cazador481** [autozimu/LanguageClient-neovim#180]
If the document buffer is dirty the LanguageClient does not send a didChange on start of the LanguageServer.
I do see a didopen command.

> If you are reporting a bug, please read following FAQ first

# Not editor command: LanguageClientStart?
Have you followed the instructions at
[INSTALL.md](https://github.com/autozimu/LanguageClient-neovim/blob/master/INSTALL.md)?

If not, please try follow the instructions there first.

# If you are still seeing an error or other types of issue, please create ticket with
- neovim version 
0.2.0
- Plugin version (git SHA)
 a54485aec89cd52ed0dc35b0fc5ba93d41f64eea
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim>).
- Content of `:CheckHealth`.
- Content of `~/.local/share/nvim/rplugin.vim`.
- Language server name and version.
LanguageServer-Perl
- Reproduction steps (from clean state).
Open a perl document
edit document
StartLanguageServer
StopLanguageServer
StartLanguageServer
# only open document rpc called, change rpc is not called
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach contents of
  `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
18:39:39 WARNING [MainThread] Unknown parameter key: rootPath
18:39:44 INFO    [MainThread] Begin handle TextChangedI
18:39:44 INFO    [MainThread] Begin handle TextChanged
18:39:45 INFO    [MainThread] deoplete LanguageClientSource initialized.
18:39:45 DEBUG   [MainThread] Gathered arguments: ['uri', 'buftype'] = ['file:///home/eash/scripts/Language-Server/t/test.pm', '']
18:39:45 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:45 DEBUG   [MainThread] Gathered arguments: ['self', 'uri', 'languageId'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, 'file:///home/eash/scripts/Language-Server/t/test.pm', 'perl']
18:39:45 INFO    [MainThread] textDocument/didChange
18:39:45 DEBUG   [MainThread] => {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/eash/scripts/Language-Server/t/test.pm","version":2},"contentChanges":[{"text":"my $ea; my $ea2;\n\n\nmy $ea4; my $ea5;\n\n"}]}}
18:39:51 INFO    [MainThread] Begin handle TextChangedI
18:39:51 INFO    [MainThread] Begin handle TextChanged
18:39:51 DEBUG   [MainThread] Gathered arguments: ['uri', 'buftype'] = ['file:///home/eash/scripts/Language-Server/t/test.pm', '']
18:39:51 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:51 DEBUG   [MainThread] Gathered arguments: ['self', 'uri', 'languageId'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, 'file:///home/eash/scripts/Language-Server/t/test.pm', 'perl']
18:39:51 INFO    [MainThread] textDocument/didChange
18:39:51 DEBUG   [MainThread] => {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///home/eash/scripts/Language-Server/t/test.pm","version":3},"contentChanges":[{"text":"my $ea; my $ea2;\n\n\nmy $ea4; my $ea5;\n:\n"}]}}
18:39:52 INFO    [MainThread] Begin handle CursorMoved
18:39:52 DEBUG   [MainThread] Gathered arguments: ['buftype', 'line'] = ['', 4]
18:39:52 DEBUG   [MainThread] state.last_cursor_line: 0 => 4
18:39:52 DEBUG   [MainThread] Gathered arguments: ['uri', 'line', 'columns'] = ['file:///home/eash/scripts/Language-Server/t/test.pm', 4, 113]
18:39:52 INFO    [MainThread] Begin show_line_diagnostic
18:39:57 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:57 DEBUG   [MainThread] Gathered arguments: ['self', 'languageId'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, 'perl']
18:39:57 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:57 DEBUG   [MainThread] Gathered arguments: ['self', 'languageId'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, 'perl']
18:39:57 INFO    [MainThread] exit
18:39:57 DEBUG   [MainThread] => {"jsonrpc":"2.0","method":"exit","params":{}}
18:39:57 DEBUG   [MainThread] state.servers.perl: <subprocess.Popen object at 0x7ffff0a43c18> => None
18:39:57 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:57 INFO    [MainThread] Begin LanguageClientStart
18:39:57 INFO    [RPC-perl  ] waiting for content
18:39:57 INFO    [RPC-perl  ] <= {"error":{"message":"Method not found.","code":-32601},"id":null,"jsonrpc":"2.0"}

18:39:57 INFO    [RPC-perl  ] Waking up: None
18:39:57 DEBUG   [MainThread] state.rpcs.perl: <LanguageClient.RPC.RPC object at 0x7ffff0a4f9b0> => <LanguageClient.RPC.RPC object at 0x7ffff0710e10>
18:39:57 DEBUG   [MainThread] state.servers.perl: None => <subprocess.Popen object at 0x7ffff074b278>
18:39:57 INFO    [MainThread] End LanguageClientStart
18:39:58 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:58 WARNING [MainThread] Unknown parameter key: rootPath
18:39:58 DEBUG   [MainThread] Gathered arguments: ['self', 'rootPath', 'languageId', 'handle'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, None, 'perl', True]
18:39:58 INFO    [MainThread] Begin initialize
18:39:58 INFO    [MainThread] rootPath: /home/eash/scripts/Language-Server
18:39:58 DEBUG   [MainThread] => {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":9697,"capabilities":{"textDocument":{"completion":{"completionItem":{"snippetSupport":true}}},"workspace":{"applyEdit":true}},"trace":"off","rootPath":"/home/eash/scripts/Language-Server","rootUri":"file:///home/eash/scripts/Language-Server"}}
18:39:58 INFO    [RPC-perl  ] waiting for content
18:39:58 INFO    [RPC-perl  ] <= {"jsonrpc":"2.0","result":{"capabilities":{"referencesProvider":0,"workspaceSymbolProvider":0,"documentRangeFormattingProvider":0,"hoverProvider":0,"codeLensProvider":0,"codeActionProvider":0,"documentHighlightProvider":0,"textDocumentSync":1,"documentSymbolProvider":0,"documentOnTypeFormattingProvider":{},"renameProvider":1,"documentFormattingProvider":1,"definitionProvider":0}},"id":0}

18:39:58 INFO    [RPC-perl  ] Waking up: 0
18:39:58 DEBUG   [MainThread] Gathered arguments: ['languageId'] = ['perl']
18:39:58 DEBUG   [MainThread] Gathered arguments: ['self', 'uri', 'languageId'] = [<LanguageClient.LanguageClient.LanguageClient object at 0x7ffff0aa25c0>, 'file:///home/eash/scripts/Language-Server/t/test.pm', 'perl']
18:39:58 INFO    [MainThread] Begin textDocument/didOpen
18:39:58 DEBUG   [MainThread] state.file:///home/eash/scripts/Language-Server/t/test.pm.textDocument: {"uri": "file:///home/eash/scripts/Language-Server/t/test.pm", "languageId": "perl", "text": "my $ea; my $ea2;\n\n\nmy $ea4; my $ea5;\n:\n", "last_update": 1511059191.6426988, "version": 3, "dirty": false} => {"uri": "file:///home/eash/scripts/Language-Server/t/test.pm", "languageId": "perl", "text": "my $ea; my $ea2;\n\n\nmy $ea4; my $ea5;\n:\n", "last_update": 1511059198.6991496, "version": 1, "dirty": true}
18:39:58 DEBUG   [MainThread] => {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/eash/scripts/Language-Server/t/test.pm","version":1,"languageId":"perl","text":"my $ea; my $ea2;\n\n\nmy $ea4; my $ea5;\n:\n"}}}
18:39:58 INFO    [MainThread] End textDocument/didOpen
18:39:58 INFO    [MainThread] End initialize

(Please understand the more detailed information provided, the sooner a issue
can be resolved. Low quality bug reports might be closed directly.)

**Comment by autozimu** [comment]
Closed in db1a3cfca09dbfd4350fe04c10084194d77cca1c. Thanks for reporting.
