### ISSUE TITLE
Support for textDocument/definition to show a list for jump

### ISSUE THREAD

**Issue by swistak35** [autozimu/LanguageClient-neovim#182]
Hello and thank you for creating this great project which brings LSP to neovim :)

I have a question - is there a plan to support `textDocument/definition` displaying results in some quickfix window if there's more than one result ( https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L641 )? I imagine it working like vim built-in ctags support, with a command to "if there's one result, jump to it, if there's more, display quickfix window".

**Comment by autozimu** [comment]
Could you give an sample of this use case?

The support could be easily added but I'm holding on it because haven't found a test case so that I can verify it.

**Comment by swistak35** [comment]
In dynamic languages which allow class/method definitions on the fly (like ruby, probably javascript too for example), a tool can't be 100% sure about definition place, so it can only provide a list of it's best guesses. It is especially true when you try to jump to the definition of the method (static resolution of the constants is relatively accurate, but it also can't be done with 100% accuracy).

I'm writing an LSP server for ruby and for now I've quite often have at least few results (in the current state my server's accuracy is very close to the pure ctags, but still, I'm sure it will always have possibility for more than one result). Therefore, when you try to use it and you always jump to the first result, which is often wrong, you don't get best experience :)

**Comment by autozimu** [comment]
Yes, I totally understand this is a useful case.

I meant, do you have a example project to return multiple definitions so that I can verify myself after I make the change?

**Comment by swistak35** [comment]
For my own server, I don't have yet good installation instructions because it is very alpha stage. I've found however that `Python Language Server` which can be considered popular already, is returning multiple definitions.

I have installed python language server with following config:

```
let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ }
```

and I have used following obvious file for which one can't predict only *one* place of definition:

```
class Test1:
    def foo(self, x):
        print("Test1 %d" % x)

class Test2:
    def foo(self, x):
        print("Test2 %d" % x)


def bar(some_test_object):
    some_test_object.foo(42)


bar(Test1())
bar(Test2())
```

I have then placed cursor on `foo` method call on `some_test_object` at line 11. After jumping, it jumps to the first definition and I see in `LanguageClient.log` an error `11:45:42 ERROR   [MainThread] Handling multiple definitions is not implemented yet. Jumping to first.` which is displayed only if there's more than one definition to jump. Do you need any more details?

**Comment by autozimu** [comment]
Great. That was what I was looking for.
