### ISSUE TITLE
Is it possible to use this plugin without Python3?

### ISSUE THREAD

**Issue by romix** [autozimu/LanguageClient-neovim#184]
It looks like this plugin requires Python3. If this is the case, can something be done so that it works with Python2 as well?

**Comment by Shougo** [comment]
Why Python2 support is needed?
Python2 will be obsolete in 2020.

**Comment by romix** [comment]
It is just the default setting on most MacBooks. And so far I could use all other plugins without changing the defaults, etc.

**Comment by romix** [comment]
But if you could point to a simple description of how to configure vim/nvim on MacOS to use Python3, it would work as well.

In general, the only reason for filing this issue is to make this plugin work for MacBook owners out-of-the-box. As I mentioned, most other plugins I use (and I use may be 20 plugins) do not fail on MacBooks even if Python3 is not set as a default.

**Comment by Shougo** [comment]
> It is just the default setting on most MacBooks. And so far I could use all other plugins without changing the defaults, etc.

Can you install Python3 on MacBooks?

I think new Vim/neovim plugins should not support Python2.
The support of Python2 increases the maintainance cost.

**Comment by Shougo** [comment]
> In general, the only reason for filing this issue is to make this plugin work for MacBook owners out-of-the-box. As I mentioned, most other plugins I use (and I use may be 20 plugins) do not fail on MacBooks even if Python3 is not set as a default.

I have created the Python3 only plugins, but no claim from Mac users.

**Comment by romix** [comment]
No problem. 

I'll try to find a good reference about configuring vim/nvim + Python3 on MacBooks and  paste it here. It may help other MacBook users.

**Comment by languitar** [comment]
just install everything via homebrew...

**Comment by autozimu** [comment]
Closing. See https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-350525383
