### ISSUE TITLE
Add support for user provided project root & root markers

### ISSUE THREAD

**Issue by xbreak** [autozimu/LanguageClient-neovim#186]
This is feature request is the outcome from a discussion in PR #185, to accommodate projects with uncommon project structures, by allowing the user to specify either root marker(s) or a root path.

- `g:LanguageClient_rootMarkers` a list of markers to look for when searching upwards, that if found, identifies the project root. 
- `g:LanguageClient_root` directly specifies the project root and is default none.  If specified it takes precedence over `g:LanguageClient_rootMarkers`.

**Questions:**
To keep a backwards compatibility in behaviour, the options could be fully optional and default not set by at all. But if any of these options are set, the current rules in `utils.get_rootPath` should not be used.

Does `g:LanguageClient_rootMarkers` need to be language dependent? What would the impact be if the user instead set the root marker in a filetype autocmd for example?

LSP uses the term `rootUri`, should that term be used instead? I think so.
- `g:LanguageClient_rootUri`
- `g:LanguageClient_rootUriMarkers`

**Comment by autozimu** [comment]
Right now, we can implement it as language independent, which can be later extended to support language dependent by allowing
```vim
rootMarkers = {
    \ 'javascript': ['packge.json'],
    \ };
```
But could be done in a future work.

I'd prefer the name `rootMarkers`, as in LSP the name `rootUri` has both the meaning of variable name `root` and type `uri`. In this case though, we care only about the `root`.

**Comment by DeltaEvo** [comment]
@autozimu I think we can implementing it directly as language dependent because it do not require a lot of work. 
I will try to do it tomorrow and send a PR

**Comment by DeltaEvo** [comment]
Finally with the new branch `next` and @autozimu rewriting everything in Rust I think it's better to wait for him to finish 

(PS: Rust ❤️  FTW)
