### ISSUE TITLE
Add a bidirectional (supporting forward/backward) jump list for LanguageClient_textDocument_{references,definitions}

### ISSUE THREAD

**Issue by MaskRay** [autozimu/LanguageClient-neovim#189]
It will be useful to have a separate jump list (different from the standard jump list `<C-o>` `<C-i>` ) for xrefs jumps. After `LanguageClient_textDocument_{references,definitions}`, it is common for me to navigate around the jump target and it will be convenient to have a single key to jump back.

**Comment by autozimu** [comment]
Why is `C-I` and `C-O` is not sufficient?

Or alternatively, you can always create your marks along with the function call in your mappings, like in https://github.com/autozimu/LanguageClient-neovim/issues/171#issuecomment-344064377

**Comment by MaskRay** [comment]
Because I may do a few more movement after jumping to the target. You may see this as the LSP counterpart of `<C-t>` (jumping backward in the tag stack)

**Comment by autozimu** [comment]
Let's say we're in the process of tracing back implementations, and called xref three times, at this point, we want to go back to the initial tracing back starting point, but how can the program know which location you want to go back to?

I still believe it's should be done manually and explicitly by marking the initial starting point. Or live with the multiple `<C-O>`.

**Comment by autozimu** [comment]
Closing as not feasible.
