### ISSUE TITLE
simplify_snippet in deoplete source doesn't work

### ISSUE THREAD

**Issue by yshui** [autozimu/LanguageClient-neovim#192]
It only removes `$0`, but not `${0:text}`

**Comment by autozimu** [comment]
I believe this has already been resolved in https://github.com/autozimu/LanguageClient-neovim/pull/193

**Comment by jandamm** [comment]
Sorry for commenting on this issue after such a long time but I have exactly the same issue.
I'm using the sourcekit-lsp from Apple and in every input I get `${1:value}` which does not get replaced by deoplete.
Is there a way to enable `simplify_snippets` or should this already activated?
