### ISSUE TITLE
Possible to get output of LanguageClient_textDocument_hover() as variable?

### ISSUE THREAD

**Issue by Tehnix** [autozimu/LanguageClient-neovim#197]
In the same line of https://github.com/parsonsmatt/intero-neovim/issues/118, I'm currently trying to capture the echo output of `call LanguageClient_textDocument_hover()` so I can manipulate it a bit and show it when the cursor is being held on the same word for a short while, but had little luck.

Would it be possible to have an alternate version that simply returns the output instead of echo'ing it? Or perhaps just accept a `funcref` callback?

**Comment by autozimu** [comment]
The short answer is no.

There are two options here,
1. Use the `next` branch. The codebase is mostly done, but lacks documentation. I can answer question here if you have any.
2. With current `master` branch, replace the parameter of `handle` with a funcref, e.g., https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L590. I was originally planning support such use cases, but found out that neovim remote functions has to be either sync or async. Making those calls sync is not acceptable, thus `handle` parameter never worked.

**Comment by autozimu** [comment]
Branch `next` has already been released.

To give some guidance, you can call hover with
```
call LanguageClient_textDocument_hover({}, callback)
```

where `callback` should be similar with https://github.com/autozimu/LanguageClient-neovim/blob/next/plugin/LanguageClient.vim#L179-L188

Let me know if you need any further help.

**Comment by Tehnix** [comment]
Sorry for not getting back to you on this - the new release is working perfectly, thanks so much for this! :)
