### ISSUE TITLE
Gracefully handle selective load of LanguageClient

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#198]
The rplugin for LanguageClient presumes that the LanguageClient plugin will always be loaded. It is oftentimes advantageous to use a vim plugin manager that offers selective loading of plugins (like dein) and configuring it to load plugins only when they are needed.

I have LanguageClient set to only load for certain file types, but since the rplugin is always loaded, I am getting some errors if I start neovim without LanguageClient. In particular, I see the following under neovim 0.2.3 builds:

```
no notification handler registered for "/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:BufReadPost:*" 
Press ENTER or type command to continue
no notification handler registered for "/home/mqudsi/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:CursorMoved:*" 
Press ENTER or type command to continue
```

If reproduction steps are required, I can provide that. However, I am presuming that this is by design and that the LanguageClient rplugin assumes the LanguageClient vim plugin will always be loaded, leading to this error. I did not previously see these errors, so I'm presuming it's a recent update.

**Comment by DerWeh** [comment]
`It is oftentimes advantageous to use a vim plugin manager that offers selective loading of plugins (like dein) and configuring it to load plugins only when they are needed.`

Why is that the case for `LanguageClient`. As fare as I know, it is only important for badly written plug-ins which don't use `autoload`.
Using [Startuptime](https://github.com/tweekmonster/startuptime.vim) says that the `LanguageClient` needs 0.010 ms to start. So what is the advantage of lazy loading it?

**Comment by autozimu** [comment]
Branch `next` should already support this feature.

**Comment by mqudsi** [comment]
Thank you.
