### ISSUE TITLE
PHP language server issues

### ISSUE THREAD

**Issue by phil-nelson** [autozimu/LanguageClient-neovim#2]
I did a quick test with https://github.com/felixfbecker/php-language-server and found a couple of issues, I did quick fixes to continue testing, I will try and create pull requests but if these are easy for you then you can probably do them faster than me as my python is not great. After the quick fixes starting/initialising/hover/go to definition all worked, I haven't done further testing yet:

* RPC.py serve() assumes only one header, whereas php-language-server sends more than one. So it needs to parse headers and get Content-Length.
* LanguageClient.py handleTextDocumentDefinitionResponse() assumes an array of one result however php-language-server just returns one result directly (not array) (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover - see `contents: MarkedString | MarkedString[];`

Great work this is exciting stuff!

**Comment by autozimu** [comment]
Thanks for reporting. I will try fix them today.
