### ISSUE TITLE
LanguageClient_textDocument_formatting() gives undefined variable error

### ISSUE THREAD

**Issue by ffky** [autozimu/LanguageClient-neovim#204]
- neovim/vim version: NVIM v0.2.3-dev
- Plugin version (git SHA): f0d5820e098e723c1868e236bf36bd502825c537
- Minimal vimrc 
  ```
  call plug#begin('~/.vim/plugged')
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': './install.sh' }
  call plug#end()
  let g:LanguageClient_serverCommands = {
      \ 'ocaml': ['ocaml-language-server', '--stdio'],
      \ }
  ```
- Language server name/link and version
https://github.com/freebroccolo/ocaml-language-server
1.0.16
- Reproduction steps (from clean state)

    - Created a test file called test.ml. Pasted in a short example

  ``` ocaml
  type schoolPerson =
    | Teacher
    | Director
  let greeting stranger =
    match stranger with
    | Teacher  -> "Hey professor!"
    | Director  -> "Hello director."
  ```

    - Ran `:call LanguageClient_textDocument_formatting()`. I get a `Vim(let):E121: Undefined variable: tabstop` error in my status line. Other commands such as `LanguageClient_textDocument_definition()` and `LanguageClient_textDocument_hover()` work as expected.

- Logs

  [LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1547504/LanguageClient.log)

  LanguageServer.log (empty)

Let me know if I can provide any more useful information! Thanks!

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by euclio** [comment]
With the new change, I'm still getting an error: ``invalid type: integer `1`, expected a boolean``.

**Comment by autozimu** [comment]
Sorry about that. Need some extra work.

**Comment by autozimu** [comment]
Please try latest fix and let me know if it still doesn't work. Thanks.

**Comment by ffky** [comment]
Confirmed it works with latest @ 92c8475a303b3803b005c4818b552582a0af4f07. Thank you!
