### ISSUE TITLE
textDocument/formatting leaves extra code behind

### ISSUE THREAD

**Issue by euclio** [autozimu/LanguageClient-neovim#206]
- neovim/vim version: nvim 0.2.2
- Plugin version (git SHA): 8075feeebabe442eb56aa422ebcd37ec278dae9e
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
- Language server name/link and version: rls-preview 0.124.0-nightly (be23ad3 2017-12-06)
- Reproduction steps (from clean state)
    1. Create a new cargo project with a main.rs with the following contents:
         ```
         fn main() {
             println!("Hello, world!");

             let mut test = 


             5;

             test = 4;
        }
        ```
    2. `:call LanguageClient_textDocument_formatting()`
    3. Observe that the document is formatted as
        ```
        fn main() {
            println!("Hello, world!");

            let mut test = 5;

            test = 4;
       }

            test = 4;
       }
       ```
- Logs. Run `:call LanguageClient_setLoggingLevel('DEBUG') |
:LanguageClientStop | :LanguageClientStart`, follow previous provided
reproduction steps to reproduce the bug. Attach contents of
`/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.

[logs.log](https://github.com/autozimu/LanguageClient-neovim/files/1550049/logs.log)

This formatting appears to work correctly in vscode, so I don't think it's a bug in the rls.

**Comment by autozimu** [comment]
Thanks for reporting. The bug is in https://github.com/autozimu/LanguageClient-neovim/blob/next/src/languageclient.rs#L536

But I haven't figured out a straightforward fix yet.
