### ISSUE TITLE
file URI without authority field

### ISSUE THREAD

**Issue by eed3si9n** [autozimu/LanguageClient-neovim#207]
- neovim version NVIM v0.2.2
- Plugin version (git SHA) eac16849eb5cb5592cf043fa222282a7082f257b
- Language server name/link and version sbt 1.1.0-RC1 (http://www.scala-sbt.org/) with https://gist.github.com/eed3si9n/0ee26a15218f1d4031b451dd61315d6c

## steps

1. Install sbt 1.0.4 launcher.
2. Download https://gist.github.com/eed3si9n/0ee26a15218f1d4031b451dd61315d6c to `~/bin/`
3. vimrc:

```
let g:LanguageClient_autoStart = 1

let g:LanguageClient_serverCommands = {
    \ 'scala': ['node', '/Users/foo/bin/sbt-server-stdio.js']
    \ }
```

4. Create a hello world Scala application.

project/build.properties:

```
sbt.version=1.1.0-RC1
```

build.sbt:

```scala
lazy val root = (project in file("."))
```

Hello.scala:

```scala
object Hello extends App {
  println("
}
```

5. Run sbt on the working directory.

6. Add whitespace after `"` and save.

7. `:cc`

Log file: https://gist.github.com/eed3si9n/03e3f68247b9fe8e1ec6955561aa9feb

## problem

`:cc` returns `E42: No Errors`.

The diagnosis report is not being registered.

## notes

This is likely due to sbt server sending URI in the form `file:/Users/someone/work/vimtest/Hello.scala` without the authority/host field, which is legal under [RFC 8089](https://tools.ietf.org/html/rfc8089#appendix-B) that came out in 2017. Changing it to `file:///Users/someone/work/vimtest/Hello.scala` with 3 slashes fixes the issue, but I thought you might want to know.

**Comment by autozimu** [comment]
Don't know why this language server use this uncommon form in the first place.

You can switch to branch `next`, as the rust implementation can support this form.

I don't have enough time/interest to fix the master/python implementation, but PRs are always welcome.
