### ISSUE TITLE
Python Language Service Hang

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#21]
Problem:
----
Language Client ceases to work after editing for a while. Diagnostic remains even if errors are fixed. No completion is suggested. But the plugin initially works well.

https://github.com/palantir/python-language-server

Env:
----
LC version: master
neovim version: NVIM 0.1.7
Python Language Server version: master.
OS:  producible on both mac OS & Linux

Log: 
---

I have modified logging to record all raw server/client output, so I think it quite useless without source code. 

However, my conclusion is that Client side works well, except reading blocks.

A typical raw log looks like this:

```
15:25:08 INFO    Content-Length: 899
15:25:08 INFO    Content-Type: application/vscode-jsonrpc; charset=utf8
15:25:08 INFO    {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///code/test/python-language-server/pyls/__main__.py","diagnostics":[{"source":"pycodestyle","range":{"start":{"line":31,"character":79},"end":{"line":31,"character":112}},"message":"E501 line too long (111 > 79 characters)","code":"E501","severity":1},{"source":"pycodestyle","range":{"start":{"line":35,"character":79},"end":{"line":35,"character":90}},"message":"E501 line too long (89 > 79 characters)","code":"E501","severity":1},{"source":"pycodestyle","range":{"start":{"line":37,"character":79},"end":{"line":37,"character":89}},"message":"E501 line too long (89 > 79 characters)","code":"E501","severity":1},{"source":"pycodestyle","range":{"start":{"line":37,"character":89},"end":{"line":37,"character":89}},"message":"W292 no newline at end of file","code":"W292","severity":2}]}}
```

Finding:
----

After some changes to logging, I found both  language server and client stop to reading from /writing to stdio.

Related source.

Client block:
https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/RPC.py#L73

Server block:
https://github.com/palantir/python-language-server/blob/master/pyls/jsonrpc.py#L155

I don't know if it is server's problem or client problem. However, I cannot reproduce it with golang server.

**Comment by autozimu** [comment]
Thanks for this fantastic report.

I will look into it sometime today.

**Comment by HerringtonDarkholme** [comment]
After long long trial and error like debugging, it might be Python Language Server's logging problem.

PLS will log to stderr by default. And Language Client opens PLS as `Popen(stderr=pipe)`. So stderr's buffer is filled after several editing. Strangely, it also blocks stdout.

Removing `stderr=pipe` in Language Client can mitigate hanging, however, I still found occasional hang for Language Server. But this time in `stdout.write` not `stdout.flush`.

**Comment by autozimu** [comment]
Hmm, that's interesting.

I've been busy right now, so I haven't got time to look into it yet.

You can take a look at the [wrapper.sh here](
 https://github.com/autozimu/LanguageClientneovim/blob/master/rplugin/python3/LanguageClient/wrapper.sh), which might help debugging in this case.

**Comment by autozimu** [comment]
I got the issue reproduced locally.

It is more of a language server issue. As by default, the python language server output debug level logging message into stderr.

I cannot remove the `stderr=pipe` part cause it is very useful when the language server quit unexpectedly.

As a workaround for python language server, you can create a wrapper to redirect its stderr to some log file, or even /dev/null. Something like
```
pyls 2>>/tmp/pyls.log
```

**Comment by HerringtonDarkholme** [comment]
Indeed. PLS needs much improvement.

Close this issue for now since LanguageClient is doing well.
If I can find improvement I will open new issue for it.
