### ISSUE TITLE
Formatting leaves last lines if the file becomes shorter

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#212]
If formatting makes the current file shorter, all lines past the new last line remain.

- neovim/vim version: NVIM v0.2.0
- Plugin version (git SHA): 7c4624d71d018b59f68f5978e20538f0a0fbd169
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>): yes
- Language server name/link and version: rls-preview 0.124.0-nightly (be23ad3 2017-12-06)
- Reproduction steps (from clean state)
    1. Make a new Cargo project: `cargo new --bin temp`
    2. `nvim temp/src/main.rs`
    3. Insert a couple of blank lines inside the `main` function
    4. `:call LanguageClient_textDocument_formatting()`
    5. Observe that the blank lines were deleted, but all lines after the new last line were left.
- Logs. Run `:call LanguageClient_setLoggingLevel('DEBUG') |
:LanguageClientStop | :LanguageClientStart`, follow previous provided
reproduction steps to reproduce the bug. Attach contents of
`/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`: [LanguageClient.log](http://sprunge.us/OfYT) [LanguageServer.log](http://sprunge.us/DbZg)

**Comment by autozimu** [comment]
Could you run
```
bin/languageclient --version
```
inside this plugin folder and paste the output here?

As this issue should have been fixed in https://github.com/autozimu/LanguageClient-neovim/commit/420ff743c87cbe572d3be9a4b4321f27d87c2146, but it might not been included in binary releases yet as there were some issues with release process.

**Comment by YaLTeR** [comment]
That gave me `languageclient UNKNOWN (UNKNOWN 2017-12-12)`

**Comment by YaLTeR** [comment]
Built the latest version locally (`make release`) and it works fine. Looking at the Travis log, it only updates the GitHub release only on tagged commits, so since there weren't any, the change hasn't made it through yet.

**Comment by YaLTeR** [comment]
So, it looks like if the result is only 1 line shorter, it still remains.

**Comment by autozimu** [comment]
Oops, sounds like an off-by-1 bug.
