### ISSUE TITLE
textDocument_didOpen sends null as version

### ISSUE THREAD

**Issue by meck** [autozimu/LanguageClient-neovim#213]
This functions send no version number 
[here](https://github.com/autozimu/LanguageClient-neovim/blob/7c4624d71d018b59f68f5978e20538f0a0fbd169/src/languageclient.rs#L1287)

This makes Haskell langserver complain:
`("uri",String "file:///Users/meck/test/src/Main.hs"),("version",Null)]))])),("method",String "textDocument/didOpen")])
 "expected Int, encountered Null"`

I see that the state needs to be set in this function. However I'm not proficient enough in rust for a PR

**Comment by autozimu** [comment]
Thanks for reporting. Should be able to fix by replacing `None` with `Some(0)`.
