### ISSUE TITLE
High CPU Usage when language server does not start

### ISSUE THREAD

**Issue by minijackson** [autozimu/LanguageClient-neovim#214]
- neovim version: v0.2.3-240-g6ff13d78b / vim version: 8.0 (2016 Sep 12, compiled Dec  3 2017 02:02:17)
- Plugin version (git SHA): 3d16b905960e708ee17d720227d5b462d78f809c
- Minimal vimrc: yes
- Language server name/link and version: non-existing rls
- Reproduction steps (from clean state)
    1. Have an rls command that outputs `error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary 'rls'`
    2. `:LanguageClientStart`
    3. Watch the RPC-rust thread(s) have 100% CPU (endless read from a pipe, according to strace)
- Logs.
  - [`/tmp/LanguageClient.log`](https://gist.github.com/minijackson/fc9e40f978587d785f7e2385e33e80a7)
  - `/tmp/LanguageServer.log`: just several `error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary 'rls'`

**Comment by autozimu** [comment]
Could you double check plugin version?

You pasted a commit version from branch master, but the log file are generated by branch next.

**Comment by minijackson** [comment]
Yes sorry, I did `git show master` instead of `git show HEAD`. My HEAD is at e04725ae5da84af0afecf7b7ae425fc339a6931d
