### ISSUE TITLE
High CPU Usage by languageclient process

### ISSUE THREAD

**Issue by piouPiouM** [autozimu/LanguageClient-neovim#216]
- neovim/vim version: NVIM v0.2.3-58-gd109f5645
- OS: macOS High Sierra 10.13.1 (17B1003)
- Plugin version (git SHA): 55bbfac (`next` branch)
- Release: languageclient-0.0.0-x86_64-apple-darwin.tar.gz
- Language server name/link and version:
  - [LanguageServer-php-neovim](https://github.com/roxma/LanguageServer-php-neovim) [33381f1](https://github.com/roxma/LanguageServer-php-neovim/commit/33381f1c9111304145e2c93dab896b543b37c41a)
  - [javascript-typescript-langserver@2.5.5](https://github.com/sourcegraph/javascript-typescript-langserver)
- `:CheckHealth` is OK
- Reproduction steps (from clean state)
    1. launch nvim without editing any file: the `languageclient` processus take 0% of CPU
    2. edit one PHP or JS file
- Logs: [LanguageClient-JS.log](https://gist.githubusercontent.com/piouPiouM/b693c02b08b6a11e3f31e7ca70812f86/raw/bd72a12cadd996d1089cb1d1b2d9984f235bda2c/LanguageClient-JS.log), [LanguageClient-PHP.log](https://gist.githubusercontent.com/piouPiouM/b693c02b08b6a11e3f31e7ca70812f86/raw/bd72a12cadd996d1089cb1d1b2d9984f235bda2c/LanguageClient-PHP.log)

When I edit a simple PHP (`<?php echo 'Hello World!';`) or JS file (`document.getElementById('test-table');
`) the `languageclient` process uses between 90% and +400% of CPU.

Tested with the following minimal vimrc:

```
call plug#begin('~/.local/share/nvim/bundle')

Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': './install.sh' }
Plug 'roxma/LanguageServer-php-neovim',  {
      \ 'do': 'composer install && composer run-script parse-stubs'
      \ }

call plug#end()

let g:LanguageClient_serverCommands = {
      \ 'javascript':     ['javascript-typescript-stdio', '--logfile', '/tmp/javascript-typescript-stdio']
      \ }
```

**Comment by autozimu** [comment]
Should fix with https://github.com/autozimu/LanguageClient-neovim/commit/c2388fb9a53002d013a4b94de29dd6768ca6fa62

**Comment by piouPiouM** [comment]
@autozimu thx for the update. Now the process uses between 130 and 175% of CPU.

- Plugin version (git SHA): 6d0e953 (`next` branch)
- Release: languageclient-0.1.0-x86_64-apple-darwin.tar.gz  
   (MD5 (bin/languageclient) = 0c6b61a43420bb051fae4e453846b24c)
- Logs:
  - [LanguageClient-JS.log](https://gist.github.com/piouPiouM/366ea190f2bdf7469d294d5016444037/raw/979e4e60576014bb50a210ba55f723063adad6aa/LanguageClient-JS.log)
  - [LanguageClient-PHP.log](https://gist.github.com/piouPiouM/366ea190f2bdf7469d294d5016444037/raw/979e4e60576014bb50a210ba55f723063adad6aa/LanguageClient-PHP.log)
