### ISSUE TITLE
C++ rename refactoring with cquery fails

### ISSUE THREAD

**Issue by vargheseg** [autozimu/LanguageClient-neovim#217]
#### Installation Details: ####
- neovim v0.2.1-dev
- Plugin version: 55bbfacdff17689a52709261d40a16c90274195c
- Language server: cquery  (a90a1b31c4ba51156f8c43ee66ef716afd6eebf7)

#### Issue: ####
Refactoring class name Foo to Fo, with :call LanguageClient_textDocument_rename()
 fails in the code below:

```
#include <iostream>

class Foo {
    public:
        int bar;
};

int main(int argc, char* argv[]) {
    Foo foo;
    int a;
    std::cout << 9;
}
```
![langserver_error](https://user-images.githubusercontent.com/19566373/34064445-47aaf3a0-e1f9-11e7-8b1b-6a72905098a3.png)

#### Logs ####
From LanguageClient.log

> 2017-12-16T00:21:00.240679041+01:00 INFO languageclient::languageclient - => {"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"Fo","position":{"character":4,"line":8},"textDocument":{"uri":"file_path_to_main.cpp"}},"id":38}
>  
> 2017-12-16T00:21:00.241042531+01:00 INFO languageclient::languageclient - <= {"jsonrpc":"2.0","id":38,"result":{"documentChanges":[{"textDocument":{"uri":"file_path_to_main.cpp","version":0},"edits":[{"range":{"start":{"line":2,"character":6},"end":{"line":2,"character":9}},"newText":"Fo"},{"range":{"start":{"line":8,"character":4},"end":{"line":8,"character":7}},"newText":"Fo"}]}]}}
> 
> 2017-12-16T00:21:00.242505962+01:00 ERROR languageclient::languageclient - Error handling message. Message: {"id": 4, "jsonrpc": "2.0", "method": "textDocument/rename", "params": {"character": 4, "handle": true, "languageId": "cpp", "line": 8, "buftype": "", "cword": "Foo", "filename": "file_path_to_main.cpp"}}. Error: Err(ErrorImpl { code: Message("missing field `changes`"), line: 0, column: 0 })
> 

From the logs I see  cquery responds correctly to the textDocument/rename request, but afterwards the LanguageClient runs into error for some reason.

**Comment by MaskRay** [comment]
The issue seems like: `changes?` in `WorkspaceEdit` is optional.

**Comment by vargheseg** [comment]
Language Server Protocol v 2-x, seems changes are not optional in WorkspaceEdit.
https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#workspaceedit

**Comment by DeltaEvo** [comment]
@vargheseg  LanguageClient-neovim supports 3.x version of the protocol

This plugin use a library that provide LSP Types in Rust but this lib seems to don't have the 3.0 version of WorkspaceEdit https://github.com/gluon-lang/languageserver-types/blob/master/src/lib.rs#L269

I will try to work on this tommorow
