### ISSUE TITLE
 c++ projects rootUri

### ISSUE THREAD

**Issue by vargheseg** [autozimu/LanguageClient-neovim#219]
Is there a way to set the rootUri for your projects?

I see the logic for setting the rootUri for a cmake project is to set it to the directory with the CMakeLists.txt. This doesn't work for a project I am looking at, because some of the sub directories are sub projects with  their own CMakeLists.txt.

**Comment by DeltaEvo** [comment]
There is no way for the moment but, allowing custom project root markers (#186) will resolve your issue ?

**Comment by vargheseg** [comment]
Not sure about what  a good root marker would be. In my use case, CMakeLists.txt was not a good option.
Letting the user choose a root path when the logic fails to find a good option imo may be  a reasonable fallback.

**Comment by DeltaEvo** [comment]
There is some discutions about this in #185 

You can specify the rootPath when launching the LanguageServer with `:LanguageClientStart rootPath=/path/to/dir` but I know this is not practical.

Have you some ideas how to expose it to the user ?

**Comment by vargheseg** [comment]
How can I do this; typing `:LanguageClientStart rootPath=/path/to/dir` on nvims ex mode doesn't work. 
I get:
![trailing](https://user-images.githubusercontent.com/19566373/34075545-47f04d48-e2ca-11e7-9a86-1075208bd483.png)
What am I doing wrong?

On the first look #186 `g:LanguageClient_rootUri` suggestion looks like an option that would work in my situation. But I am not experienced enough with other use cases to know if this is the best way for all.
