### ISSUE TITLE
Feature - Only validate after save and initial load

### ISSUE THREAD

**Issue by haringsrob** [autozimu/LanguageClient-neovim#22]
I think it would make sense to have the validation to be more configurable:

1. Only validate on file load
2. Only validate on file save

What do you think? If you give me a starting point I might try to implement myself.

**Comment by autozimu** [comment]
Thanks for interest in contributing.

Right now, the language client will receive all text changes events, send those changes to language server.

At the same time, language client receives all kinds of from language server, which includes all diagnostic messages. (Obviously, if the server didn't implement this feature, no such messages are included.)

If you are interested in implementing the requested feature. You can introduce a variable to keep track of whether to keep received diagnostic messages or discard them.

Specially the function for handling received diagnostic message is https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L762

**Comment by haringsrob** [comment]
Actually,

I think the real issue I had with automatic validation was the fact that I had a dozen of messages.
This seems to have been solved here #c1e89fdeb6a8a65d01c63073f645a37bbc09066b?

I will close this for now as it is for me okay to have instant validation.

**Comment by cdelledonne** [comment]
@autozimu to be honest I still believe it would be nice to have validation more configurable. I, for instance, do not really like diagnostics popping up while editing. It just does not make sense to check my syntax so often, for sure it's gonna be wrong before I finish what I'm typing.

You could argue that this is the language server's responsibility. For example, [ccls does give the option to delay computation of diagnostics](https://github.com/MaskRay/ccls/wiki/Customization#diagnosticsonopen--diagnosticsonchange--diagnosticsonsave), but that does not seem to work for me. And my wish is not to delay diagnostics, but to not compute them at all while editing.

Another reason why I think it would be best to have the client control the behaviour is that the server does not have access to the editor's interface. For instance, some users (at least one =]) could prefer **diagnostics to be updated only when exiting insert mode** in Vim/Neovim. When enabling this option, LanguageClient could
1. receive all the server's diagnostics updates, but not display them until the next `InsertLeave` event, or
2. not send `textDocument/didChange` to the server until the next `InsertLeave` event.

The second method would treat a whole insert-mode session as an atomic `textDocument/didChange` operation, effectively saving some communication (client -> server -> client) and processing (client processing diagnostics) bandwidth.

I'm not sure how difficult this would be to implement, but definitely it's not doable on the server side.

Any thoughts?

---

EDIT: just noticed similar discussions in #603, #754 and #816.
