### ISSUE TITLE
language client and ale -> wrong highlights

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#223]
When using https://github.com/w0rp/ale in combination with this project, highlights (probably from this project, because they take more time to appear), are off and do not match what they should address.

@w0rp maybe you can have a look at this as well?

- neovim/vim version: neovim 0.2.2
- Plugin version (git SHA): 6d0e9538ea81a002d884533bb4fb1a13c2a7948e
- Minimal vimrc

```
set nocompatible
set hidden

set runtimepath+=~/.local/share/nvim/bundle/deoplete.nvim
set runtimepath+=~/.local/share/nvim/bundle/ale
set runtimepath+=~/.local/share/nvim/bundle/LanguageClient-neovim

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ }
let g:LanguageClient_autoStart = 1

let g:ale_lint_on_text_changed = 'never'
let g:ale_linters = {
    \ 'python': ['flake8'],
    \ }
```

- Language server name/link and version: https://github.com/palantir/python-language-server, 0.12.0
- Reproduction steps (from clean state)
    1. ensure that flake8 is installed and available on path
    2. open the following python file from disk:

    ```python
    class XPath(object):
    
        @classmethod
        def create(cls, name, config):
            from lxml import etree
            try:
                xpath = config['xpath'].strip()
                # validate the expression
                try:
                    etree.fromstring('<a></a>').xpath(xpath)
                except etree.XPathEvalError:
                    raise ConfigurationError('Invalid xpath expression: ' + xpath)
                return cls(name, xpath, config['url'])
            except KeyError as error:
                raise ConfigurationError('No ' + str(error) +
                                         ' entry defined for the XPath check')
    
        def __init__(self, name, xpath, url):
            self._xpath = xpath
            self._url = url
    
        def check(self):
            import requests
            import requests.exceptions
            from lxml import etree
    
            try:
                reply = requests.get(self._url).text
                root = etree.fromstring(reply)
                if root.xpath(self._xpath):
                    return "XPath matches for url " + self._url
            except requests.exceptions.RequestException as error:
                raise TemporaryCheckError(error)
            except etree.XMLSyntaxError as error:
                raise TemporaryCheckError(error)

    ```

    3. The result will be like in this screenshot:

        ![2017-12-20t11 09 14 01 00](https://user-images.githubusercontent.com/1336287/34201880-43d5de90-e576-11e7-9bd1-91bbb8ebda31.png)

        The blue highlights are completely off and do not correctly relate to any of the warnings, neither from flake 8 via ale, nor the ones produced by the language server.

        With only ale (so `g:LanguageClient_autoStart = 0`), things look correct:

        ![2017-12-20t11 12 48 01 00](https://user-images.githubusercontent.com/1336287/34202028-d2bade08-e576-11e7-8d42-1d46a63f1414.png)

         The other way around, with only language client, things also look ok:

         ![2017-12-20t11 15 17 01 00](https://user-images.githubusercontent.com/1336287/34202102-15cf9968-e577-11e7-9760-1ed6a9088c10.png)

         If I start with ale enabled and laguage client autostart set to 0 and then after some time manually start the client, things are still broken:

         ![2017-12-20t11 16 38 01 00](https://user-images.githubusercontent.com/1336287/34202182-485f4356-e577-11e7-9ecc-f98901960004.png)

- Logs. Run `:call LanguageClient_setLoggingLevel('DEBUG') |
:LanguageClientStop | :LanguageClientStart`:

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1575127/LanguageClient.log)
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1575128/LanguageServer.log)

**Comment by autozimu** [comment]
Should fixed by https://github.com/autozimu/LanguageClient-neovim/commit/e4206af73aa440dccbf935e2d811fdba9789b039
