### ISSUE TITLE
Support multi-line textDocument/hover

### ISSUE THREAD

**Issue by MaskRay** [autozimu/LanguageClient-neovim#224]
Currently textDocument/hover is implemented via

```python
    @neovim.function("LanguageClient_textDocument_hover")
    @deco_args
    def textDocument_hover(self, uri: str, languageId: str,
........
        echo(info)

# state.py
def echo(message: str) -> None:
    """Echo message."""
    message = escape(message)
    execute_command("echo '{}'".format(message))
```

For multi-line macro/struct/class declaration and comment support (see jacobdufault/cquery#29 for cquery's ongoing support), this UI may be infeasible. We might need to provide an alternative UI (e.g. preview window) 

![](https://ptpb.pw/Qyup.jpg)

**Comment by YaLTeR** [comment]
Maybe it's possible to display the info in a "popup" similar to autocomplete suggestions?

**Comment by stellarhoof** [comment]
Also, don't use `echomsg` if possible. It pollutes the messages history.

**Comment by prabirshrestha** [comment]
[vim-lsp](https://github.com/prabirshrestha/vim-lsp) supports multiline hover. Feel free to port this related commits.

* https://github.com/prabirshrestha/vim-lsp/commit/203d682e30ca30d995fdceaf53df8a7808409baa
* https://github.com/prabirshrestha/vim-lsp/commit/d3af2b8e1a6d15edab49410e1c1f60deef1d654c
