### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by KillTheMule** [autozimu/LanguageClient-neovim#226]
Hey!

Thanks for your nice plugin. Works nicely outside of this error for me. I can work around the error by restarting the client.

- neovim/vim version: neovim v0.2.3-dev
- Plugin version (git SHA): 9a56ef06bf06fc514f20f2b4d135b78faf121f2f
- Minimal vimrc: https://gist.github.com/KillTheMule/cf2e277dc8d9b42cba3a06ef8ffcc018. Note I also have a file `after/ftplugin/rust.vim` which might be relevant: https://gist.github.com/KillTheMule/0024966f56a76b72560424577972209d
- Language server name/link and version: rls-preview 0.124.0-nightly (be23ad3 2017-12-0
- Reproduction steps (from clean state)
    1. Start with a rust file
    2. If error did not occur, alternate between `gd` and `RustFmt` until the error occurs.

Most of the times, step 2 is needed, but not always. Most often, after 1 usage of `gd` and `RustFmt` the error will occur, but sometimes more is needed, sometimes it seemed to not occur at all.

Error description: `:messages` contains `Broken pipe (os error 32)`. All further tries to use e.g. `gd` will result in this error message and no action. Restarting the plugin will resolve this, until it occurs again some time later.

- Logs: There are 2 logs, one where the error occured after step 1 (https://gist.github.com/KillTheMule/bc1602bc65001a68db1c0e0532c22b50), and one where I used `gd` and `RustFmt` once (https://gist.github.com/KillTheMule/1856f231dcf56351482cc8cfd47343bd). The LanguageServer.log always contains

```
thread 'main' panicked at 'ActionContext already initialized', /checkout/src/tools/rls/src/actions/mod.rs:92:38
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I did not produce a backtrace, but will of course do so if needed.

I can't tell if this is a problem with the plugin or RLS itself, and hope for further guidance (although if it's a problem with the RLS, one might hope for a better error message from the plugin). I've just today updated the plugin from the python version to the rust version, but I've had hiccups before (but no such error message), so it might not be related to that. If there's any more information I should provide let me know!

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by KillTheMule** [comment]
Great, thank you!

Would you mind indicating what the problem was? I'm facing something similar in a related context, maybe this can give me an idea how to investigate .

**Comment by autozimu** [comment]
Its caused by trying to start rls twice whr it should not.

When the second rls starts, the first rls stin got closed due to resouce
cleanup.

**Comment by KillTheMule** [comment]
That's indeed something I should check for my problem, thanks a lot!
