### ISSUE TITLE
Failed to download with curl and wget

### ISSUE THREAD

**Issue by nponeccop** [autozimu/LanguageClient-neovim#227]
I get the following error on PlugUpdate (neovim/vimplug):

```
Warning: Failed to create the file bin/languageclient:
   0 6781k    0 16360    0     0  16360      0  0:07:04  0:00:01  0:07:03  163k
curl: (23) Failed writing body (0 != 16360)
Failed to download with curl and wget
```
Local build works, so it's not permissions issue

**Comment by autozimu** [comment]
Recommended install approach has changed to use tags. See https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#vim-plug-user

Besides, there isn't enough information provided to troubleshoot. PR is welcome.

**Comment by nponeccop** [comment]
Do I still need `do: './install.sh'`?

**Comment by autozimu** [comment]
nope

**Comment by nponeccop** [comment]
ok, it works for me now
