### ISSUE TITLE
Installation instructions in INSTALL.md are out of date with README

### ISSUE THREAD

**Issue by joereynolds** [autozimu/LanguageClient-neovim#228]
The readme reads

```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': './install.sh'
    \ }
```

While the INSTALL.md file reads

```
Plug 'autozimu/LanguageClient-neovim', {'tag': 'binary-*-x86_64-apple-darwin' }
```

Which is the best way?
Great plugin by the way :)

**Comment by autozimu** [comment]
Thanks for reporting. The latter is recommended.

**Comment by meck** [comment]
Is the Install.sh method deprecated? I use the same vimrc for linux and macOS, would it be better with a case statement in vimrc then?

**Comment by autozimu** [comment]
yes
