### ISSUE TITLE
Function parameter expansion with nvim-completion-manager and UltiSnips?

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#232]
- neovim version: 0.2.2
- Plugin version (git SHA): 640a74cce174172245429b3096bf3bd88053dbcf
- Language server name/link and version: cquery or rls

Is there a way of getting the function parameters in completed items to behave like they would in snippets? Right now upon completing a function I get a huge line like:
```cpp
printf(${1:const char *__restrict __format, ...})$0
```
and have to clean it up by myself. If I understand correctly, in this case NCM should use UltiSnips to placeholder the function parameters with their names and allow me to jump between them with the UltiSnips bindings.

Maybe there's some setup I'm missing?

**Comment by autozimu** [comment]
Quote myself from another issue

>Basically what needs to be done is to detect if snippet plugin is loaded, if not, indicate that in the
initialize request parameters sent to server.
> https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md Search for snippetSupport.

**Comment by YaLTeR** [comment]
This would solve the issue in case of no snippet plugin being present, however I have UltiSnips installed and working and would like the completions to utilize it somehow.

**Comment by autozimu** [comment]
Not too familiar with this part, but I'm guessing UtilSnips wasn't activated after completion finish, or the snippet format used by language server protocol was not understandable by UtilSnips.

There is a similar issue opened on NCM side. https://github.com/roxma/nvim-completion-manager/issues/172

@roxma

**Comment by YaLTeR** [comment]
This works since the recent commits.

**Comment by yshui** [comment]
Request this to be reopened for the Rust implementation.

The Python implementation no longer works with more recent versions of cquery. And I don't want to spend time fixing that if it's going to be replaced by the Rust one.

**Comment by autozimu** [comment]
I don't get it. This _is_ in rust implementation.

**Comment by yshui** [comment]
@autozimu OK. But it's not working for me.

Maybe I'm doing something stupid.

**Comment by autozimu** [comment]
It is kind of tricky to get them working together. As a reference, you could check https://github.com/autozimu/LanguageClient-neovim/pull/327#issuecomment-377829341
