### ISSUE TITLE
elixir-ls

### ISSUE THREAD

**Issue by roberbnd** [autozimu/LanguageClient-neovim#234]
which is the configuration if I want to use elixir-ls?
https://github.com/JakeBecker/elixir-ls

I tried 
.zshrc
alias eli-ls="cd /home/bnd/Workspace/5Elixir/elixir-ls && env ERL_LIBS=~/eli mix elixir_ls.language_server"

and in init.vim
let g:LanguageClient_serverCommands = {
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ 'elixir': ['eli-ls'],
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }

but It doesn't work.

with other plugin has something similar
https://github.com/JakeBecker/elixir-ls/issues/35

**Comment by autozimu** [comment]
Try put the alias in a script, say `/usr/local/bin/eli-ls`,
```sh
#!/usr/bin/env bash

cd /home/bnd/Workspace/5Elixir/elixir-ls && env ERL_LIBS=~/eli mix elixir_ls.language_server
```

**Comment by colbydehart** [comment]
What is located at `~/eli` in this example? Is that the elixir-ls clone?
