### ISSUE TITLE
Show build progress

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#235]
Language servers like RLS and cquery provide custom notifications for the build progress which could be useful to display (to show that the language server isn't showing the diagnostics because it's doing something as opposed to being broken or whatever, and to show the indexing/build progress if the language server like cquery provides it).

I implemented simple `echo` for the three RLS notifications in [this branch](https://github.com/YaLTeR/LanguageClient-neovim/tree/rls-progress). From the initial testing, they are nice on the first file open but get spammy as you type. I think showing them only the first time would work, however some kind of a dedicated indicator would be better. I'm not sure how to make one though as I'm not experienced with vim plugin writing.

Making an issue to ask for feedback and ideas on how to show this.

**Comment by YaLTeR** [comment]
Printing cquery's notifications the same way results in stuff like hover messages being overriden by them (but, once again, nice on the first open).

Maybe it can be shown in the statusline?

**Comment by autozimu** [comment]
I agree it would be better a fit in status line. Could be exposed through a global variable or function and later consumed by user status line setting.

**Comment by autozimu** [comment]
Vim's capability to show extra information is too limited and echo area is over crowded even within this plugin.
