### ISSUE TITLE
"invalid type: map, expected u8" on LanguageServerStart with NCM

### ISSUE THREAD

**Issue by Anrock** [autozimu/LanguageClient-neovim#238]
neovim version: v0.2.3-271-g1e68e0630
Minimal vimrc:
```
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {
    \ 'tag': 'binary-0.1.9-x86_64-pc-windows-gnu'
    \ }
Plug 'roxma/nvim-completion-manager'
call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie', '--lsp', '-d', '-l', 'D:\Temp\hie.log']
    \ }
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_autoStart = 0
```
Language server name:
https://github.com/haskell/haskell-ide-engine @ 3ec8e93e9ca751cf282556998851ffa65f32e06b with haskell-lsp dep override to https://github.com/alanz/haskell-lsp @ 4462fa7a97e99cba954cfbce27b63363cd3f06c9

Reproduction steps (from clean state):
1. Install plugin
2. Open file (with .hs extension) with contents (maybe will work with other languages, didn't try)
```
main :: IO ()
main = putStrLn "hello"
```
3. `:LanguageClientStart`

Expected: langserver launched and working
Actual: `invalid type: map, expected u8` error appears, langserver features don't work.

If NCM is commented out in init.vim - everything works as expected.
Also it looks like langserver features are broken because `didOpen` event is not sent when error happens.
Both logs contain two launches - first with NCM (not working), second without NCM (working).

Logs:
[LanguageClient.log](https://pastebin.com/stF6tQhj)
LanguageServer.log is empty.
[hie.log](https://pastebin.com/U6v0HjH7)

**Comment by autozimu** [comment]
Thanks for providing concrete reproduction steps.

The issue is caused by hie returns a response cannot be properly deserialized into a type (which is defined by languageserver-types, one of this plugin's dependencies.)

```json
{
	"capabilities": {
		"textDocumentSync": {
			"openClose": true,
			"change": 2,
			"willSave": false,
			"willSaveWaitUntil": false,
			"save": {
				"includeText": false
			}
		},
		"hoverProvider": true,
		"completionProvider": {
			"resolveProvider": true,
			"triggerCharacters": [
				"."
			]
		},
		"definitionProvider": true,
		"referencesProvider": true,
		"documentHighlightProvider": true,
		"documentSymbolProvider": true,
		"codeActionProvider": true,
		"documentFormattingProvider": true,
		"documentRangeFormattingProvider": true,
		"renameProvider": true,
		"executeCommandProvider": {
			"commands": [
				"applyrefact:applyOne",
				"hare:demote"
			]
		}
	}
}
```

I will shortly make a fix to bypass this error in NCM registration, with which this issue will only affect NCM integration but not other functionalities.

Proper deserialization fix should be made in either hie or langaugeserver-types, depend on who violate the protocol.
