### ISSUE TITLE
vim-plug :PlugStatus reports LanguageClient-neovim as broken

### ISSUE THREAD

**Issue by nponeccop** [autozimu/LanguageClient-neovim#239]
and recommends reinstallation:
```
- yats.vim: OK                                                                            |~
- deoplete.nvim: OK                                                                       |~
x LanguageClient-neovim:                                                                  |~
    Diverged from origin/master (186 commit(s) ahead and 13 commit(s) behind!             |~
    Backup local changes and run PlugClean and PlugUpdate to reinstall it.                |~
```

And the suggested reinstallation steps don't help. Also `:PlugUpdate` didn't update to a newer tag (but I can't reproduce that anymore).

These ones are likely upstream bugs in vim-plug, but I know too little about nvim/vimplug to report them and to help with reproduction.

I use neovim

**Comment by meck** [comment]
Definitely Vim-Plug, looks like defaults to master branch for the statuscheck when you specify a tag 
`Plug 'autozimu/LanguageClient-neovim', { 'tag': 'binary-*-x86_64-apple-darwin', 'branch': 'next' }`
made it compare to next, but I could not get it to compare to a tag, but it only seems to be the status check, the checkout and update seem fine.

**Comment by gadkadosh** [comment]
Moreover, vim-plug doesn't update the plugin anymore when doing :PlugUpdate. I guess it doesn't check for newer tags matching the 'tag' property. There should maybe be a warning about that in the docs/install instructions.

**Comment by deathmaz** [comment]
It is possible to update the plugin via `:PlugClean` and `:PlugUpdate`

**Comment by deathmaz** [comment]
though i don't think its a good way of doing this

**Comment by gadkadosh** [comment]
That's what I'm doing. Kind of defeats the point of using a plugin manager.

**Comment by autozimu** [comment]
I believe this is a `vim-plug` issue. Created a issue https://github.com/junegunn/vim-plug/issues/719

**Comment by ahmedelgabri** [comment]
Although it's a `vim-plug` issue, I think it might be better if we have a better way of distribution. 

Because you are now tightly coupling the usage of the `LanguageClient-neovim` with `vim-plug`, what if someone is using [`minpac`](https://github.com/k-takata/minpac) or something else... how can they use the plugin with their plugin manager of choice? Especially that idea of a wild card might not be in some of these plugin managers too.

**Comment by autozimu** [comment]
The recommended installation is changed to install.sh based, which should work with most vim plugin.
