### ISSUE TITLE
Document available tag patterns

### ISSUE THREAD

**Issue by nponeccop** [autozimu/LanguageClient-neovim#240]
Current installation instructions only contain the darwin/MacOS tag pattern. However, 4 more variants are available: 2 windows and 2 linux builds.

Also explain the rules to select bitness. E.g. if bitness of Python/neovim matters. E.g. on 64-bit Windows it's common to have 32-bit Python. Will it work with the 64-bit LanguageClient-neovim tag?

**Comment by autozimu** [comment]
Should be self-explanatory. Not sure what to doc any more.

Python doesn't matter at all as branch `next` doesn't depend on python.

**Comment by nponeccop** [comment]
Where is the current doc? https://github.com/autozimu/LanguageClient-neovim/blob/bb480c47b68a7ad10f4d56396c2ff75b91fb00d1/INSTALL.md ? It mentions install.sh and next branch. Is it the recommended installation method again?

**Comment by autozimu** [comment]
yes

**Comment by nponeccop** [comment]
Should I revert back from tags? I suppose this move is because tags are broken upstream in vim-plug?

**Comment by autozimu** [comment]
I’d say yes.

You check the issue I created at vim-plug.

**Comment by nponeccop** [comment]
Yes, I've seen the issue. The issue looks good to me.
