### ISSUE TITLE
Document logs in Troubleshooting

### ISSUE THREAD

**Issue by nponeccop** [autozimu/LanguageClient-neovim#241]
LanguageClient-neovim creates LanguageServer.log and LanguageClient.log in unexpected locations. Document that these ones exists and how to control verbosity.

Also document that language servers may have their own logs which are worth enabling.

**Comment by ah-** [comment]
For future reference: These logs go into $TMP, $TEMP or /tmp: https://github.com/autozimu/LanguageClient-neovim/blob/next/src/utils.rs#L123

**Comment by mcepl** [comment]
And how can verbosity be increased?

**Comment by mcepl** [comment]
> And how can verbosity be increased?

And I can reply to myself:
```
4.8 LanguageClient_setLoggingLevel(level: str)
*LanguageClient_setLoggingLevel*

Set the plugin logging level. By default, only errors are logged into
/tmp/LanguageClient.log (%TMP%/LanguageClient.log for Windows).

Valid logging levels are 'ERROR'(default), 'INFO', 'DEBUG'.
```

**Comment by nponeccop** [comment]
LGTM
