### ISSUE TITLE
The CMakeLists.txt file is not a good indicator of a project root

### ISSUE THREAD

**Issue by mkollaro** [autozimu/LanguageClient-neovim#246]
In [get_rootPath()](https://github.com/autozimu/LanguageClient-neovim/blob/next/src/utils.rs#L14), when using a C or C++ project, the directory with the closest `CMakeLists.txt` gets chosen as the project root. However, I'm using several `CMakeLists.txt` files and they get called [by the top one](https://github.com/intel/small-gpu-rendering-examples/blob/master/CMakeLists.txt) using `add_subdirectory`. 

Because of this, `cquery` isn't able to find `compile_commands.json` and I have to copy it to each of these sub-directories for it to work. This is an acceptable workaround, but I don't think `CMakeLists.txt` is a good indicator of a project root and should be used only if nothing else is found.

**Comment by YaLTeR** [comment]
Duplicate of #219?

**Comment by mkollaro** [comment]
Rather a duplicate of #186, sorry for not noticing earlier.
