### ISSUE TITLE
I got `languageclient: Not executable!` on starting nvim

### ISSUE THREAD

**Issue by octaltree** [autozimu/LanguageClient-neovim#248]
Why don't you append `chmod u+x bin/$name` to install.sh?

**Comment by autozimu** [comment]
The `install.sh` is already an executable.

You need either run the script to download latest binary or follow the latest installation instruction https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#3-install-this-plugin.

**Comment by octaltree** [comment]
The `install.sh` is an executable. `bin/languageclient` which is downloaded with install.sh isn't an executable.

**Comment by autozimu** [comment]
Hmm. This is unexpected.

It used to have executable bit previously.

**Comment by wpcarro** [comment]
I'm unsure what I need to do to get this working. I have the following configuration in my `.vimrc`, and per @autozimu suggestion:

```viml
Plugin 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': 'bash install.sh',
  \ }
```

I am still receiving the following error:

```
LanguageClient: Not executable!
Press ENTER or type command to continue
```

I dug around in `~/.vim/bundle/LanguageClient-neovim/install.sh`, but I couldn't see what I need to make executable to make it execute.

**Comment by autozimu** [comment]
Can you check if the binary is executable in your host?

You can see previous diff to add executable bit.

**Comment by wpcarro** [comment]
Hi @autozimu can you be more specific?

A). Which binary? Can you tell me where to find the binary file so that I can check whether or not it is executable?

B). The previous diff of what? `install.sh`?

**Comment by autozimu** [comment]
A) In your copy of plugin, `bin/languageclient`
B) https://github.com/autozimu/LanguageClient-neovim/commit/b2fea8e2c58f5bd89f4e51e586ccea299b8c19ad

**Comment by wpcarro** [comment]
@autozimu if I run `locate languageclient` on my machine, all of the candidates are related to Visual Studio Code. I'm not seeing any vim-related results. Additionally, this command returns nothing for me:

```bash
❯ find ~/.vim -type f -name 'languageclient'

```

Any ideas as to where I locate `bin/languageclient`?

**Comment by wpcarro** [comment]
@autozimu regarding the diff, my version of the `install.sh` has the call to `chmod`, so I'm not sure what else to do.

**Comment by wpcarro** [comment]
@autozimu and future readers, I got this working by manually downloading the release from the GH release page and running:

```bash
$ curl --location https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.25/languageclient-0.1.25-x86_64-apple-darwin --output ~/.vim/bundle/LanguageClient-neovim/bin/languageclient && chmod 755 ~/.vim/bundle/LanguageClient-neovim/bin/languageclient
```

**Comment by asilvadesigns** [comment]
@wpcarro worked for me thanks! I just replaced the `~/.vim/bundle/` with my plugin manager location, in my case using dein and neovim so... `~/.cache/dein/repos/github.com/autozimu/`.

thanks!

**Comment by mmai** [comment]
I had the same problem and fixed it by replacing 

```
Plugin 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': 'bash install.sh',
  \ }
```

by 

```
Plugin 'autozimu/LanguageClient-neovim', {
  \ 'branch': 'next',
  \ 'do': './install.sh',
  \ }
```

**Comment by willdavidow** [comment]
I had to go into my `minpac` plugin directory for `LanguageClient-neovim` and manually run `install.sh` to get this working...

**Comment by rachmadaniHaryono** [comment]
got the same error `LanguageClient: Not executable!` on ubuntu 18.04

the last part command from wpcarro fix it

```shell
chmod 755 ~/.vim/bundle/LanguageClient-neovim/bin/languageclient
```
