### ISSUE TITLE
Adding Preview Option to FZF usage

### ISSUE THREAD

**Issue by sbdchd** [autozimu/LanguageClient-neovim#249]
Adding the `fzf#vim#with_preview()` as an option for the `:fzf` usage would be nice.

The following is a WIP as paths seem to be misconfigured, i.e. the file path that fzf opens is always `src/file_name_here` even if I am in `src` or some other directory.
If you `cd` to the directory above `src` then the preview will work.
I am probably missing some path parameters.

```diff
diff --git a/plugin/LanguageClient.vim b/plugin/LanguageClient.vim
index 9497dc4..f2339d7 100644
--- a/plugin/LanguageClient.vim
+++ b/plugin/LanguageClient.vim
@@ -578,10 +578,13 @@ function! s:getInput(prompt, default) abort
 endfunction
 
 function! s:FZF(source, sink) abort
+    let options = fzf#vim#with_preview('right:50%', '?').options
     call fzf#run(fzf#wrap({
                 \ 'source': a:source,
                 \ 'sink': function(a:sink),
+                \ 'options': options
                 \ }))
+
     if has('nvim')
         call feedkeys('i')
     endif
```

Here is an example on preview configuration from the docs: https://github.com/junegunn/fzf.vim/blob/ba7a22888b25f6cbd6f4714ccd350a3b3488061e/README.md#advanced-customization

**Comment by autozimu** [comment]
How is this preview activated with this option? Can someone give me a hint? I tried this patch, but `C-?` doesn't do anything.

**Comment by davidosomething** [comment]
@sbdchd add `cwd` to the fzf run options
@autozimu do you have the highlight gem or other highlighter set up for fzf? instructions in readme https://github.com/junegunn/fzf/blob/202872c2dc0cec5216466d6fc9f5c7346a932973/README.md#preview-window
