### ISSUE TITLE
Disable Preview and Autocompletion

### ISSUE THREAD

**Issue by chrisduerr** [autozimu/LanguageClient-neovim#25]
So I've been trying out the LanguageClient with RLS for a bit now and it works okay most of the time (sometimes renaming and stuff like that can be an issue but nothing unexpected).
I have two major problems with it tho:

My first issue is that whenever I'm autocompleting from another file with nvim it shows the path of the file in a preview window, which I then have to manually close. It's possible to use autocmd to close this window instantly but that creates a bug with neovim (the current buffer in vim-airline has unfocused colors). I'd love the option to disable this completely since I don't really see a benefit in the way it works right now anyways (just showing the path to the module I'm autocompleting to).
With variables this is a little more helpful since it shows the line where the variable is created but it still opens this annoying buffer every time that I then have to close again. Since it always only shows a single line maybe the cmdline is a better place to show this info?

My second issue is the autocompletion. I have to admit I haven't tried the autocompletion yet, but right now rust.vim does that for me anyways. I have that installed for syntax (I could use polyglot for that), autocompletion and rustfmt. Now since I have both rust.vim and LanguageClient enabled I feel like weird stuff is happening. Sometimes if I type variables it autocompletes without me doing anything. Which, I'm sure you can imagine, can be quite annoying. Disregarding if I should use rust.vim or LanguageClient for autocompletion I feel like it would be a good idea to be able to disable certain features of the LanguageClient. This would allow to use only what I actually want without having the rest of the LanguageClient mess with my stuff.

I hope this is the right place for these improvement ideas and I really feel like the LanguageClient and RLS might have a bright future. However I'd love to be able to use it as soon as possible without starting to hate it for minor annoyances.

**Comment by autozimu** [comment]
For your first issue, it is a vim/neovim feature, nothing to do with this plugin. You can display the completion preview with
```
set completeopt-=preview
```

Or you can use plugin `Shougo/echodoc.vim`, which as you wish, will display those info in cmd line.

As the second issue, I am not sure I understand your problem correctly. As far as I know, rust.vim does not provide completion. If you came across the issue of autocompletion without user action, then you might want to check https://github.com/Shougo/deoplete.nvim/issues/440, which is caused by a vim/neovim bug. Shougo will probably take care of that.

If you are using deoplete for completion, it is always possible to disable source from LanguageClient-neovim, check deoplete doc.

**Comment by chrisduerr** [comment]
Yeah that bug seems indeed like what I'm running into, so I guess it was just bad timing for the LanguageClient install. And I am using vim-racer not rust.vim, my bad.

However using vim-racer I don't get a preview, but using LanguageClient I do. I actually am using echodoc but for some reason that seems to be broken too right now (?).
Using `set completeopt-=preview` is exactly what I was looking for tho, thanks.

Is there any advantage of racer right now? Besides having to install racer vim plugin and the binary? It might be smarter to just remove that vim-plugin.

**Comment by autozimu** [comment]
I believe rls internally use racer right now, and they are planning/being phasing racer out to use compiler to get more accurate information.

**Comment by chrisduerr** [comment]
Yeah thanks for all the help. I can't seem to figure out how to make LanguageClient work with deoplete but maybe I can figure this out (I guess I'll stick with the racer plugin for now). And I'll try to find out why echodoc doesn't work anymore which will probably help with the preview thingy too. That doesn't have anything to do with this plugin tho (I hope).

**Comment by autozimu** [comment]
I'd recommend starting with minimal config file and small test project.

Hope it helps. Thanks.

**Comment by chrisduerr** [comment]
I just wanted to add that completion didn't work because I didn't set the `RUST_SRC_PATH` variable.
Even tho the completions still are significantly worse than what the `racer-vim` plugin gives me.
For example `use std::fs::` does not complete but I have to do `use std::fs::Fi` for making anything pop up. Even if I manually start completing after `use std::fs::` it doesn't work. Maybe there needs to be some more work done on the RLS tho and this might not be because of the LanguageClient.

**Comment by autozimu** [comment]
For the case that `use std::fs::` not triggering completion, it is indeed an issue.

I will try push a commit to fix the issue.

**Comment by chrisduerr** [comment]
Great! Guess like that I found at least one bug with LanguageClient. And everything else now works too. :)
