### ISSUE TITLE
Setting up with CQuery

### ISSUE THREAD

**Issue by joaospinto** [autozimu/LanguageClient-neovim#251]
I'm trying to get LanguageClient-neovim to work with CQuery.
I'm aware there is a brief tutorial explaining how to do it [here](https://github.com/autozimu/LanguageClient-neovim/wiki/cquery).

The content of `/tmp/LanguageClient.log` is mostly the following line (repeated ad nauseum):
```WARN languageclient::languageclient - Unknown notification: "$cquery/progress"```

You can find my init.vim [here](https://gist.github.com/joaospinto/9ec0606a5a2456d542214f959fb6996d).

Both `cquery --clang-sanity-check` and `cquery --test-unit` pass.
`:PlugStatus` also passes.

neovim version: v0.2.3-353-g9ad557f
plugin version: commit 0c3f171
language server: CQuery

For completeness, the `~/.config/nvim/settings.json` file is:
```
{
        "initializationOptions": {
                "cacheDirectory": "/tmp/cquery"
        }
}
```

When I open `main.cpp` in `tests/data/sample-cpp`, I get a warning in line 10.
For glfwtest.cpp, I get errors at all lines inside the main function and also at the GLFW include line.
The error at line 7 is a bit surprising: `no matching function for call to 'sleep_for'`.

Both in the project where I want to use this as well as the sample-cpp folder, I have a `compile_commands.json` file linking to the real `build/compile_commands.json`.

Can someone help me out? Thanks.

**Comment by MaskRay** [comment]
`tests/data/sample-cpp/.vim/settings.json` needs updating. `resourceDir` can now be automatically detected and thus unnecessary.

Per discussion in https://gitter.im/cquery-project/Lobby , this is not an issue on LanguageClient-neovim's side.

I find an issue that may also bother LanguageClient-neovim https://github.com/emacs-lsp/lsp-mode/issues/225

**Comment by joaospinto** [comment]
Here is the problem:
https://github.com/autozimu/LanguageClient-neovim/commit/eabe27ac72bf5a43ed33aa825338c17202c81379#diff-3dbd16223f25e8b5e0bcf099743107e9R50

1. It's not a good idea to think that CMakeLists.txt is an indication of the root directory, not at all! Other issues have raised this point.
2. g:LanguageClient_rootMarkers should have higher search priority; it seems to be ignored as soon as CMakeLists.txt is found.

**Comment by autozimu** [comment]
The second claim is false. `rootMarkers` already has the highest priority.

**Comment by joaospinto** [comment]
Also, it would be a good idea to suggest using the following options in the init.vim file:
```
" Support for more languages may be added here.
let g:LanguageClient_serverCommands = {
\ 'cpp': ['cquery', '--language-server', '--log-file=/tmp/cq.log'],
\ }
```
Analyzing `/tmp.cq.log` helped me diagnose the issue (the root directory being incorrectly set).

**Comment by autozimu** [comment]
Good point. Please add it into https://github.com/autozimu/LanguageClient-neovim/wiki/cquery

Thanks.

**Comment by joaospinto** [comment]
@autozimu Thanks for clarifying. I'm not sure why I'm getting this problem, then.
In my `init.vim` file, I have:
```
let g:LanguageClient_rootMarkers = {
\ 'cpp': ['compile_commands.json', 'build'],
\ }
```
However, neither of these exists in the directory that is being detected as root. Any idea why?

**Comment by autozimu** [comment]
You might be using tag 0.11 release. The mentioned `rootMakers` support is only in `next` branch and hasn't been released yet.

**Comment by joaospinto** [comment]
I just reinstalled the plugin, with the following vim-plug line:
`Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': './install.sh' }`
Still getting the same issue, though - the same directory is being detected as root as before.

**Comment by autozimu** [comment]
> not released yet

means there isn't prebuilt binary available yet, no matter which approach you use.

You'd have to checkout to latest `next` branch and use `'do': 'make release'` as post install action.

**Comment by joaospinto** [comment]
Thanks for clarifying. Works with 0.1.12 :) Keep up with the good work!
