### ISSUE TITLE
LanguageClient-neovim loses track of signs when inserting or deleting lines

### ISSUE THREAD

**Issue by evolarium** [autozimu/LanguageClient-neovim#253]
This occurs with any language server.  Using neovim 0.2.1 and LanguageClient-neovim fc6c82f7.  An example using the [`python language server`](https://github.com/palantir/python-language-server):

File opened and signs displaying properly.
![before1](https://user-images.githubusercontent.com/5010373/34503225-745caee6-efd4-11e7-8518-6ea8237b49b9.png)
![before2](https://user-images.githubusercontent.com/5010373/34503239-84eba0b4-efd4-11e7-8bc1-67cc06ac6e90.png)

A line is inserted and one line is missing it's sign.
![after1](https://user-images.githubusercontent.com/5010373/34503250-92fa40c0-efd4-11e7-8884-76a02b6a74df.png)
![after2](https://user-images.githubusercontent.com/5010373/34503251-94615b42-efd4-11e7-9c41-5a1ee15fac4f.png)

Internally, the client is comparing the list of signs from before the insertion to the list after the insertion.    This would be fine, but neovim automatically moves signs for line insertions or deletions.  In this case, the client reuses the sign that was on line 4, but vim has moved it to line 5, resulting in a missing sign.

**Comment by autozimu** [comment]
Thanks for reporting. Seems like the diff optimization is fundamentally flawed.
