### ISSUE TITLE
dart-language-server get a timeout error.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [autozimu/LanguageClient-neovim#254]
- neovim/vim version
`NVIM v0.2.2`
- Plugin version (git SHA)
`4087bef3221fdadf76efc36e439077e7c1017556`
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': './install.sh'
    \ }

let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ 'javascript': ['~/javascript-typescript-langserver/lib/language-server-stdio.js'],
    \ 'javascript.jsx': ['~/javascript-typescript-langserver/lib/language-server-stdio.js'],
    \ 'dart': ['dart_language_server'],
    \ 'objc': ['~/cquery/build/release/bin/cquery', '--language-server'],
    \ 'cpp': ['~/cquery/build/release/bin/cquery', '--language-server'],
    \ 'c': ['~/cquery/build/release/bin/cquery', '--language-server'],
    \ }

```

- Language server name/link and version
`https://github.com/natebosch/dart_language_server`

- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1599676/LanguageClient.log)

Client start successfully,but all the functions are invalid. At last plugin throw timeout error.
`2018-01-02T22:50:19.082985606+08:00 ERROR languageclient::languageclient - Error handling message. Message: {"id": 2, "jsonrpc": "2.0", "method": "textDocument/definition", "params": {"character": 6, "handle": true, "languageId": "dart", "line": 2, "buftype": "", "filename": "/home/max/v2ex-flutter/lib/detail.dart"}}. Error: Err(Timeout)
`

**Comment by autozimu** [comment]
The timeout is 5mins, which IMO is reasonably long enough.

It's more like a dart language server issue. Either ask them to improve server performance or provide some temporary workarounds.

Also, the attached log didn't have any error.
