### ISSUE TITLE
Don't try to go to definition in another file with unsaved changes in the current buffer

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#255]
- neovim/vim version nvim v0.2.2
- Plugin version (git SHA) 62f278a93d0e153594e8195179ce1d84f1701205
- Language server name/link and version RLS or cquery
- Reproduction steps (from clean state)
    1. Open a file.
    2. Make some change, like inserting a line.
    3. Try to go to definition of something that's defined in another file.

The language client tries going to definition, but vim refuses to change the open file due to unsaved changes. It sometimes gives an error `Vim(edit):E37: No write since last change (add ! to override)` and then puts the cursor into a random spot in the current file (maybe to where it was supposed to go in the target file).

**Comment by KillTheMule** [comment]
You could use `:set hidden`. As far as I can see, this is the intended behavior, except for putting the cursor in a different spot.

**Comment by autozimu** [comment]
See previous comment.

Also similar to https://github.com/autozimu/LanguageClient-neovim/issues/5
