### ISSUE TITLE
Jump back to previous position after LanguageClient_textDocument_formatting

### ISSUE THREAD

**Issue by dvcrn** [autozimu/LanguageClient-neovim#260]
First of all, big thank you for maintaining this! 

I am trying to use the format option but noticed that my cursor always jumps to the top of the document when doing that. I tried some vim magic like 

```
:execute 'normal mp' | call LanguageClient_textDocument_formatting() | execute 'normal `p'
```

but (guessing) because of the async communication it doesn't really work. The mark is getting set fine and I can jump back to it with `p, I just can't chain it directly after the command. 

Can I somehow specify a callback to execute my mark jump once formatting is done?

**Comment by autozimu** [comment]
It should restore cursor but I think I missed this point. Will make a change shortly to fix this.

**Comment by dvcrn** [comment]
Thanks a lot for implementing this! It works perfect 👍 

Another side question related to my question above, but is it possible to somehow specify a callback? 

For example, when specifying that it should reformat with every save:
```
autocmd BufWritePre *.exs silent :call LanguageClient_textDocument_formatting()
```
The autocmd is dispatching `LanguageClient_textDocument_formatting()` just fine, but because it is async the editor will write faster than LanguageClient is able to get the callback from the languageserver and format the text, effectively meaning that the save happens without the formatted code

**Comment by autozimu** [comment]
The main benefit of lsp is the async property. Sync operation is possible, see how `LanguageClient#complete` implemented, but it's ugly and hacky.

For your use case, it might be much easier to call standalone formatter (e.g., rustfmt, go fmt) rather use LSP.
