### ISSUE TITLE
"Failed to get file texts" error on publishDiagnostics

### ISSUE THREAD

**Issue by Anrock** [autozimu/LanguageClient-neovim#261]
neovim version: v0.2.3-271-g1e68e0630
Plugin version:  binary-0.1.19-x86_64-pc-windows-gnu
Minimal vimrc:
```
call plug#begin()
Plug 'autozimu/LanguageClient-neovim', {
    \ 'tag': 'binary-*-x86_64-pc-windows-gnu',
    \ 'branch': 'next'
    \ }
" Plug 'roxma/nvim-completion-manager'
call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie', '--lsp', '-d', '-l', 'D:\Temp\hie.log']
    \ }
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_autoStart = 0
```
Language server: https://github.com/haskell/haskell-ide-engine at dfff35dbb2054b3de0ef5e3cc5875809db114f7d with haskell-lsp package overriden to 0.2.0.1
Reproduction steps (from clean state)
1. Open tests/data/sample-hs/main.hs from this repo
2. Make error in file, i've erased first letter from `putStrLn`, so file looked like this:
```
main :: IO ()

main = utStrLn "hello"
```
Expected: "variable not defined" error on 3 line
Actual: no error reported, "Failed to get file texts" in LanguageClientLog for every publishDiagnostics event.

Error appeared after update from 0.1.13-0.1.14 (don't remember exact version) to 0.19.0

[LanguageClientLog](https://pastebin.com/keVi94vX)
[hie log](https://pastebin.com/nyc16eJC)

**Comment by Anrock** [comment]
Git bisect reported that a3416798fd1253c66fc8e3b45e4af5fcc5b00a16 is the first bad commit.

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by Anrock** [comment]
> Windows paths are so annoying!

Oh yeah
