### ISSUE TITLE
Duplicate help tag

### ISSUE THREAD

**Issue by KillTheMule** [autozimu/LanguageClient-neovim#263]
https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L280 and https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L285 define the same help tag, giving trouble on installation through dein.

**Comment by autozimu** [comment]
CLosed in https://github.com/autozimu/LanguageClient-neovim/commit/720c41069ed75a15f9775396674adb1c313ea17a
