### ISSUE TITLE
Json: is 'null' a substitute for optional json parameter 

### ISSUE THREAD

**Issue by vargheseg** [autozimu/LanguageClient-neovim#265]
neovim: NVIM v0.2.2
Plugin version:  tag- 0.1.22

cquery crashes on receiving lsp initialize message from LanguageClient-neovim (https://github.com/jacobdufault/cquery/issues/247)
Suspect this is probably because  the initialize message has optional parameters with null as its value: eg `"workspace":null`

> 2018-01-06T23:38:47.708110617+01:00 INFO languageclient::languageclient - => {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"experimental":null,"textDocument":{"codeAction":null,"codeLens":null,"completion":{"completionItem":{"commitCharactersSupport":null,"documentationFormat":null,"snippetSupport":false},"dynamicRegistration":null},"definition":null,"documentHighlight":null,"documentLink":null,"documentSymbol":null,"formatting":null,"hover":null,"onTypeFormatting":null,"rangeFormatting":null,"references":null,"rename":null,"signatureHelp":null,"synchronization":null},"workspace":null},"initializationOptions":{"cacheDirectory":"/tmp/cquery","compilationDatabaseDirectory":"/home/vargheseg/Projects/DeviceAccess","resourceDirectory":"/home/vargheseg/bin/cquery/lib/clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04/resource-dir/"},"processId":20355,"rootPath":"/home/vargheseg/Projects/DeviceAccess","rootUri":"file:///home/vargheseg/Projects/DeviceAccess","trace":"off"},"id":7}

Is it valid JSON  for optional parameters to be represented as having a null value as opposed to not being part of the message? Depending on this either LanguageClient-neovim would have to change behavior or cquery will have to support current behavior.

**Comment by autozimu** [comment]
As far as I understand, null should be treated same as ommited. Better to
make changes in cquery side.

**Comment by autozimu** [comment]
And cquery should not quit itself even if parameter send by client is
invalid.

**Comment by jiegec** [comment]
Okay, now we have the conflict here. 😒
