### ISSUE TITLE
REQ: auto run language client

### ISSUE THREAD

**Issue by butterflyfish** [autozimu/LanguageClient-neovim#27]
when using deoplete/deoplete-source, it does not need to run command manually. I wonder is it possible to introduce this feature also, then user experience is improved.

**Comment by autozimu** [comment]
Thanks. I might start implementing that shortly.

**Comment by autozimu** [comment]
I've been kind of busy these days. So the actual work might be delayed.

As always, PRs are very welcomed.

At the same time, one can achieve the same result using
```
autocmd BufReadPost *.rs LanguageClientStart
```
