### ISSUE TITLE
Propagate workspace info after jumping to a new file (esp. outside of a project)

### ISSUE THREAD

**Issue by MaskRay** [autozimu/LanguageClient-neovim#272]
a.cc in a project
```c++
#include <vector>   // textDocument/definition on `vector` jumps to /usr/include/.../vector
```

If the buffer associated with `<vector>` does not exist, LanguageClient-neovim should open the file and set the language to `filetype`.
Next. If the buffer associated with `<vector>` does not have workspace information, assigns it the workspace information.

https://github.com/emacs-lsp/lsp-ui/pull/22
https://github.com/jacobdufault/cquery/issues/261

**Comment by autozimu** [comment]
The file newly opened doesn't have to be the same filetype as current one.

For second item, it's already implemented.
