### ISSUE TITLE
Errors at unpredictable times

### ISSUE THREAD

**Issue by KillTheMule** [autozimu/LanguageClient-neovim#276]
Hey!

I'm seeing some errors which, when occuring, make neovim unusable on rust files, because they'd keep popping up all the time. Outside of these errors though, everything seems to work ok, and I have not yet been able to reproduce them reliably. They just seem to pop up now and then, sometimes fast, sometimes later.

- neovim version: 0.2.3.-dev
- Plugin version (git SHA): bb480c47b68a7ad10f4d56396c2ff75b91fb00d1
- Minimal vimrc: None yet, see below.
- Language server name/link and version: rls-preview 0.124.0-nightly (be23ad3 2017-12-06)
- Reproduction steps: None yet.
- Logs. https://gist.github.com/KillTheMule/41a880bb1f58e88b75b24f251cc8a954 is the output of `:messages` from neovim. I've left in everything, even the things I don't think are related.

After the error(s) occured, they seem to pop up on most keypresses. I'm a bit lost on how to debug this, so maybe you can give me some hints. I'll try to narrow down my `init.vim`, but it's not huge to begin with.

**Comment by technetos** [comment]
I am also experiencing this behavior in neovim on rust files.  Have you noticed that the diagnostics seem to only work when you first open your rust file (start the language server) and then vanish after you make a change?

**Comment by KillTheMule** [comment]
What do you mean by "diagnostics"?

**Comment by technetos** [comment]
Warnings and errors in the sign column such as unused imports.

**Comment by KillTheMule** [comment]
Ah yeah, they seem to get stuck. I've use `:sign unplace *` to get rid of them, I think they regenerate after that.

**Comment by autozimu** [comment]
Please try latest commit.

Note the commit will only mitigate the impact when the error happened, but I haven't figure out why the issue occurred in the first place, so I will keep this issue open.

To fully resolve the original error, please do me a favor by having
```vim
let g:LanguageClient_loggingLevel = 'info'
```
in your vimrc. And attach the log here when the error happened again.

**Comment by KillTheMule** [comment]
Will do, thank you!

**Comment by technetos** [comment]
Much appreciated and will do.

**Comment by KillTheMule** [comment]
So, with the then-latest-commit (I think I'm on 0.27 now) I have not yet seen the error again, even though I've spent quite some time with it. I'll keep the logginglevel, but I'll close this issue and come back if something appears.

**Comment by autozimu** [comment]
Thanks for this feedback.
