### ISSUE TITLE
 signTexthl does not work

### ISSUE THREAD

**Issue by Dcryfm** [autozimu/LanguageClient-neovim#277]
This is my configuration:

```vim
let g:LanguageClient_diagnosticsDisplay = {
  \1: {'name': 'Error', 'texthl': 'ALEError', 'signText': 'E', 'signTexthl': 'ALEErrorSign',},
  \2: {"name": "Warning", "texthl": "ALEWarning", "signText": "W", "signTexthl": "ALEWarningSign",},
  \3: {"name": "Information", "texthl": "ALEInfo", "signText": "ℹ", "signTexthl": "ALEInfoSign",},
  \4: {"name": "Hint", "texthl": "ALEInfo", "signText": "➤", "signTexthl": "ALEInfoSign",},
\}
```

This is the error sign of ale:
![](https://github.com/Dcryfm/jsdoc/blob/master/issues_images/LanguageClient-neovim/%23277_01.png?raw=true)

This is the error sign of LanguageClient:
![](https://github.com/Dcryfm/jsdoc/blob/master/issues_images/LanguageClient-neovim/%23277_02.png?raw=true)

**Comment by autozimu** [comment]
Can you remove ale and try it again?

As far as I can see, the signs in both screenshots were not created by LanguageClient. As if they were, they would be shown as `E` instead of the fancy unicode chars.

**Comment by ghost** [comment]
@autozimu 
I want to show you the sign after disabling ale and LanguageClient respectively, but now LanguageClient is not working.
![](https://github.com/Dcryfm/jsdoc/blob/master/2018-01-16%2012-07-19%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png?raw=true)

I tried to disable ale and LanguageClient's sign still has no color. And it seems that when ale and LanguageClient take effect at the same time, ale's sign has no color.

**Comment by autozimu** [comment]
Please follow issue template to provide necessary info, especially providing minimal vimrc and reproduction steps. I don't have time to debug various env issue.

**Comment by ghost** [comment]
@autozimu 

## environment
- neovimversion: 0.2.2
- Plugin version (git SHA): 7d0a5cc
- Minimal vimrc:

```vim
" Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'proxychains4 bash install.sh',}
nnoremap <space>lch :call LanguageClient_textDocument_hover()<CR>
set hidden
let g:LanguageClient_serverCommands = {
  \'javascript': ['javascript-typescript-stdio'],
  \'css': ['css-languageserver', '--stdio'],
  \'html': ['html-languageserver', '--stdio'],
  \'json': ['json-languageserver', '--stdio'],
  \'vue': ['vls'],
\}
let g:LanguageClient_diagnosticsDisplay = {
  \1: {'name': 'Error', 'texthl': 'ALEError', 'signText': '', 'signTexthl': 'ALEErrorSign',},
  \2: {'name': 'Warning', 'texthl': 'ALEWarning', 'signText': '', 'signTexthl': 'ALEWarningSign',},
  \3: {'name': 'Information', 'texthl': 'ALEInfo', 'signText': 'ℹ', 'signTexthl': 'ALEInfoSign',},
  \4: {'name': 'Hint', 'texthl': 'ALEInfo', 'signText': '➤', 'signTexthl': 'ALEInfoSign',},
\}

Plug 'roxma/nvim-completion-manager'
```

When I first installed LanguageClient, there was a problem I was reporting now, but I didn't care about it at that time, and the problem was only that sign had no color, I didn't know how to reproduce it.

By the way, is there a plan for diagnosticsDisplay to be integrated with airline, like ale:
![](https://github.com/Dcryfm/jsdoc/blob/master/issues_images/LanguageClient-neovim/%23277_04.png?raw=true)

**Comment by autozimu** [comment]
Minimal vimrc is not an excerpt from your current vimrc. It's a minimal vimrc to get the issue reproduced.

I cannot help when you cannot provide minimal vimrc and definite reproduction steps. Besides, the diagnostics display customization works properly when I tried it.

For the airline integration, it's not supported (yet) as I'm not interested/motivated. As always, PR is welcome.
