### ISSUE TITLE
TypeScript and JavaScript completion problems.

### ISSUE THREAD

**Issue by JulioJu** [autozimu/LanguageClient-neovim#278]
- neovim/vim version NVIM v0.2.2 or NVIM v0.2.3-104-g12b8cd6a2
- Plugin version (git SHA) 72ce5b750368b95be58641ab591182fd859400dc
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
```vim
call plug#begin('~/.vim/plugged')
" Syntax typescript
Plug 'leafgarland/typescript-vim', { 'for': ['typescript']}
Plug 'HerringtonDarkholme/yats.vim', { 'for': ['typescript']}
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
call plug#end()
filetype plugin indent on
augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END
let g:LanguageClient_serverCommands = {
    \ 'typescript': ['javascript-typescript-stdio'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ }
let g:LanguageClient_loggingLevel = 'DEBUG'
```

- Language server name/link and version javascript-typescript-stdio version 2.5.5
- Reproduction steps (from clean state)
    1. In a TypeScript file type for example "console.<C-x><C-O>"
== > Omin completion doesn't work. "console" is replaced by "assert". 
I've try lot of solutions, doesn't work. I've tried with a file JavaScript, doesn't work too. Others features work, but not completion. 

With [ALE](https://github.com/w0rp/ale), with your https://github.com/autozimu/LanguageClient-neovim/tree/next/tests/data/sample-ts + a file tsconfig.json, it works. 
- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1631643/LanguageServer.log)
[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1631644/LanguageClient.log)

**Comment by autozimu** [comment]
Sorry about that. It was introduced in a recent cleanup. And thanks for reporting.
