### ISSUE TITLE
`infile.read` is not compatible with vscode-rpc

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#28]
I'm using vetur's language server. The setup is rather complicated.

And I encountered cross boundary read. 

The log looks like 
```json
TIMESTAMP  DEBUG     <=  {"jsonrpc":"2.0",
....
'on content inserted into child components to indicate which named slot the content belongs to."}]}}Content-Length: 15
```

The root cause is the discrepancy how python reading bytes and how vscode-jsonrpc computes length. 

Note the vscode-implementation: `Buffer.byteLength`  is used instead of `message.length`

https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messageWriter.ts#L75

This makes LC-neovim misfunctions.

Example response: https://gist.github.com/HerringtonDarkholme/456d6af5d6a8509df00019fc8bd0a973

You can inspect the string length and the Buffer.byteLength difference.

**Comment by autozimu** [comment]
Thanks, I will look into it some time this week.
