### ISSUE TITLE
Vim cannot read JSONRPC messages

### ISSUE THREAD

**Issue by ThomasFaivre** [autozimu/LanguageClient-neovim#282]
Hello!

- neovim/vim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 13 2017 16:37:45)
Included patches: 1-972

- Plugin version (git SHA)
b4033ed34fa4

- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
Yes

- Language server name/link and version
pyls: palantir/python-language-server 0.12.0

- Reproduction steps (from clean state)
    Just launch vim. Client is launched but vim cannot read its messages.
    Git bisect gave me this commit: ccec0c6e08cbe91ccce8652992de9f2011b5adfb.
    From what I understand, Vim execute its callback (stdout at least, probably stderr too) for every line. This makes HandleMessage's loop run only once every time, resetting ``input`` and ``content_length`` and therefore it tries to get the ``Content-Length`` message every time.

- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
  No actual Language Server is launched so LOGGER is not initialized. There is no log to attach, sorry :x Even with this line in the main function:
``lazy_static::initialize(&LOGGER);

**Comment by autozimu** [comment]
Yes, you are right. Thanks for reporting.
