### ISSUE TITLE
Working in Neovim but not Vim 8

### ISSUE THREAD

**Issue by AgentCosmic** [autozimu/LanguageClient-neovim#283]
- neovim/vim version (vim8)
- Plugin version (git SHA) (72ce5b750368b95be58641ab591182fd859400dc)
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>) (Yes)
- Language server name/link and version (https://www.npmjs.com/package/javascript-typescript-langserver latest version)
- Reproduction steps (from clean state)
    1. Tried out most feature in Neovim and works.
    2. Copy the config over to vim8
    3. Tried running LanguageClientStart and various commands such as call LanguageClient_textDocument_rename(). Nothing works. No error, no message.
    4. Check Task Manage to see if the language started. Nope. But it did in Neovim.

- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.

I'm on Windows. Where is the log located? C:\Windows\Temp doesn't have anything.

On an unrelated note, the g:LanguageClient_serverCommands only works when I put the full path even though the command is already in my PATH. Not sure if this is a bug. It took me a long time to figure this out.

**Comment by autozimu** [comment]
Please update to latest version and try again.

Dup #282.
