### ISSUE TITLE
404 on 0.1.28 on OSX and probably other clients during install.sh

### ISSUE THREAD

**Issue by admmasters** [autozimu/LanguageClient-neovim#284]
I don't think the binary path exists yet for some platforms - which is causing the error:
The requested URL returned error: 404 Not Found
--2018-01-17 12:36:39--  https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.28/languageclient-0.1.28-x86_64-apple-darwin
This is on OSX but I'm pretty sure it will be the same on other platforms:
https://github.com/autozimu/LanguageClient-neovim/releases/tag/0.1.28

**Comment by ghost** [comment]
Travis CI is not working.

https://www.traviscistatus.com/

**Comment by autozimu** [comment]
Travis back to normal and binaries are available.
