### ISSUE TITLE
tslint in TypeScript

### ISSUE THREAD

**Issue by JulioJu** [autozimu/LanguageClient-neovim#290]
Hi,

Is it possible than LanguageClient-neovim use the local tslint ? With [ALE](https://github.com/w0rp/ale), is it possible thanks to `let g:ale_typescript_tslint_config_path = 'tslint.json'`. There is a similar command with LanguageClient-neovim ? I've looking for in the documentation and in the issues, but not founded. 

Thanks in advance,

**Comment by autozimu** [comment]
This should be made on language server side. Please file ticket in their repo.

**Comment by JulioJu** [comment]
@autozimu 
[ALE](https://github.com/w0rp/ale) implements this, and it's only a client. So it could be at the client side. 
TSLint is only a linter. It's independant of tsserver (see at https://github.com/Microsoft/TypeScript/issues/15589).

What do you think about that ? I beilieve actually it should not be made on language server side. And maybe it will be never for some of linting errors.
