### ISSUE TITLE
Command to reset highlights

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#295]
Sometimes language servers crash and I am left with left-over highlights from previous runs. It would be nice if there was a way to completely clear the state of this plugin for a buffer. `:LanguageClientStop` doesn't do the trick.

**Comment by autozimu** [comment]
In latest versions, `:LanguageClientStop` should clean that up.

**Comment by languitar** [comment]
I think this reappeared or never worked correctly. I am currently facing issues with the python language server. It frequently crashes and leaves a lot of highlights and annotations in the gutter. `LanguageClientStop` does not clean them. Even a subsequent `LanguageClientStart` does not clear the previous highlights and gutter entries. Updated today to 15cba0e724458dd3e44e0603bc898e2cfdf77e9b
