### ISSUE TITLE
Display diagnostics source in diagnostics output

### ISSUE THREAD

**Issue by jadedarko** [autozimu/LanguageClient-neovim#296]
For ALE, one can use

    let g:ale_echo_msg_format = '%linter%: %s'

To prepend the linter to the diagnostics output.
Is there a similar mechanism for this?
I was unable to see how diagnosticsDisplay could be configured to allow this.

**Comment by autozimu** [comment]
No.

I'm not interested in implementing this myself. PR is welcome.

**Comment by martskins** [comment]
Closing this, as it is fixed by #1062
