### ISSUE TITLE
Possible to call `LanguageClient_textDocument_formatting()` in a blocking manner?

### ISSUE THREAD

**Issue by jasongraham** [autozimu/LanguageClient-neovim#297]
Is it possible call `LanguageClient_textDocument_formatting()` in a blocking manner?

I have the following line set up in my config file, and whenever I write I believe the write is completing prior to the format operation, because after the write I end up with a correctly formatted but modified buffer.
```vimscript
autocmd filetype python autocmd BufWritePre <buffer>
            \ :call LanguageClient_textDocument_formatting()<cr>
```

**Comment by autozimu** [comment]
See https://github.com/autozimu/LanguageClient-neovim/issues/260#issuecomment-359271432
