### ISSUE TITLE
Snippets showing up with Rust Lang Server

### ISSUE THREAD

**Issue by bzm3r** [autozimu/LanguageClient-neovim#298]
I am using the following plugins:

    " (Optional) Multi-entry selection UI.
    Plug 'junegunn/fzf'

    " because I am on windows, my 'tag' variable is different than in the install instructions
    " see: https://github.com/autozimu/LanguageClient-neovim/issues/270
    Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'tag': 'binary-*-i686-pc-windows-gnu'}

    " completion manager
    Plug 'roxma/nvim-completion-manager'

    " rust
    Plug 'rust-lang/rust.vim'
    Plug 'roxma/nvim-cm-racer'

I find that when I started typing a function name, and then choose an option from the auto-complete drop down menu, some sort of snippet type deal gets produced, for example:

    create_surface(${1:entry}, ${2:instance}, ${3:window})

That's pretty cool, **but I can't seem to find documentation for the feature**. For instance, when opening up help with `:h LanguageClient`, if I search for snippet, I get no results.

I posted about this problem on the Rust subreddit, wondering if it was a Rust.vim feature, but was pointed here: https://www.reddit.com/r/rust/comments/7t34a7/neovim_with_official_rustvim_how_to_expand/

In particular, the following issues were recommended to me:

* https://github.com/autozimu/LanguageClient-neovim/pull/193: I don't quite understand how this one is relevant, because I am not using deoplete? 

* https://github.com/autozimu/LanguageClient-neovim/pull/286: suggests that the issue might be on the side of the language server for providing snippets when there is no snippet manager installed, but the language server I am using (RLS) seems to have already fixed this issue: https://github.com/rust-lang-nursery/rls/pull/648

* https://github.com/autozimu/LanguageClient-neovim/issues/294: this issue is a bit too technical for me to appreciate and thus hard for me to use to solve my current problem

So I would like to ask two questions:

1) If the snippets are intended: what is providing the snippets? Where can I read about how to complete them?

2) If the snippets are unintended, what should I do?

**Comment by KillTheMule** [comment]
> I don't quite understand how this one is relevan

Just as a side node, I don't understand either, I just wanted to point out some things that seemed related.

**Comment by bzm3r** [comment]
@KillTheMule no problem! I was just mentioning, in case it *is* somehow relevant, and I am simply missing the point.

**Comment by autozimu** [comment]
Can you paste here your rls version?

The fix is merged in rls, but might only included in recent versions of nightly rls.

**Comment by bzm3r** [comment]
@autozimu I decided to update my rust nightly, before I posted the version (wanted to say it was the latest), but the problem disappeared as soon as I disabled nightly. Thank you, and sorry for this silly issue that I raised!
