### ISSUE TITLE
How to disable gutter?

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#302]
why? I think `texthl` has enough conspicuous.
I try to set the value of `signText` to an empty string, but there are still gutter:

```vim
let g:LanguageClient_diagnosticsDisplay = {
  \1: {'name': 'Error', 'texthl': 'ALEError', 'signText': '', 'signTexthl': 'ALEErrorSign',},
  \2: {'name': 'Warning', 'texthl': 'ALEWarning', 'signText': '', 'signTexthl': 'ALEWarningSign',},
  \3: {'name': 'Information', 'texthl': 'ALEInfo', 'signText': '', 'signTexthl': 'ALEInfoSign',},
  \4: {'name': 'Hint', 'texthl': 'ALEInfo', 'signText': '', 'signTexthl': 'ALEInfoSign',},
\}
```

So is there any option to disable gutter?
Thanks.

**Comment by autozimu** [comment]
No, but happy to take in PR.

**Comment by dcosson** [comment]
By disable gutter, do you also mean disable error checking on save altogether? That's a feature I'm looking for that i haven't found.

Now that ALE also has support for LSP, I'd like to stick with ALE for error & syntax checking (mainly because I'm already running some non-LSP linters through ale and it makes sense to me for all error checking & highlighting to be handled by one plugin for consistency. Plus ALE has some nice helpers like making the current error count available to display in powerline, and being able to jump to the next error which I don't think LanguageClient has).

But I still want to use LanguageClient when possible for things like showing the type under the cursor, jump to definition, refactoring, and other non-error-displaying LSP use cases.

Is this possible?

**Comment by autozimu** [comment]
I think you need check this setting https://github.com/autozimu/LanguageClient-neovim/blob/7cf0f288ce80d633f3f68a6476260e0dd48f6bc0/doc/LanguageClient.txt#L147

Just to be clear, when LanguageClient is handling diagnostics (default behaviour), it will update quickfix/location list, so jumping to next error etc is supported.

**Comment by matthewgrossman** [comment]
Not sure if this is a related issue;

 I'm in a similar boat to some users where I'm already setup w/ ALE as my linter/fixer but still want to use a Language Server for jump-to/completion/etc. I thought I could accomplish this with
```
let g:LanguageClient_diagnosticsEnable = 0
```
For the most part, it seemed to work (no longer checking on `pyls`'s internal linters that I didn't care for). However, something strange is happening where it seems that all the gutter symbols _are_ coming from ALE, but simply having `LanguageClient` installed is messing with the configuration of the what they look like. 

With diagnostics off, I would expect this plugin to have no effect on the gutter/quickfix/locationlist at all, but it seems to still be leaking its config. Will https://github.com/autozimu/LanguageClient-neovim/pull/492 fix this problem? If this is unclear, I can elaborate w/ some screenshots and example init.vims

EDIT: from digging through `:highlight`, I noticed that all the ALE signs were cleared
```
ALEInfoSign    xxx cleared
ALEErrorSign   xxx cleared
ALEWarningSign xxx cleared
```
is this possibly caused from this line? https://github.com/autozimu/LanguageClient-neovim/blob/92b047bea8e47cada801da9bfe1f3aa89eaa5775/src/languageclient.rs#L411

I would think that shouldn't run if the diagnostics setting is disabled

**Comment by autozimu** [comment]
Resolved in https://github.com/autozimu/LanguageClient-neovim/commit/bb733ef7ff87328426cf00ab517495ea45d90cdf

**Comment by dsifford** [comment]
@autozimu Sorry to bother, but I can't seem to locate this anywhere:

Is it currently possible to jump between error/info/warning messages? From looking over the past half hour, it doesn't seem to be possible.

Thanks

**Comment by matthewgrossman** [comment]
hey @dsifford , this part of the docs notes that that all the diagnostic info is populated in the quickfix or loclist: https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L47

Theres a bunch of ways of navigating these two lists, but I'd recommend looking into https://github.com/tpope/vim-unimpaired for some nice keybindings

**Comment by dsifford** [comment]
@matthewgrossman You are a saint :pray: 

Not sure how I missed that. Thanks so much!

**Comment by liushapku** [comment]
Is it possible to enable diagnostic information in gutter but at the same time disable its handling in quickfix list/location list? For me, I feel the info in gutter is quite nice to have and helpful. But I don't want it to automatically update my quickfix list. 

The quickfix list is used for many different purposes. For example, `:vimgrep /TODO:/ *` and then jump to each occurrence to make some changes. But this list is replaced by the diagnostics short after the change happens.

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/12a1f60cb25754c6e63c56a4df79aed280377710/doc/LanguageClient.txt#L172-L177
