### ISSUE TITLE
Support for Asynchronous Lint Engine?

### ISSUE THREAD

**Issue by Industrial** [autozimu/LanguageClient-neovim#304]
Hi.

I use [ALE](https://github.com/w0rp/ale) for displaying syntax errors. When I enable `javascript-typescript-stdio` then it will not cooperate with ALE.

Would it be possible to let languageclient-neovim become a provider for ALE?

**Comment by Saul-Mirone** [comment]
I also have this question. Is there any way to do this?

**Comment by Anrock** [comment]
@Saul-Mirone ALE already provides LSP client, why have two of them?

**Comment by Saul-Mirone** [comment]
@Anrock because ALE's LSP support isn't implemented perfectly, for example the completion is only support for typescript.
