### ISSUE TITLE
Broken pipe (os error 32)

### ISSUE THREAD

**Issue by romgrk** [autozimu/LanguageClient-neovim#308]
- neovim/vim version: `NVIM v0.2.3-533-g9a36337d3`
- Plugin version (git SHA): `6f46c92150d95252390d7977ccb0c430578a75e6`
- Minimal vimrc: https://gist.github.com/romgrk/a44634aea49e39c5205a7310f847c0b4
- Language server name/link and version: `ocaml-language-server` (from npm, `npm i -g ocaml-language-server@1.0.23`)
- Reproduction steps (from clean state)
    1. Open a reason file
    2. Press K (`call LanguageClient_textDocument_hover()`)
    3. `Broken pipe (os error 32)`
- Logs: https://gist.github.com/romgrk/377bcd54b13925c14207beb3d1ebf195

Hi! I'm getting the above error just after installing the plugin and trying with the ocaml-language-server. Let me know if you need more details. Thanks!

**Comment by romgrk** [comment]
Solution: missing binaries needed by ocaml-language-server.

**Comment by AMCorvi** [comment]
@romgrk  which binaries were required to get this up and running.

**Comment by romgrk** [comment]
Not sure which ones are required, but installing the following packages solved my problem (for ReasonML):

[https://www.npmjs.com/package/reason-cli](https://www.npmjs.com/package/reason-cli)
[https://www.npmjs.com/package/ocaml-language-server](https://www.npmjs.com/package/ocaml-language-server)

Otherwise, check `:message` output for more details.

**Comment by AMCorvi** [comment]
@romgrk thanks alot! That was exactly my intended question. I had the [ocaml-language-server](https://www.npmjs.com/package/ocaml-language-server) installed, but didn't find [reason-cli](https://www.npmjs.com/package/reason-cli) in the [vim-reason-plus](https://github.com/reasonml-editor/vim-reason-plus) Readme...
