### ISSUE TITLE
Cquery configuration problem

### ISSUE THREAD

**Issue by ram535** [autozimu/LanguageClient-neovim#313]
I am trying to configure the Cquery server and tested in simple [helloWorld.cpp](https://gist.github.com/ram535/d1ce054a2d0192459799aa37876f9acf) file.

Layout of the "project".

.
├── .cquery
└── main.cpp

By reading the serverclient.log seems that the rootpath and settingspath are not being recognize.

- NVIM v0.2.3-533-g9a36337d3

- Plugin version (git SHA) **c51c5d3**
- Minimal vimrc 

```
    call minpac#add('autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' })

     let g:LanguageClient_autoStart = 1
     let g:LanguageClient_settingsPath = expand('~/.config/nvim/settings.json')
     let g:LanguageClient_rootMarkers = {
     \ 'cpp': ['.cquery', 'compile_commands.json', 'build'],
     \ }

     let g:LanguageClient_serverCommands = {
     \ 'cpp': ['cquery', '--language-server', '--log-file=/tmp/cq.log'],
     \ }
```
 - .cquery
```
# Driver
clang++

# Language
-xc++
-std=c++11

# Includes
-I/work/cquery/third_party
```

- .settings.json

```
{
        "initializationOptions": {
                "cacheDirectory": "/tmp/cquery",
        }
}
```

- Language server name/link and version. **Cquery** [v20180215](https://github.com/cquery-project/cquery/tree/v20180215)

 - Reproduction steps (from clean state)
The server is not responding when I call any function of the LanguageClient-neovim I got this error.

**Failed to start language server. See /tmp/LanguageServer.log**

1- Get on top of **addOne(x);**
2- :call LanguageClient_textDocument_definition()
3- Failed to start language server. See /tmp/LanguageServer.log

- log files

[cq.log](https://github.com/autozimu/LanguageClient-neovim/files/1729826/cq.log)
[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1729827/LanguageClient.log)
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1729828/LanguageServer.log)

**Comment by autozimu** [comment]
cquery is not supported by python implementation. Please try with rust implementation in branch `next`.

**Comment by ram535** [comment]
I did as you suggested and now I get this error:
```
Broken pipe (os error 32)
```
**rls** seems to be working fine but **dart_language_server** which was working fine before now I get this error when I enter a dart file.
```
LanguageClient: failed to register as NCM source!
```

**Comment by ivanalejandro0** [comment]
@ram535 It looks like there are other issues related to "Broken pipe (os error 32)", like https://github.com/autozimu/LanguageClient-neovim/issues/308, https://github.com/autozimu/LanguageClient-neovim/issues/231, https://github.com/autozimu/LanguageClient-neovim/issues/226

You can find them using the search option for issues on this very same repository:
https://github.com/autozimu/LanguageClient-neovim/search?q=Broken+pipe+%28os+error+32%29&type=Issues&utf8=%E2%9C%93
