### ISSUE TITLE
Path to URL conversion failing on Cygwin

### ISSUE THREAD

**Issue by yasammez** [autozimu/LanguageClient-neovim#314]
I am using vim 8.0.1486 with Cygwin 2.10 on Windows 7 and commit 2e9c3d2eb511d8ddbbb063b313f9ab23a04e32b6 on the next branch of the plugin.

When trying to do anything that requires communication with the language server, it tries to convert the file path to a Url in src/utils.rs:114, which fails because it is given a Cygwin path and tries the Windows code path (I have opened an issue at servo/rust-url as well: https://github.com/servo/rust-url/issues/434).

Minimal vimrc
```
set nocompatible
filetype off

call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh',  }
call plug#end()

let g:LanguageClient_autoStart = 0
nnoremap <leader>lcs :LanguageClientStart<CR>
let g:LanguageClient_serverCommands = {
    \ 'python': ['pyls'],
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'go': ['go-langserver'] }

noremap <silent> <C-B> :call LanguageClient_textDocument_definition()<CR>
```

**Comment by autozimu** [comment]
This does look like rust-url issue. Will wait for their fix first.

**Comment by autozimu** [comment]
Sorry to close this, but I don't know how to fix this properly and really don't want to fight Windows path mess.

It would be great if it can be fixed upstream, but it looks no one is interested enough.

**Comment by newmankyle** [comment]
In Cygwin, you can convert your file paths using 'cygpath' so I'm able to get around the problem by adding the following to LanguageClient#Call
```
if has('win32unix') && type(a:params.filename) == 1
      let l:initialfilename = a:params.filename
      " convert path to windows format
      let l:cygpathfilename = system("cygpath -wa " . l:initialfilename)
      " remove trailing newline
      let a:params.filename = substitute(l:cygpathfilename, '\n\+$', '', '')
endif
```
https://www.cygwin.com/cygwin-ug-net/using-effectively.html
https://cygwin.com/cygwin-ug-net/cygpath.html
