### ISSUE TITLE
KeyError in workspace.py line 110, in get_document 

### ISSUE THREAD

**Issue by mcepl** [autozimu/LanguageClient-neovim#317]
(originally filed as palantir/python-language-server#263 )

> If you are reporting a bug, please read following FAQ first. If you are
requesting new features or other types of questions, you can ignore it.

Have you followed the instructions at
[INSTALL.md](https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md)?
Yes (originally, this bug came with binary downloaded via ``install.sh``, now (after #315  being fixed for me) it is my own build.

# If you are still seeing an error or other types of issue, please create ticket with
- neovim/vim version vim-X11-8.0.1520-1.0.86.el7.centos.x86_64
- Plugin version (git SHA) 6f46c92
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
- Language server name/link and version palantir/python-language-server
- Reproduction steps (from clean state)
    1. Not, sure, most likely by using LanguageClient_textDocument_definition() on some symbol
    2.
    3.
- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
I don't have them from the time of reproduction, only the snippet from ``/tmp/pyls-log.txt`` in https://github.com/palantir/python-language-server/issues/263#issue-298357242

I know this is probably not enough information, so feel free to close this.

**Comment by autozimu** [comment]
Couldn't reproduce locally.

Feel free to reopen after getting concrete reproduction steps.

**Comment by wmonk** [comment]
@autozimu I think the issue here is that the `textDocument/didOpen` method is not triggered until the file is edited in some way. I am experiencing the same behaviour as @mcepl, but when I trigger insert mode I can see messages in the server log like:
```
2018-03-01 09:20:35,940 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc":"2.0","method":"textDocument/didOpen"
...
```
I think the issue originally reported in palantir/python-language-server#263 is showing an error where the file isn't stored in the cache, and this is only triggered once the file is "edited" in some way.

**Comment by autozimu** [comment]
Were you able to provide concrete reproduction steps?
