### ISSUE TITLE
[Question] How to use settings.json feature?

### ISSUE THREAD

**Issue by miuirussia** [autozimu/LanguageClient-neovim#319]
How to use settings.json feature with: https://github.com/haskell/haskell-ide-engine? I don't understand how to send hlintOn: false to languageServer

**Comment by autozimu** [comment]
Inside your project, create `.vim/settings.json`. Insert whatever config you want to pass to server, e.g.,
```json
{
    "hlintOn": false
}
```

See https://github.com/autozimu/LanguageClient-neovim/blob/32bb56bacbf6040e49bf43d73891021dcfc877eb/doc/LanguageClient.txt#L155-L159

**Comment by DerWeh** [comment]
Is it possible to use these settings on a global basis? Therefore, we probably need to specify which language severs these settings are for.
Or is the proper way to dynamically set the file
```vim
autocmd FileType python let g:LanguageClient_settingsPath = 'HOME/.config/nvim/languageclient/python_settings.json'
```
and keep a file for every server?
