### ISSUE TITLE
Feature REQ: auto key map

### ISSUE THREAD

**Issue by butterflyfish** [autozimu/LanguageClient-neovim#322]
currently, language server is started automatically. If language server support 'go to definition',  it's better if map key *gd* to :call LanguageClient_textDocument_definition().
 
if language support formatting, execute it automatically on Bufwrite event etc.
if language support diagnostics, execute it automatically on Bufwrite event etc.

**Comment by autozimu** [comment]
Will answer one by one.

1. No. Overriding existing key bindings would be an awful UX.
1. This is currently impossible since all of the operation is async. Check previous similar issue for detailed explanation.
1. It's already been done.

**Comment by butterflyfish** [comment]
@autozimu  I agree it's not a good idea to override key map for some user. But I think LanguageClient_textDocument_definition is better for builtin gd if language support this feature. How about provide this feature, but turn it off, leave control at user hand.

**Comment by autozimu** [comment]
Then what's the difference from let user do the mapping themselves? They're all one lines.
