### ISSUE TITLE
How to make hints register-independent(case-insensitive)?

### ISSUE THREAD

**Issue by D1mon** [autozimu/LanguageClient-neovim#323]
How to make hints(autocomplete) register-independent(case-insensitive)?
`document.qSA` => `document.qsa`

**Comment by autozimu** [comment]
It's language server and completion engine decision/feature.

BTW, case-insensitive completion is supported  by javascript language server and deoplete,
![screen shot 2018-03-13 at 18 18 05](https://user-images.githubusercontent.com/1453551/37378089-f70257ea-26ea-11e8-85db-e94e96d780a1.png)
