### ISSUE TITLE
Deoplete poorly support Rust completion via LC (trigger character)

### ISSUE THREAD

**Issue by andreyorst** [autozimu/LanguageClient-neovim#329]
Hello. I've read from your [README.md](https://github.com/autozimu/LanguageClient-neovim/blob/next/README.md) that you support deoplete, and nvim-completion-manager (wich i've never heared of, but we'll come to that later).
Personally I use deoplete for a long time with [deoplete-clang](https://github.com/zchee/deoplete-clang) and it provides great completion system to me when I program in C and C++. I've decided to try Rust, and went through many different plugins that _provide_ completion system for it. But none of them use deoplete _(except deoplete-rust, but I couldn't make it to work. And the last commit is 8 month ago, so i think it's dead anyway)_, wich I use daily and don't want to change to the other thing for another language. If I could. And assuming that you support deoplete I think that I could. But there is an issue:

That's how deoplete works with C++:
![deoplete_clang](https://user-images.githubusercontent.com/19470159/37322714-57d2907c-2690-11e8-8293-1c8e84bede87.gif)

And this is how deoplete works with LanguageClient-neovim:
![deoplete_lc](https://user-images.githubusercontent.com/19470159/37322718-615e022a-2690-11e8-9370-7a2796708d7a.gif)

I type use std:: and nothing happens. Yes it will eventually show something if I type in some more, but I don't know Rust, and I like to check what completion system shows, to explore method names etc.
![image](https://user-images.githubusercontent.com/19470159/37296079-ecb3e6d4-262a-11e8-9346-b2875fab92f9.png)

Well but this is not what I guessed when watched gifs in readme... I started to think that's the plugin itself works this way, but I decided to give a try to nvim-completion-manager, and the result is fascinating:
![ncm_lc](https://user-images.githubusercontent.com/19470159/37322725-6a7e3866-2690-11e8-9244-9e9f80f74a53.gif)

I tried to use nvim-completion-manager for C/C++, but I don't quite like its completion output. When I switched from YCM to deoplete I feeled major difference, that deoplete provides better autocompletion list.

So I tried to reproduce it with theese plugins only: `deoplete + LanguageClient-neovim`. Still poor completion
However `nvim-completion-manager + LanguageClient-neovim` works wery well. Is there something wrong in my particular deoplete setup, or is it partly supported?

---

**neovim version:**
NVIM v0.2.2
Build type: Release
**Plugin version (git SHA):**
git rev-parse origin/master
d0133bffd5c1d31f624f3f5f4f544d95ab4f7c4c

**Language server name:**
rls-preview 0.124.0-stable (299a6a9 2017-12-25)

**Reproduction steps (from clean state):**
    1. Installed LanguageClient-neovim according to README.md
    2. Tried to use it with my deoplete setup

**minimal vimrc**
Sorry, I use vundle and don't understand how to use that `Plug` thing in [your minimal vimrc](https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim), and will provide this [minimalrc.txt](https://github.com/autozimu/LanguageClient-neovim/files/1803708/minimalrc.txt) instead. Here are contained all setting that i use with deoplete, wich work fine for C/C++ but not for Rust. And at the end of the file some settings for nvim-completion-manager.

**Comment by Shougo** [comment]
https://github.com/autozimu/LanguageClient-neovim/commit/fbc46862af7fa254f74f1108149fd0669c46f1ad

The change breaks deoplete source.

**Comment by autozimu** [comment]
The reason behind this change is that there isn’t a proper way to customize
different keyword to trigger completion in different filetype. The regex
works with one filetype would cause problems in a different filetype. Or
you could point me to the right way to do it?

**Comment by Shougo** [comment]
deoplete omni source uses `input_patterns` variable for it.
omni source `get_complete_position()` checks it.

**Comment by sodiumjoe** [comment]
I opened https://github.com/Shougo/deoplete.nvim/issues/687 on deoplete thinking it was an issue there, but Shougo closed it pointing here. I'm not sure, but it does seem like a similar issue, except with javascript.

**Comment by autozimu** [comment]
Should be resolved by 5cce14326e8a7c317b72a85a5a6064727e401e54.

**Comment by andreyorst** [comment]
Yes. It works. Thank you for the fix!
