### ISSUE TITLE
Dart language server error with completion with (NCM) nvim-language-server

### ISSUE THREAD

**Issue by therealcisse** [autozimu/LanguageClient-neovim#335]
Nvim version: 0.2.2

Plugin version (git SHA): 
* 61657c9 (HEAD -> next, tag: 0.1.42, origin/next, origin/HEAD) (cargo-release) version 0.1.42

Minimal vimrc:

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

  Plug 'roxma/nvim-completion-manager'
  Plug 'dart-lang/dart-vim-plugin', { 'for': [ 'dart' ] }

call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'dart'           : ['dart_language_server'],
    \ }

let g:LanguageClient_loggingLevel = 'DEBUG'
```

Language server name/link and version: 
dart_language_server
https://github.com/natebosch/dart_language_server
version: v0.1.9+3

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1826159/LanguageClient.log)
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1826160/LanguageServer.log)

- Reproduction steps (from clean state)
1 - Start vim
2 - Open dart file
3 - Error: LanguageClient: failed to register NCM source.

<img width="1440" alt="screenshot 2018-03-19 17 31 04" src="https://user-images.githubusercontent.com/271111/37612149-4a42dfa0-2b9c-11e8-9998-dbfec73ef2d7.png">

I did a little debugging to show underlying by modifying https://github.com/autozimu/LanguageClient-neovim/blob/next/src/languageclient.rs#L641 and I got the following error:

<img width="845" alt="screenshot 2018-03-18 21 45 15" src="https://user-images.githubusercontent.com/271111/37612223-83b14b32-2b9c-11e8-9b31-eadc2c5ae154.png">

Thanks.

**Comment by autozimu** [comment]
This is a language server bug.

Dart language server sent
```
"codeLensProvider": false
```
when it should be
```
"codeLensProvider": null
```

Please report at dart language server repo.

@natebosch

**Comment by therealcisse** [comment]
Done. I will keep this open for now.

Thanks.

**Comment by autozimu** [comment]
Sorry. Closing this to keep the board clear.

**Comment by therealcisse** [comment]
The issue was fixed. The error is gone but code completion is not working.
