### ISSUE TITLE
Integration with Python Language Server

### ISSUE THREAD

**Issue by joaospinto** [autozimu/LanguageClient-neovim#340]
I've used this plugin with `cquery` for a while, and am trying to set it up with `pyls`. It mostly works fine, but the `.style.yapf` file seems to be getting ignored; maybe I should be asking them instead, but I was wondering if anyone here has done something similar already. Thanks

**Comment by autozimu** [comment]
From my experience, if you put those style configs in `setup.cfg`, it should automatically work. But the language server might not support configs in other places. If you need that, file a bug at language server side.
