### ISSUE TITLE
Maven, several projects

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#343]
Hi!

eclipse.jdt.ls [supported several project](https://github.com/eclipse/eclipse.jdt.ls/issues/593). How run languageClient in root folder?
languageClient autostart when opening a file of associated filetype. `:LanguegeClentStart` works only with an open file and only in a local project, even if the nvim is launched in the root folder.

**Comment by autozimu** [comment]
You could use `:LanguageClientStart rootPath=...` to specify the root folder.

Or use https://github.com/autozimu/LanguageClient-neovim/blob/abeb8b3434503c140645a717b94ecc23d742a39f/doc/LanguageClient.txt#L176 to customize the rule to search for project root.

**Comment by whitebyte** [comment]
Please consider adding `rootPath` option to the docs
