### ISSUE TITLE
On version 0.1.49, `Undefined variable: g:loaded_fzf` and `Broken pipe` errors happen.

### ISSUE THREAD

**Issue by ryutah** [autozimu/LanguageClient-neovim#344]
I have caught some errors when I updated LanguageClient-neovim to latest.

1. Raise error `Vim(let):E121: Undefined variable: g:loaded_fzf` and LSP server not started.
2. Raise error `code: 32, message: "Broken pipe"` and can't work LanguageClient-neovim.

The first error happen if `g:LanguageClient_selectionUI` is not set. (And may be the `junegunn/fzf` is not installed)

I guess the first error is caused by below.
https://github.com/autozimu/LanguageClient-neovim/blob/5a521a93731edb5c479361117f3751f4e9c9cb20/src/languageclient.rs#L117

And it fixed if i change above code to like this.

```rust
let selectionUI = if let Some(s) = selectionUI {
    SelectionUI::from_str(&s)?
} else if self.eval::<_, i64>("exists('g:loaded_fzf')")? == 1 {
    SelectionUI::FZF
} else {
    SelectionUI::default()
};
``` 

The LSP server is work if variable `g:LanguageClient_selectionUI` is set or change code like above, but the second error happen when some LanguageClient-neovim command is executed (like completion)

The second error, I don't found the reason why it happen yet.

I'm investigating the cause of error, I send error logs for now.

## neovim versions
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```

### LanguageClient-neovim config
```vim
let g:LanguageClient_autoStart                        = 1
let g:LanguageClient_diagnosticsEnable                = 0
let g:LanguageClient_serverCommands                   = {}
let g:LanguageClient_serverCommands["rust"]           = ['rustup', 'run', 'nightly', 'rls']
let g:LanguageClient_serverCommands["python"]         = ['pyls']
let g:LanguageClient_serverCommands["javascript"]     = ['javascript-typescript-stdio']
let g:LanguageClient_serverCommands["typescript"]     = ['javascript-typescript-stdio']
let g:LanguageClient_serverCommands["javascript.jsx"] = ['javascript-typescript-stdio']

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
nnoremap <silent> <F3> :call LanguageClient_textDocument_references()<CR>
```

## error logs
[LanguageClient.error1.log](https://github.com/autozimu/LanguageClient-neovim/files/1847219/LanguageClient.error1.log)

[LanguageClient.error2.log](https://github.com/autozimu/LanguageClient-neovim/files/1847222/LanguageClient.error2.log)

**Comment by autozimu** [comment]
Yes, the first suspection is correct. Would you like to submit a PR?

**Comment by autozimu** [comment]
The second issue might because trace=null is not supported by rls yet.

**Comment by autozimu** [comment]
I've made those changes myself as many users might be affected. Thanks for your reporting though.

**Comment by ryutah** [comment]
@autozimu I confirmed these fixed.
Sorry for reply late and thanks for fix it!
