### ISSUE TITLE
Preview window hover is broken

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#345]
I'm using an autocmd to call hover on CursorMove, and whenever it uses the preview window it acts very weirdly, preventing the further cursor movement and sometimes moving the cursor into the preview window.

- neovim/vim version NVIM v0.2.2
- Plugin version (git SHA) bbb92f5ebbebc44d5a3e2333f4b01d1eb92495e0
- Minimal vimrc (e.g. <https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim>)
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rls'],
    \ }
let g:LanguageClient_loggingLevel = 'DEBUG'
let g:LanguageClient_autoStart = 1

" Automatic Hover
let g:Plugin_LanguageClient_running = 0
augroup LanguageClient_config
  autocmd!
  autocmd User LanguageClientStarted let g:Plugin_LanguageClient_running = 1
  autocmd User LanguageClientStopped let g:Plugin_LanguageClient_running = 0
  autocmd CursorMoved *.rs,*.c,*.cpp,*.h,*.hpp if g:Plugin_LanguageClient_running | call LanguageClient_textDocument_hover() | endif
augroup end
```
- Language server name/link and version RLS rls-preview 0.124.0-stable (299a6a9 2017-12-25)
- Reproduction steps (from clean state)
    1. Open some Rust file.
    2. Try stepping over something that produces a multi-line hover message.
- Logs. Ensure `let g:LanguageClient_loggingLevel = 'DEBUG'` is in minimal
  vimrc. Follow previous provided reproduction steps to reproduce the bug.
  Attach contents of `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.
[LanguageClient.log](https://0x0.st/sBIO.log)
[LanguageServer.log](https://0x0.st/sBIV.log)

**Comment by Shougo** [comment]
> I'm using an autocmd to call hover on CursorMove, and whenever it uses the preview window it acts very weirdly, preventing the further cursor movement and sometimes moving the cursor into the preview window.

I think the screencast is better.

For example: asciinema

**Comment by YaLTeR** [comment]
Good idea. Here's a recording: https://asciinema.org/a/7iW9jdi3M7YLXioDftbT9Ub64

When the cursor isn't moving and blinking between the preview and the main window — that's me trying to move the cursor normally.

**Comment by Shougo** [comment]
Oh, I see.  It seems hover problem.

**Comment by autozimu** [comment]
It is caused by those lines
https://github.com/autozimu/LanguageClient-neovim/blob/bbb92f5ebbebc44d5a3e2333f4b01d1eb92495e0/src/languageclient.rs#L557-L563

For neovim, there is an api to set buffer content directly, `nvim_buf_set_lines()`, but for vim, as far as I researched, there isn't a way to set buffer content without switching to it first.

**Comment by autozimu** [comment]
I will make a change to make use of this neovim API.

For vim though, it could be workarounded by writing the content to a tmp file and then use `pedit` to open the file. Definitely not ideal. There might be better ideas.

**Comment by Shougo** [comment]
> For vim though, it could be workarounded by writing the content to a tmp file and then use pedit to open the file. Definitely not ideal. There might be better ideas.

For Vim8, I think you can use `setbufline()` instead.
Note: 8.0.1039 is needed.

**Comment by autozimu** [comment]
Did I miss something? I believe `setbufline()` can only set content of current buffer.

**Comment by Shougo** [comment]
> Did I miss something? I believe setbufline() can only set content of current buffer.

It is not only current buffer.
For current buffer is `setline()`.

```
setbufline({expr}, {lnum}, {text})			*setbufline()*
		Set line {lnum} to {text} in buffer {expr}.  To insert
		lines use |append()|.

		For the use of {expr}, see |bufname()| above.

		{lnum} is used like with |setline()|.
		This works like |setline()| for the specified buffer.
		On success 0 is returned, on failure 1 is returned.

		If {expr} is not a valid buffer or {lnum} is not valid, an
		error message is given.
```

I have tested `setbufline()` and it worked well.

**Comment by autozimu** [comment]
@Shougo Yeah, I did miss this part. Thanks.

**Comment by YaLTeR** [comment]
While we're at it I'd like to point out a couple of other issues:
- `\n` used to split the preview message seems to remain visible as `^@` (can be seen in the asciinema recording)
- Some multi-line messages are still shown as an echo:
```
2018-03-27T11:07:27.037201346+03:00 INFO languageclient::vim - => {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":65,"line":52},"textDocument":{"uri":"file:///home/yalter/Source/rust/vapoursynth-rs/vapoursynth/src/plugins/mod.rs"}},"id":64}
2018-03-27T11:07:27.037659875+03:00 INFO languageclient::vim - <= {"jsonrpc":"2.0","id":64,"result":{"contents":[{"language":"rust","value":"unsafe extern \"system\" fn(identifier: *const c_char,\n                          defaultNamespace: *const c_char,\n                          name: *const c_char, apiVersion: c_int,\n                          readonly: c_int, plugin: *mut VSPlugin)"}],"range":null}}
2018-03-27T11:07:27.038670237+03:00 INFO languageclient::vim - => {"jsonrpc":"2.0","method":"execute","params":["echo 'unsafe extern \"system\" fn(identifier: *const c_char,\n                          defaultNamespace: *const c_char,\n                          name: *const c_char, apiVersion: c_int,\n                          readonly: c_int, plugin: *mut VSPlugin)'"]}
```

**Comment by autozimu** [comment]
Thanks for pointing this out.

**Comment by YaLTeR** [comment]
Noticed one more thing: in visual select mode stepping over something that produces a multi-line hover cancels the selection. This doesn't happen with not multi-line hover.
