### ISSUE TITLE
Question: Is there a way to listen for a custom message?

### ISSUE THREAD

**Issue by TylerLeonhardt** [autozimu/LanguageClient-neovim#348]
This is kinda like the opposite of #Call/#Notify.

I want to listen for a custom message called `output` and run a function when it's received. Is there a way to do that at the moment?

btw, this plugin is awesome and works out of the box with the PowerShell language server:
https://github.com/powershell/powershelleditorservices/

**Comment by autozimu** [comment]
Not at the moment, but should be nice to have, for extensibility.

**Comment by TylerLeonhardt** [comment]
With PowerShell Editor Services, we have this message called "evaluate" that gets sent from the Language Client. That will then evaluate the PowerShell code and respond with an message called "output" that will contain the result.

Here's an example, the keybinding is F8. You select the code, hit F8 and it runs the code and shows up in the console at the bottom:

I paused before hitting F8, the actual execution was near instant.
![f8](https://user-images.githubusercontent.com/2644648/37999491-e9374358-31d7-11e8-9454-9ff58bf37eb6.gif)

**Comment by TylerLeonhardt** [comment]
#Call/#Notify works really well to send the initial "evaluate" message btw! Awesome work on that!

**Comment by autozimu** [comment]
`#Call` should work in this use case (including get the response). Did I miss something?

**Comment by TylerLeonhardt** [comment]
unfortunately (in this scenario), due to implementation details, we send info back through `#Call` (and that works!) but we also send different information in a new message called `output` (from the language server to the client) which is why listening for a message is important.

**Comment by hurricanehrndz** [comment]
@tylerl0706,

Please do not forget to add the details of the powershell setup to the wiki.

**Comment by TylerLeonhardt** [comment]
Will do!

**Comment by TylerLeonhardt** [comment]
Oooo is this implemented? 😀

Any docs on how to use you it?

**Comment by TylerLeonhardt** [comment]
I tried to give this a try from the docs (after updating LanguageClient-neovim) and got:

`E117: Unknown function: LanguageClient_registerHandlers` in my init.vim

I also noticed a:
`Os { code: 13, kind: PermissionDenied, message: "Permission denied" }` when trying to start up  with `:LanguageClientStart`

**Comment by autozimu** [comment]
It needs to be done after this plugin is fully loaded.

**Comment by TylerLeonhardt** [comment]
So at the end of init.vim isn't good enough? Because that's where I added the example.

**Comment by autozimu** [comment]
It won't work as `registerHandlers` hasn't been sourced yet.

**Comment by autozimu** [comment]
You could add it after one of the autocmd events.

**Comment by TylerLeonhardt** [comment]
So for some reason, I'm able to get registerHandlers working within vim, but now when I put it in my init.vim.

Here's my init.vim that contains all the stuff:

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh',
        \ }
Plug 'sheerun/vim-polyglot'
Plug 'roxma/nvim-completion-manager'
call plug#end()

set hidden

let g:LanguageClient_serverCommands = {
    \ 'ps1': ['pwsh', '~/Desktop/PowerShellEditorServices/module/Start-EditorServices.ps1', '-HostName', 'nvim', '-HostProfileId', '0', '-HostVersion', '1.0.0', '-EditorServicesVersion', '1.6.0', '-LogPath', '~/Desktop/pses.log.txt', '-LogLevel', 'Diagnostic', '-BundledModulesPath', '~/Desktop/PowerShellEditorServices/module', '-Stdio', '-SessionDetailsPath', '~/Desktop/.pses_session']
    \ }

let g:LanguageClient_loggingLevel = 'DEBUG'

" from the docs - the function passed into registerHandler vvvvvvvv
function! HandleOutput(params) abort
        echomsg json_encode(a:params)
endfunction

" used to handle the response of #Call
function Log(result, error)
	:echo a:result
endfunction

" Set up all the keybindings
autocmd FileType ps1 call VsimEnableLanguageServerKeys()
function! VsimEnableLanguageServerKeys()
	nnoremap <silent> <S-K> :call LanguageClient_textDocument_hover()<CR>
	nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
	nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
	nnoremap <silent> <F12> :call LanguageClient_textDocument_definition()<CR>
	set formatexpr=LanguageClient_textDocument_rangeFormatting()
	vnoremap = :call LanguageClient_textDocument_rangeFormatting()<CR>
	nnoremap <C-k><C-r> :call LanguageClient_textDocument_references()<CR>
	nnoremap <C-e><C-d> :call LanguageClient_textDocument_formatting()<CR>
	autocmd! CursorHold * call LanguageClient_textDocument_hover()

        " Note the registerHandlers here vvvvvvvvvvvvvvv
	:call LanguageClient_registerHandlers({'output': 'HandleOutput'})

         " This keybinding doesn't actually work (nothing happens when I hit F8), still need to figure out why
	nnoremap <silent> <F8> :call RunCode()<CR>
endfunction

function RunCode()
	let codeString = s:get_visual_selection()

         " And the #Call here that does get properly sent to the language server
	:call LanguageClient#Call("evaluate", { 'expression': s:get_visual_selection() }, function("Log"))
endfunction

function! s:get_visual_selection()
    " Why is this not a built-in Vim script function?!
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    if len(lines) == 0
        return ''
    endif
    let lines[-1] = lines[-1][: column_end - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endfunction
```

After selecting some code and running `RunCode` I get the following error:
`'Vim(let):E119: Not enough arguments for function: HandleOutput'`

If I do this all from within vim interactively (like typing out the function, setting the handler, calling #Call) it works as expected.

**Comment by autozimu** [comment]
Try replace the line with
```
call LanguageClient#registerHandlers({'output': 'HandleOutput'})
```

**Comment by TylerLeonhardt** [comment]
That doesn't seem to exist :(
```
Error detected while processing function VsimEnableLanguageServerKeys:
line   11:
E117: Unknown function: LanguageClient#RegisterHandlers
```

little 'r' doesn't either :(
```
Error detected while processing function VsimEnableLanguageServerKeys:
line   11:
E117: Unknown function: LanguageClient#registerHandlers
```

**Comment by autozimu** [comment]
You need to update to latest version.

**Comment by TylerLeonhardt** [comment]
So that gives me the original problem:

`'Vim(let):E119: Not enough arguments for function: HandleOutput'`

:( can you repro at all?

**Comment by autozimu** [comment]
I'm busy at the moment.

But could you change your function name to something `PS1OutputHandle`? It might conflict with https://github.com/autozimu/LanguageClient-neovim/blob/998531e04805ffb7a6edf462d325adfe2ce1ecb8/autoload/LanguageClient.vim#L193

**Comment by TylerLeonhardt** [comment]
Same thing :(

```
'Vim(let):E119: Not enough arguments for function: PS1OutputHandle'
```
```vim
function! PS1OutputHandle(result, error) abort
        echomsg json_encode(a:result)
endfunction

autocmd FileType ps1 call VsimEnableLanguageServerKeys()
function! VsimEnableLanguageServerKeys()
        " TODO hover with timer
        nnoremap <silent> <S-K> :call LanguageClient_textDocument_hover()<CR>
        nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
        nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
        nnoremap <silent> <F12> :call LanguageClient_textDocument_definition()<CR>
        set formatexpr=LanguageClient_textDocument_rangeFormatting()
        vnoremap = :call LanguageClient_textDocument_rangeFormatting()<CR>
        nnoremap <C-k><C-r> :call LanguageClient_textDocument_references()<CR>
        nnoremap <C-e><C-d> :call LanguageClient_textDocument_formatting()<CR>
        autocmd! CursorHold * call LanguageClient_textDocument_hover()

        #important part
        call LanguageClient#registerHandlers({'output': 'PS1OutputHandle'})
        nnoremap <silent> <F8> :call RunCode()<CR>
endfunction
```

**Comment by autozimu** [comment]
No, the function should look like this
```
function! PS1OutputHandle(output) abort
        echomsg json_encode(a:output)
endfunction
```

**Comment by autozimu** [comment]
Follow the doc example.

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/3647454684d316afadf8ae857fb36c7cd417812a/doc/LanguageClient.txt#L331-L333

**Comment by TylerLeonhardt** [comment]
That was it! Sorry I thought you wanted me to change the params as well.

Thanks for your help!
