### ISSUE TITLE
install.sh error: languageclient-0.1.52-x86_64-apple-darwin not found

### ISSUE THREAD

**Issue by fannheyward** [autozimu/LanguageClient-neovim#349]
404: https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.52/languageclient-0.1.52-x86_64-apple-darwin

**Comment by YaLTeR** [comment]
That's probably because the CI hasn't finished building and uploading the artifacts at the time you tried to install. Try again.

**Comment by ahmedelgabri** [comment]
@YaLTeR it's still no there https://github.com/autozimu/LanguageClient-neovim/releases/tag/0.1.52

**Comment by YaLTeR** [comment]
Looks like Travis is taking its time with the OSX job, you can see the progress by checking the yellow circle by the commit in the commits view. Here's the link for 0.1.52: https://travis-ci.org/autozimu/LanguageClient-neovim/builds/359121917?utm_source=github_status&utm_medium=notification

**Comment by autozimu** [comment]
Travis finished building.
