### ISSUE TITLE
Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

### ISSUE THREAD

**Issue by willdavidow** [autozimu/LanguageClient-neovim#355]
Everything was working perfectly, I was getting inline error reporting in my JavaScript files (coming from the `javascript-typescript-stdio` language server), the Language Server was auto-starting and the plugin gave me "no language server installed for ____" in the case of a filetype with no language server - which was expected and desired... 

...then I ran some VIM package updates (I'm using `minpac`) and restarted my machine; now I'm seeing this error when attempting to run `:LanguageClientStart`:

`Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`

Has anyone seen this issue and/or do you know a way to fix it? I have tried re-installing the plugin, adding the plugin path (manually) to my `$PATH` (in my `.zshrc` and `rtp` in my `.vimrc`). I've also run `chmod -R +X bin` inside the LanguageClient-neovim plugin directory.

I can't get it working again...

`.vimrc`

```
" Be iMproved. (Don't allow vi compatibility mode)
if has('vim_starting')
    set nocompatible
endif

" Minpac (plugin system)
" must be installed manually (from GitHub): `k-takata/minpac`
"===============================================================================================================

" set working directory
set packpath^=~/.vim
packadd minpac
call minpac#init()

call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('autozimu/LanguageClient-neovim', { 'branch': 'next' })       " LSP Support

set background=dark                                             " Set background (should be before colorscheme)


" Minpac Commands
"===============================================================================================================
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update()
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
```

`NVIM version`

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"
```

Plugin version/hash: `789338f5f47577b288a37f64d12643a7b5ba8f3c`

Reproduction steps:

```
1. Install LanguageClient-neovim
2. in terminal go to plugin directory and run `bash install.sh`
3. (from plugin directory) `chmod -R +X bin` (i see the error with or without this)
4. open nvim and `:LanguageClientStart`
```

Result (in message line):
`Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`

**Comment by autozimu** [comment]
Can you change to plugin directory and run
```
bin/languageclient --version
```

**Comment by willdavidow** [comment]
languageclient 0.1.54 (756e6932a02d03308689b2bd8dc31fef2736c4a3 2018-03-31T02:31:14.896173Z)

**Comment by TylerLeonhardt** [comment]
+1 am also seeing this on macOS.

languageclient 0.1.58 (8b7e1dd8a150bace0ecb6dff8664032345fe143d 2018-04-02T03:16:46.145731Z)

**Comment by autozimu** [comment]
Please attach log files here. I cannot reproduce this issue locally.

**Comment by TylerLeonhardt** [comment]
@autozimu can you give some instructions on where the logs are?

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/next/.github/ISSUE_TEMPLATE.md#if-you-are-still-seeing-an-error-or-other-types-of-issue-please-create-ticket-with

**Comment by TylerLeonhardt** [comment]
```
> cat /tmp/LanguageClient.log

2018-04-01T01:16:04.927371-07:00 WARN languageclient::languageclient - No language server command found for type: vim.
2018-04-01T01:16:09.905148-07:00 WARN languageclient::languageclient - Not opened yet. Switching to didOpen.
> cat /tmp/LanguageServer.log

```

Unfortunately, those have nothing useful in them :(  (p.s. those are stale logs. I was opening a PowerShell file)

**Comment by TylerLeonhardt** [comment]
Interestingly, nvim-completion-manager had a strange permission related error: cannot open .git/FETCH_HEAD: Permission denied

I fixed it by following this StackOverflow: https://stackoverflow.com/questions/13195814/trying-to-git-pull-with-error-cannot-open-git-fetch-head-permission-denied

**Comment by TylerLeonhardt** [comment]
I updated my mac which included an update and it works again.

**Comment by willdavidow** [comment]
@autozimu: I'll leave this issue open for you to close or mark as something to investigate, but I just had a Mac OS update and XCode update that restarted my machine and similar to @tylerl0706 this fixed/got rid of my issue here.

So strange..

**Comment by autozimu** [comment]
I cannot investigate without  local reproduction or useful logs.

**Comment by willdavidow** [comment]
Makes sense - my logs are the same as the ones posted above... If I ever have this issue again, I'll post here.

**Comment by kyrisu** [comment]
Just heads up - if anyone is experiencing this issue check your log files permissions. 
I must have run nvim as root (sudo) cause this is what I had:
```js
$ ls -l /tmp/Lang*
-rw-r--r-- 1 root root 407 May 28 11:33 /tmp/LanguageClient.log
-rw-r--r-- 1 root root   1 May 28 11:33 /tmp/LanguageServer.log
```

Removing log files solved the issue for me.

**Comment by faultysegment** [comment]
Just here to confirm that I had the same issue, Language Servers log had root as an owner.
After they were deleted an issue was resolved
