### ISSUE TITLE
support windows neovim

### ISSUE THREAD

**Issue by deepseeksss** [autozimu/LanguageClient-neovim#358]
neovim version is 0.2.2

because of i don't know vim script, so i do not create a pr.
1) modify autoload/LanguageClient.vim, add '.exe' extension to the target
2) fix auto complete not work problem, the last 1.5.x version is ok, but the latest 1.6.1 not wrok, and i set log level, but can not found the log

sorry to my bad english...

**Comment by autozimu** [comment]
Please specify point 2, I don't get the problem.

你可以这里用中文描述 (复现步骤，具体 error)，但描述不清的 bug 我没办法 fix。

**Comment by deepseeksss** [comment]
(原来是中国大神）
最新版本的自动补全在windows下不好使
比如rust文件输入```use std::```不弹出任何提示
设置了let g:LanguageClient_loggingLevel = 'DEBUG'，但是找不到log文件， c:\windows\temp里没有

**Comment by autozimu** [comment]
请提供能复现问题的 minimal vimrc.

**Comment by deepseeksss** [comment]
```
:set hidden
:set noswapfile 

nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>

" Automatically start language servers.
let g:LanguageClient_autoStart = 1

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }


if has("win32")
:set shell=powershell
:set shellcmdflag=-command
:set runtimepath+=C:\Users\Matrix\.cache\vimfiles\repos\github.com\autozimu\LanguageClient-neovim
let g:python3_host_prog = 'C:/Users/Matrix/AppData/Local/Programs/Python/Python35/python.exe'
e
```

**Comment by autozimu** [comment]
With this configuration, completion won't be automatically triggered. It has to be triggered manually, with `C-X C-O`.

To have automatically triggered completion, you will need to have nvim-completion-manager or deoplete or other similar plugin.

**Comment by deepseeksss** [comment]
抱歉，我用的是spacevim，配置太复杂，就没贴，deoplete是有的。。。

**Comment by autozimu** [comment]
创建能够复现 bug 的 minimal vimrc 是你的问题。
