### ISSUE TITLE
command not found: "LanguageClientStart"

### ISSUE THREAD

**Issue by SirDoctors** [autozimu/LanguageClient-neovim#36]
#16 may be related to this.
- Git SHA:
42c29d6999c76d6b4a11afffc3a8f1135a5c91bd
- [Minimal init.vim](https://gist.github.com/SirDoctors/bc5760a292bb8d1ac08aecf26d795b7e)
- ~/.local/share/nvim/rplugin.vim
```
" ruby plugins


" python plugins


```
- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`.
![Attempting to run said command](http://i.imgur.com/XliPELp.png)
- ``:CheckHealth``
https://gist.github.com/SirDoctors/abc49ba388d020cbd9323d35f69c0a92
- ![:UpdateRemotePlugins](http://i.imgur.com/7MU26qn.png)

This occurs using the minimal nvim config even after clearing all nvim dirs and reinstalling plugins & python deps.

**Comment by autozimu** [comment]
Obviously this plugin is not recognized by neovim in your case.

I noticed something suspicious. It seems you are using a non-standard python3, whose path is "/home/benjamin/.config/nvim/plugged/python-support.nvim/autoload/nvim_py3/bin/python", which seems came from another third party plugin. Could you try setup with standard python3?

Also, your screenshot says the plugin is already registered, but your rplugin.vim files shows empty. Please try restart your neovim and update this ticket accordingly.

**Comment by autozimu** [comment]
Also, please try with [min-init.vim](https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim).

**Comment by SirDoctors** [comment]
Nope, had no affect, still not working. CheckHealth
![](http://i.imgur.com/PS0dGwe.png)

**Comment by autozimu** [comment]
Can you try the fourth step at https://github.com/autozimu/LanguageClient-neovim/blob/master/.github/ISSUE_TEMPLATE.md#not-editor-command-languageclientstart-?

**Comment by SirDoctors** [comment]
Same unknown command as eariler

**Comment by autozimu** [comment]
As last shot, you can try add the plugin path to your rtp manually in init.vim,

```
set runtimepath+=$HOME/[your-languageclient-neovim-folder]
```

You still need `:UpdateRemotePlugins`, restart neovim.

**Comment by SirDoctors** [comment]
WTH It works perfectly now. I copied back my original vim file and it works just fine, along with the rest of my plugins.

**Comment by autozimu** [comment]
Great!

**Comment by SirDoctors** [comment]
I've narrowed the problem down to these lines
```
"*****************************************************************************
"" Basic Setup
"*****************************************************************************"
"" Encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set bomb
set binary

"" Fix backspace indent
set backspace=indent,eol,start

"" Tabs. May be overriten by autocmd rules
set tabstop=4
set shiftwidth=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
filetype plugin indent on

"" Map leader to ,
let mapleader=','

"" Enable hidden buffers
set hidden

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
nnoremap <C-L> :noh<CR><C-L>

"" Directories for swp files
""" Persistent undo
set undodir=~/.config/nvim/.undo//
set backupdir=~/.config/nvim/.backup//
set directory=~/.config/nvim/.swp//
set undofile

" convenience
imap <Nul> <Esc><Leader>
set noesckeys
set noshowmode
set laststatus=2
set relativenumber scrolloff=5

" cursor shapes
let $NVIM_TUI_ENABLE_CURSOR_SHAPE = 1

" Clear current highlight
nnoremap <CR> :noh<CR><CR>

set fileformats=unix,dos,mac
set showcmd
set ruler

if exists('$SHELL')
    set shell=$SHELL
else
    set shell=/bin/zsh
endif

" session management
let g:session_directory = "~/.config/nvim/session"
let g:session_autoload = "no"
let g:session_autosave = "no"
let g:session_command_aliases = 1

" Save
noremap  <silent> <C-S> :update<CR>
vnoremap <silent> <C-S> <C-C>:update<CR>
inoremap <silent> <C-S> <C-O>:update<CR>
```
I'm unsure as to what in there is causing it but the issue defiantly lies there.

**Comment by autozimu** [comment]
I am actually also have that setting and I didn't see a problem yet.

**Comment by DerWeh** [comment]
I have the same issue as @SirDoctors, if I set `ignorecase` the command is not available.

**Comment by autozimu** [comment]
Hmm, interesting.

Could you try [min vimrc](https://github.com/autozimu/LanguageClient-neovim/blob/master/min-init.vim) + `set ignorecase` on your side to see if it works? 

If it is still reproducible, please following instructions in issue template to create reproduction steps.

Thanks.

**Comment by SirDoctors** [comment]
hmm I'll also try that, I've been playing with my neovim environment and I'm curious if ``set ignorecase`` is still causing me issues.

**Comment by Eisfreak7** [comment]
I had the same problem. `python3` working, the `.rplugin` file looks correct but no `LanguageClient` commands were available.
Removing the `set ignorecase` from my vimrc fixed it (manually `set noignorecase` did not, I assume it matters only during startup). However, after adding it back its still working.

**Comment by Eisfreak7** [comment]
To reproduce:
Save `min-init.vim` somewhere
`echo "set ignorecase" >> min-init.vim`
`rm -r ~/.local/share/nvim/plugged`
`rm ~/.local/share/nvim/rplugin.vim`
`nvim -u min-init.vim +PlugInstall +UpdateRemotePlugins`
Now `:LanguageClientStart` doesn't work. If I remove the `set ignorecase` line and run `UpdateRemotePlugins` again, it does.
