### ISSUE TITLE
Jumps to start of file after symbol renaming

### ISSUE THREAD

**Issue by vimpunk** [autozimu/LanguageClient-neovim#364]
I noticed that after renaming a symbol the editor jumps to the start of the file, i.e. the top of the editor.

Is this a bug or an intended feature? If the latter, may I request to change it?

If it's a bug or if not, but my request is accepted and help is needed, I can try to look into it next week or so, when things settle down a little over here.

Thanks, otherwise the plugin is great!

**Comment by autozimu** [comment]
It's a bug.

Probably within https://github.com/autozimu/LanguageClient-neovim/blob/72b18cdfc156bb10af07973c5a4124accb7e43fd/src/vim.rs#L228-L243 and introduced with some previous changes as it used to be working.

**Comment by autozimu** [comment]
Please retry latest version as it is not reproducible locally.

If you need my help fixing this edge case, please follow issue template.

**Comment by autozimu** [comment]
Not reproducible, no reproduction steps, no response.
