### ISSUE TITLE
Expose argument utility functions for executeCommand

### ISSUE THREAD

**Issue by snoe** [autozimu/LanguageClient-neovim#365]
When using `workspace/executeCommand` it is often desirable to get arguments similar to the other calls like `textDocument/definition`. 

It would be nice to get the file's uri directly from rust so we can guarantee they match.
The file's version stored by the client
The cursor position if it's more difficult than `line('.')-1`, `col('.') - 1`

Thanks!

**Comment by richox** [comment]
@autozimu this commit makes all omni-completion unusable with error "unknown function s:Text()"

**Comment by autozimu** [comment]
You shouldn't use dev branch unless you know what you're doing.

In your case, the downloaded binary doesn't match  dev branch head.
