### ISSUE TITLE
Client is not updating diagnostics correctly with SBT as server

### ISSUE THREAD

**Issue by PawkyPenguin** [autozimu/LanguageClient-neovim#369]
## Summary

When I use this plugin with the built-in LanguageServer of [sbt](https://www.scala-sbt.org/) , some errors don't show up.

For instance, if I have two files, `Test.scala` and `Main.scala` and errors in both of them, sbt's LanguageServer will send diagnostics for both of them but it seems the client only processes one of them.

## Reproduction

- Vim version: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:00:19) Included patches: 1-1542`
- Plugin version: `312d88e`
- binary version: `languageclient 0.1.63 (NULL 2018-04-07T13:57:15.236073131Z)`
- Minimal vimrc: 

```vim
set nocompatible

augroup scala
    autocmd!
    autocmd BufReadPost *.scala setlocal filetype=scala
augroup END

packadd LanguageClient-neovim
let g:LanguageClient_autoStart = 0
let g:LanguageClient_serverCommands = {
    \ 'scala': ['node', expand('~/discover.js')]
    \ }
let g:LanguageClient_loggingLevel = 'INFO'
```

- Language server link and version: [here](https://www.scala-sbt.org/1.x/docs/sbt-server.html) are the associated Sbt docs. Sbt uses [LSP 3.0](https://microsoft.github.io/language-server-protocol/specification).
- Steps to reproduce the issue from clean state
    1. Install the latest version of sbt (I used sbt 1.1.1) and scala (I used 2.12.5) and Node.js for executing the discovery file.
    2. Download [this file](https://gist.githubusercontent.com/eed3si9n/0ee26a15218f1d4031b451dd61315d6c/raw/5693fbcafbb9a71f1ac5a9d13ace94df3b091cbc/sbt-server-stdio.js) and save to `~/discover.js` or anywhere you want (be sure to adjust the path in the minimal vimrc though!).
    3. `mkdir -p scalasample/src/main/scala`
    4. `cd "$_"`
    5. `echo 'object Main {def main(args: Array[String]) = println(garbage)}' > Main.scala`
    6. `echo 'class Test {other_garbage}' > Test.scala`
    7. `cd ../../..` (so that your present working dir is `scalasample`)
    8. `sbt`
    9. Probably open new terminal, go to the `scalasample/` directory again (otherwise the discover script doesn't work), start vim with `vim -p src/main/scala/{Main.scala,Test.scala} -u <path_to_minimalvimrc>`. Then execute `:LanguageClientStart`. Then execute `:w` in **only one** of the two files. If everything went "well", you should see that only one of two errors is marked.
    
I attached the `client log` file. The server log was empty (probably because the discover.js interferes with it), but I connected to the language server while I did my test to see what got sent to the client. The content that got sent is in `server.log`.

[client.log](https://github.com/autozimu/LanguageClient-neovim/files/1886450/client.log)
[server.log](https://github.com/autozimu/LanguageClient-neovim/files/1886465/server.log)

## Current Behavior

Both errors diagnosed by Sbt's language server are received by the plugin (lines 61 and 71 in `client.log`) but they are not displayed in Vim.

## Expected Behavior

I would expect that both the error in the file `Main.scala` and the error in `Test.scala` are displayed in Vim.

**Comment by PawkyPenguin** [comment]
I've narrowed it down somewhat. The cause seems to be in `src/languageclient.rs` on [this line](https://github.com/autozimu/LanguageClient-neovim/blob/9400392cc40071d2116a3196ab8606512b5c3ae4/src/languageclient.rs#L1629):

```rust
        if filename != current_filename.canonicalize() {
            return Ok(());
        }

        self.display_diagnostics(&current_filename, &params.diagnostics)?;
        self.notify(None, "s:ExecuteAutocmd", "LanguageClientDiagnosticsChanged")?;
```

If I remove the if-condition and replace `&current_filename` with `&filename` in the `self.display_diagnostics` call, both error signs appear as expected (though the quickfix list still contains only one entry, probably because it gets overwritten [here](https://github.com/autozimu/LanguageClient-neovim/blob/9400392cc40071d2116a3196ab8606512b5c3ae4/src/languageclient.rs#L317)). Maybe the code right before that:

```rust
let qflist: Vec<_> = diagnostics
            .iter()
            .map(|dn| QuickfixEntry {
                filename: filename.to_owned(),
                lnum: dn.range.start.line + 1,
                col: Some(dn.range.start.character + 1),
                nr: dn.code.clone().map(|ns| ns.to_string()),
                text: Some(dn.message.to_owned()),
                typee: dn.severity.map(|sev| sev.to_quickfix_entry_type()),
            })
.collect();
```

could be extended with something like 

```
get current quickfix list
delete all quickfix entries that belong to file `filename.to_owned()`
add `qflist` to the current quickfix list
```

and then call the method with 

```rust
self.display_diagnostics(&filename, &params.diagnostics)?;
```

instead of `&filename_current`. 

I'm not sure if that's still compliant with the LSP specification though... Maybe the bug is on Sbt's side. I wish I could be more helpful and make a pullrequest but unfortunately I barely know Rust and LSP, so understanding the source code is difficult for me.

**Comment by autozimu** [comment]
I see.

Will double check the behaviours of VSCode and vim quickfix.
