### ISSUE TITLE
Problems with autocompletion after updating cquery

### ISSUE THREAD

**Issue by kafendt** [autozimu/LanguageClient-neovim#370]
## Summary
After updating cquery the autocompletion feature stopped working for me. I am using nvim-completion-manager but I have also checked with deoplete and it experiences the same problem. So I am fairly sure that it is either a LanguageClient-neovim problem or a cquery problem.

After I noticed this i reverted to cquery-commit: 588169d.
Using that commit everything works fine but when I cherry pick cquery-commit: d029f64 autocompletion again stops working. So I guess that commit has to be the one causing the problem.
Now I am not sure whether the problem is a problem of cquery or a problem of LanguageClient-neovim handles cquery.

## Reproduction
- neovim/vim version: v0.2.2
- Plugin version: 878a680
- binary version: 0.1.67
- Language server: cquery, working commit: 588169d, problematic commit: d0s9f64
- Steps to reproduce the issue from clean state
    1. Working state: Build cquery with commit ID: 588169d, use current LanguageClient-neovim, use nvim-completion-manager or deoplete
    2. Broken state: Use current master of cquery or cherry pick commit ID: d029f64 and rebuild cquery, use current LanguageClient-neovim, use nvim-completion-manager or deoplete
- Logs:
LanguageServer.log:
```
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/7.3.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
 "/usr/bin/clang-6.0" -cc1 -triple x86_64-pc-linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -pic-is-pie -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /usr/lib/clang/6.0.0 -working-directory /home/chris/Documents/worktree/nao/build/simrobot/Develop/src/tuhhsdk -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/x86_64-pc-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/clang/6.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/chris/Documents/worktree/nao -ferror-limit 19 -fmessage-length 0 -stack-protector 2 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o - -x c++ -
clang -cc1 version 6.0.0 based upon LLVM 6.0.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1
 /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/x86_64-pc-linux-gnu
 /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/7.3.1/../../../../include/c++/7.3.1/backward
 /usr/local/include
 /usr/lib/clang/6.0.0/include
 /usr/include
End of search list.
```

LanguageClient.log:
```
#######
LanguageClient 0.1.67 
#######
```

## Current Behavior
No autocompletion in either deoplete or nvim-completion-manager

## Expected Behavior
autocompletion suggestions in at least one of deoplete or nvim-completion-manager

**Comment by autozimu** [comment]
It seems the only difference in your experiment is different commits of cquery, which implies the problem is more likely to be caused by cquery.

Please file this bug on cquery first.

**Comment by autozimu** [comment]
Plus cquery doesn't have a commit of d0s9f64

**Comment by kafendt** [comment]
Sorry must have copied the commit ID wrongly, it is d029f64. I will also post this issue in the cquery repo.

**Comment by kafendt** [comment]
Opened issue regarding this problem in cquery repository (issue: [#604](https://github.com/cquery-project/cquery/issues/604)). The problematic commit has been reverted as a result. I was also asked to file a bug report here though.
