### ISSUE TITLE
`textDocument/codeAction` remove unused imports

### ISSUE THREAD

**Issue by gvolpe** [autozimu/LanguageClient-neovim#371]
## `textDocument/codeAction` remove unused imports

This is the key command I have configured but I'm not sure whether I should pass the parameters explicitly or doing it as a key map like `hover`:

```
nnoremap <silent> rui :call LanguageClient_textDocument_codeAction()<CR>
```

The `unused imports` diagnostic is working as shown in [this screenshot](https://ibb.co/f042Gc).

## Reproduction
- neovim/vim version: `NVIM v0.2.2 Build type: RelWithDebInfo LuaJIT 2.0.4`
- Plugin version: `475f949`
- binary version: `languageclient 0.1.61 (NULL 2018-04-09T05:34:35.425510539Z)`
- Logs: nothing in the logs.

## Current Behavior

I get this error when I try to execute the `codeAction` command as soon as I get the `unused import` report:

```
E117: Unknown function: LanguageClient_textDocument_codeAction
```

## Expected Behavior

To execute the action of remove the unused imports reported by the server.

**Comment by autozimu** [comment]
SHA `475f949` is not a valid commit of this plugin.

Please update to latest version and follow template to provide vimrc and logs.

**Comment by gvolpe** [comment]
My bad. I updated the plugin to the latest version and it's now working.

- Plugin version: `4cfc01a`
- binary version: `languageclient 0.1.61 (NULL 2018-04-10T01:22:45.409975485Z)`

My vim configuration is here: https://github.com/gvolpe/vim-setup/blob/master/init.vim

One thing to notice, is that the `remove unused imports` command only works if the cursor is on top of one of the unused imports, otherwise I get a `Diagnostics not found` error message.
