### ISSUE TITLE
Autoload functions not loaded when exporting global variables with session

### ISSUE THREAD

**Issue by kafendt** [autozimu/LanguageClient-neovim#373]
## Summary

Hey, I have trouble to restore my saved session due to the following code:

https://github.com/autozimu/LanguageClient-neovim/blob/6c545eba610d3b399bf3f7a67b5023253420a1e8/autoload/LanguageClient.vim#L1-L3

Since I am using [Taboo](https://github.com/gcmt/taboo.vim) (allows to save named tabs) I have to save global variables with my sessions by setting `sessionoptions+=globals` in my vimrc. This leads to saving the `LanguageClient_loaded` variable which is set to 1 and results in not autoloading the functions in autoload/LanguageClient.vim and a lot of error messages when I try to load a session.

A very easy fix for this would be to just make the variable start with a lowercase letter (`languageClient_loaded`) since only global variables that start with a captial letter are saved.

**Comment by autozimu** [comment]
Changing this variable name might be a breaking change for some users. Like this user obviously uses this global variable https://github.com/autozimu/LanguageClient-neovim/issues/374

**Comment by autozimu** [comment]
I'd recommend use some workarounds like autocmds to reset the value. Something like

```vim
autocmd QuitPre let g:LanguageClient_loaded = 0
```
