### ISSUE TITLE
Provide a separate log window for the server

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#375]
Currently, log messages from the language server are displayed in the status bar. Some servers provide excessive logging and this floods the status bar messages. A separate buffer could be nicer for this purpose.

**Comment by autozimu** [comment]
Are you referring to `window/logMessage` messages?

Did you check https://github.com/autozimu/LanguageClient-neovim/blob/5a12d701d6ec962781c7c50319490ddcbd7a01b5/doc/LanguageClient.txt#L149

**Comment by languitar** [comment]
Yes, I am talking about that.

I know the setting. But maybe I want to be able to look at the log in case of problems with a high level of detail. The problem is, that these messages are not logged in the log files in `/tmp` without also increasing the log level for the client itself.

**Comment by autozimu** [comment]
I just realized that those messages are outputted using `:echomsg`, which means it is possible to retrieve them back using `:messages`, or even better with `:Messages` from tpope's https://github.com/tpope/vim-scriptease.

Alternately, you can register your own handler to handle `window/logMessage` however you'd like to do with them.

**Comment by languitar** [comment]
The plugin is a good reference, because the normal `:messages` pager is a nightmare. However, in case a language server makes heavy use of `window/logMessage`, `:echomsg` can result in a lot of screen flickering. Is there an example how to register such a handler to avoid this?

**Comment by autozimu** [comment]
Search for registerHandler in doc. There should be one example in it.
