### ISSUE TITLE
"failed to register as NCM source"

### ISSUE THREAD

**Issue by alok** [autozimu/LanguageClient-neovim#376]
## Summary

This is odd, as I don't even have NCM installed.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.2.3-975-g84bac9f50
- This plugin version (`git rev-parse --short HEAD`): 5a12d70
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.67 878a680c38c258cbf94617555a3037f3298b1b95

## Current Behavior

LanguageClient: failed to register as NCM source: 'Vim(let):E117: Unknown function: 
cm#register_source'   

## Expected Behavior

No error message.

**Comment by autozimu** [comment]
Not reproducible.

Please follow template and provide log files.

**Comment by autozimu** [comment]
Not reproducible and no response.

**Comment by jacks0n** [comment]
I also was getting this error with the latest version of LanguageClient-neovim. I had NCM2 installed, however I had a left over `g:cm_matcher` variable defined in my `.vimrc`. The [`registerCMSource` function appears to check](https://github.com/autozimu/LanguageClient-neovim/blob/next/src/languageclient.rs#L700) whether NCM1 is installed by checking for the presence of the `g:cm_matcher` variable. Perhaps it could check to see if a function that only exists in NCM1 is present?

E.g.
```
let exists_CMEnableForBuffer: u64 = self.eval("exists('cm#enable_for_buffer')")?;
if exists_CMEnableForBuffer == 0 {
    return Ok(());
}
```
