### ISSUE TITLE
Code actions result in empty file state in undo history

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#377]
## Summary

When using `codeAction`s offered by a language server, the undo history is populated with a state where the file is completely empty in between the new state after the action and the previous state before the action. Moreover, the view is scrolled to a different position.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):
    ```
    NVIM v0.2.2
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt - Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
    Compiled by builduser
    
    Features: +acl +iconv +jemalloc +tui 
    See ":help feature-compile"
    
       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/share/nvim"
    
    Run :checkhealth for more info
    ```
- This plugin version (`git rev-parse --short HEAD`): 75e8674a0f7985ac5f5da00693ebacfd55a35f9d
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.68 75e8674a0f7985ac5f5da00693ebacfd55a35f9d
- Minimal vimrc content:
```
scriptencoding utf8
set hidden

" bundle settings
filetype off

call plug#begin('~/.local/share/nvim/bundle/')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/denite.nvim', {'do': ':UpdateRemotePlugins'}

call plug#end()

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_serverCommands = {
    \ 'java': ['jdtls', '-data', getcwd() . '/..', '--add-modules=ALL-SYSTEM', '--add-opens', 'java.base/java.util=ALL-UNNAMED', '--add-opens', 'java.base/java.lang=ALL-UNNAMED'],
    \ }
```
- Language server link and version: https://github.com/eclipse/eclipse.jdt.ls 0.16.0
- Steps to reproduce the issue from clean state
    1. Open the following file as `Test.java`. The language server should provide diagnostics for the `test` method because it is unused.
        ```
        public class Test {
	        private void test() {
	        }
        }
        ```
    2. With cursor on `test`: `:Denite codeAction` + Enter, the test method will be removed by the code action
    3. `u`

## Current Behavior

At step 2, buffer might be scrolled and at step 3 the buffer becomes empty.

## Expected Behavior

Previous state with the test method included should be visible and nothing moves.

**Comment by languitar** [comment]
A follow up to this: currently, the empty state is still gone, however, after `u`, the cursor is at the top of the file and not at the original position.

**Comment by purpleP** [comment]
Seems like this line is the one to blame

https://github.com/autozimu/LanguageClient-neovim/blob/9e62b2d59979e68d3f27566bcabcb4b44db3d56d/src/languageclient.rs#L251
