### ISSUE TITLE
[newbie] Only override `K` and `gd` for file types with a language server?

### ISSUE THREAD

**Issue by yatesco** [autozimu/LanguageClient-neovim#380]
I have some languages which support a language server (e.g. `reasonml`) and some that don't (e.g. `clojure`).

In the documentation it suggests overriding various some keys:
```
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>                                                                                                        
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>                                                                                                  
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>  
```

This works fine with languages that have a language server but breaks on languages that don't.

What magical incantations do I need so that `K` and `gd` (for example) do the right thing when there is and isn't a language server?

Thanks!

**Comment by nicodebo** [comment]
hello,

One possibility would be to define those mappings per filetype.
For exemple you can create the following filetype plugin `~/.config/nvim/after/ftplugin/reason.vim` which content is the following:
```vim
nnoremap <buffer> <silent> K :call LanguageClient_textDocument_hover()<CR>                                                                                                        
nnoremap <buffer> <silent> gd :call LanguageClient_textDocument_definition()<CR>                                                                                                  
nnoremap <buffer> <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
```
Then those mappings will only be effective in a `reason` filetype buffer. Create one filetype plugin for each language that has a language server and define those hereabove mentionned mappings. You can even wrap the mappings inside a `if executable("<langserver-bin>")` condition to make sure that the corresponding language server is in your $PATH.

**Comment by yatesco** [comment]
Thanks @nicodebo for the suggestions. I will try them tomorrow and report back.

**Comment by yatesco** [comment]
Yep, works perfectly! Thanks.

**Comment by cmcaine** [comment]
Here's a nice way of doing it:

```viml
  function! LC_maps()
    if has_key(g:LanguageClient_serverCommands, &ft)
      nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<cr>
      inoremap <buffer> <silent> <c-i> <c-o>:call LanguageClient#textDocument_hover()<cr>
      nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
      nnoremap <buffer> <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
    endif
  endfunction

  autocmd BufEnter * call LC_maps()
```
