### ISSUE TITLE
Add support for non-file urls

### ISSUE THREAD

**Issue by snoe** [autozimu/LanguageClient-neovim#381]
Vim comes with a set of standard plugins (`:help standard-plugin-list`) that allows it to open various url schemes. Notably, see the help for `pi_netrw.txt` and `pi_zip.txt`.

For instance, this will open the `clojure/core.clj` file in the specified jar.
`:e zipfile:///Users/case/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar::clojure/core.clj` This is how https://github.com/tpope/vim-fireplace jumps to definitions in jars.

Would it be possible to allow a server to send these urls (to support `definition`) to be passed directly to vim? At the moment, this is the error that you get when you send LanguageClient one of these urls: https://github.com/autozimu/LanguageClient-neovim/blob/d690d2b62fb161266ccce15c3160760530f3c085/src/types.rs#L769

**Comment by autozimu** [comment]
That's good to know vim can handle zip files as well.

But when I tried it out, it  didn't work out well for me.

First, vim doesn't show any content.

And if I try to save the editing, it shows an error
![screen shot 2018-04-16 at 19 35 28](https://user-images.githubusercontent.com/1453551/38845650-599ed536-41ad-11e8-84ec-9c7f5814845e.png)

Is there any special setup to make this work?

**Comment by snoe** [comment]
I definitely see the content - I think as long as you have `zip` and `unzip` on your PATH it works.
 
Honestly, I had never tried to write the zipfile and I get that same error as in your screenshot although my changes **are** persisted to the zip. 

vim-fireplace chooses to open the dependency zipfiles in readonly mode which might be an ok thing for LC to do too. I think vscode-java makes jar links (in the eclipse`jdt` url scheme) readonly with this line https://github.com/redhat-developer/vscode-java/blob/0244d6e80d3c572275fcfb2381595dd998665e76/src/extension.ts#L227

Looking a bit closer this is what I get:

```bash
$ unzip -l sample.zip
Archive:  sample.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  04-16-2018 21:20   sample/
        8  04-16-2018 21:28   sample/test
---------                     -------
        8                     2 files
$ unzip -p sample.zip
ffaxooo
$ vim -c '%s/ff//|wq' zipfile:///Users/case/dev/lsp/sample.zip::sample/test
$ unzip -p sample.zip
axooo
$ vim zipfile:sample.zip::sample/test # works
$ vim zipfile:$(pwd)/sample.zip::sample/test # works
$ vim zipfile://$(pwd)/sample.zip::sample/test # works

$ vim zipfile://sample.zip::sample/test # DOES NOT work
$ vim zipfile:~/dev/lsp/sample.zip::sample/test # DOES NOT work
```

**Comment by autozimu** [comment]
Great. Thanks for helping out.

I believe I missed the top level `sample` component.

As long as read is supported, I can tune the code to let paths like this pass.

**Comment by autozimu** [comment]
I haven't came across any language server reports zipfie uri yet.

In the referred commit, only the error out is removed. The translation of zip files from language server to vim will be revisited later.
