### ISSUE TITLE
Feature Request: Semantic syntax highlighting

### ISSUE THREAD

**Issue by ajmwagar** [autozimu/LanguageClient-neovim#383]
According to Sourcegraph, most langservers currently support semantic syntax highlighting. 

I am hoping to get syntax highlighting from my ls in vim.

I know that there is an implementation for c++ with this plugin: https://github.com/JBakamovic/cxxd-vim/

I am hoping to see this as a feature for more/all languages. 

Best of luck!

AJ

**Comment by htfy96** [comment]
Just a note: [`vscode-languageserver-node` is proposing their semantic highlighting protocol extension](https://github.com/Microsoft/vscode-languageserver-node/pull/367).

**Comment by ajmwagar** [comment]
Thanks. Good to see progress in this field.

**Comment by GordianDziwis** [comment]
The eclipse java language server already has an [implementation](https://github.com/eclipse/eclipse.jdt.ls/issues/715) based on the [protocol extension proposal](https://github.com/Microsoft/language-server-protocol/issues/513).

**Comment by marv** [comment]
`clangd` also gained support for semantic syntax highlighting based on the proposed protocol extension: https://clang.llvm.org/extra/clangd/Features.html#complete-list-of-features

**Comment by martskins** [comment]
Fixed by #954
