### ISSUE TITLE
Add FreeBSD pre-built binary

### ISSUE THREAD

**Issue by herrbischoff** [autozimu/LanguageClient-neovim#388]
I'm using FreeBSD for most of my development. Although `languageclient` builds well on this platform (given that Rust is installed), I'd appreciate if you could add a pre-built binary to the downloads and make it available via the install script. Since you already have Windows, Linux and macOS binaries, FreeBSD would complement that nicely, given it's the most popular of the BSD's.

Rust has [Tier 2 support](https://forge.rust-lang.org/platform-support.html) for FreeBSD via `x86_64-unknown-freebsd`.

**Comment by herrbischoff** [comment]
Thank you very much!

**Comment by vendion** [comment]
It seems the FreeBSD pre-built binary is no longer available even though _install.sh_ still tries to download it. See https://github.com/autozimu/LanguageClient-neovim/blob/next/install.sh#L50 is this intentional or an oversight?

**Comment by autozimu** [comment]
The prebuilt binary was previously removed due to cross compile error.

I gave it another try and it seems no longer the case. I just added it back and cut a new release. Binaries should be available in a few hours.
