### ISSUE TITLE
telemetry/event bouncing back?

### ISSUE THREAD

**Issue by ljw1004** [autozimu/LanguageClient-neovim#389]
Sorry this bug report is hard to action, because I haven't been able to reproduce it myself (haven't figured out how to install NeoVim, and can't ready Ruby). Nevertheless, I maintain an LSP server, and it's getting weird messages from a LanguageClient-neovim user.

My LSP server sends "telemetry/event" notifications to the client at various times.

It looks like LanguageClient-neovim seems to be echoing back the very same "telemetry/event" notification right back to the server. This is an error (telemetry/event isn't an allowed notification to send from client to server), and so my LSP server logs it. That's how I noticed.

Does that sounds feasible? Is it possible that LanguageClient-neovim is indeed echoing telemetry/event messages right back to the server? This repo claims that telemetry/event is implemented, but I couldn't find any handlers for it in the LanguageClient-neovim source code.

**Comment by autozimu** [comment]
Thanks for reporting.
