### ISSUE TITLE
How could I disable the lint feature of javascript-typescript-langserver

### ISSUE THREAD

**Issue by chemzqm** [autozimu/LanguageClient-neovim#391]
I'm use eslint to lint my javascript files, but it looks like javascript-typescript-langserver doesn't know anything about that, it's giving warning and errors by it's own logic.

I have looked through the documentation but didn't find a way to disable diagnostic/lint of a specified server.

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/b96f442cba41cad9c8432027c72314f25fff5ebb/doc/LanguageClient.txt#L147

Probably you need to use some autocmd to disable only for specific filetypes.
