### ISSUE TITLE
Uris like `jdt://...` not supported

### ISSUE THREAD

**Issue by GordianDziwis** [autozimu/LanguageClient-neovim#392]
The error thrown is:

```
Uri is not valid file path: "jdt://contents/slf4j-api-1.7.10.jar/org.slf4j/Logger.class?=linkedgeodata-core/%5C/home%5C/someone%5C/.m2%5C/repository%5C/org%5C/slf4j%5C/slf4j-api%5C/1.7.10%5C/slf4j-api-1.7.10.jar%3Corg.slf4j(Logger.class"
```

The not closed bracket is not a copy paste error. The string looks funny for example in the part `linkedgeodata-core/%5C/home%5C/someone...` the project name is perpended to the location of the jar. It looks like an easy fix. If you need more detailed information, just close the issue and I will provide the reproduction. 

Thanks

**Comment by autozimu** [comment]
Not sure this url is intentional or just bugs on server side.

Could you try the same steps with vscode and report it back?

**Comment by GordianDziwis** [comment]
It works with vscode.

**Comment by chemzqm** [comment]
The protocol could also be `git`, `https` etc. 
Vscode knows how to handle different protocols, but LanguageClient-neovim lacks this ability.

**Comment by GordianDziwis** [comment]
This 'jdt' protocol is also used inside javadocs. This looks like something vim/neovim should handle. Should I create an issue there?

**Comment by GordianDziwis** [comment]
Okay, I opened an issue in the eclipse.jdt.ls repo. There is an extension to lsp in the java lsp: A function which resolves a jdt:// url and returns source code. 
Would that help? Are you inclined to implement non standard lsp extensions?

**Comment by tbo** [comment]
I did some investigation on this. First of all you would need to add a protocol handler:

```
au BufReadCmd,FileReadCmd,SourceCmd jdt://* call retrieveJdt(expand("<amatch>"))
```
eclipse.jdt.ls has an LSP extension, that can retrieve the content for those URIs for us ([java/classFileContents](https://github.com/eclipse/eclipse.jdt.ls/wiki/Language-Server-Protocol-Extensions)). 
My knowledge of the LanguageClient internals is limited, but I think a possible solution could look like this:
```
au BufReadCmd,FileReadCmd,SourceCmd jdt://* call LanguageClient#Call("java/classFileContents", {uri: expand("<amatch>")}, showResultInNewReadOnlyBuffer)
```
This is apparently the same way the atom team is going to implement it: https://github.com/atom/ide-java/issues/42

The current version of eclipse.jdt.ls offers those jdt-URIs only to clients, that explicitly support it. So you would need to add this to your `settings.json`:

```
{
        "initializationOptions": {
            "extendedClientCapabilities": {
                "classFileContentsSupport": true
            }
        }
}
```

**Comment by autozimu** [comment]
Thanks for this input. It is super helpful.
