### ISSUE TITLE
Unable to find file "xxxx.c" on windows

### ISSUE THREAD

**Issue by skywind3000** [autozimu/LanguageClient-neovim#394]
> If you are reporting a bug, please read following FAQ first. If you are
requesting other types of issue, please ignore.

- Did you upgrade to latest plugin version?
yes

- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
yes, languageclient 0.1.70

- Did you check [troubleshooting]?
nothing about the troubleshooting.

## Summary

Cpp files work as expected on windows, but for c files, when I run:

```VimL
:call LanguageClient#textDocument_definition()
```
languageclient prompts:

> Unable to find file E:/path-to-my-code.c

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): 8.0.1733
- This plugin version (`git rev-parse --short HEAD`): b96f442
- This plugin's binary version (`bin/languageclient --version`): 0.1.70
- Minimal vimrc content. A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim].  Make sure
  your vimrc contains `let g:LanguageClient_loggingLevel = 'DEBUG'` to have
  full log:

```VimL
	Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next' }
	let g:LanguageClient_loadSettings = 1
	let g:LanguageClient_settingsPath = expand('~/.vim/languageclient.json')
	let g:LanguageClient_selectionUI = 'location-list'
	let g:LanguageClient_loggingLevel = 'DEBUG'
	let g:LanguageClient_serverCommands = {
				\ 'cpp': ['e:\github\cquery\bin\cquery.exe', '--language-server', '--log-stdin-stdout-to-stderr', '--log-file=d:/cq.log'],
				\ 'c': ['e:\github\cquery\bin\cquery.exe', '--language-server', '--log-stdin-stdout-to-stderr', '--log-file=d:/cq.log'],
				\ }
```

- Language server link and version: cquery https://github.com/cquery-project/cquery/commit/9ada8546fdb619d58dae5d3f5114348d0bcc87d1

- Steps to reproduce the issue from clean state
    1. open a c source file.
    2. move cursor on a function name
    3. `:call LanguageClient#textDocument_definition()`

- Logs. Paste or attach `/tmp/LanguageClient.log` and `/tmp/LanguageServer.log`.

## Current Behavior
error: Unable to find file E:/path-to-my-code.c

## Expected Behavior
find the definition for me.

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1936527/LanguageClient.log)

[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/1936528/LanguageServer.log)

**Comment by autozimu** [comment]
The error message was returned by language server.

Please report this issue at cquery.
