### ISSUE TITLE
[feature request] An option to open definition in a new split or new tab

### ISSUE THREAD

**Issue by skywind3000** [autozimu/LanguageClient-neovim#395]
Vim has a `switchbuf` option to allow me open a new file in a split or tabpage.

if  `switchbuf` has been set to `useopen,usetab,newtab`, when I selected an compiling error in the quickfix window, vim will check if the file has been open , if so , switch to the tabpage/window belongs to the file; if not, create a new tabpage for the file.

Vim will not just switch away my current file if I use `<c-w>]` instead of `<c-]>`, it will open a new split to display the definition. 

When I use quickfix window or ctags in vim, vim allows me to choose what I want, switch away current file ? or just open in a new split/tabpage.

I don't like my current file to be switched away, and I hate the `hidden` option too.

Can LanguageClient give me the right of choice too ? May I use LanguageClient without breaking my work-flow ??

**Comment by skywind3000** [comment]
Sometimes, I just want to preview the definition and keep my current document, can I open it in the preview window ??

Maybe the best way is leaving me an argument in the function, like:

```VimL
LanguageClient#textDocument_definition(open_command)
```

and can be used like:

```VimL
call LanguageClient#textDocument_definition("e")
call LanguageClient#textDocument_definition("split")
call LanguageClient#textDocument_definition("vs")
call LanguageClient#textDocument_definition("tabedit")
call LanguageClient#textDocument_definition("preview")
call LanguageClient#textDocument_definition("MyOwnBufferSwitchingCommand")
```

Or, just follow `switchbuf` option, imitate vim's behavor ?

**Comment by autozimu** [comment]
Check the function implementation. It should already been supported.

**Comment by skywind3000** [comment]
I can't find it in the code or in the documentation, could you explain a little ??

**Comment by skywind3000** [comment]
I can't find any clue in the source,  any hint ?

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/b96f442cba41cad9c8432027c72314f25fff5ebb/autoload/LanguageClient.vim#L374-L391

You could override default gotoCmd, using
```vim
:call LanguageClient#textDocument_definition({
    \ 'gotoCmd': 'split',
    \ })
```

**Comment by autozimu** [comment]
Good to know the option `switchbuf`. I believe this plugin should respect this setting as well.

**Comment by imjustfly** [comment]
@autozimu any progress about the  `switchbuf` option ?

**Comment by ipod825** [comment]
`gotoCmd` does not work when multiple targets exist and selecting by fzf. How do one use customized command to open the target file in such case? @autozimu

**Comment by theHamsta** [comment]
@ipod825 I'm using

```viml
nnoremap <buffer> <silent> gD <c-w>v:call LanguageClient#textDocument_definition()<CR>
```
So first splitting, then going to the definition. Is a new option really necessary?

**Comment by ipod825** [comment]
My customized command first check if the destination path is already open in a existing tabpage. If it does, jump to that tabpage. If not, record the current position in a stack, then open the target path in a new tabpage. Such operation is not possible without a new option.

**Comment by ipod825** [comment]
FYI, here's the [plugin](https://github.com/ipod825/vim-tabdrop) that I use to achieve this.

**Comment by martskins** [comment]
> @ipod825 I'm using
> 
> ```viml
> nnoremap <buffer> <silent> gD <c-w>v:call LanguageClient#textDocument_definition()<CR>
> ```
> 
> So first splitting, then going to the definition. Is a new option really necessary?

I think this is the proper way to achieve this. I don't think switchbuf should have any effect in this case? From what I've seen it should have an effect on quickfix commands and it already does that in the way that if you have diagnostics in your quickfix and select one of those diagnostics it will open in whatever way you have set in `switchbuf`.

As what I believe a proper solution has been already provided I'm closing this issue, but feel free to re-open if you feel like there's a better way to do this or are not satisfied with that answer.
