### ISSUE TITLE
version or commit of rls

### ISSUE THREAD

**Issue by sbeckeriv** [autozimu/LanguageClient-neovim#4]
hello,

I was wondering what version or commit of rls you are running? I am on commit db07d336e13e563802692887fc79b3abf9f9db37 and rename seems to fail for me. 

`"Content-Length: 222\r\n\r\n{\"params\": {\"textDocument\": {\"uri\": \"file:///Users/becker/trash/cargo-becker/src/bin/bench.rs\"}, \"position\": {\"character\": 25, \"line\": 73}, \"newName\": \"Renamed\"}, \"id\": 5, \"jsonrpc\": \"2.0\", \"method\": \"textDocument/rename\"}\0"`

response 
`"{\"jsonrpc\":\"2.0\",\"id\":5,\"result\":{\"changes\":{}}}\0"`

I do not think its a problem with the plugin. 
thanks
Becker

**Comment by autozimu** [comment]
I am also running rls db07d336e13e563802692887fc79b3abf9f9db37.

Can you try with the basic example like showing in the GIF?

Can you try the same operation in vscode with rls plugin installed?

If it can still be reproduced, then maybe you found a bug in rls.

**Comment by sbeckeriv** [comment]
looks like a simple project works well. Thanks! I am excited to use the plugin!
