### ISSUE TITLE
Add option to use different sinks for FZF

### ISSUE THREAD

**Issue by blahgeek** [autozimu/LanguageClient-neovim#401]
For example, one may want to open the reference in a new window (using `split` or `vsplit`) or a new tab (using `tabe`), rather than in current window. I would suggest adding an option named `LanguageClient_fzfSink`.

**Comment by chemzqm** [comment]
I think that it's not a good idea for LanguageClient-neovim to take too much responsibility, a global list and a User custom command would be enough for the generated list.

**Comment by autozimu** [comment]
If you're looking for customizing the command of opening locations, then it is already easily customizable, see https://github.com/autozimu/LanguageClient-neovim/wiki/Goto-definition-in-a-split.

If you want to take over the fzf sink functions, just override them like
https://github.com/autozimu/LanguageClient-neovim/blob/05c4b93c58c524a83bd30b388ec7ff74888ebd49/autoload/LanguageClient.vim#L759
https://github.com/autozimu/LanguageClient-neovim/blob/05c4b93c58c524a83bd30b388ec7ff74888ebd49/autoload/LanguageClient.vim#L763
