### ISSUE TITLE
[feature-request] Use quickfix window to display references

### ISSUE THREAD

**Issue by skywind3000** [autozimu/LanguageClient-neovim#402]
Currently `g:LanguageClient_selectionUI` can only be set to 'location-list' or 'fzf' and can't be set to 'quickfix-list', if I don't use 'fzf' , the location-list is very hard to use.

Location list belongs to window, but symbol references should be a global result and shared by entire vim instance. Think that, I get some references result in the location list, than I choose one result and open a new buffer, when I am done, I need to switch to the original buffer and see other results in its location list.

This is very annoying. if I can use quickfix window to display references I don't need to switch back just press F10 to open my quickfix window an select another result.

I have also write a plugin [vim-preview](https://github.com/skywind3000/vim-preview) for previewing results from quickfix list.

![](https://github.com/skywind3000/vim-preview/raw/master/doc/preview-quickfix.png)

When you are in quickfix window, just press p, the item under cursor will be displayed in the preview window immediately on the right side, then move around the cursor choose another item and press p again, all files is displayed in the same preview window. 

It will not open new split or switch away your current buffer no matter what switchbuf is. When you finished, just use P (upper case) or CTRL+W z to close the preview window.

If `g:LanguageClient_selectionUI` supports quickfix list, I can use `vim-preview` to preview symbol references without open new buffers.

Another reason is that location list is usually used for display diagnostic/lint errors by [ale](https://github.com/w0rp/ale) or LanguageClient itself. Output symbol references to the location window will conflict with diagnostic/lint errors.

**Comment by skywind3000** [comment]
Do you think it is a reasonable point to support `quickfix` in `g:LanguageClient_selectionUI`

**Comment by autozimu** [comment]
Yes, it should be supported.

**Comment by skywind3000** [comment]
there is an error:

```
Invalid option for LanguageClient_selectionUI: quickfix
```

**Comment by autozimu** [comment]
It's not included in prebuilt binaries yet.

You need to either compile yourself or wait for next release.

**Comment by skywind3000** [comment]
any schedule for next release ?

**Comment by autozimu** [comment]
Should be within next few days.

**Comment by skywind3000** [comment]
It is a good day today. 😄
