### ISSUE TITLE
Incorrect map for CompletionItem to VimCompleteItem

### ISSUE THREAD

**Issue by chemzqm** [autozimu/LanguageClient-neovim#409]
* `label` should always map to `abbr` in vim
* `text_edit.new_text` should left unmodified

Fix:
``` diff
diff --git a/src/types.rs b/src/types.rs
index 3c19075..dc355dc 100644
--- a/src/types.rs
+++ b/src/types.rs
@@ -379,17 +379,13 @@ pub struct VimCompleteItem {

 impl From<CompletionItem> for VimCompleteItem {
     fn from(lspitem: CompletionItem) -> VimCompleteItem {
-        let mut abbr = lspitem.label.clone();
+        let abbr = lspitem.label.clone();
         let word = lspitem
             // Try use textEdit.
             .text_edit
             .clone()
             .map(|edit| {
-                // EXTREMELY HACKY.
-                abbr = "".into();
-                edit.new_text.split_whitespace().last().unwrap_or(&edit.new_text)
-                    .trim_left_matches(|c| !char::is_alphanumeric(c))
-                    .into()
+                edit.new_text.into()
             })
             // Or else insertText.
             .or_else(|| lspitem.insert_text.clone())
```
White space and none alphanumeric characters should be allowed for inserted text.
The `text_edit` contains a range to remove, and that should be done complete plugin.
If the CompletionItem is snippet, the `new_text` could contain some placeholder, I think that it's better to set the modify configuration to `user_data` of VimCompleteItem, and let the complete plugin to support snippet expand.

**Comment by autozimu** [comment]
Did you check the original issue the code was trying to fix? https://github.com/autozimu/LanguageClient-neovim/issues/398

**Comment by chemzqm** [comment]
@autozimu that could be bug of language server or deoplete, the change of `new_text` would makes correct language server buggy.
LanguageClient-neovim shoud not assume `new_text` not containing white space.

**Comment by autozimu** [comment]
No, that’s not lanuage server bug. It’s completion doesn’t play well with
LSP. When the lanuage server returns TextEdit, it could be the content of
the whole line (as is the screenshot shown in previously mentioned issue),
while completion plugin only expects one word.

**Comment by chemzqm** [comment]
The actually issue is deoplete could not respect the range in `text_edit `,  LanguageClient-neovim could listen to `CompleteDone` event and remove characters according to range in `text_edit`

**Comment by chemzqm** [comment]
@autozimu neovim/vim could accept a line of words
<img width="302" alt="screen shot 2018-04-30 at 6 58 01 am" src="https://user-images.githubusercontent.com/251450/39411808-e33c195c-4c43-11e8-84f4-31ed32d6e82d.png">
It's bug/limitation of complete plugin if it can't

**Comment by autozimu** [comment]
You could try with it and see how it goes. I personally don’t think that’s
going to be a good user experience.

(Off-topic, please create PR if you could instead of embeded diff, which is
hard to read and comment.)
