### ISSUE TITLE
After the last update LanguageClient does not respect Deoplete's min_pattern_length

### ISSUE THREAD

**Issue by whitebyte** [autozimu/LanguageClient-neovim#412]
This is probably related to https://github.com/autozimu/LanguageClient-neovim/commit/e93ec5939d5a47e20501b4812e02a6cdac4a3ba6

I have this string in my init.vim: `call deoplete#custom#option('min_pattern_length', 2)
`
yet completion suggestions start to appear immediately, not waiting for 2 symbols input. Turns out that LanguageClient never took this setting into consideration, and always sets own `min_pattern_length`, It just wasn't so clear when it was = 1

**Comment by autozimu** [comment]
Changing default min_pattern_length in that commit is a mistake. I've pushed another commit.

On the other hand, your mentioned approach to customize is not correct. Try something like
```vim
call deoplete#custom#source('LanguageClient',
            \ 'min_pattern_length',
            \ 2)
```

**Comment by whitebyte** [comment]
Ok, thanks for the clarification
