### ISSUE TITLE
cquery jump marker not working

### ISSUE THREAD

**Issue by peopleskai** [autozimu/LanguageClient-neovim#414]
Hi! I'm not sure if I'm the only one hitting this issue where the auto complete would also include the jump markers as shown in the screenshot below?

![image](https://user-images.githubusercontent.com/33247565/39496032-b0501e30-4d51-11e8-968c-7edab98322a4.png)

My setup:
Neovim + Deoplete + LanguageClient-neovim + cquery

Thanks!

**Comment by autozimu** [comment]
Duplicate https://github.com/autozimu/LanguageClient-neovim/issues/396.
