### ISSUE TITLE
Support for Cargo's "feature"

### ISSUE THREAD

**Issue by spamwax** [autozimu/LanguageClient-neovim#415]
Is it possible to enable this wonderful plugin to work on Rust modules/functions that are gated through Cargo's feature-gate.

In [this project](https://github.com/spamwax/alfred-rs/tree/feature/updater) for example, I can use the plugin in `src/lib.rs` but not in `src/updater/mod.rs` since 

```rust
#[cfg(feature = "updater")]
mod updater;
```

thus `updater` is a feature that should be enabled explicitly: `cargo build --features updater`

**Comment by YaLTeR** [comment]
The way I've been working around it is by enabling everything in the `default-features` in Cargo.toml for development.

**Comment by spamwax** [comment]
I see, but then every time I want to test/build some unrelated feature I have to edit Cargo.toml to make sure not everything is gonna get built, right?

**Comment by autozimu** [comment]
According to rls README, it is possible to enable features by setting `features` or `all_features`. https://github.com/rust-lang-nursery/rls/blob/master/README.md (search for those two words)

You could give it a try.

**Comment by spamwax** [comment]
> You could give it a try.

Thanks for the tip.

My neovim setting includes:
```viml
let g:LanguageClient_settingsPath = "/Volumes/Home/hamid/settings.json"
```

and the `settings.json` content is:
```json
{
    "cfg_test": true,
    "all_features": true
}
```

I tried it with `features` as well but still no luck:
```json
{
    "cfg_test": true,
    "features": ["updater"]
}
```

**Comment by spamwax** [comment]
Thanks for the quick fix for this

I have tried different options in my `settings.json` but still can't get this to work. Any hints or examples?

**Comment by autozimu** [comment]
It’s not included in any prebuilt binaries yet. You will need to compile
yourself or wait for next release.

https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/data/sample-rs/.vim/settings.json

**Comment by spamwax** [comment]
ok, I'll give it a try.
