### ISSUE TITLE
Java import completion not correctly inserted

### ISSUE THREAD

**Issue by blahgeek** [autozimu/LanguageClient-neovim#416]
## Reproduction

Using Java lang server:

![2018-05-04-12 51 36](https://user-images.githubusercontent.com/1308450/39613649-4cc3426a-4f9b-11e8-9f90-e93ba53b74ca.png)

Hit `<DOWN>`:

![2018-05-04-12 51 49](https://user-images.githubusercontent.com/1308450/39613662-604dbb94-4f9b-11e8-822e-93f1afea10ac.png)

## Expected

no duplicated `org.` inserted.

## Versions

Latest version of LanguageClient-neovim
Latest version of deoplete
jdtls 0.18.0

**Comment by blahgeek** [comment]
No it's still the same :(
(yes I've manually compiled the executable from HEAD before testing)

**Comment by wsdjeg** [comment]
@autozimu This issue should be reopend, as it still can be reproduced in next branch.
