### ISSUE TITLE
codeAction doesn't work 

### ISSUE THREAD

**Issue by slonoed** [autozimu/LanguageClient-neovim#418]
## Summary

Functions `call LanguageClient#textDocument_codeAction()` doesn't send a message to language server and shows `No diagnostics found!`. Other fuctions work fine.
Looks like it raises an error in `vim.rs` files without touching language server.

## Reproduction
- neovim  0.2.2, vim 8, macvim 8
- This plugin version 8483fc3
- This plugin's binary version languageclient 0.1.74 fb5044ccd536877aae7e021220ed88f85f04fe82
- Minimal vimrc content. 
```
filetype off
call plug#begin()

Plug 'autozimu/LanguageClient-neovim', {
\ 'branch': 'next',
\ 'do': 'bash install.sh',
\ }

"\ 'javascript.jsx': ['javascript-typescript-stdio'],
let g:LanguageClient_serverCommands = {
\ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
\ 'javascript.': ['tcp://127.0.0.1:2089'],
\ 'javascript': ['tcp://127.0.0.1:2089'],
\ }

let g:LanguageClient_loggingLevel = 'DEBUG'

call plug#end()
filetype on
```
- Language server link and version: https://github.com/sourcegraph/javascript-typescript-langserver, version 2.8.0
- Steps to reproduce the issue from clean state
    1. Run `javascript-typescript-langserver` with `--trace`
    2. Open vim with ts or js file and run `LanguageClientStart`
    3. Run `call LanguageClient#textDocument_codeAction()`
- Logs. [LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/1978818/LanguageClient.log)

## Current Behavior
`javascript-typescript-langserver` logs everything, but not `codeAction`

## Expected Behavior
`javascript-typescript-langserver` logs `codeAction`.

**Comment by autozimu** [comment]
Please specify the project/file you tested on and the cursor position when you invoked the command.

Also the attached log file doesn't help much. Ensure you reproduce the issue and upload the file immediately, otherwise it got override.

**Comment by slonoed** [comment]
I'm sorry. Log file was overwritten after I checked it.

This is the correct log entry.
```
11:11:44 WARN main src/utils.rs:69 Unknown project type. Fallback to use dir as project root: Ok("/tmp")
11:11:48 ERROR main src/vim.rs:57 Error handling message: No diagnostics found!

Message: {"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"buftype":"","character":9,"filename":"/tmp/file.js","handle":true,"languageId":"javascript.jsx","line":1,"text":["function hello() {","  return 1;","}",""]},"id":8}

Error: ErrorMessage { msg: "No diagnostics found!" }
```

I use file with content
```
function hello() {
  return 1;
}
```
In the position where symbol '1' is. But I checked many different files and different positions. The result is the same.
