### ISSUE TITLE
A way to recover from hanging language server?

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#419]
I'm working on a project with rls and cquery becoming unresponsive very frequently. They stop responding to any messages and issuing `LanguageClientStop` doesn't stop them. The only way to continue working is to restart neovim completely which isn't very convenient.

I'm assuming the problem lies in the language servers and not in the client but I don't know for sure. Upon `LanguageClientStop` I can see the exit message appearing in `LanguageClient.log`, however I see no change in `LanguageServer.log` while using `wrapper-server.sh`.

If it's an issue with the language client itself it'd be great to have that fixed, and if it's the language servers hanging there should be a command for forcibly killing them so a full editor restart isn't required.

To clarify, I have two windows open in nvim, one with the C files (handled by cquery) and one with the Rust files (handled by rls). The setup mostly works except this frequent hanging issue.

**Comment by YaLTeR** [comment]
I thought maybe `wrapper-server.sh` could be the culprit with multple things trying to output into the same `LanguageServer.log` file, so I changed it so that everything (stdin, stdout, stderr for cquery and rls) outputs to its own file (6 files in total). Still got a hang in the same way: `LanguageClient.log` says the client is sending messages like hover, but nothing new appears in either of the `LanguageServer` log files. This makes me suspect the client is actually the culprit here.

Maybe there's some threading issue going on in the client?

**Comment by autozimu** [comment]
That script isn’t used at all unless you specify it in your settings.

Right now the client is processing requests from vim sequencially and
waiting for a max of 5 mins before timing out.

I am waiting for the rust async story stable a bit before making the
process async.

You can try change the 5mins threshold  to be something more sensible like
10s. I will make the threshold configurable when I got some time.

**Comment by YaLTeR** [comment]
I did specify the script in my settings (I made separate scripts for cquery and rls actually) to debug this issue.

This isn't a timeout issue because it occurrs right in the middle of heavy language server usage. On the other hand, not doing anything for up to 30 mins leaves the language server working if it was before.

EDIT: or do you mean after 5 mins it restarts whatever it's doing and should fix itself?

**Comment by autozimu** [comment]
Yes, the symptom matches exactly my guessing.

Say the language server takes 10 mins to respond to one request, the client should timeout promptly since 10 mins operation is useless for an end user.

Right now, the client is waiting for that operation for 5 mins before timing out, which is not a sensible setting and this waiting will block subsequent requests like `:LanguageClientStop` from vim.

You could first try change this line https://github.com/autozimu/LanguageClient-neovim/blob/f5d50cda46ca96f94c0b8fe7cd3e604b3f68072f/src/vim.rs#L32

**Comment by YaLTeR** [comment]
Thanks, I'll make sure to try that tomorrow.

**Comment by YaLTeR** [comment]
Looks like that was the issue indeed, with the commit it unhangs after 10 seconds.
