### ISSUE TITLE
Feature request: disable signs per filetype

### ISSUE THREAD

**Issue by romgrk** [autozimu/LanguageClient-neovim#421]
Hi,

I'd like to be able to disable signs based on certain filetypes, e.g. for python don't show sign, but for javascript show them.

If it's too much, then just a command to disable signs without stopping the LSP althogether, e.g. `LanguageClientDisableSigns`, `LanguageClientEnableSigns`, `LanguageClientToggleSigns`

Thanks!

**Comment by autozimu** [comment]
Duplicate https://github.com/autozimu/LanguageClient-neovim/issues/302
