### ISSUE TITLE
expected Config, encountered Null

### ISSUE THREAD

**Issue by hyhugh** [autozimu/LanguageClient-neovim#424]
![wx20180512-131240](https://user-images.githubusercontent.com/16500351/39953047-373589f2-55e6-11e8-9d8e-847a553b5f51.png)

this error message shows up after i updated to the new version of this plugin today.

my current vim settings for LanguageClient-neovim 
![image](https://user-images.githubusercontent.com/16500351/39953057-69954838-55e6-11e8-985e-63e7e76c727b.png)

**Comment by hyhugh** [comment]
![image](https://user-images.githubusercontent.com/16500351/39953195-d8d4a98e-55e9-11e8-9244-ce0283c056ca.png)
![image](https://user-images.githubusercontent.com/16500351/39953200-ed13b5c0-55e9-11e8-8040-3c6a99d240f9.png)

this error message is still there after upgrading to 1.78

**Comment by autozimu** [comment]
That part is a language server issue though.

According to the spec, the params is defined as
```typescript
interface DidChangeConfigurationParams {
	/**
	 * The actual changed settings
	 */
	settings: any;
}
```

In your case, there is no settings found, so client is sending `null` as expected.

**Comment by hyhugh** [comment]
I don't really think that's a language server issue.
That works flawlessly yesterday. And the server still works with vscode. This error just appeared after upgrading.
And it seems that error message is not from the language server side. It seems that it shows up during that initialisation phase.

**Comment by autozimu** [comment]
In the new releases, this client sends more info to the lanuage server. One
case (null) is not supported by the hie though, which is a bug in hie that
it cannot handle this null input.

And the error is coming from language server.

Please cc language server author or raise at their repo. He will understand
this remaining part.
