### ISSUE TITLE
有没有选项禁止 hover 时候弹出 preview window

### ISSUE THREAD

**Issue by skywind3000** [autozimu/LanguageClient-neovim#428]
Preview window 极度干扰我的视线，打乱窗口布局，有没有办法hover时不显示preview window，只是再下面命令行 echo 一下即可？

**Comment by mqudsi** [comment]
Google translation:

> Preview window is extremely disturbing my view, disrupt the window layout, there is no way to show the preview window hover, just the following command line echo can be?

**Comment by skywind3000** [comment]
The google translation sucks.

Just request an option to disable preview window when calling LSP hover function. Opening a peview window accidentally will mess up my workspace and distract my focus.

Why this request is labeled as "help wanted" ?? I don't see any difficulty to disable the preview window, it is opened by LanguageClient-neovim itself.

**Comment by KillTheMule** [comment]
> Why this request is labeled as "help wanted" ?? I don't see any difficulty to disable the preview window, it is opened by LanguageClient-neovim itself.

It's not alwas a question of difficulty, but also of priorities and total time spent. The maintainer has probably decided that he's open to merging a PR for that particular feature, but does not want to spend time on it by himself. Often, things are a tad more involved than is apparent on your first look, too.

**Comment by skywind3000** [comment]
I suppose ui elements should be implemented in script, not in a native language like rust and it can be iterated rapidly. 

LanguageClient-nvim chose an opposite way and implement almost all the ui logics in rust. This will definitely slow down the iteration progress and become hard to add features in the future. 

And got less people who can help the development even if they want.

I suggest move the entire ui layer out of rust and keep the rust module as simple as a data service or message gateway between vimscript and Language Servers.

If so, more developers can get involved easily and help this plugin to become better.

**Comment by skywind3000** [comment]
多谢 ！！
