### ISSUE TITLE
Failed to start language server: []

### ISSUE THREAD

**Issue by fantiq** [autozimu/LanguageClient-neovim#43]
- neovim version `0.1.7 `
- Plugin version (git SHA) `7c5a0cc`
- Minimal vimrc.
```
Plug 'autozimu/LanguageClient-neovim', { 'do': ':UpdateRemotePlugins' }
let g:LanguageClient_serverCommands = {'php' : ['php', '~/.local/share/nvim/plugged/LanguageServer-php-neovim/vendor/bin/php-language-server.php']}
let g:LanguageClient_autoStart = 1
let g:LanguageClient_signColumnAlwaysOn = 1
" nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> <C-]> :call LanguageClient_textDocument_definition()<CR>

Plug 'roxma/nvim-completion-manager'
Plug 'roxma/LanguageServer-php-neovim', {'do': 'composer install && composer run-script parse-stubs'}
autocmd FileType php LanguageClientStart
```
- Content of `:CheckHealth`.
```
python2 is not support
python3 is support
```
- Content of `~/.local/share/nvim/rplugin.vim`.

- Run `:call LanguageClient_setLoggingLevel('DEBUG')` and then
  `:LanguageClientStart`, reproduce the bug, attach content of
  `/tmp/LanguageClient.log`.

```
23:55:58 INFO     Begin LanguageClientStart
23:55:58 INFO     End LanguageClientStart
23:55:58 INFO     Begin initialize
23:55:58 INFO     rootPath: /vagrant/trunk/kqc/cyb
23:55:58 DEBUG     => {"params": {"capabilities": {}, "rootPath": "/vagrant/trunk/kq
c/cyb", "rootUri": "file:///vagrant/trunk/kqc/cyb", "trace": "off", "processId": 156
67}, "jsonrpc": "2.0", "method": "initialize", "id": 0}
23:55:58 DEBUG     <= 
23:56:04 ERROR    Failed to start language server: []
23:56:05 ERROR    Failed to start language server: []
23:56:05 ERROR    Failed to start language server: []
23:56:05 ERROR    Failed to start language server: []
23:56:05 ERROR    Failed to start language server: []
```

when i call the `LanguageClient_*`  function , there is the error messahe `Failed to start language server: []`

**Comment by autozimu** [comment]
Thanks for reporting.

Did you see any error when you run the language server from command line? i.e.,
```
php ~/.local/share/nvim/plugged/LanguageServer-php-neovim/vendor/bin/php-language-server.php
```

**Comment by fantiq** [comment]
@autozimu  
i got nothing when i execute this command
```
php ~/.local/share/nvim/plugged/LanguageServer-php-neovim/vendor/bin/php-language-server.php
```

and i can find it from the active process by the command `ps -ef` , like the following
```
vagrant  16795 16778  0 20:38 pts/2    00:00:00 PHP Language Server
```

**Comment by autozimu** [comment]
Cloud you try using
```
let g:LanguageClient_serverCommands = {'php' : ['php', $HOME . '/.local/share/nvim/plugged/LanguageServer-php-neovim/vendor/bin/php-language-server.php']}
```

i.e., replace `~` with a variable expansion. As the server command is passed directly to python popen, which have no idea of `~`.

Also, please try remove
```
let g:LanguageClient_signColumnAlwaysOn = 1
autocmd FileType php LanguageClientStart
```

As for one thing, they are effectively the same thing. Secondly, for debug purpose, please use explicit `:LanguageClientStart` to start the plugin as it will display errors if there is any.

**Comment by autozimu** [comment]
I made a commit to expand user dir. Please try it or use the previous suggestion.

**Comment by fantiq** [comment]
thanks for your work, it is because the path `~`

replace the `~` with `$HOME` , it works will !
