### ISSUE TITLE
Latest release breaks `install.sh`

### ISSUE THREAD

**Issue by tricktux** [autozimu/LanguageClient-neovim#430]
> If you are reporting a bug, please read following FAQ first. If you are
requesting other types of issue, please ignore.

- Did you upgrade to latest plugin version? `Yes`
- Did you upgrade to/compile latest binary? Run shell command 
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?

## Summary
Binaries for architectures other than `languageclient-0.1.79-x86_64-apple-darwin` are missing. There were uploaded as `tags`, therefore the 404 error.

(placeholder)

## Reproduction
1. Run the `install.sh`

## Current Behavior
```bash
⏚ [reinaldo:~/.local … ns/LanguageClient-neovim] next ± ./install.sh
Downloading bin/languageclient...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Failed to download with curl and wget
Trying build locally ...
cargo build --release
make: cargo: Command not found
make: *** [Makefile:19: release] Error 127
```

## Expected Behavior
Downloads and installs binary normally.

> Please understand the more detailed information provided, the sooner a issue
could be resolved. Low quality bug reports might be closed directly.)

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by dryya** [comment]
The prebuilt binary wasn't finished/didn't get uploaded to github yet. It should work soon. It fails because if it cannot get a prebuilt binary, it tries to build from source, but you don't have Rust installed.

**Comment by tricktux** [comment]
Good to know they are on the way. Because I have no interest in installing cargo and the whole Rust environment.

Thanks for the quick response. I'll close as soon as its there.

**Comment by whitebyte** [comment]
This is somewhat related to https://github.com/autozimu/LanguageClient-neovim/issues/429. The fact that dependencies required for build from the source (rust and cargo) should be mentioned somewhere.
