### ISSUE TITLE
Add support for global project settings

### ISSUE THREAD

**Issue by jonhoo** [autozimu/LanguageClient-neovim#431]
Currently, the file pointed to by `settingsPath` (by default) is a per-project `.vim/settings.json`. However, in many cases, it makes sense to define some settings globally (e.g., `build_on_save`). It'd be nice if LanguageClient read `~/.vim/settings.json` *and* `./.vim/settings.json`, and merged them (with the latter overriding the former).

Second, it'd be fantastic if we could have support for per-language settings similar to [what exists](https://github.com/jonasbb/rls_vscode/blob/e3884bbae7a0012fd7adea9565a2e36343c2f0e5/package.json#L263) in VSCode. For example, if my `settings.json` contains `rust.build_on_save`, the setting `build_on_save` should only be sent if the language is `rust`.

**Comment by dryya** [comment]
I very much support this idea, but think it would be better to follow the XDG spec. I couldn't find any discussion of how .vim was selected in #179 , but I don't think it's the most intuitive folder name - neovim doesn't even read any files from ~/.vim, as far as I can tell. Trying to read $XDG_CONFIG_HOME/nvim/settings.json, then if not defined ~/.config/nvim/settings.json, and then if that does not exist ~/.vim/settings.json sounds like a good option. I honestly think ~/.vim should be removed altogether, but that would probably break some people's configs by surprise.

In terms of per-project options, it think it might also make sense to just save it as ./.LSPsettings.json or something like that, similar to the way pylint does it, where I believe it checks for ./.pylintrc for per-project settings.

(If the file name is changed, it would of course make sense to change the name of the global settingsPath file to LSPsettings.json or whatever is selected as well).

**Comment by autozimu** [comment]
For per project settings, you can already change the path, and it can also
be absolute path. I’d rather not change the decent default.

For per language server settings, it is  supported. Check for the rust
example in tests folder.

As for global settings, one alternative is pass those settings as
parameters  when specifying language server commands.

**Comment by jonhoo** [comment]
Ah, I did not know about the language-specific features! That's great! It'd probably be good if this feature was documented somewhere though.

I'm not sure exactly what you mean about specifying them when giving commands? And would this still then merge the settings with the per-project ones, and make the per-project settings override the global ones when some setting is specified by both?

**Comment by Anrock** [comment]
Somehow related question: is there any doc on what options are allowed in this settings.json file? Can't find anything on Google. Is it related to LSP itself or is it LanguageClient-neovim specific?

**Comment by dryya** [comment]
It is related to the specific options provided by servers. For example, here are the RLS options: https://github.com/rust-lang-nursery/rls#configuration

**Comment by jonhoo** [comment]
(note, however, that that list is [non-exhaustive](https://github.com/rust-lang-nursery/rls/issues/870#issuecomment-389286606))

**Comment by autozimu** [comment]
> specifying them when giving commands

This is an example of achieving global settings by specifying it within commands, https://github.com/cquery-project/cquery/wiki/Initialization-options

I don't think it will be applicable to all settings and all language servers, but thought it might be helpful to some use cases.

**Comment by jonhoo** [comment]
@autozimu in particular, as one data point, Rust's RLS does not take any command-line options to configure its behavior. I filed https://github.com/rust-lang/rls/issues/1325

**Comment by blahgeek** [comment]
I think it would be great if the language client can
1. check for project specific settings in current folder, and fallback to global settings if not found
2. merge the project specific settings with the global setting (override specified fields only)

One use case is that, MSPYLS requires python interpreter path in initialization options, which is different for projects using virtual environment. But there's other settings like cache directory that I want to share across different projects.

For now, I need to copy the whole settings to project folder, and change the settings path using something like https://github.com/embear/vim-localvimrc (not all projects have local per-project settings). Also if I want to change the cache directory, I need to change settings from all projects.
