### ISSUE TITLE
Optionally do not stop server on exit vim

### ISSUE THREAD

**Issue by shkm** [autozimu/LanguageClient-neovim#435]
In cases where a TCP socket is provided for a language server, the server needs to be started manually; this is fine, but I do find it unintuitive that exiting vim will still automatically stop the server.

My real-life use-case is in running Solargraph; the only way I'm aware to get it working with LanguageClient is to run the server myself.

As such, I propose a variable to control auto-stopping the language server. Ideally this could be configured on a per-language basis, but for now it'd be nice to just have the option.

**Comment by autozimu** [comment]
Resolved with https://github.com/autozimu/LanguageClient-neovim/pull/436.
