### ISSUE TITLE
Change order/priority of results?

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#437]
I'm not sure if this is deoplete's job, LC's job, or the language server's job, but is it possible to change the order of results?

With the clangd LSP provider, there are about half a million snippets that come back from LSP and they come up above member variables in the list of completions for `foo-><COMPLETIONS>`.

I imagine the fact that they come up at all in the middle of a word completion is already a bug in the server, but is there anything that can be done in LC to either change their order or filter them out completely? (I never use snippets).

Deoplete allows both sorting and changing priority of results based on provider, but on deoplete's end all I see is completions of different types all by the one (LC) provider, and it doesn't seem that there's a mechanism to change the priority based on the _type_ of result reported by the same provider. I believe this is because initially (pre-LSP), deoplete had a different provider for each "type" of completion (syntax, snippet, buffer, include, etc) so there wasn't a need for that.

Of course, I could be missing something and the functionality is already there, either in LC or in deoplete.. but I haven't been able to find it by reading both docs and playing around with my configuration. The only thing I didn't do is a custom deoplete filter, which I could presumably use to block snippets entirely. However, I _would_ prefer to do this on LC's end as there seems to be a delay associated with the number of completions returned by the language server ultimately bubbling up to deoplete, so filtering them lower down the food chain would be ideal.

cc @Shougo for ideas (hope you don't mind!)

**Comment by autozimu** [comment]
I believe [`sorters`](https://github.com/Shougo/deoplete.nvim/blob/165e693cbb1198569954b2a01f7ba56026bf7ddf/doc/deoplete.txt#L981) is one way to achieve this, though you might need to create your own `sorter` to make it work as you described.

**Comment by autozimu** [comment]
Nothing to be done in this plugin.
