### ISSUE TITLE
Exec format error (os error 8)

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#440]
## Summary

When opening a .java file, language server fails to start with error: Exec format error (os error 8).

## Reproduction
- neovim version: 0.2.2
- This plugin version (`git rev-parse --short HEAD`): 61ce058
- This plugin's binary version (`bin/languageclient --version`): 0.1.80
- Language server link and version: eclipse.jdt.ls [link](https://github.com/eclipse/eclipse.jdt.ls)
- Steps to reproduce the issue from clean state
    1. Just open a .java file
- LanguageClient-neovim settings in my init.vim:
`nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>`
`nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>`
`nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>`
`let g:LanguageClient_serverCommands = {`
`    \ 'c': ['cquery', '--log-file=/tmp/cq.log'],`
`    \ 'cpp': ['cquery', '--log-file=/tmp/cq.log'],`
`    \ 'java': ['jdtls', '-Dlog.level=ALL'],`
`    \ 'rust': ['rustup', 'run', 'stable', 'rls'],`
`  \ }`
`let g:LanguageClient_loadSettings = 1`

- Logs.
    1. /tmp/LanguageClient.log:
        `#######`
`LanguageClient 0.1.80`
`#######`
`10:46:27 INFO main src/languageclient.rs:1839 End languageClient/setLoggingLevel`
`10:46:27 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","result":null,"id":1}`
`10:46:35 INFO reader-main src/vim.rs:379 <= None {"method": "languageClient/handleBufReadPost", "jsonrpc": "2.0", "params": {"languageId": "java", "buftype": "", "filename": "/home/babba/Downloads/sample-java/src/main/java/app/App.java"}}`
`10:46:35 INFO main src/languageclient.rs:1877 Begin languageClient/handleBufReadPost`
`10:46:35 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename] = [String(""), String("java"), String("/home/babba/Downloads/sample-java/src/main/java/app/App.java")]`
`10:46:35 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["!!get(g:, 'LanguageClient_autoStart', 1)"],"id":1}`
`10:46:35 INFO reader-main src/vim.rs:379 <= None {"id": 1, "jsonrpc": "2.0", "result": 1}`
`10:46:35 INFO main src/languageclient.rs:2320 Begin languageClient/startServer`
`10:46:35 INFO main src/languageclient.rs:29 Some arguments are not available. Requesting from vim. Keys: ["cmdargs"]. Exps: ["[]"]`
`10:46:35 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[[]]"],"id":2}`
`10:46:35 INFO reader-main src/vim.rs:379 <= None {"method": "languageClient/handleTextChanged", "jsonrpc": "2.0", "params": {"languageId": "java", "buftype": "", "filename": "/home/babba/Downloads/sample-java/src/main/java/app/App.java"}}`
`10:46:35 INFO reader-main src/vim.rs:379 <= None {"id": 2, "jsonrpc": "2.0", "result": [[]]}`
`10:46:35 INFO main src/languageclient.rs:46 gather_args: [("cmdargs", "[]")] = [Array([])]`
`10:46:35 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename] = [String(""), String("java"), String("/home/babba/Downloads/sample-java/src/main/java/app/App.java")]`
`10:46:35 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["get(g:, 'LanguageClient_loggingLevel', 'WARN')"],"id":3}`
`10:46:35 INFO reader-main src/vim.rs:379 <= None {"id": 3, "jsonrpc": "2.0", "result": "WARN"}`
`10:46:35 WARN main src/languageclient.rs:1910 Failed to start language server automatically. Exec format error (os error 8)`

    2.  /tmp/LanguageServer.log is empty.

## Comments
I honestly don't know if the problem is with jdt or with this plugin; if I try to execute `jdtls` (the file created following the [wiki](https://github.com/autozimu/LanguageClient-neovim/wiki/Java)) from the command line, no output is printed, so I guess there is no error in this case.

**Comment by autozimu** [comment]
Please check the updated content of `jdtls` at https://github.com/autozimu/LanguageClient-neovim/wiki/Java

The previous version is missing shebang.

**Comment by ghost** [comment]
Great! Thank you very much
