### ISSUE TITLE
[Enhancement] Context menu

### ISSUE THREAD

**Issue by kristijanhusak** [autozimu/LanguageClient-neovim#442]
LSP has a lot of options, and mapping all those or calling them manually is a bit annoying.
We could create a context menu that will give user a selection.
Something like this with a  built in `confirm` function:
![screenshot](https://i.imgur.com/kvRfMWe.png)

Or `inputlist`
![screenshot_inputlist](https://i.imgur.com/zjVnoML.png)

Maybe the second option is better because there's a lot of options, and first one goes horizontally, where the second one goes vertically.

If you are interested I'll create a PR.

**Comment by autozimu** [comment]
Interesting idea! Please go for it.

**Comment by DerWeh** [comment]
Sounds like a great idea. Maybe `LanguageClient-neovim` could just provide a `Denite` menu with its commands, as it already integrated with `Denite`.

**Comment by KillTheMule** [comment]
That would restrict the feature to denite users, though.

**Comment by Anrock** [comment]
How about **also** provide a Denite menu?

**Comment by KillTheMule** [comment]
Sounds like a plan :)

**Comment by kristijanhusak** [comment]
If we would support denite, then i guess we should support fzf too, like for everything else. This escalated quickly :D

**Comment by Anrock** [comment]
Yeah. Denite and fzf support could be moved to separate issues, though.

**Comment by kristijanhusak** [comment]
I'll try to create shared solution for all 3.

**Comment by autozimu** [comment]
Merged in #446.
