### ISSUE TITLE
Multi-language settings.json not working for cquery

### ISSUE THREAD

**Issue by RobertBuhren** [autozimu/LanguageClient-neovim#450]
Hi,
I'm using this settings conf:
```
{
    "c": {
      "initializationOptions": {
        "cacheDirectory": "/tmp/cquery"
      }

    },
    "rust": {
        "all_features": true,
        "clippy_preference": "on",
        "wait_to_build": 0
    }

}
```
When opening a rust file, completion works as expected and the options are also used.
However, when I open a c file, the log of cquery says:

"cacheDirectory cannot be empty."

When I only use this settings.json:
```

{
      "initializationOptions": {
        "cacheDirectory": "/tmp/cquery"
      }

    }

```
cquery works as expected.

Any suggestions?

Regards,
Robert

**Comment by autozimu** [comment]
You might want to try
```json
{
	"initializationOptions": {
		"cacheDirectory": "/tmp/cquery"
	},
	"rust": {
		"all_features": true,
		"clippy_preference": "on",
		"wait_to_build": 0
	}
}
```

**Comment by RobertBuhren** [comment]
Thanks, this work for both language. IMHO this should be documented.
