### ISSUE TITLE
languageclient fails to start on a multi-user system

### ISSUE THREAD

**Issue by hvenev** [autozimu/LanguageClient-neovim#451]
Not all systems are single-user. `/tmp` is shared between all users. The first user to try to start `languageclient` since the system was booted will succeed, but all other users will fail because the first-user-owned system-wide log files already exist.

**Comment by hvenev** [comment]
This feels dirty. In my opinion not working is far better than world-rw logs.

Also, how does this interact with `umask`?

**Comment by Eyenseo** [comment]
@autozimu  I ran into this issue today - the other user was not updated - and I got a unhelpful message about `NoLanguageServer { languageId: "sh" }`.
While the fix does prevent the creation of unwritable files it doesn't handle the case that the location is unwritable? - it would be nice if there would be a better error message. 

I'm also wondering why it has to be 'one' log per system - why can't we use one log per user or even better one log per instance?

**Comment by autozimu** [comment]
If there is one log file per session, it would easily be hundreds of log
files generated.

Plus it’s already complicated to guide user to find log file and attach it
in bug report. I don’t want want to complicate the process further.

Ideally, vim/neovim should provide a mechanism for storing/displaying
temporary data.

I might reconsider this though.

**Comment by Eyenseo** [comment]
@autozimu why would there be hundreds? Sure if there are 100+ vim instances open the same time that would be the case (but then a single log would be quite cluttered). If we close vim the log can be discarded (maybe only if no error or waning happend?), can't it? That way we wouldn't accumulate useless log files in case of successive vim instances.
Regarding the user issue - can't we introduce a `LanguageClientLog` command that prints (at least) the log location?

**Comment by autozimu** [comment]
The log files are discarded but still reside on the file system, until the
system is rebooted.

**Comment by hvenev** [comment]
Having world-readable log files is bad because of possible disclosure of information.

Having world-writable log files is bad because that makes them unreliable. If another user starts languageserver, the current user's log is destroyed.

I think vim has a mechanism for logging - the `message` command. I think that setting `verbosefile=/path/to.log` makes it store them in a file as well.

Alternatively, make the log file 0o600 and add the user's numeric id to its name, like almost everybody else does for temporary files (and nobody does for logs because logs shouldn't be stored in `/tmp/`).

**Comment by KillTheMule** [comment]
> Ideally, vim/neovim should provide a mechanism for storing/displaying temporary data.

You might be interested in https://github.com/neovim/neovim/pull/6272.

**Comment by Eyenseo** [comment]
@hvenev wouldn't a log file still be "useless" if written by different vim instances (by the same user)?

~Regarding the security concerns - an command to write the log to a file would be nice.~
~`:LanguageClientLog user/path/what/ever<cr>`~
~Log will then be written to the location.~

~I'm not familiar with the code base but this should be possible to implement in a way that works 99,9% of the time / issues / errors.~

An off by default setting (that excepts a path) would be enough and in every way better.

**Comment by hvenev** [comment]
@Eyenseo As I said at some point, refusing to work is better behaviour than world-writable logs.

Edit: reasoning. Think quotas. At some point all space in /tmp has been used mostly by one user. They happened to be the first to start a languageserver since the system last rebooted last month. Now they can't write to /tmp. If there isn't a per-user limit, nobody can write. This breaks, among other things, shell completion for everyone. The user gets a stern talking to from the university sysadmin.

**Comment by lunks** [comment]
I'm getting the same error after running neovim with the `root` user, but it might not be the case because another project is working. I don't have any logging files in `/tmp`. How can I debug and fix the possible permission issue I'm encountering?
