### ISSUE TITLE
[cquery] completion item removes previous input characters

### ISSUE THREAD

**Issue by Synray** [autozimu/LanguageClient-neovim#452]
## Summary
Cquery handles completions differently - instead of returning a whole function name, it returns the the last part of the name
Clangd returns the whole function name, so the issue only happens when using cquery.

I looked at the specification for a precise definition of what a server is supposed to return, but couldn't find any, which is why I opened an issue here.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): nvim v0.3.0-1308-g3585df3f0
- This plugin version (`git rev-parse --short HEAD`): 9e62b2d
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.82 
- Minimal vimrc content: 
```vim
let g:LanguageClient_serverCommands = {
            \ 'c': ['cquery'], 
            \ }
```
- Language server link and version: latest cquery
- Steps to reproduce the issue from clean state
1. Make a test project
```sh
mkdir test && cd test
echo '[]' > compile_commands.json
nvim main.c
```
2. Write in main.c:
```c
int main() {

}
```
3. Put the cursor in the body of `main()`, then type `ma`
```c
int main() {
     ma
}
```
4. Now press `<C-X><C-O>`. You should see `in()` as the completion result.
5. Pressing `<C-X><C-Y>` deletes `ma` and inputs `in()`.

**Comment by autozimu** [comment]
Resolved in https://github.com/autozimu/LanguageClient-neovim/commit/0d0e254f9f620e6b6507414690a29aa8f842a2eb.
