### ISSUE TITLE
Custom cross references requests returning Location[] | null

### ISSUE THREAD

**Issue by MaskRay** [autozimu/LanguageClient-neovim#454]
Some language servers support custom cross reference requests (e.g. `$ccls/vars`).

* params: `TextDocumentPositionParams` or its subclass
* result: `Location[] | null`

Here is an example request `$ccls/vars` which has an additional parameter `kind`
```javascript
{"jsonrpc":"2.0","method":"$ccls/vars","params":{
  "textDocument":{"uri":"file:///home/maskray/Dev/llvm/include/llvm/IR/PassManager.h"},
  "position":{"line":320,"character":11},
  "kind":2      // additional request parameter
},
"id":1189}
```

It will be helpful to have a generic interface to support them. Moreover, LSP standard may have additional parameters.

`textDocument/references` has an additional parameter `context`
```javascript
{"jsonrpc":"2.0","method":"textDocument/references","params":{
  "textDocument":{"uri":"file:///home/maskray/Dev/llvm/include/llvm/IR/PassManager.h"},
  "position":{"line":320,"character":11},
  "context":{"includeDeclaration":false}  // additional request parameter
},
"id":1203}
```

Rather than define an enum (`IncludeDeclaration,` in `src/types.rs`) for each possible cross reference request, it will be helpful to just make the parameters schema-free. LanguageClient-neovim can help fill in `TextDocumentPositionParams`, but let the user specify the request name and its extra parameters.

**Comment by MaskRay** [comment]
It will be more convenient for users to specify additional fields of the request, instead of creating an enum for each possible field (e.g. `"includeDeclaration"`). Here the abstraction I think is unnecessary.

In [ccls](https://github.com/MaskRay/ccls), I have added a few other extensions:

* `kind` in [`$ccls/vars`](https://github.com/MaskRay/ccls/blob/master/src/messages/ccls_vars.cc)
* `role` `excludeRole` in [`textDocument/references`](https://github.com/MaskRay/ccls/blob/master/src/messages/textDocument_references.cc)

**Comment by MaskRay** [comment]
Thanks for making `find_locations` generic? BTW, cquery has removed `$cquery/derived` in May (ccls may have removed it earlier).

Do you know how to send a `find_locations` request like this:

```javascript
{
  "jsonrpc": "2.0",
  "method": "$ccls/inheritanceHierarchy",
  "params": {
    "textDocument": {
      "uri": "file:///home/ray/Dev/Bin/radare2/shlr/sdb/src/array.c"
    },
    "position": {
      "line": 342,
      "character": 30
    },
    "flat": true,
    "level": 3,
    "derived": true
  },
  "id": 3164
}
```

**Comment by autozimu** [comment]
```vim
call LanguageClient#find_locations('$ccls/inheritanceHierarchy', {
    \ 'flat': true,
    \ 'level': 3,
    \ 'derived': true,
    \ }
```

**Comment by MaskRay** [comment]
I have tried
```vim
call LanguageClient#find_locations('$ccls/inheritanceHierarchy', {
    \ 'flat': v:true,
    \ 'level': 3,
    \ 'derived': v:true,
    \ })

```

but the request `params` is not a supetset of `TextDocumentPositionParams`
```
{"jsonrpc":"2.0","method":"$ccls/inheritanceHierarchy","params":{"buftype":"","character":7,"derived":true,"filename":"/tmp/c/a.cc","flat":true,"gotoCmd":null,"handle":true,"languageId":"cpp","level":3,"line":1,"text":["struct A {};","struct B : A {};","struct C : B {};",""]},"id":147}
```

**Comment by autozimu** [comment]
From where did you get this message? language server?

**Comment by MaskRay** [comment]
sudo sysdig -As9999 --unbuffered "proc.exe contains ccls and fd.type=pipe"

```
let g:LanguageClient_serverCommands = {
      \ 'c': ['ccls.debug'],
      \ 'cpp': ['ccls.debug'],
      \ 'objc': ['ccls.debug'],
      \ 'go': ['go-langserver', '-gocodecompletion', '-func-snippet-enabled', '-logfile=/tmp/gols.log'],
      \ 'python': ['pyls', '--log-file=/tmp/pyls.log'],
      \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
      \ }
```

**Comment by autozimu** [comment]
Sorry about that.

Please upgrade to latest release and try
```vim
call LanguageClient#findLocations({
    \ 'method': '$ccls/inheritanceHierarchy',
    \ 'flat': v:true,
    \ 'level': 3,
    \ 'derived': v:true,
    \ })
```

**Comment by MaskRay** [comment]
Thanks! It works.

```
nn xb :call LanguageClient#findLocations({'method':'$ccls/inheritanceHierarchy','flat':v:true,'level':3,'derived':v:false})<cr>
nn xd :call LanguageClient#findLocations({'method':'$ccls/inheritanceHierarchy','flat':v:true,'level':3,'derived':v:true})<cr>
nn xe :call LanguageClient#findLocations({'method':'$ccls/callers'})<cr>
nn xv :call LanguageClient#findLocations({'method':'$ccls/vars'})<cr>
nn xV :call LanguageClient#findLocations({'method':'$ccls/vars','kind':1})<cr>
nn xx x
```
