### ISSUE TITLE
Request: Always Show diagnostics messages Column Option

### ISSUE THREAD

**Issue by dsohbii** [autozimu/LanguageClient-neovim#457]
Sorry If I'm missing something, this is by far my favorite plugin for completions however, is there a way I can always show the diagnostic column? 

to the left of the line numbers that show the X if something is wrong.

Using it with the LanguageServer-php-neovim, even when typing

public function Foo(bar)
{

}

The first line will activate and close the column multiple times while i type creating a distracting situation.

Sorry if this is already implemented, I tried looking at the Wiki and I can't seem to find the option.

**Comment by autozimu** [comment]
Check https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-324095421

**Comment by autozimu** [comment]
Also created a wiki page for similar stuffs https://github.com/autozimu/LanguageClient-neovim/wiki/Recommended-Settings

**Comment by dsohbii** [comment]
Thank you!
