### ISSUE TITLE
Showing Parameter Hints

### ISSUE THREAD

**Issue by Nomadluap** [autozimu/LanguageClient-neovim#458]
## Summary
I'm wondering if LanguageClient supports showing parameter hints when typing an opening-brace
for a function. 

## Reproduction
- Neovim 0.3.0
- LanguageClient 143eaac9421a8bfe68175ac4c08cf6c5dfd22167
- deoplete master
- cquery 1fa36852b5dbe0d8e8207b1362a150c722a077c7

### Minimal init.vim: 
    call plug#begin()
    Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh'
        \ }
    Plug 'junegunn/fzf' " Multi-entry selection UI
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

    call plug#end()

    let g:deoplete#enable_at_startup = 1

    call deoplete#custom#option('sources', {
        \ 'cpp': ['tag', 'LanguageClient']
        \ })

    let g:LanguageClient_serverCommands = {
        \ 'cpp': ['/usr/local/bin/cquery', '--log-file=/tmp/cq.log'],
        \ 'hpp': ['/usr/local/bin/cquery', '--log-file=/tmp/cq.log']
        \ }
    let g:LanguageClient_loadSettings = 1

    " LanguageServer settings
    nnoremap <F5> :call LanguageClient_contextMenu()<CR>

### How to Reproduce
1. While the current directory is an exsting project where method/variable completion works, Open new nvim buffer, `:e test.cpp`
2. call `:LanguageClientStart`
3. Type the following: 
    ```
    #include <string>


    int main(int argc, char** argv)
    {
        std::string s;
        s.push_back( // < no parameter completion or paramater names here. 
      // ^
      // Typing the '.' here shows methods of std::string correctly. 
    }
    ```
#######
    LanguageClient 0.1.84 
    #######
    09:27:16 WARN main src/rpchandler.rs:193 Message not handled: Notification { jsonrpc: Some(V2), method: "$cquery/setInactiveRegions", params: Some(Map({"inactiveRegions": Array([]), "uri": String("file:///home/pbelanger/source/jetson-blackbox/test.cpp")})) }
    09:27:16 WARN main src/rpchandler.rs:193 Message not handled: Notification { jsonrpc: Some(V2), method: "$cquery/publishSemanticHighlighting", params: Some(Map({"symbols": Array([Object({"kind": Number(253), "parentKind": Number(12), "ranges": Array([Object({"end": Object({"character": Number(30), "line": Number(3)}), "start": Object({"character": Number(26), "line": Number(3)})})]), "stableId": Number(2), "storage": Number(1)}), Object({"kind": Number(253), "parentKind": Number(12), "ranges": Array([Object({"end": Object({"character": Number(17), "line": Number(3)}), "start": Object({"character": Number(13), "line": Number(3)})})]), "stableId": Number(1), "storage": Number(1)}), Object({"kind": Number(12), "parentKind": Number(1), "ranges": Array([Object({"end": Object({"character": Number(8), "line": Number(3)}), "start": Object({"character": Number(4), "line": Number(3)})})]), "stableId": Number(0), "storage": Number(1)})]), "uri": String("file:///home/pbelanger/source/jetson-blackbox/test.cpp")})) }
    09:28:19 WARN main src/rpchandler.rs:193 Message not handled: Notification { jsonrpc: Some(V2), method: "$cquery/setInactiveRegions", params: Some(Map({"inactiveRegions": Array([]), "uri": String("file:///home/pbelanger/source/jetson-blackbox/test.cpp")})) }
    09:28:19 WARN main src/rpchandler.rs:193 Message not handled: Notification { jsonrpc: Some(V2), method: "$cquery/publishSemanticHighlighting", params: Some(Map({"symbols": Array([Object({"kind": Number(13), "parentKind": Number(12), "ranges": Array([Object({"end": Object({"character": Number(21), "line": Number(5)}), "start": Object({"character": Number(20), "line": Number(5)})})]), "stableId": Number(5), "storage": Number(1)}), Object({"kind": Number(252), "parentKind": Number(3), "ranges": Array([Object({"end": Object({"character": Number(19), "line": Number(5)}), "start": Object({"character": Number(13), "line": Number(5)})})]), "stableId": Number(4), "storage": Number(0)}), Object({"kind": Number(253), "parentKind": Number(12), "ranges": Array([Object({"end": Object({"character": Number(21), "line": Number(3)}), "start": Object({"character": Number(17), "line": Number(3)})})]), "stableId": Number(1), "storage": Number(1)}), Object({"kind": Number(12), "parentKind": Number(1), "ranges": Array([Object({"end": Object({"character": Number(12), "line": Number(3)}), "start": Object({"character": Number(8), "line": Number(3)})})]), "stableId": Number(0), "storage": Number(1)}), Object({"kind": Number(3), "parentKind": Number(1), "ranges": Array([Object({"end": Object({"character": Number(11), "line": Number(5)}), "start": Object({"character": Number(8), "line": Number(5)})})]), "stableId": Number(3), "storage": Number(0)}), Object({"kind": Number(253), "parentKind": Number(12), "ranges": Array([Object({"end": Object({"character": Number(34), "line": Number(3)}), "start": Object({"character": Number(30), "line": Number(3)})})]), "stableId": Number(2), "storage": Number(1)})]), "uri": String("file:///home/pbelanger/source/jetson-blackbox/test.cpp")})) }
### `/tmp/LanguageServer.log`

    [0m[2m2018-06-07 09:27:15.851 (   0.000s) [     47DB3740]        loguru.hpp:2049     0| [0m[1mLogging to '/tmp/cq.log', mode: 'w', verbosity: 9[0m
    [0m[1m[31m(   0.108s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/include[0m
    [0m[1m[31m(   0.108s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/mocs_compilation.cpp[0m
    [0m[1m[31m(   0.108s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/include[0m
    [0m[1m[31m(   0.109s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/mocs_compilation.cpp[0m
    [0m[1m[31m(   0.112s) [scan_includes]          utils.cc:191   | Unable to read file index.html when reading directory /home/pbelanger/source/jetson-blackbox/[0m
    [0m[1m[31m(   0.233s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/include[0m
    [0m[1m[31m(   0.234s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/mocs_compilation.cpp[0m
    [0m[1m[31m(   0.234s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/include[0m
    [0m[1m[31m(   0.234s) [querydb      ]        project.cc:68    | Failed to normalize /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/mocs_compilation.cpp[0m
    [0m[1m[31m(   2.261s) [indexer4     ]  clang_indexer.cc:2178  | Cannot index /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/mocs_compilation.cpp because it can not be found[0m
    [0m[1m[31m(   2.488s) [indexer4     ]  clang_indexer.cc:2178  | Cannot index /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/mocs_compilation.cpp because it can not be found[0m
    [0m[1m[31m(   3.063s) [indexer4     ]  clang_indexer.cc:2178  | Cannot index /home/pbelanger/source/jetson-blackbox/build/src/dev/sensorgraph-editor/sensorgraph-editor_autogen/mocs_compilation.cpp because it can not be found[0m
    [0m[1m[31m(   3.065s) [indexer0     ]  clang_indexer.cc:2178  | Cannot index /home/pbelanger/source/jetson-blackbox/build/src/dev/cdl_parse/cdl_parse_autogen/mocs_compilation.cpp because it can not be found[0m

## Current Behavior

Currently nothing is shown when inside a function call.

## Expected Behavior
Some sort of completion notification showing parameter hints should appear

**Comment by autozimu** [comment]
Ideally, I would like to implement this feature inside this plugin. But it hasn't been finished yet.

At the moment, please check https://github.com/Shougo/echodoc.vim

**Comment by Maltimore** [comment]
Friendly bump, is this still on the roadmap?

https://github.com/Shougo/echodoc.vim is quite annoying, it only shows the parameter hints for functions that have been autocompleted at least once in the current vim session.

**Comment by autozimu** [comment]
It is.

It's just I’ve been busy recently and don’t have too much time working on
this project.
