### ISSUE TITLE
Language server c exited unexpectedly: failed to fill whole buffer

### ISSUE THREAD

**Issue by zanglg** [autozimu/LanguageClient-neovim#461]
languageclient 0.1.84

health#LanguageClient#check
  - OK: binary found: /home/xxxx/.config/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.84

already put `let g:LanguageClient_loggingLevel = 'DEBUG'` in my init.vim

no /tmp/LanguageServer.log or  /tmp/LanguageClient.log in /tmp folder, ubuntu 16.04

two account in one server, account A ok, but account B failed.

same init.vim with vim-plug auto install all same plugins.

very confused.

**Comment by autozimu** [comment]
Duplicate https://github.com/autozimu/LanguageClient-neovim/issues/451
