### ISSUE TITLE
Partially typed words are lost when triggering omnicomplete

### ISSUE THREAD

**Issue by rliebz** [autozimu/LanguageClient-neovim#463]
## Summary

When triggering omnicomplete for certain language servers (e.g., `javascript-typescript-langserver`) after having typed part of the word to be completed, that partial match is completely ignored. Instead, the full list of matches for that word is presented, although if you start editing the results, the behavior becomes the correct behavior by filtering out non-matches.

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): `NVIM v0.2.2`
- This plugin version (`git rev-parse --short HEAD`): 641dee7
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.86 87acc5505f733f8256661e5b44a982d4293c822a`
- Minimal vimrc content. A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim].  Make sure
  your vimrc contains `let g:LanguageClient_loggingLevel = 'DEBUG'` to have
  full log:
```vim
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_typescript
    autocmd!
    autocmd BufReadPost *.ts setlocal filetype=typescript
augroup END

set omnifunc=LanguageClient#omniComplete

let g:LanguageClient_serverCommands = {
    \ 'typescript': ['javascript-typescript-stdio'],
    \ }
let g:LanguageClient_loggingLevel = 'DEBUG'
```
- Language server link and version: 
    - https://github.com/sourcegraph/javascript-typescript-langserver
    - Version 2.9.2
- Steps to reproduce the issue from clean state
    1. Use the `min-init.vim` from above, open any sample typescript file: `nvim -u min-init.vim tests/data/sample-ts/index.ts`
    2. On a new line, type `''.c`
    3. Trigger omnicompletion using `<c-x><c-o>`
- Logs. Paste or attach `($TMPDIR || $TMP || $TEMP || $TEMPDIR ||
  /tmp)/LanguageServer.log` and `($TMPDIR || $TMP || $TEMP || $TEMPDIR ||
  /tmp)/LanguageClient.log`.
```
(node:61982) ExperimentalWarning: The fs.promises API is experimental
```

## Current Behavior
A list of every possible completion for `''.` is returned, ignoring the fact that `c` was already typed. The first matching result is selected by default, so the existing context (the fact that `c` was typed) is lost:
![image](https://user-images.githubusercontent.com/5321575/41201851-e249043c-6c8d-11e8-86df-3d42931b7b1c.png)

## Expected Behavior
Only completions that match the partially typed word should be shown:
![image](https://user-images.githubusercontent.com/5321575/41201857-ffdec55e-6c8d-11e8-8f3c-7f9f05ce95ff.png)

## Additional Details
- Once omnicompletion has been triggered, editing the existing word will filter partial completions correctly. The incorrect behavior only reproduces on triggering the initial completion. 
- The same behavior does _not_ reproduce for all language servers. For example, `rls` on `stable` gives the proper behavior.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by autozimu** [comment]
I came across this same issue if I remember correctly.

It seems to be a "feature" of vim that the input is hidden when completion items don't match input.

Need time to confirm this though.

**Comment by rliebz** [comment]
That's how all of the other omnicomplete-based plugins I use have worked from a user-experience perspective.

From `:h complete-functions`:

```
The function is called in two different ways:
- First the function is called to find the start of the text to be completed.
- Later the function is called to actually find the matches.

...

On the second invocation the arguments are:
   a:findstart  0
   a:base	the text with which matches should match; the text that was
		located in the first call (can be empty)

The function must return a List with the matching words.  These matches
usually include the "a:base" text.  When there are no matches return an empty
List.
```

And the relevant part of the example from that help documentation:
```viml
	    " find months matching with "a:base"
	    let res = []
	    for m in split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec")
	      if m =~ '^' . a:base
		call add(res, m)
	      endif
	    endfor
	    return res
```

So I would think the expectation here is that filtering based on `a:base` is done by the completion function.

**Comment by autozimu** [comment]
That’s right.

Vim is expecting the completion items all matching base.

But if when using this specific language server, the completion items are
not filtered. Instead it returns all possible items without considering
base.

I’d suggest use one of the completion management plugin, e.g., deoplete,
which will handle the filtering.

**Comment by autozimu** [comment]
BTW, not going to implement filtering in this plugin. As theoretically, the completion items returned by language servers should already be filtered, like rls does.

**Comment by rliebz** [comment]
Even though many of the language servers do it, I couldn't find anything in the language server spec that guarantees filtering will be done on the server side. The closest is the discussion here, which indicates that filtering may need to be done on the client side, although it looks like it's still unresolved: https://github.com/Microsoft/language-server-protocol/issues/105#issuecomment-255743799

While language servers don't necessarily have to guarantee filtered results, `complete-functions` do have the expectation of returning only completed results. This becomes obvious from a user-experience perspective when after typing or changing the base completion, the results become filtered after the fact, so you get that inconsistency between opening the completion window for the first time versus changing it.

For me, it would be relatively straightforward to just wrap the completion function provided here and filter the results myself outside of the plugin, but I think it's likely others will run into the same issue.

If the concern is that the generic completion logic in this client shouldn't be filtering, which is totally fair, would you be open to filtering being done specifically in the top-level omnifunc (rather than the underlying, more generic completion logic in rust) to fix this specifically for omnifunc users for language servers that happen to not implement filtering? Or, less ideally, make it configurable?

**Comment by autozimu** [comment]
Make sense.

Ideally it would be two completion function. One is returning the completion items without processing such that completion plugins like deoplete can do filtering themselves. The other, as you said, filter the items as expected by omnifunc.
