### ISSUE TITLE
Support codeAction without a diagnostic

### ISSUE THREAD

**Issue by snoe** [autozimu/LanguageClient-neovim#465]
VSCode will display a codeAction prompt whether or not there's a diagnostic at that position. Is it possible LanguageClient-neovim could do the same?

It would be useful for exposing custom commands such as [refactorings](https://github.com/snoe/clojure-lsp#refactorings).

**Comment by autozimu** [comment]
I believe if the server responds properly to the codeAction request, it should work.

What issue did you come across?

**Comment by snoe** [comment]
My mistake, I believe I was on an old version of the client that gave a message of `No Diagnostic`.
