### ISSUE TITLE
Log files from multiple vim instances mix up

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#469]
Currently, if you have multiple vim instances running, all of them write to the same path for logging. It would be better to include something unique in the file names (pid, uuid) to clearly disambiguate the logs.

**Comment by hvenev** [comment]
I'd suggest logging to stderr by default. It looks like languageserver's stderr is already handled by the vim plugin.

**Comment by languitar** [comment]
That's not the point. My issue is that, as the default, all language clients use the same logfiles in `/tmp`.

**Comment by hvenev** [comment]
Logging to stderr by default would mean that `/tmp` is not used for logging, which would fix the interleaving problem. Having the ability to configure the path would help too.

@autozimu Should I start working on this?

**Comment by autozimu** [comment]
I've made it possible to configure logging file path, https://github.com/autozimu/LanguageClient-neovim/commit/30577f42e055fefe18ba1219730bc2b246e79b00

There must be places to improve through.

**Comment by autozimu** [comment]
Option to customize log file path was added, with default to none.

I'm not planning to make the logging more sophisticated. Anyway, it is only useful for debugging and bug reporting.
