### ISSUE TITLE
No GUI tooltip information for build errors/linters

### ISSUE THREAD

**Issue by hasufell** [autozimu/LanguageClient-neovim#472]
I use gvim and most linter plugins I used before (syntastic, ale) also show build errors in a tooltip when you move your mouse over the line with the error. Doesn't seem to work with LanguageClient-neovim.

Example:

![peek 2018-06-15 20-20](https://user-images.githubusercontent.com/1241845/41488868-237d863a-70ee-11e8-8566-e51110a60da4.gif)

**Comment by martskins** [comment]
You can achieve something like this by calling `LanguageClient#explainErrorAtPoint`, either manually (with a mapping) or by configuring it to run on `CursorHold` (probably not a great idea).

I'll close this one as it is quite dated and solved really, but feel free to re-open if you still have any doubts about it.

**Comment by hasufell** [comment]
How is this solved?

Also: cursor /= mouse pointer.

**Comment by martskins** [comment]
~I don't think you can do that on mouse hover, as I don't think there's a `MouseHover` event (I may be mistaken), but if there is then you just need to call that function on an autocmd for that event.~

What I meant by solved is that the function that provides the functionality you requested exists (`LanguageClient#explainErrorAtPoint`), you just need to decide where you want to fire that function call (within the options that vim provides you). If vim doesn't provide a `MouseHover` event then we can do nothing about it, and if it does provide one then it's just a matter of calling that function on that event with an `autocmd`.

**EDIT**: In your screencast you seem to be using some GUI version of vim, which seems to provide something like a MouseHover, but as I said, you can set this yourself by adding an autocmd for it: `autocmd MouseHover * call LanguageClient#explainErrorAtPoint()` (replace MouseHover by whatever the event that is fired on mouse hover is named in that vim frontend).
