### ISSUE TITLE
Warning highlight overrides error

### ISSUE THREAD

**Issue by tbo** [autozimu/LanguageClient-neovim#474]
## Summary

If a line contains a warning and an error, then only the last one is being displayed. This might lead to a situation, where a warning completely replaces the highlighting of an error (this includes the gutter sign and the cmdline message as well).

In my case `textDocument/publishDiagnostics` reports two entries in the same line:

```
23:08:43 INFO reader-java src/vim.rs:392 <= Some("java") {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"[...]","diagnostics":[{"range":{"start":{"line":12,"character":8},"end":{"line":12,"character":11}},"severity":1,"code":"16777218","source":"Java","message":"Map cannot be resolved to a type"},{"range":{"start":{"line":12,"character":44},"end":{"line":12,"character":69}},"severity":2,"code":"536871008","source":"Java","message":"The serializable class  does not declare a static final serialVersionUID field of type long"}]}}
```

Sometimes I'm even able to see the error highlight flicker up only to be replaced by the warning a split-second later. The quickfix list and the message history contain the error and the warning, so I assume, that this is just visual problem. 

## Reproduction
- neovim version: v0.3.1-9-gf27a665e0
- This plugin version: d233c6e
- This plugin's binary version: languageclient 0.1.87 5015aa164dc9ad96a0f5fbadaf92a888d16bc0d9
- Language server link and version: [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls)
- [LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2108589/LanguageClient.log)

The issue can be reproduced with this example (Line 14). It is based on the [java example](https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/data/sample-java/src/main/java/app/App.java) in this repository.
```
package app;

import java.util.HashMap;
import java.util.Map;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        Map<String, Object> variables = new HashMap<String, String>() {{
            put("Firstname", "John");
        }};
        System.out.println( "Hello test!" );
    }
}
```

## Current Behavior

The last diagnostics entry per line wins and overrides the highlights, gutter signs and messages of all others.

## Expected Behavior

All highlights, gutter signs and messages should be applied in an additive manner. Should this not be possible, then at least the most important entries (errors > warnings) should win. The messages should be sorted by importance and concatenated.

**Comment by tbo** [comment]
@autozimu 18fa436 fixed the issue for me. Thanks!

**Comment by tbo** [comment]
I just noticed, that it only fixed the highlighting. The gutter sign and message still report a warning.

**Comment by tbo** [comment]
Another observation: The highlight is only fixed after saving the file. The initial state still only shows the warning.

**Comment by autozimu** [comment]
The changes are still in dev branch.

You'd need to build the changes yourself or wait for next release.
