### ISSUE TITLE
'key "languageServerHaskell" not present' error in WorkspaceDidChangeConfiguration

### ISSUE THREAD

**Issue by luochen1990** [autozimu/LanguageClient-neovim#476]
## Summary

Vim displays the following message on start and languageclinet keeps working seemingly normally.

https://github.com/haskell/haskell-ide-engine/issues/369

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):

```
vim 8.0  (gvim, windows 64bit)
```

- This plugin version (`git rev-parse --short HEAD`):

```
$ git rev-parse --short HEAD
9a316ef
```

- This plugin's binary version (`bin/languageclient --version`):

```
$ ./languageclient --version
languageclient 0.1.88
```

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):

```
	let g:LanguageClient_serverCommands = {
		\ 'haskell': ['hie-wrapper', '--lsp', '-r', 'C:\dev\stack\stack_root\global-project'],
		\ }
```

- Language server link and version:

https://github.com/haskell/haskell-ide-engine
```
$ git rev-parse --short HEAD
9eb426e
```

- Steps to reproduce the issue from clean state
    1. open a file named `test.hs` (e.g. a haskell hello world program)
    2. the error message is shown (but seems the plugin is still working).

a demo `test.hs` file:
```
main = do
    name <- getLine
    print ("hello " ++ name)
```

- Logs (Paste or attach log file content):

```
LanguageClient project root: C:\Users\Luo\Dropbox\Workspace
[Error] haskell-lsp:didChangeConfiguration error. NotificationMessage {_jsonrpc = "2.0", _method = WorkspaceDidChang
eConfiguration, _params = DidChangeConfigurationParams {_settings = Object (fromList [])}} "key \"languageServerHask
ell\" not present"
```

## Current Behavior

The error message is shown (but seems the plugin is still working).

## Expected Behavior

No error message.

**Comment by luochen1990** [comment]
@autozimu  Is there any more information I should provide, or anything I should read but I missed?

**Comment by autozimu** [comment]
It should have been fixed.

**Comment by luochen1990** [comment]
I'm trying to update this plugin to confirm it, but the command `powershell -executionpolicy bypass -File install.ps1`  seems trying to download the same binary version as before, is there any other way to force update this plugin?

the downloading log info:
`Downloading https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.89/languageclient-0.1.89-x86_64-pc-windows-gnu.exe`

**Comment by autozimu** [comment]
0.1.89 is the latest release.

**Comment by luochen1990** [comment]
I can confirm that this issue is fixed on the latest version:

```
$ git rev-parse --short HEAD
e5e44f2

$ ./languageclient.exe --version
languageclient 0.1.90
```
