### ISSUE TITLE
Support multiple servers for the same type

### ISSUE THREAD

**Issue by fredemmott** [autozimu/LanguageClient-neovim#477]
## Summary

It can be useful to support multiple servers - for example, there may be a primary language service, and additional linters, command providers, etc.

For example, in Hack:
- `hh_client lsp` provides core language functionality, and comes with HHVM/Hack
- [HHAST](http://github.com/hhvm/hhast) is an entirely separate linter, which has support for LSP in master

It looks like this will shortly be useful for more popular languages - for example, in PHP, there is `php-language-server`, and @muglug / Vimeo's Psalm [is working on LSP server support](https://github.com/vimeo/psalm/tree/server).

**Comment by TysonAndre** [comment]
https://github.com/autozimu/LanguageClient-neovim/issues/473 is a similar/duplicate feature request. I accidentally closed that when posting a comment.

**Comment by autozimu** [comment]
Duplicate #473.
