### ISSUE TITLE
Support "newText" in completion items

### ISSUE THREAD

**Issue by jdonaldson** [autozimu/LanguageClient-neovim#478]
## Support "newText" in completion items

The Haxe languageserver uses newText instead of insertText for declaring code content to include in completions: https://github.com/vshaxe/haxe-languageserver/blob/d7799fa0570b91f10ec272ee4e7287f0224acf09/src/haxeLanguageServer/features/completion/CompletionFeature.hx#L275

This plugin uses insertText (insert_text) with a fall back to the label: https://github.com/autozimu/LanguageClient-neovim/blob/next/src/types.rs#L934

It looks like insertText usage is deprecated according to Microsoft : https://github.com/Microsoft/language-server-protocol/issues/264

What's the plan for handling insertText deprecation?  My 2 cents would be to:

1. Check for new_text here in this plugin, and use it if present.
2. If it is not present, check for insert_text, and use it (while also displaying a warning message about deprecation)
3. If neither are present, use the label.

I would give you a pull request, but I'm not very familiar with rust.  I can build the project, but it doesn't appear to work in my vim session.

**Comment by autozimu** [comment]
It's not so obvious as it looks.

With the new insertText, the `newText` might not be starting from completion starting point. Say
```
const varname;
sort(var<cursor>
```
With `insertText`, it could be that the `newText` property is `sort(varname)` with range start to be 0.

I've actually started the work to support this. Check https://github.com/autozimu/LanguageClient-neovim/blob/1004edf2542168f1a15f75d9078590b4f59dae89/src/types.rs#L958 

Just a few issues remaining before I can release it.

**Comment by jdonaldson** [comment]
Good point.  

Thanks for putting the thought into it.  I'll look forward to the update.
