### ISSUE TITLE
Add an configuration setting to ignore messages from stderr?

### ISSUE THREAD

**Issue by TysonAndre** [autozimu/LanguageClient-neovim#479]
Stderr may be of use to people debugging or developing language servers, but less useful (and distracting/unactionable) for end users (they briefly flash in the status bar).

The messages are of the form `LanguageClient stderr: ['message from language server']` in autoload/LanguageClient.vim , and may have started in the latest releases

```vim
229     elseif a:event ==# 'stderr'
230         call s:Echoerr('LanguageClient stderr: ' . string(a:lines))
231     elseif a:event ==# 'exit'
```

**Comment by autozimu** [comment]
Thanks for reporting. Will fix it shortly.
