### ISSUE TITLE
Quickfix gets overwritten by Diagnostics

### ISSUE THREAD

**Issue by pjio** [autozimu/LanguageClient-neovim#48]
Hello,

this is not a real bug but something that interferes with other usecases.

If the quickfix list is populated with search results and an item is selected, the LanguageServer diagnostics pushes diagnostic results to the client and the quickfix list is overwritten.

It happens in this line: https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L963

I use LanguageClient-neovim and LanguageServer-php-neovim.

Suggestions: The (file dependant) LocationList can be used instead of the QuickfixList or an option to disable diagnostics could be added...

Thanks in advance!

**Comment by pjio** [comment]
This patch should work:
[0001-Use-location-list-for-diagnostic-results.patch.txt](https://github.com/autozimu/LanguageClient-neovim/files/1016387/0001-Use-location-list-for-diagnostic-results.patch.txt)

**Comment by autozimu** [comment]
Thanks for reporting.

I will make the diagnostics configurable.
