### ISSUE TITLE
The unicode mark conflict with cursorline

### ISSUE THREAD

**Issue by luochen1990** [autozimu/LanguageClient-neovim#481]
## Summary

After the cursor line move across a mark (which is a unicode char on the left side of the line number), the right-half-part of the mark disappears.

![z5 x bxl cf1as 7 q_ y7](https://user-images.githubusercontent.com/2309868/41694889-1e2a8408-753f-11e8-8d61-163d54ac0b17.png)

## Reproduction

- neovim/vim version (`nvim --version` or `vim --version`):

```
vim 8.0  (gvim, windows 64bit)
```

- This plugin version (`git rev-parse --short HEAD`):
```
$ git rev-parse --short HEAD
e5e44f2
```

- This plugin's binary version (`bin/languageclient --version`):
```
$ ./languageclient.exe --version
languageclient 0.1.90
```

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):

```
	let g:LanguageClient_serverCommands = {
		\ 'haskell': ['hie-wrapper', '--lsp', '-r', 'C:\dev\stack\stack_root\global-project'],
		\ }
```

- Language server link and version:

https://github.com/haskell/haskell-ide-engine
```
$ git rev-parse --short HEAD
9eb426e
```

- Steps to reproduce the issue from clean state
    1. edit a file with languageclient working.
    2. `:set cursorline`.
    3. waiting for marks of info/warnning/error tips to display at the left side.
    4. observe the marks.
    5. move cursor to a line which have a mark at left side.
    6. move cursor to a next line.
    7. observe the marks again.

## Current Behavior

After the cursor line move across a mark, the right-half-part of the mark disappears.
And `set ambiwidth=double` doesn't help.
And `:set nocursorline` will fix the problem.

## Expected Behavior

The marks always displayed correctly.

**Comment by autozimu** [comment]
Is this reproducible with terminal vim on your side?

Not being able to reproduce for both terminal vim and neovim. Looks like a gvim issue.

**Comment by autozimu** [comment]
Also, it might because of Windows itself, especially locale settings.

Anyway, the gutter sign symbols are customizable. ASCIIs are generally less error-prune on Windows.

**Comment by luochen1990** [comment]
I cannot reproduce this on cmd, but can still reproduce this on neovim-qt, seems this is a gui-only problem, not sure if this is windows-specific.
