### ISSUE TITLE
[cquery, configuration] Support for env variables in settings.json

### ISSUE THREAD

**Issue by andreyorst** [autozimu/LanguageClient-neovim#483]
Referring to cquery's wiki, [settings.json](https://github.com/cquery-project/cquery/wiki/Neovim#homeyour_usernameconfignvimsettingsjson) need to be set up to use cquery with LCN. However I didn't find any info how to configure it more flexible. Is there any way to use Environment variables in settings.json file? I would like to set it to my home directory e.g. `/home/username/.cache/cquery` but I have seamless configuration over 3 PCs, and one of them have different username. To prevent using absolute path, I d like to use environment variable in it. So I googled that, and tried to use `$USER` and `$HOME` but It just creates folder named like so.
```json
{
        "initializationOptions": {
                "cacheDirectory": "${env.HOME}/.cache/cquery"
        }
}
```

In the result I've ended up with a folder named `${env.HOME}` which contained cache. So how could I use my $HOME variable in initialization section? Or I'd like to drop settings.json entirely and configure everything in my .vimrc if possible.

**Comment by autozimu** [comment]
I'm not sure how much useful would it be outside this single use of cquery config.

Could you create an issue on cquery repo for requesting support of specifying `cacheDirectory`? i.e.,
```sh
cquery --cacheDirectory=/tmp/query
```

**Comment by andreyorst** [comment]
actually they've send me here. Though I've asked them about settings. json, because I was sure it belongs to cquery. I'll ask them again.

**Comment by autozimu** [comment]
See https://github.com/cquery-project/cquery/issues/717
