### ISSUE TITLE
Add an option to prevent textDocument/didChange notifications to the server?

### ISSUE THREAD

**Issue by TysonAndre** [autozimu/LanguageClient-neovim#484]
Reasons for requesting this:

- Language servers may have bugs analyzing incomplete ASTs or large numbers of notifications. Right now, they may crash without getting automatically restarted.
- Language servers may use up a lot of CPU.

- Also, I'm not sure how the throttling works. But, it looks as though if throttling is used, the client might not always send the change notification for the most recent edit, if the user stops typing (e.g. if the delay is 0.5 seconds, the actual state of the file might be 0.4 seconds before the typing stops?).
  I saw this a month ago, but it may have been fixed since then.

Proposed behavior:

1. (Long-term because it's in TODO.md): If the language server itself forbids change notifications in `textDocumentSync: TextDocumentSyncOptions | number`, don't send them.
2. If the user turns off change notifications, don't send them unless necessary
3. Otherwise, send them (the way this already does).

Note: In order for completion, go to definition, etc. to continue working properly, the client will probably need to force the change notification to be sent before specific requests or notifications (even if the user disabled change notifications).

The change seems like it would need to be made in src/languageclient.rs for `pub fn textDocument_didChange(&mut self, params: &Option<Params>) -> Result<()> {`

```rust
        // This feature request would require this to check user preferences,
        // whether or not the caller forced the change notification to be sent, etc.
        // before calling notify for textDocument/didChange  
        self.notify(
            Some(&languageId),
            lsp::notification::DidChangeTextDocument::METHOD,
            DidChangeTextDocumentParams {
                text_document: VersionedTextDocumentIdentifier {
                    uri: filename.to_url()?,
                    version: Some(version),
                },
                content_changes: vec![TextDocumentContentChangeEvent {
                    range: None,
                    range_length: None,
                    text,
                }],
            },
        )?;
```

**Comment by autozimu** [comment]
If you set `changeThrottle` to a max enough value, it's the same effect.
