### ISSUE TITLE
Error in header file with using clangd

### ISSUE THREAD

**Issue by arwtyxouymz** [autozimu/LanguageClient-neovim#495]
## Summary

Hi all!
Firstly i apologize my poor English and please laugh at me!

I use this plugin to develop my c++ app.
I develop it with the libraries, [vtk](https://www.vtk.org/) and integrate with `cmake` and I use this plugin with `clangd` for c/c++ language server.

I have the serious problem...
When i include the library header file, in my header file it becomes error while in my source file success to include.
It's strange isn't it?

I show you my strange problem pictures.
The left file is my header file, and the right one is my source file.
![2018-07-03 17 03 35](https://user-images.githubusercontent.com/16755660/42206748-04183558-7ee3-11e8-8c4a-953009399b08.png)

In addition, in header file, libraries functions aren't be complemented while in source file they are complemented.
In header file,
![2018-07-03 17 06 36](https://user-images.githubusercontent.com/16755660/42206903-7696fb5a-7ee3-11e8-9aee-288e5223a3fb.png)

In source file,
![2018-07-03 17 06 48](https://user-images.githubusercontent.com/16755660/42206910-7b0b74ea-7ee3-11e8-9317-f850b2b23963.png)

My `LanguageClient-neovim` configuration is here:
```vim
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = ['./install.sh']
hook_add = '''
    let g:LanguageClient_serverCommands = {
        \ 'c': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
        \ 'cpp': ['clangd', '-compile-commands-dir=' . getcwd() . '/build'],
    \ }
    let g:LanguageClient_hoverPreview = "Never"
    " not stop completion $ & /
    set hidden
    set signcolumn=yes
    nnoremap <F5> :call LanguageClient_contextMenu()<CR>
    " Or map each action separately
    nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
    nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
    nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''
```
Is this problem a `Language-Client` bug or is my configuration wrong?
I think CMake's settings(CMakeLists.txt) is not wrong because in source file correctly completion work.

Please help me!

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): nvim v0.3.0
- This plugin version (`git rev-parse --short HEAD`): 6c94b3e
- This plugin's binary version (`bin/languageclient --version`):0.1.93 6c94b3eda046207b03c93b57911ffa97fb9edb15
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [[here][min-init.vim]):]: [My Minimal init.vim](https://github.com/arwtyxouymz/dotfiles/blob/master/.config/nvim/min_init.vim)
- Language server link and version:
- Steps to reproduce the issue from clean state
    1. download [vtk](https://www.vtk.org/) and build + install it.
    2. clone [this repository](https://github.com/arwtyxouymz/temp) and `mkdir -p build && cd build && cmake .. `
    3. in project root, `nvim src/UI/Window.hpp`

## Current Behavior
In header file, error has occurred and libraries function completion doesn't work.

## Expected Behavior
In header file, error doesn't occur like source file above, and completion work.

**Comment by MartenBE** [comment]
I think this has to do with the fact that cmake only exports information for cpp files, not for headers, into `compile_commands.json` when using the `CMAKE_EXPORT_COMPILE_COMMANDS=ON` flag. This is a known issue and I am not sure if they will/can solve it (soon); I remember they discussed it on the mailing list of clangd, but I can't find it anymore.
I solved this by using compdb (https://github.com/Sarcasm/compdb), which appends the necessary information to the `compile_commands.json` for the header files.

An example of the files I use to set up projects can be found here (disclaimer: I'm not sure if it is best practice as I am not exactly an expert on CMake): https://github.com/MartenBE/gevorderde-algoritmen/tree/master/generic-project-files:

1) Put the files `CMakeLists.txt`, `CMakeLists.txt.in` and `generate_makefile.sh` in your project root (`.clang-format` is only necessary for formatting)
2) Add your cpp and header files in the `SOURCES` or `TEST_SOURCES` sets in `CMakeLists.txt` (`ADDITIONAL_INPUT_FILES` and `ADDITIONAL_TEST_FILES` only need to contains files you want to copy to the build directory when generating the makefiles, e.g. csv or json files or cetera)
3) Run `generate_makefile.sh` to start CMake and let it generate the makefiles

More examples can be found in the repo. `CMakeLists.txt.in` is only necessary to download and link GoogleTest when you specify source files in `TEST_SOURCES`, and does not need any changes

**Comment by arwtyxouymz** [comment]
@MartenBE 

Thanks! It worked!
I really hope cmake solve this problem.
