### ISSUE TITLE
Sharing the language server between multiple vim instances

### ISSUE THREAD

**Issue by xu-cheng** [autozimu/LanguageClient-neovim#497]
This is a feature request. I wonder if it is possible to share the language server between multiple vim instances. In my typical workflow, I use tmux to manage projects and open one file per vim instance. This works great since vim is fast. However, when using the LSP, such workflow will result to multiple language server processes created in the background. This causes high resources usage as some language server (e.g. cquery) is quite resource consuming.

Therefore, it would be beneficial if the LanguageClient-neovim only creates a single global language server instance and shares it between multiple vim instances.

Finally, thanks for your work on this project.

**Comment by wsdjeg** [comment]
@xu-cheng Nice idea, but if we open one file in two vim instances, how does language server deal with the situation?

**Comment by autozimu** [comment]
> one file in two vim instances

That's a very good point.

Anyway, with current implementation, it's pretty difficult to sharing languageclient instance as it is lunched as a subprocess of vim with redirected stdin, stdout, stderr.

It might eaiser tweak your settings so that language servers only got launched for specific projects.

**Comment by xu-cheng** [comment]
Sorry for the late response. I was busying on the other matters recently.

> one file in two vim instances

Why would this become a problem? Please noted vim does not allow editing same file by two instances. One of them must be in read-only mode.

> it's pretty difficult to sharing languageclient instance as it is lunched as a subprocess of vim with redirected stdin, stdout, stderr.

A better solution would be sharing language server instead of language clients. For example, if we want to support such feature inside a project (which would make more sense than sharing globally), we could have:
* Let each vim instance have its own language client.
* By default, the language server sharing is disabled. But users can configure the project settings to enable it.
* When the sharing is enabled, the language client checks if the language server is running. If not, starting the language server as a daemon process and communicating with it using either TCP or unix socket.
* Other language clients can also connect to that language server using TCP or unix socket.
* If all other vim instances are closed, the last vim instance will kill language server upon quitting. 

What do you think?

I think still this is still a valid request. Since some language server such as cquery eats too much RAM on my machine. Anyway, would it better if we open this issue and try to find a long term solution?

**Comment by autozimu** [comment]
The problem of multiple vim instances opening the same file is that the
in-buffer changes might be different, in this case, which change should the
language server pick?

Regarding your proposal of sharing language server, it is already possible
with tcp approach of server commands. It is missing the parts of managing
tcp servers, but I’m not indended to make this plugin more complex. With
this said, PRs are always welcome.

**Comment by untitaker** [comment]
I use https://github.com/pr2502/ra-multiplex for this
