### ISSUE TITLE
Provide a way to query analysis progress for RLS

### ISSUE THREAD

**Issue by euclio** [autozimu/LanguageClient-neovim#50]
This would be possible by using `textDocument/diagnosticsBegin` and `textDocument/diagnosticsEnd`.

I'd like to be able to write an airline extension that displays the progress of the analysis, like the status bar of the RLS vscode plugin.

From a quick googling it appears that these methods are RLS-specific.

**Comment by autozimu** [comment]
Right now, you can implement it like this,

Create a event handler in your plugin, e.g.,
```
func setRustAnalysisState(state: string)
```

Then make pull requests to this repo to actually trigger your event handler
```
textDocument_diagnosticsBegin()
textDocument_diagnosticsEnd()
```

I know that this suggested approach is not ideal, but I cannot think of any better solution given current implementation. I am thinking of restructure this project to make it easier for plugin development based on this, but haven't got time to do it yet.
