### ISSUE TITLE
Using LSP's range to define better text objects in Neovim

### ISSUE THREAD

**Issue by snoblenet** [autozimu/LanguageClient-neovim#507]
Language Servers can return a range (line and character number from the start of the function to the end). I'm wondering if this can be used to define better text objects in Neovim -- i.e. for sort inside function, jump to start of next function, etc etc.

**Comment by autozimu** [comment]
All the functionalities are provided by language servers and guided by the protocol.

Before the protocol adding this support, cannot make it happen in this plugin.

**Comment by snoblenet** [comment]
FYI The LSP protocol does currently define this. See the 'range' section in https://microsoft.github.io/language-server-protocol/specification
