### ISSUE TITLE
`rename` discards unsaved changes without warning

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#511]
Currently when you use `rename` all current changes are discarded, and the `rename` is applied. I don't think this should be the default. It usually happens accidentally and I need to undo everything. It is especially annoying if it affects a buffer which is currently not in a window, and you find out later that work was discarded.
I think there should be an option for the behavior of non-saved changes before a `rename`

1. Warn about unsaved changes, prompt for [s]ave, [d]iscard, [a]bort.
2. Discard changes buy default (current behavior)
3. Save before applying `rename`
4. Abort and jump to buffer with changes

Even better would of course be a `rename` working on buffers and not on the disk version of the file.

**Comment by autozimu** [comment]
It should already use buffer content whenever possible.

Can you provide detailed reproduction steps?

**Comment by autozimu** [comment]
Ping

**Comment by DerWeh** [comment]
Sorry for the slow response. I am currently away. As soon as I have time I will update the language client and test it against the newest version again. 

The problems occurred in combination with the `python-language-server`.

**Comment by DerWeh** [comment]
Sorry for the trouble, after making sure to use the latest version of the language client I can't reproduce the error anymore. I think this can be closed.
