### ISSUE TITLE
Helptext isn't installed alongside LanguageClient

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [autozimu/LanguageClient-neovim#515]
The title pretty much says it all:

```vim
" #### Languages
Plug 'autozimu/LanguageClient-neovim', {
 \ 'for': ['ocaml', 'reason'],
 \ 'branch': 'next',
 \ 'do': 'bash install.sh',
 \ }

Plug 'reasonml-editor/vim-reason-plus', {
 \ 'for': ['ocaml', 'reason'],
 \ }
```

I ran `:PlugInstall`, `:PlugUpdate`, and `:UpdateRemotePlugins`. `:call LanguageClient<tab>` shows that all the functions are available, but `:help LanguageClient` completes to … nothing!

I can read [`LanguageClient.txt`](https://github.com/autozimu/LanguageClient-neovim/blob/master/doc/LanguageClient.txt) on GitHub, but I'd prefer to have it locally. Feeling like a bit of an idiot right now, no idea how I screwed this up!

**Comment by autozimu** [comment]
That's strange.

Try running `:helptags ALL` to re-generate all help tags.
