### ISSUE TITLE
ElixirLS settings.json

### ISSUE THREAD

**Issue by bbtdev** [autozimu/LanguageClient-neovim#519]
## Summary

I have no idea if this is a LanguageClient-Neovim issue or it is the LSP ElixirLS, but I cannot disable a certain feature (dialyzer). The feature is disabled with:   "elixirLS.dialyzerEnabled": false and it works in the settings.json of vscode.

I tried to do the same in Neovim but no luck.

## Reproduction
- NVIM v0.3.0
- Plugin version: 473ad69
- Binary version: languageclient 0.1.101 bf1a22be00d69c7146a1ce276a6f648f1e297be9
- minimal init.vim:
```
set runtimepath+=/Users/bogdan/.cache/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('/Users/bogdan/.cache/dein')
  call dein#begin('/Users/bogdan/.cache/dein')
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  " -> Languages support
  call dein#add('https://github.com/sheerun/vim-polyglot')
  " LSP:
  call dein#add('autozimu/LanguageClient-neovim', {
        \ 'rev':'next',
        \ 'build': 'bash install.sh',
        \ })
  call dein#end()
  call dein#save_state()
endif
" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

let g:LanguageClient_serverCommands = {
    \ 'elixir': ['elixir-ls'],
    \ }

let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_loggingFile='/Users/bogdan/Temp/LC.log'

```
- Language server link : https://github.com/JakeBecker/elixir-ls/
- Steps to reproduce the issue from clean state
    1. nvim
    2. in an elixir project folder, open a file
    3. :copen, in a few seconds it will be full of dialyzer output

- My settings.json
```
{
  "elixirLS.dialyzerEnabled": false
}
```

- Logs (Paste or attach log file content):
https://gist.githubusercontent.com/bbtdev/7debe6ee8d7a9202afc6f75e5e9ce0d0/raw/c4eea038004049168314250ebaa827d31bd735f3/gistfile1.txt

**Comment by autozimu** [comment]
Please try settings,
```
{
    "elixirLS": {
        "dialyzerEnabled": false
    }
}
```

VSCode will make extra transformation of this settings while this plugin doesn't do it.

**Comment by bbtdev** [comment]
@autozimu Did not work :(
https://paste.ofcode.org/y8Sw7TjSgLmUMxC5VsBfpa

Found this: https://github.com/JakeBecker/elixir-ls/issues/91 and tried multiple variants but no luck

**Comment by bbtdev** [comment]
This works, I forgot to remove "ElixirLS". from ElixirLS.dialyzerEnabled. My appologies and thank you for the awesome plugin

```
{
    "elixirLS": {
      "dialyzerEnabled": false
    }
}
```
