### ISSUE TITLE
[Spec] doHover returns `MarkedString | MarkedString[]`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#52]
According to the [spec](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#hover-request), `doHover` will return a `MarkedString` rather than a plain string.

That means a response from a faithful server will be rendered as if double-escaped in LanguageClient-neovim.

![screenshot from 2017-06-03 17-45-51](https://cloud.githubusercontent.com/assets/2883231/26752522/a609b224-4884-11e7-847a-2b914800f857.png)

For example, when used with vetur-server and LCN, parenthesis are double escaped.

**Comment by autozimu** [comment]
Thanks for reporting.

I am not sure if I understand the issue clearly. Can you give a concrete
example of server response and actual rendered text?

As for one case, if the server returns markdown string and the rendered
text is as it is, then it seems working properly to me, as neovim cannot
render html yet and raw markdown format is still easy enough to read.

**Comment by HerringtonDarkholme** [comment]
For example, 
`test()`
will be sent as 
`test\\(\\)`
