### ISSUE TITLE
Support $HOME or ~ in g:LanguageClient_settingsPath

### ISSUE THREAD

**Issue by iven** [autozimu/LanguageClient-neovim#522]
## Summary

I'm trying to use global settings path of pyls, so I use this config:

```
let g:LanguageClient_settingsPath = '/Users/iven/.config/nvim/settings.json'
```

and it works fine, but when I try to use `$HOME` or `~`, it doesn't work:

```
let g:LanguageClient_settingsPath = '$HOME/.config/nvim/settings.json'
```

I'm using both Linux and macOS, so `$HOME` are not the same. I hope you can support it, thanks!

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):v0.3.0
- This plugin version (`git rev-parse --short HEAD`):736bbdf
- This plugin's binary version (`bin/languageclient --version`):0.1.101 bf1a22be00d69c7146a1ce276a6f648f1e297be9

**Comment by iven** [comment]
Update:

```
let g:LanguageClient_settingsPath = $HOME . '/.config/nvim/settings.json'
```

this works fine. But I still wish it can be supported natively.

**Comment by andreyorst** [comment]
>  But I still wish it can be supported natively.

This is native vim way of doing it. You concatenate two strings, and that's it.

**Comment by miuirussia** [comment]
use `expand` command:
```
let g:LanguageClient_settingsPath      = expand('~/.config/nvim/settings.json')
```

**Comment by darthdeus** [comment]
I know it's probably a matter of taste, but is `expand('~/...')` better than `$HOME . '/...'` or vice versa for some reason?

**Comment by andreyorst** [comment]
> I know it's probably a matter of taste, but is expand('~/...') better than $HOME . '/...' or vice versa for some reason?

From `:h expand()`:
```
		Expand() can also be used to expand variables and environment
		variables that are only known in a shell.  But this can be
		slow, because a shell may be used to do the expansion.  See
		|expr-env-expand|.
```

**Comment by iven** [comment]
As far as I know, I can use `$HOME` in `undodir`, also `~` to config plugins like startify and vim-plug. Is it really better to use `expand()`?

**Comment by autozimu** [comment]
undodir etc are options. They’re quite different with variables.

I haven’t check how plug-vim implement that, might be using expand
internally through.
