### ISSUE TITLE
How change signText color?

### ISSUE THREAD

**Issue by arwtyxouymz** [autozimu/LanguageClient-neovim#524]
## Summary

Hi, I'm developing c/c++ application by using this plugin and `clangd`.
I'm confusing about signText color because all they are black!
![2018-07-19 12 19 14](https://user-images.githubusercontent.com/16755660/42919680-004febc4-8b4e-11e8-9c28-541def9de174.png)
It's crazy isn't it?

I knew this plugin uses `ale` signs from document

> {
>     1: {
>         "name": "Error",
>         "texthl": "ALEError",
>         "signText": "✖",
>         "signTexthl": "ALEErrorSign",
>     },
>     2: {
>         "name": "Warning",
>         "texthl": "ALEWarning",
>         "signText": "⚠",
>         "signTexthl": "ALEWarningSign",
>     },
>     3: {
>         "name": "Information",
>         "texthl": "ALEInfo",
>         "signText": "ℹ",
>         "signTexthl": "ALEInfoSign",
>     },
>     4: {
>         "name": "Hint",
>         "texthl": "ALEInfo",
>         "signText": "➤",
>         "signTexthl": "ALEInfoSign",
>     },
> }

So I tried to use only `ale` and singText color is correctly red.
![2018-07-19 12 26 27](https://user-images.githubusercontent.com/16755660/42919912-34518b0c-8b4f-11e8-9c23-4fae4d7d6453.png)

why?
How can i change the color of signText?

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`): `v0.3.0`
- This plugin version (`git rev-parse --short HEAD`): `c01b4ef`
- This plugin's binary version (`bin/languageclient --version`): `0.1.97 77e90bffbe47ed26af1e37e6a8676f41a93fa1c7`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]): [this](https://github.com/arwtyxouymz/dotfiles/blob/master/.config/nvim/min_init.vim)
- Language server link and version: `LLVM verson 6.0.1`
- Steps to reproduce the issue from clean state
    1. copy my `min_init.vim` to your local machine
    2. create or open a cpp file like `nvim test.cpp`
    3. input code which occurs error

## Current Behavior
all signText(error, warning, info, message) color is black.

## Expected Behavior
all signText color is same with `ale` plugin.
Or i wanna know how to set signText color.

**Comment by autozimu** [comment]
Sign text highlight group is controlled by `signTexthl`. e.g., 

```vim
let g:LanguageClient_diagnosticsDisplay = {
    \     1: {
    \         "name": "Error",
    \         "texthl": "ALEError",
    \         "signText": "✖",
    \         "signTexthl": "ErrorMsg",
    \     },
    \     2: {
    \         "name": "Warning",
    \         "texthl": "ALEWarning",
    \         "signText": "⚠",
    \         "signTexthl": "ALEWarningSign",
    \     },
    \     3: {
    \         "name": "Information",
    \         "texthl": "ALEInfo",
    \         "signText": "ℹ",
    \         "signTexthl": "ALEInfoSign",
    \     },
    \     4: {
    \         "name": "Hint",
    \         "texthl": "ALEInfo",
    \         "signText": "➤",
    \         "signTexthl": "ALEInfoSign",
    \     },
    \ }
```

Will highlight error sign text using highlight group `ErrorMsg`, instead of default `ALEErrorSign`.
