### ISSUE TITLE
Purescript support

### ISSUE THREAD

**Issue by dakom** [autozimu/LanguageClient-neovim#527]
I tried the plugin with the [Purescript Language Server](https://github.com/nwolverson/purescript-language-server) but could not get it to work.

All the purescript stuff is installed, and I configued LanguageClient-neovim like:

```
let g:LanguageClient_serverCommands = {
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'typescript': ['javascript-typescript-stdio'],
    \ 'purescript': ['purescript-language-server', '--stdio'],
    \ }
```

But it does not seem to work. The plugin _does_ work with typescript.

Note that running `purescript-language-server --stdio` on its own in the same folder starts the server and reports:

```
Content-Length: 113

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"PureScript Language Server started"}}
```

**Comment by autozimu** [comment]
> But it does not seem to work. The plugin does work with typescript.

What does this mean?

What's the log file content?

**Comment by dakom** [comment]
sorry - I'm new to vim... where can I find the log file?

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

**Comment by autozimu** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/045fd0c52bc434439347a68c1f85276687eeb5e5/min-init.vim#L21

**Comment by dakom** [comment]
[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2212519/LanguageClient.log)

**Comment by dakom** [comment]
Oh sorry that's without the min-config... one sec

**Comment by dakom** [comment]
okay here's the file (replaced the rust example with purescript... also LanguageServer.log is empty):

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2212543/LanguageClient.log)

**Comment by dakom** [comment]
Hmm the fix for ALE was passing `--stdio --config {}` to the startup script. I tried setting the server commands:
```
'purescript': ['purescript-language-server', '--stdio', '--config', '{}']
```

But it didn't work. I think I'm also getting [ReadErrors] with :f and this enabled (if I'm reading it correctly).

Also, when I do this I am not getting any LanguageClient.log output

**Comment by autozimu** [comment]
I tested it locally and seems all the messages are passing down to the server, it's that the server always returns null in response body.

Closing at the moment as it seems to be a server side issue. Feel free to reopen if it is found to be this this client issue.

**Comment by sriharshachilakapati** [comment]
Sorry for bumping an old thread, but I've got this working. I've made a separate support plugin which is dependent on this one to add PureScript support and some nice utility functions.

Please take a look at https://github.com/sriharshachilakapati/vimmer-ps/
