### ISSUE TITLE
How can I turn off autocomplete?

### ISSUE THREAD

**Issue by steelbluelee** [autozimu/LanguageClient-neovim#528]
I'm using scala + ensime + neovim + deoplete. 
And I installed this LanguageClient-neovim + scala LanguageServer.
It is awesome. But ensime + deoplete doesn't work. I guess that
vim try to auto-complete using deoplete + LanguageClient-neovim. But
Scala LanguageServer I'm using doesn't support auto completiion.
How can I turn off autocomplete?

**Comment by autozimu** [comment]
Try
```vim
call deoplete#custom#option('ignore_sources', {
            \ 'scala': ['LanguageClient'],
            \ })
```

**Comment by steelbluelee** [comment]
@autozimu Thank you. I tried it already. But failed. Anyway, I will try other options.
