### ISSUE TITLE
Language server ruby exited unexpectedly: Unable to read from language server

### ISSUE THREAD

**Issue by bbtdev** [autozimu/LanguageClient-neovim#529]
# Issue
First sign that something is wrong is that I don't get any autocomplete suggestions. After a minute I get: Language server ruby exited unexpectedly: Unable to read from language server.

# Reproduce
Go to a rails project folder: neovim and open some *.rb files

# Log
https://gist.githubusercontent.com/bbtdev/602b8dccf987013b3239e175f3cdfb0a/raw/e66fe5b6d3ea5412b0443ad8fd4a25c22792246d/languageclient-neovimlog

# Vimrc
```
set runtimepath+=/Users/bogdan/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/Users/bogdan/.cache/dein')
  call dein#begin('/Users/bogdan/.cache/dein')
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('autozimu/LanguageClient-neovim', {
       \ 'rev':'next',
       \ 'build': 'bash install.sh',
       \ })

  call dein#end()
  call dein#save_state()
endif

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

" LanguageClient_neovim:
" " LSPs setup "
 let g:LanguageClient_serverCommands = {
       \ 'elixir': ['elixir-ls'],
       \ 'ruby': ['solargraph', 'stdio'],
       \ }
" " LSPs settings "
 let g:LanguageClient_loadSettings = 1
 let g:LanguageClient_settingsPath =
        \ ".vim/settings.json"
" " debugging "
 let g:LanguageClient_loggingLevel='DEBUG'
 let g:LanguageClient_loggingFile='/Users/bogdan/Temp/LC.log'
```

**Comment by autozimu** [comment]
Please report this to ruby language server.

The server shall not crash/quit at any circumstances unless client send request for exit explicitly.

(This bug report doesn't follow bug reporting requirements. Closing at the moment.)
