### ISSUE TITLE
Cannot start jdtls language server

### ISSUE THREAD

**Issue by raaffaaeell** [autozimu/LanguageClient-neovim#530]
## Summary

Hello, I'm trying to get this plugin work in vim (latest version) with a Java language server (jdtls)

## Reproduction
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 20 2018 09:46:12)
- This plugin version languageclient 0.1.102

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):

 set hidden
 46 let g:LanguageClient_loadSettings = 1
 47 let g:LanguageClient_serverCommands = {
 48     \ 'java': ['jdtls'],
 49     \ }
 50
 51 nnoremap <F5> :call LanguageClient_contextMenu()<CR>
 52 " Or map each action separately
 53  nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
 54  nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
 55  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

My jdtls executable is a copy paste from the wiki (except the jar version, I built it from source). I can start the server with the executable but when I open a .java file with vim nothing happens, if I try to run the command "LanguageClientStart" it gives me an error "No such file or directory (os error 2)".

I tried to look for logs in the tmp folder but I cant see any related to the languageclient.

Edit: Found a way to get a log

## Log

1   14:19:51 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[!!get(g:, 'LanguageClient_autoStart', 1), get(g:, 'LanguageClient_serverCommands', {}), get(g:, 'Langua
    geClient_selectionUI', v:null), get(g:, 'LanguageClient_trace', v:null), get(g:, 'LanguageClient_settingsPath', '.vim/settings.json'), !!get(g:, 'LanguageClient_loadSettings', 1), get(g:, '
    LanguageClient_rootMarkers', v:null), get(g:, 'LanguageClient_changeThrottle', v:null), get(g:, 'LanguageClient_waitOutputTimeout', v:null), !!get(g:, 'LanguageClient_diagnosticsEnable', 1)
    , get(g:, 'LanguageClient_diagnosticsList', 'Quickfix'), get(g:, 'LanguageClient_diagnosticsDisplay', {}), get(g:, 'LanguageClient_windowLogMessageLevel', 'Warning'), get(g:, 'LanguageClien
    t_hoverPreview', 'Auto'), get(g:, 'LanguageClient_completionPreferTextEdit', 0), has('nvim')]"],"id":4}
  1 14:19:51 INFO reader-main src/vim.rs:386 <= None {"id":4,"jsonrpc":"2.0","result":[1,{"java":["jdtls"]},null,null,".vim/settings.json",1,null,null,null,1,"Quickfix",{},"Warning","Auto",0,0]
    }
  2 14:19:51 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["[get(g:, 'LanguageClient_diagnosticsSignsMax', v:null)]"],"id":5}
  3 14:19:51 INFO reader-main src/vim.rs:386 <= None {"id":5,"jsonrpc":"2.0","result":[null]}
  4 14:19:51 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","method":"eval","params":["get(g:, 'loaded_fzf')"],"id":6}
  5 14:19:51 INFO reader-main src/vim.rs:386 <= None {"id":6,"jsonrpc":"2.0","result":1}
  6 14:19:51 WARN main src/languageclient.rs:2091 Failed to start language server automatically. No such file or directory (os error 2)
  7 14:19:51 INFO main src/languageclient.rs:2096 End languageClient/handleBufReadPost
  8 14:19:51 INFO main src/languageclient.rs:2153 Begin languageClient/handleCursorMoved

**Comment by autozimu** [comment]
Should use absolute path, e.g.,
```vim
let g:LanguageClient_serverCommands = {
            \ 'java': ['/usr/local/bin/jdtls'],
            \ }
```
