### ISSUE TITLE
Language server is not running for: javascript

### ISSUE THREAD

**Issue by ericmccarthy7** [autozimu/LanguageClient-neovim#531]
## Summary

All attempts to use javascript completion are resulting in a 'not running' error. I have verified that the binary is on my path and works. My init.vim is correctly loaded and the plugin is correctly installed.

## Reproduction
- NVIM v0.3.0-dev
- This plugin version: 6480ffd
- This plugin's binary version: languageclient 0.1.102
- Minimal vimrc content:
```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
                        \ 'branch': 'next',
                        \ 'do': 'bash install.sh',
                        \ }

call plug#end()

autocmd BufReadPost *.rs setlocal filetype=rust

let g:LanguageClient_serverCommands = {
                        \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
                        \ 'javascript': ['javascript-typescript-stdio'],
                        \ }

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_serverStderr = '/tmp/LanguageServer.log'
```
- Language server link and version: https://github.com/sourcegraph/javascript-typescript-langserver 2.10.0
- Steps to reproduce the issue from clean state
    1. Create javascript file
    2. Try completion/definition etc.
- Logs (Paste or attach log file content):
```
00:31:06 INFO main src/languageclient.rs:1684 Begin textDocument/didChange
00:31:06 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename] = [String(""), String("javascript"), String("/home/eric/Documents/programming/vue/test/test.js")]
00:31:06 INFO main src/languageclient.rs:46 gather_args: [Text] = [Array([String("console"), String("")])]
00:31:06 INFO main src/languageclient.rs:1708 Texts equal. Skipping didChange.
00:31:06 INFO main src/languageclient.rs:924 Begin textDocument/typeDefinition
00:31:06 INFO main src/languageclient.rs:46 gather_args: [Buftype, LanguageId, Filename, Line, Character, GotoCmd, Handle] = [String(""), String("javascript"), String("/home/eric/Documents/programming/vue/test/test.js"), Number(0), Number(0), Null, Bool(true)]
00:31:06 INFO main src/vim.rs:90 => Some("javascript") {"jsonrpc":"2.0","method":"textDocument/typeDefinition","params":{"position":{"character":0,"line":0},"textDocument":{"uri":"file:///home/eric/Documents/programming/vue/test/test.js"}},"id":8}
00:31:06 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"Language server is not running for: javascript"},"id":2}
```
## Current Behavior
All attempts to use language server are resulting in the above error (Language server is not running for: javascript)

## Expected Behavior
Completion/results

**Comment by h-michael** [comment]
@ericmccarthy7  What kind of FileType that you edited ?

**Comment by ericmccarthy7** [comment]
@h-Michael just a regular .js file. FileType: javascript

**Comment by autozimu** [comment]
Try use absolute path for the server commands,
```
\ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
```
(Update with your own path.)

**Comment by h-michael** [comment]
`00:31:06 INFO main src/vim.rs:90 => None {"jsonrpc":"2.0","error":{"code":-32603,"message":"Language server is not running for: javascript"},"id":2}`

It seems to me that javascript-typescript-stdio process is not running.
Can run that process from vim runtime path?

**Comment by ericmccarthy7** [comment]
@autozimu @h-michael yep seems like a vim runtime path problem... manually hardcoding the path worked. Strange because javascript-typescript-stdio is on my system path, and I run nvim from the same env.

Thanks very much for your help!
