### ISSUE TITLE
Add the ability to disable the project root message when starting up neoVim

### ISSUE THREAD

**Issue by dylan-chong** [autozimu/LanguageClient-neovim#532]
When I start up Neo Vim language client gives me a message saying `LanguageClient project root: ...`That I have to manually press enter to dismiss. This is rather annoying.

Note that I also have this set

    let g:LanguageClient_windowLogMessageLevel = 'Error'

**Comment by dylan-chong** [comment]
Are you sure this was fixed @autozimu ? I have tested it and it still occurs on 0fe72bb973953fa2c9e619d35e070910339058bf

**Comment by autozimu** [comment]
It’s not adding another configuration, but the message is made such that it
shall not trigger hit-enter prompt.

**Comment by dylan-chong** [comment]
yup. I saw the code. The project root message still comes up

**Comment by autozimu** [comment]
Did you get the latest binary or you build it yourself? Can you take
screenshot of the prompt?

**Comment by dylan-chong** [comment]
I have upgraded again to the latest released binary. 

Unfortunately my startup prompt has some colour issues so i included the :messages log below

<img width="834" alt="screen shot 2018-07-27 at 10 44 55 pm" src="https://user-images.githubusercontent.com/17482349/43316846-c8912cdc-91ee-11e8-886a-240511d554a1.png">

<img width="820" alt="screen shot 2018-07-27 at 10 45 05 pm" src="https://user-images.githubusercontent.com/17482349/43316850-cabeafc0-91ee-11e8-927c-e05c66f31dc3.png">

**Comment by autozimu** [comment]
Obviously the project root message is shortened to avoid hit-enter.

The over-long message is the error level log message, which at the moment cannot be suppressed. It might be much easier for you to fix the errors.

**Comment by l29ah** [comment]
The message prevents me to see vim's message about the file name, length and the place of the first symbol that it doesn't like encoding-wise. How do i disable it?
