### ISSUE TITLE
Go to document symbol doesn't work when the symbol contains bad symbols

### ISSUE THREAD

**Issue by Coffei** [autozimu/LanguageClient-neovim#534]
## Summary
Go to document symbol doesn't work when some symbols are present in the item.

Working on Elixir files, I found the go-to-document-symbol doesn't work if the item (usually function definition) contains one of the following symbols: `< ` `:` (not a complete list, just those I found).
Note the document symbol list is constructed well, all items are present and even the shown line numbers are OK, just navigating to them doesn't work sometimes. I am using fzf for item selection.

## Reproduction
- vim version: 8..1
- This plugin version: latest in `next` branch (`8acdc38`)
- This plugin's binary version (`bin/languageclient --version`):  0.1.89
- Minimal vimrc content: I was able to reproduce with the following
```
so ~/.vim/plugins.vim
syntax on
filetype plugin indent on
let g:LanguageClient_serverCommands = {
    \ 'elixir': ['elixir-ls'],
    \ }
```
where `elixir-ls` is the binary of the language server mentioned below

- Language server link and version:  Elixir LS server: https://github.com/JakeBecker/elixir-ls at master
- Steps to reproduce the issue from clean state
    1. create new elixir project with `mix new test`
    2. create new source under `lib/`, the following file is sufficient
```
defmodule Testing.Test do
  def aaa(<<"coolish", _rest::binary>>) do
    nil
  end

  def bbb() do
    nil
  end

  def ccc(%{id: id}) do

  end
end
```
    3. Try navigating to `aaa`, `bbb` and `ccc` via `LanguageClient_textDocument_documentSymbol()`. While `bbb` works fine, both `aaa` and `ccc` don't work, the cursor doesn't move. You can also try removing the `<` and `:` symbols and observe it starts working.

- Logs (Paste or attach log file content):
Not sure what logs to attach, let me know which logs are needed.

## Current Behavior
When a document symbol is selected the cursor stays at the same place.

## Expected Behavior
When a document symbol is selected the cursor should move to the selected symbol.

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by Coffei** [comment]
Thank you for the quick fix and for this awesome project!
