### ISSUE TITLE
'FZF not loaded!' error when trying to show code action.

### ISSUE THREAD

**Issue by QuinnFreedman** [autozimu/LanguageClient-neovim#535]
## Summary

I get the error `FZF not loaded!` whenever I try to show code action. This happens whether fzf is installed or not. Is there a way to set it to not use fzf? Or is there something I have to do with fzf to make it load?

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):
```
$ nvim --version
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```
- This plugin version (`git rev-parse --short HEAD`): `6480ffd`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.102 045fd0c52bc434439347a68c1f85276687eeb5e5`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):
```
call plug#begin(has('win32') ? '$LOCALAPPDATA/nvim' : '~/.config/nvim')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

Plug 'junegunn/fzf.vim'

call plug#end()

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ }

noremap <silent><F3> :call LanguageClient_textDocument_codeAction()<CR>
```

- Language server link and version: `rls-preview 0.127.0-stable (d2ade31 2018-05-08)`
- Steps to reproduce the issue from clean state
    1. Open a rust file
    2. Press &lt;F3>

## Current Behavior
Error: `FZF not loaded!`

This error happens regardless of whether fzf is installed or not.

## Expected Behavior
For the menu to open using a built-in list (like it can with `LanguageClient_contextMenu()`) or clear instructions about how to make fzf work.

**Comment by QuinnFreedman** [comment]
I sort-of fixed this. According to the fzf docs, you should either use `Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }` to install fzf automatically, or, if it's already installed fro the command line (e.g. with homebrew) then use `Plug '/usr/local/opt/fzf'` (or whatever the path to the installation is). However, this still feels buggy in that:

a. Unlike the rest of LanugageClient features, code action *requires* the "optional" dependency `fzf`
b. Even when there is actually no action that can be performed, it still opens up an empty fzf search buffer with nothing in it instead of just saying that nothing can be done

**Comment by autozimu** [comment]
This is working as expected.

For code actions feature, it requires user to select one item from the list and then apply that action, which is not available with stock vim/neovim.

**Comment by purpleP** [comment]
@autozimu You solve the same problem when showing menu differently by showing numbered menu items, which is a very sane fallback.
