### ISSUE TITLE
Run a single instance of cquery for both c and cpp filetypes

### ISSUE THREAD

**Issue by dimbleby** [autozimu/LanguageClient-neovim#536]
I have a large codebase with mixed C and C++ code.  My vimrc includes this:

```
let g:LanguageClient_serverCommands = {
    \ 'c': ['cquery', '--init={"cacheDirectory": "' . $HOME . '/.cache/cquery/"}'],
    \ 'cpp': ['cquery', '--init={"cacheDirectory": "' . $HOME . '/.cache/cquery/"}'],
    \ }
```

The consequence is that if I open first a .c and then a .cpp file, I get *two* cquery instances.  Which is wasteful.

Is there any way for me to configure that c and cpp files should use the *same* language server?

**Comment by autozimu** [comment]
Can you try setting c files to be cpp? e.g.,
```vim
autocmd BufNewFile,BufRead *.c setlocal filetype=cpp
```

**Comment by dimbleby** [comment]
Well, that would do it I suppose!  I'm not sure that I want vim to be treating c and cpp files identically (but I'm also not sure why not).

Anyway, I guess the answer is that there's no special support in the LanguageClient for this, which is totally fair enough.  

Please feel free to close this issue out - or to leave it open if you think you might want to do something with it.

**Comment by autozimu** [comment]
No clear way of supporting this feature from LanguageClient-neovim. Closing for now.
