### ISSUE TITLE
RLS: gotoDefinition into std libs

### ISSUE THREAD

**Issue by liuchengxu** [autozimu/LanguageClient-neovim#537]
> If you are reporting a bug, please read following FAQ first. If you are
requesting other types of issue, please ignore.

- Did you upgrade to latest plugin version?
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?

## Summary

Since https://github.com/rust-lang-nursery/rls/issues/227 has been fixed not long ago, RLS seems to be able to jump into std libs, but I can't make it work in my case. Is there any extra settings I need to add to settings.json? 

## Reproduction
- neovim/vim version (`nvim --version` or `vim --version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2018 19:20:41)
macOS version
Included patches: 1-200
```
- This plugin version (`git rev-parse --short HEAD`): 8603edb
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.102 045fd0c52bc434439347a68c1f85276687eeb5e5
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]):
```vim
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }
let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_serverStderr = '/tmp/LanguageServer.log'

nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
```
- Language server link and version:
- Steps to reproduce the issue from clean state
    1. `:call LanguageClient#textDocument_definition()` on  any std lib.
- Logs (Paste or attach log file content):

## Current Behavior
`Not found!` when gotoDefinition into std libs.

## Expected Behavior
I can jump into the correct file, even the std lib.

> Please understand the more detailed information provided, the sooner a issue
could be resolved. Low quality bug reports might be closed directly.)

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by KillTheMule** [comment]
Works for me, although you can't go any further when inside the stdlib (that's a different problem). Are you sure you're using the correct version of RLS?

**Comment by liuchengxu** [comment]
Thank you! @KillTheMule  Just realized that I'm using the stable toolchain, which still has this issue. Switching to the nightly saved my day!
