### ISSUE TITLE
call LanguageClient_textDocument_rename() doesn't work!

### ISSUE THREAD

**Issue by yedhink** [autozimu/LanguageClient-neovim#538]
> If you are reporting a bug, please read following FAQ first. If you are
requesting other types of issue, please ignore.

- Did you upgrade to latest plugin version?  yes. i did
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. yes it's latest version
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]? yes. it show's "ok" in both cases

## Summary

(placeholder)

## Reproduction
- Arch Linux version : 4.17.10-1-ARCH
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.0-1304-gf711b6351
- This plugin version (`git rev-parse --short HEAD`):ad629b1
- This plugin's binary version (`bin/languageclient --version`):languageclient 0.1.105
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-init.vim]): [minimal vimrc link](https://pastebin.com/sMXkaupC)
- Language server link and version: javascript-typescript-stdio = 2.10.0  
javascript-typescript-langserver = 2.10.0  
- Steps to reproduce the issue from clean state
    1. `nvim -u min-init.vim new.js`  [copy my min-init from the link provided above]
    2. try to rename a variable using : `call LanguageClient_textDocument_rename()`
    3. see if all occurences of the vairable has been renamed(which didn't in my case)
- Logs (Paste or attach log file content):  
[LanguageClient.log](https://pastebin.com/JEps49H4)  
LanguageServer.log -> only "DEBUB Exit notification" was present

## Current Behavior
Note that since i had installed javascript-typescript-langserver locally, i did change the default location to `~/node_modules/.bin/javascirpt-typescript-stdio` in the `min-init.vim` and changed the vim plugin manager from Vim-Plug to `dein`(cause i have been using that till now).   
sometimes when trying to replace variable occureces i get `"channel timed out" `error. sometimes nothing actually happens and after inputting the new replacement name no replacement takes place. interestingly the omni completions are spot on and working as expected!! [watch this gif to get a better idea of the error. pls watch till end
](https://imgur.com/3xpvYn6)
## Expected Behavior
rename all occurence of the declared variable in the current code without errors and this much hassle.

> Please understand the more detailed information provided, the sooner a issue
could be resolved. Low quality bug reports might be closed directly.)

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
[min-init.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-init.vim

**Comment by whitebyte** [comment]
I have this issue too. Not sure if it's related to the client part though. It happens on big projects (escpecially if you don't exclude node_modules from scanning). Even if it's a relult of javascript-typescript-langserver lack of performance, it would be nice to have some meaningful error message. 

Sometimes stopping and then restaring LanguageClinet helps, sometimes not.

**Comment by autozimu** [comment]
This is same cause as https://github.com/autozimu/LanguageClient-neovim/issues/546.

I'm closing this one and use https://github.com/autozimu/LanguageClient-neovim/issues/546 for track.
