### ISSUE TITLE
[Feature request] Allow disabling of highlighting of gutter

### ISSUE THREAD

**Issue by aaronbabaron** [autozimu/LanguageClient-neovim#543]
I find the gutter highlighting very unsightly and would rather have the errors themselves highlighted. Is there a way to already do this, or is this not implemented?
<img width="122" alt="screen shot 2018-08-01 at 12 00 26 pm" src="https://user-images.githubusercontent.com/15972357/43542690-8f5de17a-9582-11e8-8766-6473ee0bb69e.png">

**Comment by aaronbabaron** [comment]
I'm an idiot, there's a vim way of doing this

**Comment by balta2ar** [comment]
Could you share that way for users who find your issue later?

**Comment by aaronbabaron** [comment]
Sure not a problem.

Just had to add this one line in my vimrc below my colorscheme:

highlight clear SignColumn
