### ISSUE TITLE
No completion for #include with cquery

### ISSUE THREAD

**Issue by sakhnik** [autozimu/LanguageClient-neovim#547]
- Did you upgrade to latest plugin version?
> Yes :thumbsup:
- Did you upgrade to/compile latest binary? Run shell command `bin/languageclient --version` to get its version number.
> `languageclient 0.1.106`
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
> Yes, it's all OK
- Did you check [troubleshooting]?
> Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
While completion of namespaces, classes, functions and fields works well and stable, I can't get completion of `#include`. Despite cquery responding correctly:
```json
{"jsonrpc":"2.0","id":213,"result":{"isIncomplete":true,"items":[{"label":"#include <alpm.h>","kind":17,"detail":"alpm.h","sort
Text":"...........","insertText":"","insertTextFormat":1,"textEdit":{"range":{"start":{"line":1,"character":0},"end":{"line":1,
"character":12}},"newText":"#include <alpm.h>"}},{"label":"#include <alloca.h>","kind":17,"detail":"alloca.h","sortText":".....
...../","insertText":
```

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
> NVIM v0.3.2-36-g9c0c5e8bc
- This plugin version (`git rev-parse --short HEAD`):
> 94ca492
- This plugin's binary version (`bin/languageclient --version`):
> `languageclient 0.1.106`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```vim
set rtp+=~/.vim/plugged/LanguageClient-neovim

let g:LanguageClient_serverCommands = {
    \ 'cpp': ['cquery', '--language-server', '--log-file=/tmp/cq.log', '--record=/tmp/cquery'],
    \ }
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath = '~/.vim/cquery.json'

set completefunc=LanguageClient#complete
```
Contents of `~/.vim/cquery.json`:
```json
{
  "initializationOptions": {
    "cacheDirectory": "/tmp/cquery-cache"
  }
}
```
- Language server link and version:
> `cquery v20180718-2` (but it didn't work with any)

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. `mkdir test; cd test`
1. Execute [cquery-init](https://github.com/sakhnik/dotfiles/blob/master/src/.bin/cquery-init) or take any other
1. Start neovim, `nvim -u init.vim test.cpp` ...
1. Type `#include <al`
1. Invoke autocompletion `<c-x><c-o>`
1. See error: no completions
1. Observe `/tmp/cquery.out` for cquery responded with lots of headers
1. (Optional) Make sure completion works otherwise

## Current behavior
`#include` headers aren't completed by the plugin

## Expected behavior
A list of headers starting from `al` is offered for completion: `algorithm`, `alsa.h` etc

## Screenshots
~~If applicable, add screenshots to help explain your problem.~~

## Additional context
I should admit that this is so far the best LS plugin for vim.

**Comment by sakhnik** [comment]
Here is the debug log of the session: [lc.log](https://github.com/autozimu/LanguageClient-neovim/files/2259802/lc.log)
1. Tried to complete `#inc`
1. Tried to complete `#include <al`

**Comment by autozimu** [comment]
The problem boils down to the facts that
1. cquery returns completion starting line beginning.
1. this plugin/vim only supports completions starting at word beginning.
