### ISSUE TITLE
Question: does auto-completion suppose to work with deoplete?

### ISSUE THREAD

**Issue by cprn** [autozimu/LanguageClient-neovim#548]
I have Shougo/deoplete + LanguageClient-neovim + felixfbecker/php-language-server installed on Neovim. Auto-completion works fine when called from command mode. Is it supposed to also display auto-complete suggestions out of the box in deoplete or am I missing something? I can investigate further on my own, just want to make sure I'm not chasing a ghost.

**Comment by Jesse-Bakker** [comment]
It is supposed to do that, yes. Is deoplete running (it does not start by default. Add `let g:deoplete#enable_at_startup = 1` to your neovim config to enable)?

**Comment by autozimu** [comment]
It should work with deoplete.

**Comment by cprn** [comment]
Yes, deoplete is running. Thank you, it was my config, obviously.
