### ISSUE TITLE
[Suggestion] Ignore null RPC result

### ISSUE THREAD

**Issue by HerringtonDarkholme** [autozimu/LanguageClient-neovim#55]
Sometimes a language server will return  `{"id": 12, "result": null}`. Though spec itself does not allow null result, some server will return null when no info is available. For example, a `Hover` request on an empty line will return a null result.

It is better if language client can be more lenient on nullable result.

**Comment by autozimu** [comment]
Fixed in https://github.com/autozimu/LanguageClient-neovim/commit/de62f6b0bf61c4043f834e0252d618ddd6916b55

**Comment by HerringtonDarkholme** [comment]
Thanks!
