### ISSUE TITLE
[question] What's the best way to configure autoformat on save for Rust?

### ISSUE THREAD

**Issue by balta2ar** [autozimu/LanguageClient-neovim#550]
Hi. I'm trying language server in neovim and I can't get autoformatting to work well with saving functionality for Rust. I have the following setup:
```vim
autocmd BufWritePre *.py :call LanguageClient#textDocument_formatting()
autocmd BufWritePre *.rs :call LanguageClient#textDocument_formatting()
```
When I save file using `:w` in Python, everything is OK. In Rust the autoformatting also runs OK, but the buffer is still marked as modified in neovim after save. Is there a way to run autoformatting first and make sure it completes, and only then save the file?

My language server config:
```vim
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'python': ['pyls'],
    \ }
```

**Comment by autozimu** [comment]
See https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L51

`LanguageClient#textDocument_formatting()` function and most other functions are async calls.

**Comment by dead10ck** [comment]
@autozimu I'm not sure if that link is out of date, but it wasn't clear to me if it was supposed to include information about how to configure vim to do automatic formatting on save. Do you have a recommendation?

**Comment by OrangeTux** [comment]
@dead10ck I solved it this way. 

```
set formatexpr=LanguageClient#textDocument_rangeFormatting_sync()
autocmd BufWritePre * :normal ggVGgq
```

By default Vim can format your files by visual selecting the lines you want to apply format to and then press `gq`. Without extra configuration Vim's has a default formatter.

The first line of the config configures Vim to use the `LanguageClient#textDocument_rangeFormatting_sync()` formater.

The second line will select the whole file, that is `gg V G`, and the format the selection, using `gq`.

**Comment by weigangd** [comment]
@OrangeTux 's solution also solved it for me but made my saving process really slow for some reason.

I could fix it with just writting
`autocmd BufWritePre *.rs :call LanguageClient#textDocument_formatting_sync()`
in my init.vim file.
