### ISSUE TITLE
Request: dont fill quickfix window without the user explicity enabling it

### ISSUE THREAD

**Issue by dylan-chong** [autozimu/LanguageClient-neovim#554]
this plugin fills the quickfix window with messages, with conflicts with plugins like easygrep, fzf (selecting multiple files) and others that use the quickfix window.

eg

1. i select multiple files with fzf, and press enter. the quickfix window opens with the list of files
2. i navigate to the first file and then edit it so it doesnt compile. langaugeclient alters the quickfix window contents
3. i cant go to my next file :(

the reason it should be disabled by default is that its not obvious what plugin is causing the seemingly random quickfix list modifications.

**Comment by stefansonski** [comment]
Considering that the errors shown are in context of the current window, wouldn't it be correct to use the location list instead of the quickfix window? This way it would be possible to use commands as `vimgrep`.

**Comment by jeffvandyke** [comment]
I noticed it was doing this too, and it was one of the first tweaks I made. AFAIK, ALE doesn't use the Quickfix list either, so I think it would make sense for this not to as well by default - Location list is good enough, especially as it's per-window.

**Comment by dylan-chong** [comment]
Do any other plugins use location list? Or would there be a reasonable reason to use it for another plugin. If so I think it should be off by default

**Comment by autozimu** [comment]
Sorry for this inconvenience.

But I believe it is too late to change the default setting at this point.

https://github.com/autozimu/LanguageClient-neovim/blob/232774c012aa56d495a29dcae3fbe112f8d6c309/doc/LanguageClient.txt#L164
