### ISSUE TITLE
Jump to diagnostic sign command

### ISSUE THREAD

**Issue by arusahni** [autozimu/LanguageClient-neovim#556]
## Is your feature request related to a problem? Please describe.

I'd like to have an analog to ALE's `ale_next_wrap` and `ale_previous_wrap` so I can jump the cursor to the next diagnostic sign in the gutter.

For example, in ALE, I can use the following mapping:

```vim
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
```

To jump straight to lines that need attention.

## Describe the solution you'd like

Exposed functions such as: `LanguageClient#textDocument_nextDiagnostic()`, `LanguageClient#textDocument_previousDiagnostic()`

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by Anrock** [comment]
Isn't it covered by standard vim mappings for quickfix?

**Comment by arusahni** [comment]
You're right. I got so used to other plugins not respecting native vim solutions that I didn't even bother checking. Thanks for the correction!

**Comment by pchampio** [comment]
In the nightly build of neovim and in vim 8.1.1256, the  `:cabove`, `:cbelow`, `:labove`, and `:lbelow` commands are available.
It's pretty much the same behavior as `ale_previous_wrap` and `ale_next_wrap`.
