### ISSUE TITLE
Add possibility to focus the preview window on hover function call

### ISSUE THREAD

**Issue by StillStealSteel** [autozimu/LanguageClient-neovim#557]
## Is your feature request related to a problem? Please describe.
Make it possible when preview window had been opened you can get focus on it. Because for now it isn't possible to properly make this in your config. Or i didn't find a solution.

## Describe the solution you'd like
Add new global variable something like `g:LanguageClient_focusPreview` with default value 0. When it is 1, then you get focus on the preview window when you call `LanguageClient#textDocument_hover()`.

I tried something like this in my config:
```vim
function! LCNPreview() abort
  call LanguageClient#textDocument_hover()
  let g:current_win_id = win_getid()
  let g:preview_win_id = win_getid(winbufnr(bufnr('__LanguageClient__')))
  call win_gotoid(g:preview_win_id)
  setlocal wrap
  nnoremap <silent><buffer> q :q! \| call g:win_gotoid(current_win_id)<CR>
endfunction

nnoremap <silent> K :call LCNPreview()<CR>
```
I use global variables here for debugging.

It just doesn't work, i can't even get focus of the preview window i think because`LanguageClient#textDocument_hover()` opens preview window through msgpack-rpc or it's async feature (maybe not even because of this assumptions).
Maybe someone can propose working solutions on my side?

**Comment by jamesob** [comment]
This would be really nice. @StillStealSteel if you've figured something out here, it'd be great to know.
