### ISSUE TITLE
[Feature request] Add Debug information printer

### ISSUE THREAD

**Issue by kirillbobyrev** [autozimu/LanguageClient-neovim#558]
I am using LanguageClient-neovim to develop LSP server. Sometimes I have to reproduce the bug or try the experimental branch of the server. My typical workflow would involve going through the logs and attaching a debugger to the server process.

The problem is that for LanguageClient-neovim it's had to get such information as

* Process ID: I often have multiple instances of the LSP server running on my machine e.g. with different editors. To track down the issue I have to close all of them in order to see which one really belongs to LanguageClient-neoim, which is not very convenient.
* Log files and error output: while I potentially can pipe stdio and stderr to some files in my `g:LanguageClient_serverCommands` this is not ideal and it also doesn't help when I have two or more Vim instances running (because everything will be piped into the same file).
* LSP Server root URI

What I would be happy to have is something that I have seen in YouCompleteMe: `YcmDebugInfo` command, which prints the necessary information. It would help me to deal with the server crashes and would certainly improve my user experience. You can see an example of what it looks like below.

[YcmDebugInfo command](https://github.com/Valloric/YouCompleteMe/blob/master/doc/youcompleteme.txt#L1718)

![42452151-d85932f4-83bb-11e8-81d6-d9271f8f7445](https://user-images.githubusercontent.com/3352968/43989813-6e98d63a-9d51-11e8-93a1-62125c874c88.png)

**Comment by kirillbobyrev** [comment]
Thank you for implementing that!


I believe, this addresses the `stderr` redirection, but does not provide a convenient way to "redirect" `stdout` of the Language Server to some file. That would be super nice, too! Potentially, I'm interested in both server LSP dump (which, I believe, I could extract from the logs using `INFO` logging level) and Language Server LSP responses (which I currently can't get from anywhere because it is being read by the server).

**Comment by autozimu** [comment]
For that purpose, you can either use https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/wrapper-server.sh or try something similar https://github.com/autozimu/LanguageClient-neovim/issues/454#issuecomment-414167215
