### ISSUE TITLE
[Feature request] Add default key bindings

### ISSUE THREAD

**Issue by kirillbobyrev** [autozimu/LanguageClient-neovim#559]
All the demos of the LanguageClient-neovim show the user typing something like `:call LanguageClient#textDocument_definition()<CR>` to send LSP request. While the documentation mentions that one might probably want to map the function calls to the shortcuts it would be much easier for users to have some default bindings (which they can obviously override) by default. This would also improve the demo attractiveness because actually typing each time user wants to go to the definition or see documentation, etc is not great. Not having to look up the key bindings in other editors and plugins would save a lot of effort.

**Comment by DerWeh** [comment]
I disagree. Default key bindings are not necessary. You don't even have language servers for all buffers. Just  copy the example configuration and you are fine. Everything else just pollutes the configurations.

But one could think about defining these `<Plug>` things, that is the clean way for plug-ins as far as I know.

**Comment by autozimu** [comment]
Seems like users aren't complaining too much with current opt-in approach.
