### ISSUE TITLE
Make `LanguageClient#serverStatus()` clearer

### ISSUE THREAD

**Issue by liuchengxu** [autozimu/LanguageClient-neovim#560]
## Is your feature request related to a problem? Please describe.

Currently, `LanguageClient#serverStatus()` returns 1 when the server is busy, 0 when the server is idle. 

If I have this mapping in my .vimrc:

```vim
    nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
```

When editing some file which doesn't have a language server support, e.g., vim, `gd` just tells me `Language server is not running for: vim`. `LanguageClient#serverStatus()` is 0 in this case, which is a little bit confusing(no language server running at all or it's still actually doing its job?).

What I want is when there is no language server running, fall back to the default behavior of `gd`.

```vim
" Suppose -1 indicates no language server defined/running
if LanguageClient#serverStatus() == -1
  call searchdecl(expand('<cword>'))
else
  call LanguageClient#textDocument_definition()
endif
```

## Describe the solution you'd like

The solution is to provide an option to tell people whether there is a language server exists for the current buffer, e.g., let `LanguageClient#serverStatus()` return -1 when the language server is not avaliable.

## Describe alternatives you've considered

For now, I can only tell based on `g:LanguageClient_serverCommands`. If the current file type is defined in `g:LanguageClient_serverCommands`, then I am able to assume that it has a language server support. It would be better `LanguageClient#serverStatus()` is clearer.

## Additional context
Suppose `LanguageClient#serverStatus()` returns -1 when a certain file doesn't have a language server running in the background, I could have a more robust `GoToDefinition()`:

```vim
function! GotoDefinition() abort
  if LanguageClient#serverStatus() == -1
    call searchdecl(expand('<cword>'))
  elseif LanguageClient#serverStatus() == 1
    echo 'Language Server is busy now, please try again later.'
  else
    call LanguageClient#textDocument_definition()
  endif
endfunction
```

**Comment by autozimu** [comment]
The function you're looking for is `LanguageClient#isAlive`. You could use
```vim
:echomsg LanguageClient_runSync('LanguageClient#isAlive')
```
to check if server is running synchronously.

Or even better, I'd suggest use async way for your use case,
```vim
function GotoDefinitionHandler(output) abort
    if has_key(a:output, 'error')
       # fallback strategy
    endif
endfunction

function! GotoDefinition() abort
    call LanguageClient#textDocument_definition({'handle': v:true}, 'GotoDefinitionHandler')
endfunction

```

**Comment by liuchengxu** [comment]
Thank you! Your solution in my case is even better.

**Comment by liuchengxu** [comment]
BTW, I found a flaw in LCN: the funcref argument is not standard, i.e., `function('GotoDefinitionHandler')` instead of `'GotoDefinitionHandler'` makes more sense.

Here is my workaround:

```diff
diff --git a/autoload/LanguageClient.vim b/autoload/LanguageClient.vim
index d39de71..e63ce31 100644
--- a/autoload/LanguageClient.vim
+++ b/autoload/LanguageClient.vim
@@ -266,8 +266,7 @@ function! s:HandleMessage(job, lines, event) abort
                 " Function name needs to begin with uppercase letter.
                 let l:Handle = get(s:handlers, l:id)
                 unlet s:handlers[l:id]
-                if type(l:Handle) == type(function('tr')) ||
-                            \ (type(l:Handle) == type('') && exists('*' . l:Handle))
+                if type(l:Handle) == type(function('tr'))
                     call call(l:Handle, [l:message])
                 elseif type(l:Handle) == type([])
                     call add(l:Handle, l:message)
@@ -459,17 +458,16 @@ endfunction

 " Meta methods to go to various places.
 function! LanguageClient#find_locations(method_name, ...) abort
-    let l:callback = get(a:000, 1, v:null)
     let l:params = {
                 \ 'filename': LSP#filename(),
                 \ 'text': LSP#text(),
                 \ 'line': LSP#line(),
                 \ 'character': LSP#character(),
                 \ 'gotoCmd': v:null,
-                \ 'handle': s:IsFalse(l:callback),
+                \ 'handle': s:IsFalse(get(a:000, 1, v:null)),
                 \ }
     call extend(l:params, get(a:000, 0, {}))
-    return LanguageClient#Call(a:method_name, l:params, l:callback)
+    return LanguageClient#Call(a:method_name, l:params, get(a:000, 1, v:null))
 endfunction

 function! LanguageClient#textDocument_definition(...) abort
```

then LCN supports various funcref:

```vim
call LanguageClient#textDocument_definition({'handle': v:true}, function('GotoDefinitionHandler'))
call LanguageClient#textDocument_definition({'handle': v:true}, function('s:GotoDefinitionHandler'))
call LanguageClient#textDocument_definition({'handle': v:true}, { -> searchdecl(expand('<cword>')) })
```

If allowed, I could send a PR about this.

**Comment by autozimu** [comment]
Why is removing an clause from `||` would increase allowable funcref types?

**Comment by liuchengxu** [comment]
Basically, it won't, `||` is needless though. `type(l:Handle) == type(function('tr'))` will be always satisfied if the funcref is standard(`'GotoDefinitionHandler'` is not, which is a string at first glance).

Currently, the funcref provided by LCN is peculiar, which doesn't support:

```vim
call LanguageClient#textDocument_definition({'handle': v:true}, function('GotoDefinitionHandler'))
call LanguageClient#textDocument_definition({'handle': v:true}, function('s:GotoDefinitionHandler'))
call LanguageClient#textDocument_definition({'handle': v:true}, { -> searchdecl(expand('<cword>')) })
```

this error will always occur:

```
Error detected while processing function spacevim#lang#util#GotoDefinition[7]..LanguageClient#textDocument_definition[1]..LanguageClient#find_locations:
line    1:
E704: Funcref variable name must start with a capital: l:callback
```

The point is:

```vim
let l:callback = get(a:000, 1, v:null)
```

you can't assign a Funcref variable to a `l:` variable, `:h E704`:

```
A Funcref variable must start with a capital, "s:", "w:", "t:" or "b:". 
```

**Comment by autozimu** [comment]
Thanks. Good to know this.

It probably means other assignments of `l:callback` is not working.

Feel free to submit PR.
