### ISSUE TITLE
[Feature request] Allow restarting LSp server from Vim

### ISSUE THREAD

**Issue by kirillbobyrev** [autozimu/LanguageClient-neovim#564]
Allow user restart LSP servers without restarting Vim via some command like `YcmRestartServer`. This is super useful when the server crashes, but I don't want to restore the whole session.

**Comment by Anrock** [comment]
:LanguageServerStop and then :LanguageServerStart, no?

**Comment by kirillbobyrev** [comment]
@Anrock ah, yeah, I was scrolling the documentation and trying to find something with restart, my bad.
Thanks!
