### ISSUE TITLE
language servers configuration file

### ISSUE THREAD

**Issue by rebelot** [autozimu/LanguageClient-neovim#565]
## Is your feature request related to a problem? Please describe.
It is not clear whether it is possible to pass additional options to language servers which usually expect them in the json format as in VSCode.

## Describe the solution you'd like
Add a configuration file `nvim-language-server-config.json` with the same format of VSCode that is reachable by the language servers.

**Comment by Anrock** [comment]
Are you talking about [g:LanguageClient_settingsPath](https://github.com/autozimu/LanguageClient-neovim/blob/6aa9952ea16f7cfe0b2a984419cf90295ae0d476/doc/LanguageClient.txt#L181)?

**Comment by rebelot** [comment]
yes! Sorry for such a stupid question, I've read the docs thoroughly but for some reason I thought that it only applied to the diagnostics. I've set up something like this:

```
{
    "pyls.plugins.preload.enabled": true,
    "pyls.plugins.preload.modules": [
        "numpy",
        "pandas"
    ],
    "pyls.plugins.pydocstyle.enabled": true
}
```

**Comment by autozimu** [comment]
Your example setting might not work (although I'm not 100% sure). If not work, try unroll the json path, i.e.,
```json
{
    "pyls": {
         "plugins": {
          ....
        }
    }
}
```

**Comment by rebelot** [comment]
indeed it is not working. I tried:
```
{
    "pyls": {
        "plugins": {
            "preload": {
                "enabled": true,
                "modules": [
                    "numpy",
                    "pandas"
                ]
            },
            "pydocstyle": {
                "enabled": true
            },
            "jedi_completion":{
                "enabled": false
            }
        }
    }
}
```
but I am still getting completions.

**Comment by autozimu** [comment]
Check this https://github.com/autozimu/LanguageClient-neovim/issues/448#issuecomment-392491861
