### ISSUE TITLE
Denite references doesn't respect working directory

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#57]
I am using the `python-language-server`, I am sorry if the problem is on the server site.

The `Denite references` source displays the proper line numbers, but the wrong file.

In my case I have am in `projectroot` and work on the file `projectroot/subdir/myfile`, the `references` then refer to (the also existing) file `projectroot/myfile`. If I change to `projectroot/subdir` everything works fine.

It would also be nice to additionally include the content of the line in the `Denite` buffer.

**Comment by autozimu** [comment]
Thanks for reporting.

It seems like issue of python language server or denite. It's hard to tell where the problem is without knowledge of actual server response.

(I'm on vacation and don't have reliable network connection. The actual work on my side might be delayed. Thanks for understanding.)

**Comment by Shougo** [comment]
This is the denite source issue.
It can use `path` option to get the current working directory.
