### ISSUE TITLE
Check capabilities before calling formatting or rangeFormatting

### ISSUE THREAD

**Issue by docwhat** [autozimu/LanguageClient-neovim#570]
## Is your feature request related to a problem? Please describe.

The [bash language server](https://github.com/mads-hartmann/bash-language-server) cannot handle any formatting.  It also does not advertise it handles any formatting.

Due to what I would suppose is a bug, it causes LC to hang and then crashes the `bash-language-server`:

```
" vim :mess
Language server sh exited unexpectedly: Unable to read from language server
51 lines to indent...
50 lines to indent...
52 lines indented
```

## Describe the solution you'd like

Honor the capabilities advertised by the Language Server.

## Describe alternatives you've considered

None?

## Additional context

None

**Comment by autozimu** [comment]
Could you file a bug report at language server side?

Language servers shall not crash if the requested operation is not supported.

**Comment by docwhat** [comment]
After debugging it I discovered I was running the language-server incorrectly. :-(

Thanks for your help!
