### ISSUE TITLE
Select first/only result of textDocument/references if there is only one 

### ISSUE THREAD

**Issue by matt-snider** [autozimu/LanguageClient-neovim#572]
When using `LanguageClient#textDocument_references()` I would like to jump to the first & only usage if there is only a single result. I believe it works this way in IntelliJ for example with *Find usages*.  

Is there any way to accomplish this currently or would this be a new feature?

**Comment by DerWeh** [comment]
In case you are using `Denite` this should already be implemented:

```vim
						*denite-option-immediately-1*
-immediately-1
		If the number of candidates is exactly one, it runs the default action
		immediately.
Default: false
```

I think this is already exactly what you want.

**Comment by matt-snider** [comment]
@DerWeh Thanks but I do not use denite. 

@autozimu Wow. Quick fix :+1: :smile:  - thanks
