### ISSUE TITLE
Is it possible to start language client without opening a filetype?

### ISSUE THREAD

**Issue by bbtdev** [autozimu/LanguageClient-neovim#574]
A command to start a specific server or maybe using settings.json?

It would be awesome not to wait for a specific filetype, when I open nvim in a specific folder, either it could read the settings.json or I could implement something in vimscript that calls the function.

**Comment by autozimu** [comment]
What is your use case?

The implementation relies heavily on filetype to determine which language server to talk to.

**Comment by autozimu** [comment]
No response.

**Comment by bbtdev** [comment]
@autozimu 

My apologies.

For example when I open nvim in a folder without opening a file, I want to check if the folder has a mix.exs file (is an elixir project, start elixir server) or Gemfile start ruby server.

**Comment by autozimu** [comment]
I don't get what's the benefits of starting language servers for a folder buffer.

Besides, as previously stated, it's impractical to support this with current implementation.
