### ISSUE TITLE
Using newName in textDocument/rename (with vim-abolish)

### ISSUE THREAD

**Issue by matt-snider** [autozimu/LanguageClient-neovim#575]
Hi,

I wanted to use [vim-abolish](https://github.com/tpope/vim-abolish/) with this plugin, so I was looking through the documentation for a way to pre-populate the value for `LanguageClient#textDocument_rename()`, but didn't find anything. 

Reading through the code, I was pleasantly surprised to find [this](https://github.com/autozimu/LanguageClient-neovim/blob/7908e49b7c5d2b2fc10735fe07107902137b833f/tests/LanguageClient_test.py#L81https://github.com/autozimu/LanguageClient-neovim/blob/7908e49b7c5d2b2fc10735fe07107902137b833f/tests/LanguageClient_test.py#L81) in the tests. I played around with some bindings, and it works *perfectly* - so first of all, thanks for such a great plugin!

Secondly, I was wondering if there is a reason that this is undocumented - is it intended only for tests? If not, it is a very nice feature that should definitely be documented. I wouldn't mind contributing that if that's the case. Since it integrates so nicely with vim-abolish, I could also include an example in there.

FYI, here are the bindings I'm using to quickly rename to camelCase, PascalCase, kebeb-case, dot.case, etc:
```vim

" Rename - rn => rename
noremap <leader>rn :call LanguageClient#textDocument_rename()<CR>

" Rename - rc => rename camelCase
noremap <leader>rc :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.camelcase(expand('<cword>'))})<CR>

" Rename - rk => rename kebab-case
noremap <leader>rk :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.dashcase(expand('<cword>'))})<CR>

" Rename - rp => rename PascalCase
noremap <leader>rp :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.mixedcase(expand('<cword>'))})<CR>

" Rename - rs => rename snake_case
noremap <leader>rs :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.snakecase(expand('<cword>'))})<CR>

" Rename - ru => rename UPPERCASE
noremap <leader>ru :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.uppercase(expand('<cword>'))})<CR>

" Rename - r. => rename dot.case
noremap <leader>r. :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.dotcase(expand('<cword>'))})<CR>

" Rename - r<space> => rename space case
noremap <leader>r<space> :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.spacecase(expand('<cword>'))})<CR>

" Rename - rt => rename Title Case
noremap <leader>rt :call LanguageClient#textDocument_rename(
            \ {'newName': Abolish.titlecase(expand('<cword>'))})<CR>
```

**Comment by autozimu** [comment]
Glad this plugin helps.

Please submit PR to improve the doc as you see fit.

**Comment by autozimu** [comment]
@matt-snider Could you submit a PR?

**Comment by matt-snider** [comment]
@autozimu Will try to do it today or tomorrow

**Comment by autozimu** [comment]
Addressed in https://github.com/autozimu/LanguageClient-neovim/pull/582
