### ISSUE TITLE
Add a capability to expand full error messages when status bar is not long enough

### ISSUE THREAD

**Issue by tac-tics** [autozimu/LanguageClient-neovim#576]
## Is your feature request related to a problem? Please describe.
I am trying Rust's RLS feature with NeoVim. It is working nicely so far, but occasionally, an error message will be too big to fit into the console. For instance:

"[Information][E0373]closure may outlive the current function, but it borrows `m2`, which is ow..."

I don't know a way to get the full message inside of NeoVim. For the moment, I have to exit out and run `cargo build` manually.

## Describe the solution you'd like
If there is not already a feature to work around this issue, it would be nice to have a command to expand the error message in a new window buffer.

## Additional context
[Here is an image of the behavior I'm trying to describe](https://imgur.com/shASNDE). See the very bottom of the image how it cuts off in the middle of the word "parameter".

**Comment by Cypher1** [comment]
@autozimu is there a way to do this? It is unclear why this was closed.

**Comment by autozimu** [comment]
@Cypher1 It is clear if you click into the referenced commit, i.e., https://github.com/autozimu/LanguageClient-neovim/commit/5e968547dea733a25de74c1f9babd9e77459598a

**Comment by Cypher1** [comment]
Thanks @autozimu, sorry I didn't see it properly.

Would you mind showing me how to use it though? I'm not fluent in the language server APIs or data structures in vimscript.

**Comment by kamilchm** [comment]
@Cypher1 you can call it directly `:call LanguageClient#explainErrorAtPoint()` or map it to a key in your config, eg.
```
" press `E` on error to show the full message
nnoremap <silent> E :call LanguageClient#explainErrorAtPoint()<CR>
```

**Comment by Cypher1** [comment]
Thank you @kamilchm just got to use it for the first time and its awesome :D Exactly what I hoped it would do!
