### ISSUE TITLE
Timed out waiting on channel – explainErrorAtPoint

### ISSUE THREAD

**Issue by Limeth** [autozimu/LanguageClient-neovim#578]
- Did you upgrade to latest plugin version? Yes.
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. Yes.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes.
- Did you check [troubleshooting]? Yes, but I couldn't get the plugin to work with the `min-vimrc.vim` script. I suspect it doesn't load vim-plug. I'll have to look into that later.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
When trying to use the new command using `:call LanguageClient#explainErrorAtPoint()`, the following error message is shown: `timed out waiting on channel`.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.2-dev
- This plugin version (`git rev-parse --short HEAD`): `5e96854`
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.112
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version: rls-preview 0.130.5-nightly (9e4d8d5 2018-08-10)

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
Open any Rust project and try to inspect any error within that project.

## Current behavior
Executing the `:call LanguageClient#explainErrorAtPoint()` command results in the `timed out waiting on channel` error message being shown in several seconds. Nothing else happens.

## Expected behavior
Whatever `explainErrorAtPoint` is supposed to do.

**Comment by autozimu** [comment]
Sorry about this.

Please update to latest release and try it again.

**Comment by Limeth** [comment]
Perfect. This new feature will speed up my development process quite a bit, as I used to run `cargo check` in the command line when I needed the full error message. Thank you for the quick fix!

**Comment by Char-Aznable** [comment]
I have the same issue with ccls on c++ file.
```
neovim/vim version (nvim --version or vim --version): vim 8.1.0543 
This plugin version (git rev-parse --short HEAD): 1a32680
This plugin's binary version (bin/languageclient --version): languageclient 0.1.133
Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
reproduce the issue. Refer to an example here):
Language server link and version: ccls 39b214b (12/24/2018)
```
