### ISSUE TITLE
How to show complete error message

### ISSUE THREAD

**Issue by jvanbruegge** [autozimu/LanguageClient-neovim#585]
I am not sure if this is an issue of `vim-airline` or `LanguageClient-neovim`, but when I have a type error, the LSP reports it and I move my cursor in that line, I always see a truncated version of the error. How can I get the complete text like with `hover` (open a new split with multiline error`)

**Comment by Anrock** [comment]
@jvanbruegge `:copen` or `:lopen` depending on how your Language Client is configured.

**Comment by autozimu** [comment]
Or see https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-414191276
