### ISSUE TITLE
Buffer not created properly when jump into definition for a second time (buffer not showing in the tab line)

### ISSUE THREAD

**Issue by dylan-chong** [autozimu/LanguageClient-neovim#586]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Run shell command 
  `bin/languageclient --version` to get its version number. languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes everything is fine
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bu

Vim buffer may not properly be created when jumping to the definition of the file. This causes the buffer not be shown in the airline tab line

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.1
- This plugin version (`git rev-parse --short HEAD`): 891ee2c
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'vim-airline/vim-airline'

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'typescript': ['typescript-language-server', '--stdio'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile = stdpath('data') . '/LanguageClient.log'
let g:LanguageClient_serverStderr = stdpath('data') . '/LanguageServer.log'

au BufRead,BufNewFile *.ts set filetype=typescript

let g:airline#extensions#tabline#enabled = 1

```
- Language server link and version: https://github.com/theia-ide/typescript-language-server/releases/tag/v0.2.0

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. git clone https://github.com/dylan-chong/prioritask
1. yarn install or npm i
1. Start vim, nvim -u min-vimrc.vim src/pages/login/login.ts
1. Place the cursor over UserService
1. :call LanguageClient#textDocument_definition()
1. :ls should produce the results similar to
```
1 #    "src/pages/login/login.ts"     line 3
2 %a   "src/providers/user-service/user-service.ts" line 12
```
1. :bd to close the user service buffer
1. Place the cursor over UserService again
1. :call LanguageClient#textDocument_definition()
1. :ls now only produces the results
```
  1 #    "src/pages/login/login.ts"     line 3
```

## Current behavior

second :ls output shows that the buffer has not been created for the user service. the user service file does not appear in the tab line as well

## Expected behavior

second :ls outfit should be the same as the first :ls output. ie the buffer should be created properly. the files should also show in the tab line

## Screenshots

![44781347-3c6f1a80-abd8-11e8-96c7-dadc13b8debb](https://user-images.githubusercontent.com/17482349/44950804-a53ee700-aea5-11e8-9f58-5c0f8cfbf7bd.png)

as you can see in the screenshot above the file user service does not appear in the tab line

## Additional context

man . this took me several hours to figure out how to reproduce this problem

**Comment by danmikita** [comment]
Try doing a :bw to close the buffer. You will lose all the meta data that goes with the buffer, but the next time you use the go to definition, it will reopen a new buffer properly.

**Comment by autozimu** [comment]
Resolved by https://github.com/autozimu/LanguageClient-neovim/pull/683
