### ISSUE TITLE
lint message only updates once you move the cursor up or down

### ISSUE THREAD

**Issue by plexigras** [autozimu/LanguageClient-neovim#588]
## Current behavior
lint message only updates once you move the cursor up or down

https://asciinema.org/a/ZE9xRnZ3hDhxZ3oGWKRYWMMCp

## Expected behavior
lint message should updates once you move the cursor

## Environment
- neovim/vim version: `NVIM v0.3.1`
- This plugin version f75b4c1
- This plugin's binary version: `languageclient 0.1.114`
- Language server link:  [`typescript-language-server`](https://github.com/theia-ide/typescript-language-server)

**Comment by martskins** [comment]
I'm fairly certain this is not an issue anymore and given that this was reported in a rather old version of LCN I think it's fair to close this but feel free to re-open if this is still an issue for you.
