### ISSUE TITLE
pressing undo will empty current buffer when g:LanguageClient_diagnosticsEnable=0

### ISSUE THREAD

**Issue by timfeirg** [autozimu/LanguageClient-neovim#589]
- Did you upgrade to latest plugin version?
  yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
  languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/timfeirg/.nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
```
- Did you check [troubleshooting]?
I did.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

`:undo` will empty current buffer, which shouldn't happen.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.3.2-397-ge30ccd56d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180831-49714-12w98je/build/config -I/tmp/neovim-20180831-49714-12w98je/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180831-49714-12w98je/build/src/nvim/auto -I/tmp/neovim-20180831-49714-12w98je/build/include
Compiled by timfeirg@timfeirg-mba-7.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e30ccd5/share/nvim"

Run :checkhealth for more info
```
- This plugin version (`git rev-parse --short HEAD`): `f75b4c1`
- This plugin's binary version (`bin/languageclient --version`):
```
  languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
```
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```vimL
call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
            \ 'branch': 'next',
            \ 'do': 'bash install.sh',
            \ }
call plug#end()

lef g:LanguageClient_diagnosticsEnable = 0
```
- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

* enable the LanguageClient plugin
* add `lef g:LanguageClient_diagnosticsEnable = 0` to your .vimrc
* open up any text file with some existing content
* press `u` or `:undo`, and the buffer will be cleaned empty, which shouldn't happen.

**Comment by martskins** [comment]
I couldn't reproduce this, and this is a pretty dated version of LanguageClient-neovim, so I'm gonna assume this is no longer an issue, but feel free to re-open if that's not the case.
