### ISSUE TITLE
Feature Request : adds formatting functions

### ISSUE THREAD

**Issue by drasill** [autozimu/LanguageClient-neovim#59]
Thank you for your fantastic plugin.

Would it be possible to add formatting methods ?

* [textDocument/formatting](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_formatting)
* [textDocument/rangeFormatting](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rangeFormatting)
* [textDocument/onTypeFormatting](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_onTypeFormatting) (not sure it's doable or useful)

Formatting seems to be [supported](https://github.com/felixfbecker/php-language-server#document-formatting) by felixfbecker's PHP server implementation.

**Comment by autozimu** [comment]
Good to know that the methods are actually implemented in some language servers.

Yes, I will try implement as soon as I can.

**Comment by autozimu** [comment]
I've actually implemented the function calls, but it seems cause errors in pyls. Need more time to investigate.
