### ISSUE TITLE
"FZF not found!" when trying code action

### ISSUE THREAD

**Issue by dschuessler** [autozimu/LanguageClient-neovim#590]
When I try to invoke a code action with `:call LanguageClient_textDocument_codeAction()` I get the error message "FZF not found!" highlighted in red.

Installing `fzf` and `fzf.vim` does not help, but judging by the docs `fzf` is an "optional dependency" anyway.

Minimal `.vimrc`:
```
call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-rooter'
Plug 'autozimu/LanguageClient-neovim', {'tag': 'binary-*-x86_64-apple-darwin'}
call plug#end()

function SetupLanguageClients()
    let g:LanguageClient_serverCommands = {
        \'java': ['jdt-ls', FindRootDirectory()],
        \'python': ['pyls'],
    \}

    LanguageClientStart()
endfunction

autocmd FileType java,python call SetupLanguageClients()
```

Tested with:
jdt.ls 0.24.0-201808272203
pyls 0.19.0
MacVim 8.1.235

**Comment by autozimu** [comment]
FZF is an optional plugin for most of this plugin's functionalities, but for this one, it requires FZF to prompt user to select one action.

For your case, make sure after your FZF installation, you can invoke `:FZF` command from vim.

**Comment by valpackett** [comment]
Denite should be supported for this, because currently:

- `:Denite contextMenu`
- select "Code Action"
- "FZF not found"

Instead of "FZF not found" I'd expect `:Denite codeAction` to be called!
