### ISSUE TITLE
Not getting correct completions with C++ and autocomplete

### ISSUE THREAD

**Issue by jmdaly** [autozimu/LanguageClient-neovim#591]
languageclient version: 0.1.114

## Describe the bug
(I'm not sure if this bug should be reported here, or in the ncm2 project, so I figured I'd start here)
When getting completions on an object of a C++ class, after I press `.`, the suggestions are not the correct suggestions for the object. Instead, they appear to be suggestions for the current function scope. However, when I invoke omni completion using CTRL-X CTRL-O, the correct completion suggestions for the object pop up. I have recorded an example of this happening. When I initially press `.` after typing `test_object`, the suggestions that pop up are not related to `test_object`. Additionally, the members that are part of `test_object` are not shown. I then invoke omni completion and I get the correct suggestions.

![cpp_completion](https://user-images.githubusercontent.com/2916716/44933811-6d666100-ad38-11e8-8185-85bafc8686fc.gif)

## Environment
- neovim version 0.2.2
- This plugin version: f75b4c1
- This plugin's binary version: 0.1.114
- Minimal vimrc content:

```
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'

call plug#end()            " required

set number

let g:LanguageClient_serverCommands = {
\ 'cpp': ['ccls', '--log-file=/tmp/cq.log']
\ }
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath = $HOME.'/.config/nvim/settings.json'
let g:LanguageClient_loggingFile = '/tmp/lc.log'
let g:LanguageClient_loggingLevel = 'DEBUG'
set completefunc=LanguageClient#complete
set formatexpr=LanguageClient_textDocument_rangeFormatting()
nnoremap <leader>ty :call LanguageClient#textDocument_hover()<CR>
nnoremap <leader>rf :call LanguageClient#textDocument_references()<CR>
nnoremap <leader>rj :call LanguageClient#textDocument_definition()<CR>
nnoremap <leader>rw :call LanguageClient#textDocument_rename()<CR>
" enable ncm2 for all buffers
autocmd BufEnter * call ncm2#enable_for_buffer()
" IMPORTANTE: :help Ncm2PopupOpen for more information
set completeopt=noinsert,menuone,noselect
```

- Language server link and version: [ccls](https://github.com/MaskRay/ccls) commit: 5bea4f4c32e95

## To Reproduce
1. The relevant C++ file and CMakeLists.txt can be found here:
[test_proj.zip](https://github.com/autozimu/LanguageClient-neovim/files/2341471/test_proj.zip)
2. ccls must be built and installed in order to fully test it. The project has no dependencies, so it should be relatively easy to test.

## Current behavior
When I invoke the `.` operator on an object, the completion suggestions are not the ones appropriate for the object. Instead, they appear to be suggestions for the enclosing scope. However, when I invoke omni completion using CTRL-X CTRL-O, after typing `.`, the suggestions are correct.

## Expected behavior
I expect that, upon invoking the `.` operator on an object, that I will be presented with the correct auto complete suggestions.

## Screenshots
See above.

Also, thank you for your work on this plugin. I'm looking forward to getting this issue resolved, at which point, this will be an ideal setup for me.

**Comment by autozimu** [comment]
Can you attach the captured log file?

Example setting is https://github.com/autozimu/LanguageClient-neovim/blob/f75b4c1410e025ee693357e237c3065516ebb74f/tests/data/vimrc#L20-L21

**Comment by jmdaly** [comment]
I enabled logging at DEBUG level, hopefully that'll show what we need. I'm attaching the log here.
[lc.log](https://github.com/autozimu/LanguageClient-neovim/files/2341564/lc.log)

**Comment by autozimu** [comment]
Your log file don't have the C-X C-O action.

Can you capture the log one more time with one ncm2 completion and one C-X C-O completion?

**Comment by jmdaly** [comment]
Sorry I missed the omni completion. I've collected another log showing once ncm2 completion and one omni completion. Please let me know if there's anything else I can provide.
[languageclient.log](https://github.com/autozimu/LanguageClient-neovim/files/2349006/languageclient.log)

**Comment by jmdaly** [comment]
I just noticed something about my configuration. When I filed the bug, I was running neovim 0.2.2, which is currently the newest version in the neovim stable PPA for Ubuntu 16.04. I switched to the unstable PPA, and am now running neovim v0.3.2-dev. With this version of neovim, the issue I reported here does not occur, and completions work for me as expected.

**Comment by autozimu** [comment]
Hmm. That's interesting.

I actually looked into the log files but haven't found anything suspicious.

I'm going to close this for now. Feel free to reopen when the problem happens again.

**Comment by roxma** [comment]
I guess this is due to `TextChangedP` added in this PR https://github.com/autozimu/LanguageClient-neovim/pull/555

nvim-0.2.2 doesn't have `TextChangedP`

**Comment by jmdaly** [comment]
That makes a lot of sense, thanks for looking into it!

**Comment by MaskRay** [comment]
Speaking of the jump list, how about revisiting https://github.com/autozimu/LanguageClient-neovim/issues/189 (dedicated jump forward/backward for LSP cross reference requests?)
