### ISSUE TITLE
Does not differentiate between python2 and 3

### ISSUE THREAD

**Issue by esn89** [autozimu/LanguageClient-neovim#593]
- Did you upgrade to latest plugin version?
Yes
- Did you upgrade to/compile latest binary? Run shell command
Yes
  `bin/languageclient --version` to get its version number.
languageclient 0.1.114 542203b6aa435b93a21e123b2177b18cd1a1a8ed
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?

Yes
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

when I make a file called test.py and I type in python3 syntax like:

print(somevariableIjustdefined)
It will say:
Superfluous-parens:  Unnecessary parens after 'print' keyword

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
- This plugin version (`git rev-parse --short HEAD`):
0.21.0
- This plugin's binary version (`bin/languageclient --version`):
Just did that
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
let g:deoplete#enable_at_startup = 1
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
let g:LanguageClient_serverCommands = {
    \'python' : ['/Users/esn89/Library/Python/2.7/bin/pyls'],
    \'python3' : ['/Users/esn89/Library/Python/3.7/bin/pyls'],
    \'go' : ['/Users/esn89/.go/bin/go-langserver', '-gocodecompletion'],
    \}

- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. make a python file named test.py
2. write inside:   stuff = "hi"
3. write in a new line:   print(stuff)

## Current behavior
A clear and concise description of what's the current behavior.
print(somevariableIjustdefined)
It will say:
Superfluous-parens:  Unnecessary parens after 'print' keyword
## Expected behavior

It should accept the print(likethis)
## Screenshots
https://i.imgur.com/N4Qm3eV.png

**Comment by autozimu** [comment]
Your python3 language server is never going to be invoked because your python3 files are having `python` as filetype.

You could change your language server settings to
```vim
let g:LanguageClient_serverCommands = {
'python' : ['/Users/esn89/Library/Python/3.7/bin/pyls'],
}
```
With this, all the python files will be handled by the python3 language server.

If want to use different language servers for different projects, you might want to try out some local vimrc sourcing plugins like https://github.com/embear/vim-localvimrc

**Comment by esn89** [comment]
@autozimu 
So, there is only one "python" that the LanguageClient_server knows about.

And it is up to me to map that python to either the 3.7 or the 2.7 pyls?

**Comment by autozimu** [comment]
Right.
