### ISSUE TITLE
[Feature request] Simplify navigation between errors

### ISSUE THREAD

**Issue by kirillbobyrev** [autozimu/LanguageClient-neovim#594]
Often I refactor a chunk of C++ code which breaks a lot of things, for example I change function signature and callers are broken. I'd like to go through all of these callers and fix the issues, but I have to find them myself. I typically read the compiler message and go to the lines with callers, but it's suboptimal. Also, a lot of times there are just some warnings/errors in my file and I would like to go to them before compiling (and the file is large enough so that I don't actually see the diagnostics and red highlights), because otherwise that'd be a waste of time (if the file is one of the last files to get compiled).

## Solution I'd like

[w0rp/ale](https://github.com/w0rp/ale) which I used for a while has a very nice [navigation between errors](https://github.com/w0rp/ale#5ix-how-can-i-navigate-between-errors-quickly) which consists of `<Plug>(ale_previous_wrap)` and `<Plug>(ale_next_wrap)`. Having that in LanguageClient-neovim would be super cool!

## Additional context

In general, I would be super happy if LanguageClient-neovim would provide commands instead of the functions which are both hard to memorize and hard to type. `<Plug>LanguageClientCommand` (a-la ALE errors navigation) would also be OK.

**Comment by davidosomething** [comment]
You can use  https://github.com/romainl/vim-qf or tpope's unimpaired for those bindings

**Comment by autozimu** [comment]
As @davidosomething suggested, you can use whatever mapping to jump between quickfix list (default) or location list.

**Comment by kirillbobyrev** [comment]
Ah, okay, I didn't know about `:lnext`, `:cnext` etc. Makes sense to me, thanks a lot!

**Comment by pchampio** [comment]
In the nightly build of neovim and in vim 8.1.1256, the  `:cabove`, `:cbelow`, `:labove`, and `:lbelow` commands are available.
I find them more suited than `:lnext`, `:cnext` and are closer to what ALE proposes.
