### ISSUE TITLE
Add (Linux) ARM targets to pre-built binaries

### ISSUE THREAD

**Issue by mwilliammyers** [autozimu/LanguageClient-neovim#596]
## Describe the solution you'd like
Anyway we could add ARM targets to the pre-built binary list; specifically `armv8`: `aarch64-unknown-linux-gnu`... Is it as simple as adding the target triplet to [line 17](https://github.com/autozimu/LanguageClient-neovim/blob/29d8ef8841b849437ea2e47b60f2581b2fd81f5e/.travis.yml#L17) of the Travis build config? I would be happy to open a PR...

## Describe alternatives you've considered
It is pretty annoying to have to compile on my Chromebook (which takes about 15ish minutes) every time I want to update the plugin via a plugin manager...

PS very cool that you are migrating to Rust! Have you measured the performance improvement over Python yet?

**Comment by mwilliammyers** [comment]
I guess we could also throw in `arm-unknown-linux-gnueabi ` and `arm-unknown-linux-gnueabihf` to cover ARMv6 and ARMv7 at the same time...

**Comment by autozimu** [comment]
Beside the referenced line, there is one more line to add in `install.sh` https://github.com/autozimu/LanguageClient-neovim/blob/29d8ef8841b849437ea2e47b60f2581b2fd81f5e/install.sh#L45-L51

With that, I think it should be sufficient.

I haven't done any benchmark yet. The main motivation is to ease distribution.

**Comment by app** [comment]
Hi!
I wonder if this issue will be open back since I see no armv7 target build in  branch 'next' any more?

**Comment by ck3mp3r** [comment]
It would be great to have prebuilt binaries for armv* especially for running on Raspberri PIs.

Currently the build fails with the following:
```
➜  LanguageClient-neovim (next) ✔ make
cargo build --release
   Compiling languageclient v0.1.156 (/home/pi/.cache/vimfiles/repos/github.com/autozimu/LanguageClient-neovim)
warning: unused import: `std::ops::Deref`
  --> src/main.rs:10:5
   |
10 | use std::ops::Deref;
   |     ^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

error[E0599]: no method named `as_deref` found for type `std::option::Option<std::string::String>` in the current scope
  --> src/rpchandler.rs:10:62
   |
10 |                 let result = self.handle_method_call(lang_id.as_deref(), &method_call);
   |                                                              ^^^^^^^^ help: did you mean: `as_ref`

error[E0599]: no method named `as_deref` found for type `std::option::Option<std::string::String>` in the current scope
  --> src/rpchandler.rs:25:63
   |
25 |                 let result = self.handle_notification(lang_id.as_deref(), &notification);
   |                                                               ^^^^^^^^ help: did you mean: `as_ref`

error[E0599]: no method named `as_deref` found for type `&std::option::Option<std::string::String>` in the current scope
   --> src/vim.rs:151:29
    |
151 |         let goto = goto_cmd.as_deref().unwrap_or("edit");
    |                             ^^^^^^^^ help: did you mean: `as_ref`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `languageclient`.

To learn more, run the command again with --verbose.
make: *** [Makefile:24: release] Error 101
```

As my knowledge of rust is none existend I won't be able to help I'm afraid...
This build was run on:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

using branch and commit point 
```
* cf43a9f - (grafted, HEAD -> next, origin/next, origin/HEAD) chore(docs): ensure each header and code block are separated from other content by a newline (8 days ago) <Benjamin Denhartog>
```

**Comment by juanolon** [comment]
i just got the same error. The reason was that i had an old Rust version (from debian repository, rust version 1.34.2). `as_deref` is supported from rust version 1.4 (see #930) I installed the last rust version from their website (v. 1.42) and now i can compile it.

**Comment by kadru** [comment]
I just checked the referenced PR and seems arm support was added but later was removed.

Will be any plans to support arm? @autozimu.

**Comment by martskins** [comment]
@kadru I think #1179 should bring this back
