### ISSUE TITLE
Allow forcing local build

### ISSUE THREAD

**Issue by lovesegfault** [autozimu/LanguageClient-neovim#598]
## Is your feature request related to a problem? Please describe.
I really don't like having to download the binary, since sometimes I have slow internet connections or am in a metered connection; Nine times out of ten I's much rather just build it locally.

## Describe the solution you'd like
Add an option to the build script that bypasses the arch checking and just builds locally no matter what.

## Describe alternatives you've considered
Forking this and making `install.sh` just build locally, then keep my fork up-to-date and use that inside Vim.

**Comment by lovesegfault** [comment]
I am working on this and will have a PR soon.

**Comment by autozimu** [comment]
You can build locally simply use `make release` as post install command.

If you're building locally just for the purpose of bandwidth, I don't think it will work cause when building cargo will fetch much more data than download binary.

**Comment by TamaMcGlinn** [comment]
If you don't have direct internet access that both of these options require, it is also possible to download e.g. [`https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.154/languageclient-0.1.154-x86_64-pc-windows-gnu.exe`](https://github.com/autozimu/LanguageClient-neovim/releases/download/0.1.154/languageclient-0.1.154-x86_64-pc-windows-gnu.exe) manually, rename it to languageclient.exe and place it inside LanguageClient's bin directory, e.g. `~/vimscripts/dein/repos/github.com/autozimu/LanguageClient-neovim_next/bin/languageclient.exe` (for my [dein](https://github.com/Shougo/dein.vim) based vim installation).
