### ISSUE TITLE
[FYI] vim-airline integration

### ISSUE THREAD

**Issue by hallettj** [autozimu/LanguageClient-neovim#602]
I am getting a lot of use from LanguageClient. I found it useful to write an extension for vim-airline so that I can see error and warning counts in my status bar. My pull request is here:

https://github.com/vim-airline/vim-airline/pull/1788

If you have time to take a look I am interested to know what you think of the extension. I use the `LanguageClient#getState` function to get up-to-date diagnostic data when the `LanguageClientDiagnosticsChanged` event fires. I put that data in a script variable; when airline refreshes and requests the latest error count I use data from the variable to generate a string to display.

**Comment by autozimu** [comment]
Looks awesome! Thanks.
