### ISSUE TITLE
Haskell completions weird filtering

### ISSUE THREAD

**Issue by monkoose** [autozimu/LanguageClient-neovim#605]
[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
Haskell completions isn't filtering properly. When you complete some word it adds known parameter's types to the completion. I'm using https://github.com/haskell/haskell-ide-engine language server for haskell.
Few screenshots:
- Before the completion
![](https://i.imgur.com/knw56Uy.png)
- C-x C-o was pressed
![](https://i.imgur.com/tF91Ghc.png)
- Selected first candidate
![](https://i.imgur.com/qGvOjEA.png)

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.1
- This plugin version (`git rev-parse --short HEAD`):
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.119 
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): Is it really required for this problem? If so i will add it.
- Language server link and version: `https://github.com/haskell/haskell-ide-engine` last build with stack install

## Current behavior
Described previously.

## Expected behavior
Just complete a WORD.

**Comment by monkoose** [comment]
Here is minimal vimrc
```vim
set runtimepath+=$HOME/.local/share/nvim/site/dein/repos/github.com/Shougo/dein.vim
let g:python3_host_prog = '/usr/bin/python'

if dein#load_state(expand('$HOME/.local/share/nvim/site/dein'))
  call dein#begin(expand('$HOME/.local/share/nvim/site/dein'))
  call dein#add('Shougo/dein.vim')
  call dein#add('autozimu/LanguageClient-neovim', {'build': './install.sh'})
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable
set noswapfile
let g:LanguageClient_serverCommands = {
    \ 'haskell': ['hie-wrapper'],
    \ }
let g:LanguageClient_diagnosticsEnable = 0
```

**Comment by Anrock** [comment]
Those look like snippet placeholders for arguments. Just today some fixes about snippet support landed to hie, can you try fresh master of hie and check if it's fixed?

**Comment by monkoose** [comment]
@Anrock 
Yep, it fixes the issue. So wasn't Lcn problem at all.
Thank you.
