### ISSUE TITLE
[deoplete] Delay of language server completions

### ISSUE THREAD

**Issue by monkoose** [autozimu/LanguageClient-neovim#609]
## Describe the bug
There is visible delay of the completions from language server protocol with deoplete.
First you receive some known completions like paths/buffer completions/snippets and then after some delay (actually known delay in ms of the deoplete config option, so for better visibility you can set it like this`call deoplete#custom#option('auto_complete_delay', 1000)` default is 50ms) you get completions from lsp. So it actually delayed twice. I don't get this delay from any other completion sources.
Yes you can decrease it to like 10ms or so, but there is still visible flickering that is annoying.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):  `NVIM v0.3.1`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.119`

**Comment by whitebyte** [comment]
Furthermore, if LanguageClient for some reason fails to provide completions, autocompletion popup keeps blinking, preventing you from selecting _any_ completion. This is a common case with React,js development and javascript-typescript-langserver.

**Comment by skbolton** [comment]
Yeah I have noticed a pretty big delay as well. I am pretty thankful to have any intelligent form of auto complete but would love for it to be a little faster. Has anyone found a way to improve the speed of the language completion?

**Comment by ahmedelgabri** [comment]
I have big delays in both completions & diagnostics too

**Comment by Shougo** [comment]
Unfortunately, it is LSP server side problem than LSP client problem.

If LanguageClient-neovim use diff update feature like vim-lsp, the performance may be improved though.

**Comment by skbolton** [comment]
Yeah I didn't investigate the exact reasons why, but shortly after posting my comment I realized that ALE has language server built in to it as well. I have since started using it and I am happy with the speed of its autocomplete. It it missing some of the features of this project like symbol look up, renaming of things, and other general nice to haves.

**Comment by martskins** [comment]
I'll close this as it's pretty dated and it's not clear whether it's still an issue or not, but feel free to re-open if anyone is still experiencing this.
