### ISSUE TITLE
Prune `bin/languageclient{,.exe}` from git history to reduce repository size

### ISSUE THREAD

**Issue by norcalli** [autozimu/LanguageClient-neovim#610]
Even with a shallow clone (done automatically by `vim-plug`) the git index contains the blobs of the previous commits which had `bin/languageclient` and `bin/languageclient.exe` before they began being fetched by a follow up download script.

Running the following command [taken from stackoverflow](https://stackoverflow.com/a/42544963/837964) to identify large objects it git index reveals the blobs in a shallow clone:

```sh
git rev-list --objects --all \
  | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
  | sed -n 's/^blob //p' \
  | sort --numeric-sort --key=2 \
  | cut -c 1-12,41- \
  | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

Result:
```
5e70781d1d68  105KiB src/languageclient.rs
16d3ba8ce1e6  105KiB src/languageclient.rs
df441950eea3  106KiB src/languageclient.rs
f3a88b6afbc0  106KiB src/languageclient.rs
0cf2302de42b  6.1MiB bin/languageclient
1e7857060d3d  6.2MiB bin/languageclient
a36af8314fca   58MiB bin/languageclient
ae32bb2d1f68   59MiB bin/languageclient
c49e5dff0e11   62MiB bin/languageclient
270c4d05238f   63MiB bin/languageclient
5d459dd9982c   65MiB bin/languageclient.exe
f876a54cba51   65MiB bin/languageclient
3d7d186f9d17   68MiB bin/languageclient
5be367c0f509   69MiB bin/languageclient.exe
440e8d20ad9e   69MiB bin/languageclient
8986e8f850e9   73MiB bin/languageclient.exe
7f5093c78e92   80MiB bin/languageclient.exe
```

There's a few ways to go about this, which are covered in [another stackoverflow answer](https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository).

I used this command to do it automatically for my local.
```sh
git filter-branch --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch bin/languageclient bin/languageclient.exe" \
  --tag-name-filter cat -- --all
```

And then to clean and prune the results:
```sh
git update-ref -d refs/original/refs/heads/master # Remove the backup head ref
git reflog expire --expire=now --all
git gc --prune=now # Clean it all up
```

I understand that you may not be interested in doing this (altering the commit history), but I thought I'd suggest it anyway. It drops the git repo from 170MB to less than 1MB on a shallow clone.

**Comment by autozimu** [comment]
Should have be resolved with PR https://github.com/autozimu/LanguageClient-neovim/pull/626

With a fresh installation, size is around 30M.
