### ISSUE TITLE
`let g:LanguageClient_hoverPreview = "Never"` only works sometimes

### ISSUE THREAD

**Issue by cmcaine** [autozimu/LanguageClient-neovim#611]
## Describe the bug

`let g:LanguageClient_hoverPreview = "Never"` should cause help messages to be echoed rather than opened in the preview window. It doesn't do that reliably: sometimes the messages are opened in the preview window, sometimes the same help is echoed if you try again after switching from one buffer to another and back again.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.1
- This plugin version (`git rev-parse --short HEAD`): 183fbf5
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.120
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): see example
- Language server link and version: python-language-server 0.21.2-2 from arch repos

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

```sh
vim -u ~/.local/share/nvim/plugged/LanguageClient-neovim/min-vimrc.vim foo.py
:let g:LanguageClient_serverCommands = {'python': ['pyls'] }
:LanguageClientStart
:nnoremap K :call LanguageClient#textDocument_hover()<cr>

# Observe that pressing K on keywords causes the preview window to open

let g:LanguageClient_hoverpreview = "Never"

# K still opens the preview window
# Switching to another buffer and back might fix it.
```

**Comment by whitebyte** [comment]
@cmcaine  hi, there is
```
let g:LanguageClient_hoverpreview = "Never"
```
in your code example. It works for me with `hoverPreview` (note the capital P).

**Comment by autozimu** [comment]
@whitebyte  nice finding!
