### ISSUE TITLE
keep the sign gutter open at all times

### ISSUE THREAD

**Issue by wizzup** [autozimu/LanguageClient-neovim#616]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
Option like [ale_sign_column_always=1](https://github.com/w0rp/ale#5ii-how-can-i-keep-the-sign-gutter-open) or [signcolumn=yes](https://github.com/airblade/vim-gitgutter#sign-column)

## Describe alternatives you've considered
1. Switch back to ALE
2. Use [vim-gitgutter](https://github.com/airblade/vim-gitgutter) and `set signcolumn=yes` (#13)

## Additional context

The very left column keep switching on/off while I am typing and it is very annoying.

![2018-09-22-142330_255x80_scrot](https://user-images.githubusercontent.com/342500/45914772-f6724300-be73-11e8-9b4e-f00b05057ff5.png)

![2018-09-22-142347_255x84_scrot](https://user-images.githubusercontent.com/342500/45914775-f8d49d00-be73-11e8-8a8b-a46217efbb3d.png)

**Comment by DerWeh** [comment]
You already wrote the solution to your problem. Just set `set signcolumn=yes`. It is just a Vim setting, nothing to do with plug-ins. If you just want it for buffers which have a language server, you can check if the file type is in the keys of `LanguageClient_serverCommands`.

**Comment by wizzup** [comment]
> Just set `set signcolumn=yes`. It is just a Vim setting, nothing to do with plug-ins.

Thanks, I have no idea that `signcolumn` is builtin.
