### ISSUE TITLE
warning: use of deprecated item 'std::env::home_dir'

### ISSUE THREAD

**Issue by herrbischoff** [autozimu/LanguageClient-neovim#620]
## Describe the bug

When compiling with `rustc 1.29.1 (b801ae664 2018-09-20)`, the following warning is output:

```
cargo build --release                                                                   
   Compiling languageclient v0.1.120 (file:///home/herrbischoff/.config/nvim/plugged/Lan
guageClient-neovim)                                                                     
warning: use of deprecated item 'std::env::home_dir': This function's behavior is unexpe
cted and probably not what you want. Consider using the home_dir function from https://c
rates.io/crates/dirs instead.                                                           
    --> src/languageclient.rs:2771:28                                                   
     |                                                                                  
2771 |                 let home = env::home_dir().ok_or_else(|| err_msg("Failed to get home dir"))?;                                                                            
     |                            ^^^^^^^^^^^^^                                         
     |                                                                                  
     = note: #[warn(deprecated)] on by default
```

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): `NVIM v0.3.1`
- This plugin version (`git rev-parse --short HEAD`): `288f1be`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.120 288f1beef601f8287be480ba144654ca91f86a8f`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): n/a
- Language server link and version: n/a

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## Expected behavior
Probably follow the suggestion given in the warning in exchanging the deprecated function for a supported one, to avoid breaking changes in the future.

**Comment by autozimu** [comment]
Thanks.

I've noticed this warning. The reason I haven't make the change is that the replacement lib doesn't support BSD, which is one of the target of this project.

**Comment by autozimu** [comment]
Or put it more accurately, the lib doesn't support cross-compiling to BSD.
