### ISSUE TITLE
Codelens not implemented?

### ISSUE THREAD

**Issue by tcoopman** [autozimu/LanguageClient-neovim#622]
As far as I can tell, it looks like codelens is not implemented? A lot of language servers start supporting it (for example 2 that I'm using: ElixirLs, Reason-language-server), so it would be awesome if this was implemented.

I see that you are tracking this in #177
(Didn't find the issue at first when searching for `lens` instead of `codelens`). Feel free to close this if you want to track it only at #177

**Comment by martskins** [comment]
I'm in the process of trying to implement `codeLens`, but I found that it somewhat overlaps with displaying diagnostics on virtual text (assuming we are showing them in virtual texts). Any thoughts on this? Should we disable one when the other is on? Should we just try to display all of them with the possibility of it becoming a mess?

**Comment by autozimu** [comment]
Now that both neovim and vim supports popup window, maybe we can use that.

**Comment by martskins** [comment]
I honestly feel like codeLens look a lot more natural inline with the code, as virtualText would display. And while diagnostics also feel more natural inline, they already have a natural place, which is the gutter. So if anything I would prefer moving the diagnostics from virtualText to a popup window, and display codeLens in virtualText.

![image](https://user-images.githubusercontent.com/4250565/71422578-26158980-267b-11ea-9a7a-4bad4f6e9d97.png)

Another option is making that configurable, but I can imagine that getting really messy really fast. In any case, this ends up being your decision, but I wanted to share my thoughts on this anyway.

**Comment by autozimu** [comment]
It looks like CodeLense itself is partially overlapping with diagnostics.

You can go ahead implement it with support of customization.
Default settings can be changed later.

**Comment by martskins** [comment]
Current status of my implementation of codeLens can be seen in #935.

**Comment by martskins** [comment]
Closing this, as #935 has already been merged and released.
