### ISSUE TITLE
Documentation mentions wrapper.sh, which doesn't exist anymore

### ISSUE THREAD

**Issue by languitar** [autozimu/LanguageClient-neovim#624]
The documentation currently states:

```
There is also an utility script in: >

    $RUNTIME/rplugin/python3/LanguageClient/wrapper.sh
```

This doesn't seem to exist anymore since migrating to rust.

**Comment by autozimu** [comment]
Moved to https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/wrapper-server.sh
