### ISSUE TITLE
textDocument_codeAction extremely slow

### ISSUE THREAD

**Issue by vsviridov** [autozimu/LanguageClient-neovim#625]
## Describe the bug
Populating the selections or applying the actions sometimes takes 10-15 seconds and sometimes it throws errors.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 01 2018 13:59:43)
Included patches: 1-189
```

- This plugin version (`git rev-parse --short HEAD`): `288f1be`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.120`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
set encoding=utf-8
scriptencoding utf-8
set nocompatible

call plug#begin('~/.vim/plugged')

" Plug 'w0rp/ale'
" Plug 'sheerun/vim-polyglot'
Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
Plug 'junegunn/fzf'

call plug#end()

syntax on

augroup typescript
        autocmd!
        autocmd BufReadPost *.ts setlocal filetype=typescript
augroup END

set signcolumn=yes

let g:LanguageClient_serverCommands = { 'typescript': ['typescript-language-server', '--stdio'] }

let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile = './LanguageClient.log'
let g:LanguageClient_serverStderr =  './LanguageServer.log'

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
nnoremap <F12> :call LanguageClient_textDocument_codeAction()<CR>
```
- Language server link and version: `typescript-language-server@0.3.6`

## Current behavior

https://asciinema.org/a/jO3EUTYXCcWVFsYPfSJCuPH5u

After pressing enter for the fix, the actual fix take a long time and results in both an error and the fix being applied. Sometimes the popup for actions takes similar amounts of time to populate

## Expected behavior
I expect the selections to populate in reasonable time, and the application of a fix to happen in reasonable time without errors

## Additional comments
You can see in the log that the language server provides the data to for the fix pretty much immediately...

**Comment by vsviridov** [comment]
Possibly similar to #546

**Comment by autozimu** [comment]
Right. Going to track the progress at https://github.com/autozimu/LanguageClient-neovim/issues/546. Closing this.
