### ISSUE TITLE
How to integrated with sourcegraph/sourcegraph

### ISSUE THREAD

**Issue by und3fined** [autozimu/LanguageClient-neovim#627]
Hi

New trending on github show a opensource [sourcegraph/sourcegraph](https://github.com/sourcegraph/sourcegraph), it's faster LSP
Please integrated with this extension

Thanks

**Comment by Avi-D-coder** [comment]
@und3fined What makes sourcegraph faster than the LSP servers? It uses LSP servers on the backend.

**Comment by Anrock** [comment]
If it uses LSP - what else integration does it need?

**Comment by und3fined** [comment]
Sorry all, I'm confused here
