### ISSUE TITLE
Scrub .git history and remove references to binary files no longer in use

### ISSUE THREAD

**Issue by satiani** [autozimu/LanguageClient-neovim#628]
When trying to clone this repository with default git clone options, you'd be downloading hundreds of MBs down the wire due to old binary files no longer in user, in particular see the below output from git-ls-tree:

```
100755 blob 7f5093c78e923d30c966d36d1b9fd4e721cc304c 84066247   bin/languageclient.exe
100755 blob 440e8d20ad9e48dcf0f2a462284c1d293885a4f7 72804120   bin/languageclient
100755 blob 5be367c0f5097ba0bac4dd9240324fd5185654e9 71963585   bin/languageclient.exe
100755 blob f876a54cba51b923d801eac9396ec5582c724013 68633752   bin/languageclient
100755 blob c49e5dff0e11b36be990d54d5394ed2165882dd1 64750408   bin/languageclient
100755 blob affbf9e6843ef753c306e1f2dfc7572643bb7542 14497158   bin/languageclient.exe
100755 blob bd2242c78f771e5622dd49b33d1e04982e1bb71e 14328184   bin/languageclient.exe
100755 blob 123a6e79eb1a0ca99c48f2a8fc3408ce4b395e8b 10645344   bin/languageclient
100755 blob 56e109b83368f94eb991707573824b4721ef66e6 9853316    bin/languageclient
100755 blob 39e68c4a7d0cd4a0ddfbaf2aa433a9f05e314cb6 8834256    bin/languageclient
100755 blob e78b16c8e42f8b56780152bdc13d31ca991333e9 7457517    bin/languageclient
100755 blob 0cf2302de42be8a566547ff17d2ce7850d2b0677 6347732    bin/languageclient
100755 blob 91d52ba4a875905d9d18b495eac61bd4e0afa5ac 5362476    bin/languageclient
```

Many vim plugin managers rely on the default git clone options to download (e.g. dein), which means that this repository often takes more than a few minutes on slow connections. Even with plugins like vim-plug, which does `--depth 1` by default, the download is still very large since it also specifies `--no-single-branch` during cloning.

It would be great if you could scrub the git history from references to those files.

**Comment by autozimu** [comment]
This was introduced by a previous change to include debug symbol in release binaries.

Should have been resolved with PR https://github.com/autozimu/LanguageClient-neovim/pull/626
