### ISSUE TITLE
Allow user to configure on/off for `Realtime diagnostics/compiler/lint message`

### ISSUE THREAD

**Issue by springcold** [autozimu/LanguageClient-neovim#63]
I came to know about this plugin from deoplete and the intention for installing was mainly for its autocompletion source (Which is really amazing)

For me personally, the realtime factor is not really necesary and can be slightly distracting at times.
Therefore, allow turning the diagnostic off will be helpful for me.

Maybe we could have states like:
* Realtime
* On save
* Off

Thank you!

**Comment by autozimu** [comment]
Should be easy to achieve.

**Comment by Alok** [comment]
I'd love if this was done too. I use `neomake` for error messages and I don't want to see signs or echoed messages in the statusline from the language server.

**Comment by lorenzo** [comment]
Was this actually implemented? I cannot see an option to only request diagnostics on save
