### ISSUE TITLE
support environment variables when starting a language server

### ISSUE THREAD

**Issue by kodonnell** [autozimu/LanguageClient-neovim#631]
## Is your feature request related to a problem? Please describe.

I want to use python-language-server with conda environments. Currently I can set 

```
g:LanguageClient_serverCommands.python = ['/home/user/miniconda3/envs/neovim/bin/pyls']
```

which runs pyls from my `neovim` env. However, if I'm developing in `myenv` it won't support e.g. completions for any of the packages in `myenv` (since they're not in the `neovim` env). There seems to be a lot of effort trying to fix this, but I can't (yet) see any solutions that aren't really hacky. I'm hoping that one possible (still not awesome) solution would be:

```
g:LanguageClient_serverCommands.python = ['PYTHONPATH=/home/user/miniconda3/envs/myenv/lib/python3.6/site-packages /home/user/miniconda3/envs/neovim/bin/pyls']
```

However, this fails, and other permutations (presumably something to with rust's command execution). It looks like you could easily set environment variables with `.env(...)` [here](https://github.com/autozimu/LanguageClient-neovim/blob/9a8eb0a1ea20263ba1b6819c026c1b728bc25463/src/languageclient.rs#L2807-L2816).

I imagine there are other cases where users would want to set environment variables.

## Describe the solution you'd like
To be able to set an environment variable before starting a language server. I don't mind how.

## Describe alternatives you've considered
See attempts above, which didn't work (surprisingly).

**Comment by autozimu** [comment]
This has already been supported.

By default, any subprocess started will inherit env variables from its parents, which means if you want to pass an env variable to the language server, you have at least two approaches,
- set the variable from your shell invoking vim, e.g., at your shell init file, add
```sh
export PYTHONPATH=/home/user/miniconda3/envs/myenv/lib/python3.6/site-packages:/home/user/miniconda3/envs/neovim/bin/pyls
```
- alternatively, set the env variable at your vim init file,
```vim
let $PYTHONPATH='/home/user/miniconda3/envs/myenv/lib/python3.6/site-packages:/home/user/miniconda3/envs/neovim/bin/pyls'
```
