### ISSUE TITLE
Undefined g:LanguageClient_serverCommands with vim-plug installed server

### ISSUE THREAD

**Issue by cprn** [autozimu/LanguageClient-neovim#635]
- Did you upgrade to latest plugin version?
Yes, via `vim-plug`.

- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
I think so? via `vim-plug`?
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
Yes, both checks green.
- Did you check [troubleshooting]?
Yes, no answer there.

## Describe the bug
I'm using `felixfbecker/php-language-server` but installed via wrapper plugin `roxma/LanguageServer-php-neovim` and when used like that the `LC_maps()` function from `:help LanguageClient` complains about missing variable during buffer open but works okay when `:call LC_maps()` command is issued afterwards.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.2.2

- This plugin version (`git rev-parse --short HEAD`):
288f1be
- This plugin's binary version (`bin/languageclient --version`):
languageclient 0.1.120
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```viml
" vim-plug + plugins {
    call plug#begin('~/tmp/testvim')
    Plug 'autozimu/LanguageClient-neovim',  {'branch': 'next', 'do': 'bash install.sh'}
    Plug 'roxma/LanguageServer-php-neovim', {'for': 'php', 'do': 'php ~/bin/composer install && php ~/bin/composer run-script parse-stubs'}
    call plug#end()
" }

" copied from `:help LanguageClient` {
    function LC_maps()
      if has_key(g:LanguageClient_serverCommands, &filetype)
        nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<cr>
        nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
        nnoremap <buffer> <silent> <leader>rn :call LanguageClient#textDocument_rename()<CR>
      endif
    endfunction

    autocmd FileType * call LC_maps()
" }
```

- Language server link and version:
roxma/LanguageServer-php-neovim#11

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Install `vim-plug`
1. Start `nvim -u` with testing `vimrc` provided above
1. Execute `:PlugInstall`
1. Try to open buffer of an existing file
1. See error:
```
Error detected while processing function LC_maps:
line    1:
E121: Undefined variable: g:LanguageClient_serverCommands
E116: Invalid arguments for function has_key
E15: Invalid expression: has_key(g:LanguageClient_serverCommands, &filetype)
Press ENTER or type command to continue
```

## Current behavior
The `LanguageClient_registerServerCommands()` function called in [ftplugin/php.vim](https://github.com/roxma/LanguageServer-php-neovim/blob/master/ftplugin/php.vim) creates variable `g:LanguageClient_serverCommands` after the `LC_maps()` function is called therefore no bindings are set.

## Expected behavior
A `g:LanguageClient_serverCommands` has the key from `vim-plug` installed language server on buffer open and `LC_maps()` function sets the bindings.

## Additional context
I understand this issue lies in a gray area between a bug and a feature request and I'm not asking you to *just fix it* but I am asking for help in coming up with a good practice for a generic vim plugin that installs a language server. Maybe you can recommend a different file to put `LanguageClient_registerServerCommands()` call in so that the necessary variable key would be present on buffer open? Another solution would be to maybe find a different generic condition for the `if` statement that checks whether the language server will run for a given buffer or not and update the help file?

It's a cross post of the issue from roxma's repository as I'm not sure where it belongs.

**Comment by ealves-pt** [comment]
@cprn I had the same problem and managed to get rid of it by initializing the **LanguageClient_serverCommands** with `let g:LanguageClient_serverCommands = {}`

**Comment by cprn** [comment]
Yeah, I know, but it seems to defeat the purpose of packaging language servers as separate vim plugins. 

Normally you just install the client as a vim plugin and do the rest (installing server binaries, configuring the executable path and the language to use it with in vimrc) by hand. In that approach setting this variable and it's values in `vimrc` makes perfect sense. When you install both as vim plugins, though, the idea is for the server plugin to provide the necessary settings for you. If it doesn't and you still  have to copy & paste something into your `vimrc`, it becomes basically useless.

I created this issue in hope a solution for better server packaging would be found.

**Comment by Anrock** [comment]
Last time i checked the code all config values (or at least `diagnosticsDisplay` also) was defaulted on plugin-side and wasn't exposed to vim.

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by Anrock** [comment]
@autozimu could you also export defaults of `diagnosticsDisplay` too?

**Comment by autozimu** [comment]
Just curious, what is the use case for that?

It's a complex struct, which might become out-of-sync when having two copies.

**Comment by Anrock** [comment]
@autozimu for some reason i can't make warning, info and hint symbols to properly show - they're displayed as unknown symbol. So i have to copypaste whole default `diagnosticsDisplay` dictionary just to replace three characters.

**Comment by autozimu** [comment]
If that's it , you can use the copy in doc https://github.com/autozimu/LanguageClient-neovim/blob/82055bc61211717802cb1efbd734bd41ed823825/doc/LanguageClient.txt#L97-L122

**Comment by Anrock** [comment]
That's exactly what i'm doing.
