### ISSUE TITLE
[Scala] Does a Unix Sock work?

### ISSUE THREAD

**Issue by vito-c** [autozimu/LanguageClient-neovim#637]
- Did you upgrade to latest plugin version? yup
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. `languageclient 0.1.123 283dba5754055c74e250166a99017914624625b1`
should this be on my path or is installing it via vim-plug enough?
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/vito.cutten/code/configs/pirate-vim/bundle/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.123 283dba5754055c74e250166a99017914624625b1
```
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
I'm trying to setup sbt server to work with LanguageClient-neovim and I put the file location of the unix sock but I keep getting this error `Language server is not running for: scala` even though `{'scala': ['/Users/vito-c/.sbt/1.0/server/7db92e93362923fb032b/sock']}` is up and running

**Comment by autozimu** [comment]
Unix domain socket is not supported. Only stdio and tcp connection is supported.

What is your use case? Why you need to use unix domain socket?

If the language server exposes only unix domain socket, you could have a wrapper connect it to a tcp port.

**Comment by vito-c** [comment]
yah there is a wrapper. I just thought a unix socket would work since that is also the default way that neovim enables connections via it's api

**Comment by autozimu** [comment]
Closing this for now as it doesn't seem like a of people would need this.

Would consider reopen if there is more users request this.
