### ISSUE TITLE
Links in Readme > features are dead

### ISSUE THREAD

**Issue by bew** [autozimu/LanguageClient-neovim#64]
Links at https://github.com/autozimu/LanguageClient-neovim#features are all dead, they points to a repo at https://github.com/autozimu/images which doesn't exists (anymore).

Could be fixed by using links targeting specific comments in your [Update, Screenshot & GIFs](https://github.com/autozimu/LanguageClient-neovim/issues/35) issue.

**Comment by autozimu** [comment]
Aha, thanks for pointing out.

I will update asap.
