### ISSUE TITLE
Group/Sort Completion Results

### ISSUE THREAD

**Issue by theFroh** [autozimu/LanguageClient-neovim#641]
## Is your feature request related to a problem? Please describe.
LanguageClient completions rightfully pop to the top of Deoplete's popup due to the ranking of the source, but long lists of completions can still be less than useful due to a lack of ranking within the results themselves.

## Describe the solution you'd like
Consider grouping or sorting (or allowing rank to be configured) by the presence of tags such as "Property" (uncertain of the correct term here).

For example, in Javascript, listing *Property* completions of the currently-being-typed object first would be quite helpful.

## Describe alternatives you've considered
I've poked around to see if this was resolvable via sorters in Deoplete, but that is very much a "rank the source (LC) amongst other sources" (useful, but not an issue here) and "sort results alphabetically" (which doesn't really help here).

An alternative would be a modification in Deoplete's end involving adding some ability to rank results by words within them.

## Additional context
Some screenshots illustrating how, in this JS example, VSCode simply bringing the properties of an object to the top of its completion window is useful.

Working within Vim:
![image](https://user-images.githubusercontent.com/2473822/47635341-987dfd00-db8f-11e8-8792-bb55ceeb1375.png)

After navigating the completion popup a little:
![image](https://user-images.githubusercontent.com/2473822/47635389-c5caab00-db8f-11e8-963d-f550414a6b85.png)

Working within VSCode:
![image](https://user-images.githubusercontent.com/2473822/47635226-3e7d3780-db8f-11e8-9125-ad4980c9d525.png)

**Comment by autozimu** [comment]
I suppose you're using this language server, https://github.com/sourcegraph/javascript-typescript-langserver.

To make it clear, vscode uses a different language server from this referenced one.

The way it should work is that language server returns a list of items containing property of `sortText`, which editor can make use of to display items accordingly. But this referenced language server is lacking this functionality (it is returning items whose `sortText` are all `1`).

Please file this bug at the language server side.

**Comment by theFroh** [comment]
Ah great to see it is a LSP server responsibility!

I should note it doesn't seem to be passing back a sortText value at all (a full 'DEBUG' log dump after requesting autocomplete results and seeing the above contains no mention of "sortText").
