### ISSUE TITLE
Always keep the status column on the left to avoid text area jump?

### ISSUE THREAD

**Issue by comicfans** [autozimu/LanguageClient-neovim#644]
## Is your feature request related to a problem? Please describe.
When LSP shows warning/linter hint on some line , whole text area will jump to right , 

![2018-10-31_12-10](https://user-images.githubusercontent.com/4547108/47765786-9f7b4b80-dd06-11e8-9281-173ab72c9e96.png)
![fixed](https://user-images.githubusercontent.com/4547108/47765790-a43fff80-dd06-11e8-9878-49c853bc0b83.png)

when warning is fixed , line hint disappears, text area will jump back. while quickly typing/fixing lines, this causes text area very unstable.

## Describe the solution you'd like

can I set LanguageClient-neovim to always hold status column (maybe a blank char) to avoid this problem? (maybe vim has a option for this? but I didn't found it)

**Comment by Anrock** [comment]
See #616

**Comment by comicfans** [comment]
@Anrock Thank you for that
