### ISSUE TITLE
Quickly close preview window?

### ISSUE THREAD

**Issue by olalonde** [autozimu/LanguageClient-neovim#645]
Is it possible to quickly close the preview window that is opened by `:call LanguageClient#textDocument_hover()<CR>`? It's a bit annoying having to switch to that window and type `:q` every time (`<C-k> :q` 5 key strokes with my key bindings).

edit: just found this answer on StackOverflow: https://vi.stackexchange.com/a/4057 That said, the default key bindings are still a bit annoying. Wouldn't it be possible to close the preview window if `:call LanguageClient#textDocument_hover()<CR>` is called a second time for the same symbol?

edit: ended up with those key bindings for now (that way to close the preview window I can just keep my finger on shift and press w):

```viml
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> W :pclose<CR>
```

**Comment by DerWeh** [comment]
I don't really think a something is needed here. I think this is more something for the user, you could e.g. map `K` to the function which closes the preview window if not open, else it triggers `textDocument_hover`. Is this an acceptable solution for you?

I think it would be nice to add a mapping to close the preview with `q` if you are in that buffer. It is a common mapping for most plug-ins I have seen. And while we are at it, why is the buffer modifiable?


I  always have the following key bindings to quickly close surrounding windows:

```vim
" delete window with d<C-?>
nnoremap d<C-j> <C-w>j<C-w>c
nnoremap d<C-k> <C-w>k<C-w>c
nnoremap d<C-h> <C-w>h<C-w>c
nnoremap d<C-l> <C-w>l<C-w>c
```

**Comment by autozimu** [comment]
Also,

```
CTRL-W z					*CTRL-W_z*
CTRL-W CTRL-Z					*CTRL-W_CTRL-Z* *:pc* *:pclose*
:pc[lose][!]	Close any "Preview" window currently open.  When the 'hidden'
		option is set, or when the buffer was changed and the [!] is
		used, the buffer becomes hidden (unless there is another
		window editing it).  The command fails if any "Preview" buffer
		cannot be closed.  See also |:close|.

```
