### ISSUE TITLE
Setting LanguageClient_documentHighlightDisplay does not work

### ISSUE THREAD

**Issue by horta** [autozimu/LanguageClient-neovim#647]
languageclient 0.1.125 e272010569deae73ba3235b63f2c7c775fd2bf72

## Describe the bug

Adding

```
let g:LanguageClient_documentHighlightDisplay =
            \ {
            \     1: {
            \         "name": "Text",
            \         "texthl": "Normal",
            \     },
            \     2: {
            \         "name": "Read",
            \         "texthl": "Normal",
            \     },
            \     3: {
            \         "name": "Write",
            \         "texthl": "Normal",
            \     },
            \ }
```

into my ~/.config/nvim/init.vim does not seem to interfere with the highlighting. In particular, I would like to get rid of those underlines:

https://file.globalupload.io/KvojbHJ9JR.png

I'm using NVIM 0.3.1.

Line https://github.com/autozimu/LanguageClient-neovim/blob/e272010569deae73ba3235b63f2c7c775fd2bf72/src/languageclient.rs#L126 seems to fetch that value, but somehow not using it.

**Comment by martskins** [comment]
I'll close this as it's quite dated and I've recently proven it works.
