### ISSUE TITLE
Clears Quickfix window on startup?

### ISSUE THREAD

**Issue by olalonde** [autozimu/LanguageClient-neovim#649]
## Describe the bug
When this plugin loads, it clears the quickfix window for no apparent reason? This breaks things like `vim -c ":make" index.test.js` which populate the quickfix window before this plugin clears it.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/config -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180831-45030-1c6df1y/neovim-0.3.1/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"

Run :checkhealth for more info
```
- This plugin version (`git rev-parse --short HEAD`): 471da1c

- This plugin's binary version (`bin/languageclient --version`):languageclient 0.1.124 d0c8a2bfb36b8045932212087448e4e722760b6e
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version: https://github.com/sourcegraph/javascript-typescript-langserver

**Comment by olalonde** [comment]
Appears related: https://github.com/autozimu/LanguageClient-neovim/issues/583#issuecomment-418217703

**Comment by autozimu** [comment]
Should have been resolved by https://github.com/autozimu/LanguageClient-neovim/pull/648.

Please reopen with reproduction steps if it still happens.
