### ISSUE TITLE
Remove support for rustDocument/implementations

### ISSUE THREAD

**Issue by dimbleby** [autozimu/LanguageClient-neovim#652]
`rustDocument/implementations` was removed from rls back in July - at [this commit](https://github.com/rust-lang-nursery/rls/commit/addb8b52).  It now uses the standard `textDocument/implementation`.

Happy to submit a pull request deleting all references to it - though there'll be a (tiny) conflict with #648 so I'll probably wait for that to get through (or not!) first.

**Comment by autozimu** [comment]
+1
