### ISSUE TITLE
After rename across files, didChange returns the wrong text content

### ISSUE THREAD

**Issue by snoe** [autozimu/LanguageClient-neovim#659]
## Describe the bug
Rename a symbol that is present in two files. 

When the server sends back the two textEdits they are properly applied. 

However, the follow up didChange notice for both documents contains the text content from the first file. 

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.0
- This plugin version (`git rev-parse --short HEAD`): 95608f5
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.127 
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version: https://github.com/snoe/clojure-lsp release-20181120T050154

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
text of test.clj = "(defn foo [])"
text of thing.clj = "(declare foo)"
rename to produce a change like this (see lc-errors.log[0] line 279): 
```
{"jsonrpc":"2.0","result":{"changes":{"file:///private/tmp/test.clj":[{"newText":"foobar","range":{"end":{"character":9,"line":0},"start":{"character":6,"line":0}}}],"file:///private/tmp/thing.clj":[{"newText":"foobar","range":{"end":{"character":12,"line":0},"start":{"character":9,"line":0}}}]}},"id":5}
```

## Current behavior (see lc.errors.log[0] lines 332 and 319)
didChange.text of test.clj = "(defn foobar [])"
didChange.text of thing.clj = "(defn foobar [])"

## Expected behavior
didChange.text of test.clj = "(defn foobar [])"
didChange.text of thing.clj = "(declare foobar)"

## Additional context
*Lines 313-316 look suspicious*, it seems LSP#text() is being run and getting the current buffer's text?
```
23:07:51 INFO main src/languageclient.rs:49 gather_args: [LanguageId, Filename] = [String("clojure"), String("/private/tmp/thing.clj")]
23:07:51 INFO main src/languageclient.rs:30 Some arguments are not available. Requesting from vim. Keys: ["text"]. Exps: ["LSP#text()"]
23:07:51 INFO main src/vim.rs:92 => None {"jsonrpc":"2.0","method":"eval","params":["[LSP#text()]"],"id":53}
23:07:51 INFO reader-main src/vim.rs:390 <= None {"id": 53, "jsonrpc": "2.0", "result": [["(defn foobar [])", ""]]}
```

[lc-errors.log](https://github.com/autozimu/LanguageClient-neovim/files/2598355/lc-errors.log)

**Comment by snoe** [comment]
Looking through the logs, I suspect that what's happening is:

1. rename from buffer A - changes buffer A and B
2. LC switches to buffer B
3. edits are applied to buffer B
4. LC switches to buffer A
5. edits are applied to buffer A
6. didChange is sent for B with LSP#text() so it sends content of buffer A. **<--- error here**
7. didChange is sent for A with LSP#text() so it sends content of buffer A.

**Comment by autozimu** [comment]
Thanks for reporting.

**Comment by snoe** [comment]
Thank you! This is great.
