### ISSUE TITLE
different behaviour for `LanguageClient_textDocument_hover`

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#66]
I recently switched from [jedi-vim](https://github.com/davidhalter/jedi-vim) to **LanguageClient-neovim** with the python server. The main reason is the improved performance.

I found [jedi-vim](https://github.com/davidhalter/jedi-vim)'s  `jedi#show_documentation()` way more helpful, especially for complicated functions from imported modules. 

What I would suggest is splitting `LanguageClient_textDocument_hover` into two functions. One function (`LanguageClient_text_Document_documentation`) providing something like [jedi-vim](https://github.com/davidhalter/jedi-vim), this means opening a new window with the documentation, and mapping `q` to `quite`. This allows you to have (a lengthy) documentation open, while writing code. And another function (`LanguageClient_textDocument_hover`) which echos only the first line, so that it can easily be assigned to an `CursorHold` autocommand.

**Comment by autozimu** [comment]
I cannot do that easily. It is defined in the protocol.

Ideally neovim UI shall have a popup window to show signature and documentation at the same time, like VSCode does.
