### ISSUE TITLE
CompletionItem::textEdit support is incorrect

### ISSUE THREAD

**Issue by MaskRay** [autozimu/LanguageClient-neovim#662]
## Describe the bug
When `CompletionItem.textEdit` is present but `CompletionItem.insertText` is absent, completion triggered by `triggerCharacter` does not display the completion item correctly.

```cpp
#include <bits/stdc++.h>
int main() { std::xplicit }
/*
atomic_fetch_and_explicit
*/
```

I've set `g:LanguageClient_completionPreferTextEdit` to 1

And IMHO `g:LanguageClient_completionPreferTextEdit` should just default to 1 if the server sends `CompletionItem.textEdit`.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.2-649-g512e0caae
- This plugin version (`git rev-parse --short HEAD`): 13fc7e2 
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.129
- Language server link and version: https://github.com/MaskRay/ccls/

## To Reproduce
1. Start vim
2. `let g:LanguageClient_completionPreferTextEdit = 1`
3. Insert boilerplate and `std::`
4. Select the first completion item
5. See error

## Current behavior
`newText` is somehow inserted from the line beginning though it does not overwrite existing characters.

## Expected behavior
`newText` should be inserted in the correct position, not from the line beginning.

**Comment by JeanMertz** [comment]
I believe I am hitting the same issue, while using rust-analyser.

When I complete the selection at this point:

<img width="457" alt="screenshot 2019-02-14 at 08 23 12" src="https://user-images.githubusercontent.com/383250/52769851-d9602b80-3031-11e9-9324-f19e82c4f3e5.png">

I end up with this result:

<img width="340" alt="screenshot 2019-02-14 at 08 23 24" src="https://user-images.githubusercontent.com/383250/52769865-e250fd00-3031-11e9-93cd-e6fdf232106f.png">

If I disable `g:LanguageClient_completionPreferTextEdit`, things work as expected.

**Comment by dimbleby** [comment]
I believe that the specific way in which prefer-text-edits is broken is per my comment in https://github.com/autozimu/LanguageClient-neovim/issues/857#issuecomment-517236481

> The way that this language client tries to implement prefer-text-edits is to accept the completion as specified by the server in the label, and then when the completion is done it undoes that and applies the text edits instead.
> 
> See languageClient_handleCompleteDone, called at the CompleteDone autocmd - here is the undo.
> 
> Unfortunately this is not so good unless you break the undo sequence before starting the completion (see :help i_Ctrl-G_u), because otherwise you are likely to undo much more than is intended, and then also end up making the text edit in completely the wrong place.

**Comment by dimbleby** [comment]
https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp/omni.vim#L321 is an interesting solution.  Instead of undoing the original completion, expand the text edit so that it just removes the unwanted completion.

**Comment by martskins** [comment]
I believe this is no longer an issue so I'll close this one, but feel free to re-open if you are still seeing this.
