### ISSUE TITLE
Use NeoVim Virtual Text

### ISSUE THREAD

**Issue by pwntester** [autozimu/LanguageClient-neovim#664]
Hi,

It would be great to offer an option to show the errors/warnings using new virtual text feature (`nvim_buf_set_virtual_tex`t) as, for example, ALE does (see https://github.com/w0rp/ale/pull/2056).

Thanks for the project!
A

**Comment by megalithic** [comment]
@autozimu this'd be fantastic! presently the main reason i'm still using ALE for linting + formatting.

**Comment by noomly** [comment]
It would be awesome! Is there any news on this?

**Comment by DerWeh** [comment]
`Neomake` also offers this feature, in case further examples are helpful. However, “wrapping” is missing, I always have some splits open so often enough the message is truncated...
But one step after another.

**Comment by hadronized** [comment]
Upping this! :)

**Comment by h-michael** [comment]
@autozimu Thanks for your work!! :)
https://github.com/autozimu/LanguageClient-neovim/commit/42883606a6e140bf1d922a77b2a0cc5d092d8d5c#diff-955b9d08c78bce4bdc145172ff4eaf7d

**Comment by caneta** [comment]
Great! Now...how to configure it?

**Comment by h-michael** [comment]
See document. https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L343

**Comment by ikcalB** [comment]
@autozimu this is GREAT!

wrapping (or maybe only 'sliding') the docstring would be awesome! (I'm aware that neovim does not (currently)? implement "reflow of virtual text")

### What i mean by sliding?
Maybe it'd be a compromise to 'slide' the first displayed character backwards while typing / finishing an argument?  
With splits open, and 1..3 arguments visible (depending on indetation level and docstring) it was possible to see the description of argument 3 onwards?

@DerWeh  Manually detecting how much of the string is shown & displaying that on the following line(s) might hardly be usable? (changing position to look on any character typed / arg completed)
