### ISSUE TITLE
Tagbar like overview using textDocument_documentSymbol

### ISSUE THREAD

**Issue by teasp00n** [autozimu/LanguageClient-neovim#665]
I like having an overview of the current buffer in it's own pane for understanding (and to a lesser extend navigation although existing `textDocument_documentSymbol` integration is better suited for that) purposes.

Currently I use tagbar to do this however it would be ideal to consolidate this functionality under the LSP given `textDocument_documentSymbol` provides the information we need to do it.

Does something like this fit in the scope of LanguageClient-neovim or do you think it should exist as a separate plugin?

You're probably familiar with what I'm talking about but just for completeness, this is an example of what I'm after:

![tagbar](https://user-images.githubusercontent.com/2267241/49049506-5b129b00-f233-11e8-8ce9-2924adeb0786.png)

**Comment by DerWeh** [comment]
Sounds great. If someone thinks about implementing this, it would be awesome if the best things of `tagbar` and [taglist](http://vim-taglist.sourceforge.net/index.html) could be bought together.
If `workspaceSymbols` is implemented, this should also be used.

**Comment by whitebyte** [comment]
Kinda related to #501

**Comment by gbrlsnchs** [comment]
@teasp00n at this point you may already know [vista.vim](https://github.com/liuchengxu/vista.vim), but if you don't, I think you may close this issue and use that instead. It's an LSP-based tagbar with FZF support for symbols which you can feed using LanguageClient-neovim.

**Comment by teasp00n** [comment]
@gbrlsnchs I have found that actually thanks for sharing!
