### ISSUE TITLE
Customize completion request triggers

### ISSUE THREAD

**Issue by pwntester** [autozimu/LanguageClient-neovim#667]
Hi

Is there a way to customize when deoplete request the completion candidates to the LS? I need to be able to trigger a completion request after `[` char.

According to [this](https://github.com/autozimu/LanguageClient-neovim/blob/next/autoload/LanguageClient.vim#L918):

```
function! LanguageClient#get_complete_start(input) abort
    " echomsg a:input
    return match(a:input, '\k*$')
endfunction
```

If I understood it correctly `\k` is expanded to `isKeyword` and therefore, I should be able to control it using:

```
call deoplete#custom#option('keyword_patterns', {
    \ 'myfiletype': '\S+',
    \})
```
Which should consider a keyword any sequence of non-whitespaces, including `[`.
This is not working though, any idea why?

Thanks in advance!

**Comment by autozimu** [comment]
https://github.com/Shougo/deoplete.nvim/issues/881
