### ISSUE TITLE
LanguageClient fails to load (binary problem?)

### ISSUE THREAD

**Issue by bronzehedwick** [autozimu/LanguageClient-neovim#668]
- Did you upgrade to latest plugin version? Yes
- Did you upgrade to/compile latest binary? Yes, upgraded through Plugged, then manually by running `install.sh`.
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes, got the error there as well.
- Did you check [troubleshooting]? Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): `NVIM v0.3.1`
- This plugin version (`git rev-parse --short HEAD`): `13fc7e2`
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.129 61e4ed39386c317de1b53c44da22049e67a79203`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): Using `min-vimrc.vim`
- Language server link and version: https://github.com/rust-lang/rls `rustup 1.11.0 (e751ff9f8 2018-02-13)`

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Start neovim, `nvim -u min-vimrc.vim`
1. See error

## Current behavior
When I start neovim, and when I use any movement commands or try to use language client features directly, I get this error:

```
Error detected while processing CursorMoved Auto commands for "*":
E117: Unknown function: LanguageClient#handleCursorMoved
Press ENTER or type command to continue
Error detected while processing TextChanged Auto commands for "*":
E117: Unknown function: LanguageClient#handleTextChanged
Press ENTER or type command to continue
```
I ran `:checkhealth` and got a similar error:

```
    - ERROR: Failed to run healthcheck for "LanguageClient" plugin. Exception:
      function health#check[21]..health#LanguageClient#check[2]..<SNR>138_checkBinary, lin
      e 1
      Vim(let):E117: Unknown function: LanguageClient#binaryPath
```

No one else seems to be having this issue, so maybe I'm doing something wrong, but any help would be greatly appreciated.

## Additional context
I have this problem on my home and work laptops. My work laptop runs macOS 10.13 and my home laptop runs macOS 10.14

**Comment by whitebyte** [comment]
Looks like https://github.com/autozimu/LanguageClient-neovim/issues/619
You can try to check your LanguageClient binary permissions and ownership and set it to, say, 664 and check again

**Comment by bronzehedwick** [comment]
Interesting. Unfortunately when I re-install the binary via `install.sh` I do get the correct permissions:

```
.rwxr-xr-x 5.6M delucac  3 Dec 13:49 languageclient
```

**Comment by dhollinger** [comment]
I'm seeing this issue on Macbook running MacOS 10.14 and on my Linux laptop running Ubuntu 18.04. languageclient binary is executable and re-running `install.sh` does **not** fix the issue

**Comment by simonwahlgren** [comment]
I'm having exactly the same problem and I also have the correct permissions. One moment it worked perfectly the other moment it just stopped working.

**Comment by simonwahlgren** [comment]
Removing the session file "fixes" the problem temporarily. Duplicate of https://github.com/autozimu/LanguageClient-neovim/issues/533

**Comment by wmonk** [comment]
@bronzehedwick did you get anywhere with this? I've just encountered today.

**Comment by bronzehedwick** [comment]
Unfortunately not @wmonk, I actually haven't been using LanguageClient for a bit. I'll close this in favor of #533.

**Comment by stone8419** [comment]
how can i do this?
# ./languageclient 
Segmentation fault
