### ISSUE TITLE
LanguageClient_textDocument_references -- add line

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#67]
I use the **LanguageClient** with the python server, and don't really know on which side is responsible. But I think the `LanguageClient_textDocument_references` function should not only populate [Denite](https://github.com/Shougo/denite.nvim) with the file and line information, but also show the content of the line.

**Comment by autozimu** [comment]
I think it might be possible. But to be honest, I don't feel too much motivation to investigate it though.

Feel free to implement and make a PR if you feel the urgent. Thanks.
