### ISSUE TITLE
I want to hide the description at the top of the screen.

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#677]
## Describe the solution you'd like
When complementing, a description window will be displayed at the top of the screen. Is there a way to hide this?

I'm using deoplete.nvim.

## Additional context
My Neovim setting
```
    set hidden

    let g:LanguageClient_serverCommands = {
        \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
        \ }

```

**Comment by autozimu** [comment]
```
:help completeopt
```

**Comment by nabezokodaikon** [comment]
thank you!
