### ISSUE TITLE
LanguageClient requires Python3.7

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#685]
The current version of the LanguageClient requires Python3.7 as of dfdf91743e0246063e16526ef3ead4342a15c886. The reason that `defaults` parameter of `namedtuple` is used, which was only added in Python3.7. This requirement is nowhere stated and rather harsh in my opinion as Python3.7 is still very new.
I am personally using intelpython, where the newest version is only 3.6.5.

Please consider dropping the `defaults` parameter and make it compatible with Python3.5, or at least state the requirement of Python3.7.

**Comment by autozimu** [comment]
@ficoos Can you take a look?
