### ISSUE TITLE
Suggestion: should not use RPC autocmds

### ISSUE THREAD

**Issue by Shougo** [autozimu/LanguageClient-neovim#69]
LanguageClient-neovim defines some RPC autocmds.
https://github.com/autozimu/LanguageClient-neovim/blob/ba9b4280d7429bb7596bd9bfccd9fc72ec0aa97e/rplugin/python3/LanguageClient/LanguageClient.py#L349

It slows neovim startup.
Please see below issues.

https://github.com/neovim/neovim/pull/5856
https://github.com/neovim/neovim/issues/5728

I think LanguageClient-neovim should use RPC events instead.
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/__init__.py

**Comment by autozimu** [comment]
Good to know that.

Might investigate a bit more when I got some time.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/issues/5728#issuecomment-313000122

If the feature is implemented in neovim, the problem does not affect though...

**Comment by autozimu** [comment]
Closing. See https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-350525383
