### ISSUE TITLE
Wrong `uri` in `textDocument/didClose` if a second buffer for the same language is closed with ':bd'

### ISSUE THREAD

**Issue by erlanger** [autozimu/LanguageClient-neovim#690]
- Did you upgrade to latest plugin version?
yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
languageclient 0.1.133

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
yes, it's ok.
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting
no, does not apply
## Describe the bug
`textDocument/didClose` return the wrong `uri` when there are two buffers for the same language open and one of them is closed with `:bd`

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.3.2-1059-gfa5182489
- This plugin version (`git rev-parse --short HEAD`):
3699556
- This plugin's binary version (`bin/languageclient --version`):
languageclient 0.1.133
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version:
I am developing a language server, it is not public yet. But the problem is with the client sending the
wrong uri.
[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Open two buffers for the same programing language with neovim
2. Do some edits on the first buffer to trigger the language server on the first buffer
3. Switch to the second buffer, and do some edits to make sure the language server
is working on  the second buffer
4. Close the second buffer with `:bd` and examine the contents of the `textDocument/didClose` json. You will see the uri is not the uri of the second buffer, but of the first.

## Current behavior
Wrong uri on `textDocument/didClose`.

## Expected behavior
Right  on `textDocument/didClose`.

## Additional context

I think a solution is to use buffer *numbers* to keep track of the uri's (as the key to find the uri, in a `bufnr-uri` key-value pair) , because vim/nvim gurarantee the numbers never change even when you delete and reopen buffers. They only change when you restart vim/nvim, which is totally fine.

**Comment by erlanger** [comment]
Update: I see the problem when I open the two documents in splits of the same window.

**Comment by autozimu** [comment]
Thanks.
