### ISSUE TITLE
How do I work with Scala?

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#692]
## Is your feature request related to a problem? Please describe.
How do I work with Scala?

## My setting
```
let g:LanguageClient_serverCommands = {
    \ 'scala': ['tcp://127.0.0.1:4273'],
    \ }
```

`Omni completion` and `LanguageClient#textDocument_definition()` do not work.

**Comment by Avi-D-coder** [comment]
What language server are you using?

**Comment by nabezokodaikon** [comment]
It is sbt.
`~/.sbt/1.0/global.sbt` has the following settings.
```
serverConnectionType := ConnectionType.Tcp
serverPort := 4273
```

**Comment by h-michael** [comment]
You may set wrong server command.
You have to set starting sbt command.

**Comment by nabezokodaikon** [comment]
Is metal unnecessary?

**Comment by nabezokodaikon** [comment]
> You may set wrong server command.
> You have to set starting sbt command.

What kind of command is the sbt start command?

**Comment by GordianDziwis** [comment]
Afaik all scala lsp implementations are alpha at best.

**Comment by nabezokodaikon** [comment]
I see.
thank you.
