### ISSUE TITLE
SignatureHelp not working with ccls

### ISSUE THREAD

**Issue by MarkGreeny** [autozimu/LanguageClient-neovim#693]
Hi, 

according to this [issue](https://github.com/MaskRay/ccls/issues/192) on ccls, `textDocument/signatureHelp' should be working on their side. Yet when I call it from the client, there are no results.

Can you please help me to get `textDocument/signatureHelp` working with ccls? As it is, it does not work when calling `LanguageClient#textDocument_signatureHelp()`. How should I go about making it work?

Note that i have the latest version of both this client and ccls.

**Comment by autozimu** [comment]
Can you follow the issue template?

**Comment by dimbleby** [comment]
probably fixed by #688 I think - looks like ccls uses the label offset style for which supported was added by that merge request.

**Comment by autozimu** [comment]
@MarkGreeny Can you verify?

**Comment by przemkovv** [comment]
I can confirm that `LanguageClient#textDocument_signatureHelp()` works with `ccls` very well now.

**Comment by martskins** [comment]
Closing as stale and as it seems to be working now
