### ISSUE TITLE
Is workspace symbols supported by pyls? 

### ISSUE THREAD

**Issue by GohioAC** [autozimu/LanguageClient-neovim#696]
This might be a basic question, but I could not figure it out on my own.
Running ` :Denite workspaceSymbol ` returns an empty list. ` :Denite documentSymbol ` works and project root is correctly identified.

**Comment by balta2ar** [comment]
Depends on which implementation you're talking about.
https://github.com/palantir/python-language-server -- this implementation does not seem to support workspaceSymbol. https://github.com/sourcegraph/python-langserver/ -- this implementation does seem to support, but I couldn't get it up and running for some reason.
Anyway, such questions should be addressed to the specific language server implementations (just search the code), not to the language server client.

**Comment by GohioAC** [comment]
I will look into  [https://github.com/palantir/python-language-server/](https://github.com/palantir/python-language-server/) -- which is the implementation I use. Closing the issue for now, will re-open if there's a problem in integrating with LanguageClient.
