### ISSUE TITLE
cquery incompatible with current LanguageClient-neovim

### ISSUE THREAD

**Issue by 0xjairo** [autozimu/LanguageClient-neovim#698]
It looks like `cquery`'s development has slowed down, the last commit was 5 months ago (2018-08-23). I've switched to `clangd` and it seems to have worked out of the box. I would suggest adding a note on top of the cquery wiki page to this effect.

The error I was seeing was below, this is with `cquery` on branch master (`70c755b`)

```
(   8.437s) [stdin        ]            lsp.cc:103   | Unknown field in the header
(   8.437s) [stdin        ]            lsp.cc:188   | Failed to read JsonRpc input; exiting
(   8.437s) [stdin        ]        loguru.hpp:1767  | atexit
```

Printing out the "header" it looks like there's a `Content-Length` field that cquery is unable to read.

**Comment by autozimu** [comment]
The wiki is public editable. Please add a note yourself. Thanks.

I personally don't use cquery. Mostly like it's due to cquery itself.
