### ISSUE TITLE
PHP + default rootPath 

### ISSUE THREAD

**Issue by phil-nelson** [autozimu/LanguageClient-neovim#7]
Here's a modified getRootPath() which adds support for PHP (looks for a composer.json file) and also falls back to looking for a .git folder when other checks fail. When all fail it falls back to the directory of the opened file (currently it sends back the whole file path which breaks because it's supposed to be a directory).

I don't think this is pull-request quality code so this is just to illustrate the idea, you may want to tidy it up:
```python
def getRootPath(filepath: str) -> str:
    if filepath.endswith('.rs'):
        return traverseUp(
            filepath,
            lambda folder: os.path.exists(os.path.join(folder, 'Cargo.toml')))
    elif filepath.endswith('.php'):
        try:
            path = traverseUp(
                filepath,
                lambda folder: os.path.exists(os.path.join(folder, 'composer.json')))
        except Exception:
            pass
    try:   
        return traverseUp(filepath, lambda folder: os.path.exists(os.path.join(folder, '.git')))
    except Exception:
        return os.path.dirname(filepath)
```

**Comment by autozimu** [comment]
Thanks. I will include in the next commit.
