### ISSUE TITLE
Option to use cwd as rootPath

### ISSUE THREAD

**Issue by djrenren** [autozimu/LanguageClient-neovim#70]
When `LanguageClient-neovim` sends its [`initialize`](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#initialize)  request, it sets the `rootPath` option as the directory containing the file. 

It would be very helpful for complex projects to allow the root to be set based on the current working directory. To work around this I've just created a suite of files at the root of my projects called `ls.java`, `ls.go`, etc. which I open first so the root starts in the appropriate place.

I figure this could be implemented with a boolean toggle for using cwd or as a parameter to `LanguageClientStart` where I could set the root.

**Comment by autozimu** [comment]
If you have a proper project setup (i.e., if the project is a javascript project and it has a project.json), 
ideally the project root path shall be inferred automatically. If it failed to infer, please give more details about your project layout so the infer mechanism could be improved or file PR to improve it yourself.

In general, this approach bring benefits for other users as well.

Nevertheless, I am going to find some time to implement things like
```
:LanguageClientStart rootPath=.
```
to handle really exotic project layout.

But please consider the first suggestion. Thanks.

**Comment by djrenren** [comment]
@autozimu Thanks for taking the time to answer.

I'm actually working on writing a language server (and testing using this client as well as others) that uses a remote index of multilingual codebases. Unfortunately this means the indexing and build structures don't align and the root directory is helpful in these cases. But in the meantime I've added a flag file that I can walk up the directory structure to access.

Thanks again.
