### ISSUE TITLE
Not showing Hints (rust rls)

### ISSUE THREAD

**Issue by flukejones** [autozimu/LanguageClient-neovim#705]
- Did you upgrade to latest plugin version?
As of today, yes

## Describe the bug
settings.json maybe not being passed to rls (rust), or incorrect setting for showing Hints/Info?

## Environment
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 03 2018 00:15:14)

```
" Language Server
let g:LanguageClient_windowLogMessageLevel = "Info"
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile = expand('~/.LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.LanguageServer.log')

let g:LanguageClient_settingsPath = "/home/luke/.vim/settings.json"
let g:LanguageClient_loadSettings = 1
set formatexpr=LanguageClient#textDocument_rangeFormatting_sync()
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rls'],
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
    \ 'python': ['/usr/local/bin/pyls'],
    \ }
let mapleader = ","
"let g:LanguageClient_diagnosticsSignsMax=0
let g:LanguageClient_diagnosticsEnable=1
let g:LanguageClient_diagnosticsList="Quickfix"
nnoremap <leader>d :call LanguageClient#textDocument_definition()<CR>
nnoremap <leader>r :call LanguageClient#textDocument_rename()<CR>
nnoremap <leader>f :call LanguageClient#textDocument_formatting()<CR>
nnoremap <leader>t :call LanguageClient#textDocument_typeDefinition()<CR>
nnoremap <leader>x :call LanguageClient#textDocument_references()<CR>
nnoremap <leader>c :call LanguageClient#textDocument_codeAction()<CR>
nnoremap <leader>h :call LanguageClient#textDocument_hover()<CR>
nnoremap <leader>s :call LanguageClient_textDocument_documentSymbol()<CR>
nnoremap <leader>m :call LanguageClient_contextMenu()<CR>

set formatexpr=LanguageClient#textDocument_rangeFormatting_sync()

highlight ALEHint term=standout ctermfg=15 ctermbg=DarkYellow guifg=White guibg=DarkYellow
highlight ALEInfo term=standout ctermfg=15 ctermbg=DarkGreen guifg=White guibg=DarkGreen
highlight ALEWarning term=standout ctermfg=15 ctermbg=DarkMagenta guifg=White guibg=DarkMagenta
highlight ALEError term=standout ctermfg=15 ctermbg=DarkRed guifg=White guibg=DarkRed
" ☣ ☢ ☡ ☠ ☠ ☠  ⓘ  ░ ➝ ⇉ ➞ ➜ ➟ ➲ ￫ ⇒ ⇛ ⇏ ↯ ❭ ❯ ❱ ➤ ⁇ ☄ ☇ ☈ ☀ ☉ ★ ☆ ☤ ⚕ ⚠ ⚛ ⚙ ⚗
let g:LanguageClient_diagnosticsDisplay = {
    \ 1: {
    \"name": "Error",
    \"texthl": "ALEError",
    \"signText": "E",
    \"signTexthl": "ALEError",
    \},
    \2: {
    \"name": "Warning",
    \"texthl": "ALEWarning",
    \"signText": "W",
    \"signTexthl": "ALEWarning",
    \},
    \3: {
    \"name": "Info",
    \"texthl": "ALEInfo",
    \"signText": "I",
    \"signTexthl": "ALEInfo",
    \},
    \4: {
    \"name": "Hint",
    \"texthl": "ALEHint",
    \"signText": "H",
    \"signTexthl": "ALEHint",
    \},
    \}
```
Using example `settings.json` from repo.

## To Reproduce
New rust project with the following:

``` rust
#[derive(Debug)]
struct Meaning {
    x: u8,
}

fn main() {
    println!("Hello, world!");
    let x: u8 = 42;
    let meaning = Meaning {
        x: x
    };
    println!("The meaning of life = {:?}", meaning);
}
```

## Current behavior
Only shows errors or warnings.

## Expected behavior
There should be a hint from clippy along the lines of:

```
warning: redundant field names in struct initialization
  --> src/main.rs:10:9
   |
10 |         x: x
   |         ^^^^ help: replace it with: `x`
   |
   = note: #[warn(clippy::redundant_field_names)] on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
```

### Note:

switching the rust language server to rust-analyser shows the Hints I expect. So I'm wondering if I'm actually missing something here.

### Attachments

[rls-LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2801369/rls-LanguageClient.log)

[rust_analyser-LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2801371/rust_analyser-LanguageClient.log)

**Comment by h-michael** [comment]
@Luke-Nukem 
> switching the rust language server to rust-analyser shows the Hints I expect. So I'm wondering if I'm actually missing something here.
As far as I know, rust_analyser doesn't support clippy integration.

Logs you uploaded don't include diagnostics by clippy.
Can you show not language client logs but language server logs ?

**Comment by flukejones** [comment]
Sure, reattached previous runs after re-gen.
[rls-LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2802079/rls-LanguageClient.log)
[rls-LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/2802080/rls-LanguageServer.log)
[rust_analyser-LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2802081/rust_analyser-LanguageClient.log)
[rust_analyser-LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/2802082/rust_analyser-LanguageServer.log)

**Comment by h-michael** [comment]
`rls-LanguageServer.log` is not rls log but rust-analyzer log.

`ERROR [ra_lsp_server::main_loop] unhandled notification: RawNotification { method: "workspace/didChangeConfiguration", params: Object({"settings": Object({"rust": Object({"all_targets": Bool(false), "build_on_save": Bool(true), "clippy_preference": String("on"), "full_docs": Bool(true), "wait_to_build": Number(0)})})}) }`

**Comment by flukejones** [comment]
Ah sorry. Child distractions.
Looks like it's the same because I didn't notice `rls` isn't generating anything at all in the log (so it wasn't overwritten).

**Comment by flukejones** [comment]
Added `RUST_LOG=rls_analysis=debug` to commandline for use in rls.

[rls.debug.LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/2802278/rls.debug.LanguageServer.log)

**Comment by autozimu** [comment]
The VSCode extension reports the same.

This is highly unlikely an issue of this plugin. Please file a bug report to rls.
