### ISSUE TITLE
Fails to start with g:LanguageClient_loggingFile set to custom log file

### ISSUE THREAD

**Issue by ferrao** [autozimu/LanguageClient-neovim#707]
- Did you upgrade to latest plugin version? **Yes**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
`languageclient 0.1.134 8c029c9b94e842fd13b9a830d7b452e4f33d88f0`
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **YES**
- Did you check [troubleshooting]? **YES**

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

Language client does not start if I have this line on my config:

`let g:LanguageClient_loggingFile = '~/.vim/LanguageClient.log'`

If I set it to:

`let g:LanguageClient_loggingFile = '/tmp/LanguageClient.log'`

everything is OK. `.vim` is writable and other nvim logs are going there, it's not a permissions issue.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/build/config -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20181019-20909-1hlaj6i/neovim-0.3.1/build/include
Compiled by brew@HighSierra-2.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.1/share/nvim"
````

- This plugin version (`git rev-parse --short HEAD`):  a28eced
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.134 8c029c9b94e842fd13b9a830d7b452e4f33d88f0`

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

**Comment by KillTheMule** [comment]
You probably need to use `expand` like [this](https://github.com/autozimu/LanguageClient-neovim/blob/95608f52af795804f491a5283909256a44d254a2/min-vimrc.vim#L23).

**Comment by ferrao** [comment]
You are totally right @KillTheMule , thank you! 

Docs say:

**Valid options: any valid path.**

Perhaps should be a bit clearer?

**Comment by KillTheMule** [comment]
Well, `~` is not a valid path I think, we're just used to it from our shell and almost everything else basically supporting it... but I'm sure that a PR that clarifies that bit would be welcomed :)
