### ISSUE TITLE
snippet support broken at 657ad707

### ISSUE THREAD

**Issue by dimbleby** [autozimu/LanguageClient-neovim#709]
Prior to 657ad707, I had snippet support working fine with ultisnips and ncm2-ultisnips.

But after 657ad707, the language client does not recognise that ultisnips supports snippets.  So it declares that I don't have snippet support, and no server will play along.

To be fair I did have to do a (small) amount of customisation to get this working, so the language client is not completely wrong when it says that snippets are not supported.  But I *have* made it work, and now it doesn't!

Sadly I can't override the language client's opinion: setting `g:LanguageClient_hasSnippetSupport = 1` doesn't turn on snippet support - though it sounds as though it ought to.  As it stands, that variable would be better re-named `g:LanguageClient_doNotDisableSnippetSupport`.

Can we please make this work again?  Maybe with a new setting so that I can force snippet support on, maybe by changing the meaning of the existing setting, maybe something else altogether...?

**Comment by dimbleby** [comment]
Suggest changing `s:hasSnippetSupport()` to go something like this:

```viml
if exists('g:LanguageClient_hasSnippetSupport')
    "user has chosen to force the issue, respect that choice
    return g:LanguageClient_hasSnippetSupport
endif

" else decide by checking for plug-ins known to support snippets
...

**Comment by autozimu** [comment]
You're right. Sorry for the confusion.
