### ISSUE TITLE
^@ instead of newline in the virtual text errors

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#713]
## Describe the bug
![image](https://user-images.githubusercontent.com/1794388/51960296-8438ed00-2469-11e9-9aea-b1578a6fbf02.png)

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.4
- This plugin version (`git rev-parse --short HEAD`): 273e5dc
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.135 
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): `min-vimrc.vim` but with nightly RLS
- Language server link and version: `rls-preview 1.31.6 (ae0d89a 2019-01-13)`

## To Reproduce
1. `cargo new`
1. `nvim -u min-vimrc.vim src/main.rs`
1. Add some random text before `fn main`
1. Observe

## Current behavior
`^@` are printed instead of newline characters

## Expected behavior
Ideally something smart which would lay out multiline errors on multiple lines if there's space. As a quick fix, maybe replacing newlines with just space or showing only the first line of the error, in this case the second line seems pointless.

**Comment by pinkisemils** [comment]
Not doing any digging beyond looking at commit message lines, c9bb3b5e86dfcb2c480113d29239cbd587510eb7 commit seems to work, if anyone's looking for a quick fix.
