### ISSUE TITLE
Virtual text errors don't update properly with file changes

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#717]
## Describe the bug
When you change the file with virtual text errors or warnings and then move the cursor the virtual text stays on the same line numbers as it was initially set on rather than moving according to the changes.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM v0.3.4
- This plugin version (`git rev-parse --short HEAD`): 75c7280
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.136
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): `min-vimrc.vim` but with nightly RLS and with this appended:
```rust
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_settingsPath = '~/.config/nvim/langserver_settings.json'
```
`langserver_settings.json`:
```json
{
        "rust": {
                "clippy_preference": "on",
                "wait_to_build": 500,
                "build_on_save": true
        }
}
```
Build on save helps illustrate the issue better.

- Language server link and version: `rls-preview 1.31.6 (ae0d89a 2019-01-13)`

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. `cargo new`
1. `nvim -u min-vimrc.vim src/main.rs`
1. Add some random text above `fn main()` and save the file. Virtual text errors will appear on lines 1 and 2.
1. Delete the line you added and move the cursor. Virtual text stays on lines 1 and 2, which are now different lines (expected: text from line 1 disappears since line 1 was deleted and text from line 2 moves to the new line 1).
1. Alternatively: add one more line at the top. Virtual text stays on lines 1 and 2, while it should have moved to lines 2 and 3.

## Screenshots
After step 3:
![image](https://user-images.githubusercontent.com/1794388/52039296-342f5880-2545-11e9-982a-97f078622f96.png)

After step 4:
![image](https://user-images.githubusercontent.com/1794388/52039308-3beefd00-2545-11e9-834f-bb37d484a5b6.png)
Expected (before moving the cursor after deleting the line):
![image](https://user-images.githubusercontent.com/1794388/52039368-617c0680-2545-11e9-9700-82917a3bd139.png)

After step 5:
![image](https://user-images.githubusercontent.com/1794388/52039401-7bb5e480-2545-11e9-821b-bb3999dfc0d3.png)
Expected (before moving the cursor after adding the line):
![image](https://user-images.githubusercontent.com/1794388/52039388-73f64000-2545-11e9-9b18-68fddbe4a510.png)

**Comment by autozimu** [comment]
This should be resolved by https://github.com/autozimu/LanguageClient-neovim/commit/e368dcb4b138f2858803e7f544aad9e52313c698

Let me know if it's not the case.
