### ISSUE TITLE
How can I disable in line lint warnings?

### ISSUE THREAD

**Issue by sdemura** [autozimu/LanguageClient-neovim#719]
How do I disable the inline lint messages? They are incredibly annoying

![image](https://user-images.githubusercontent.com/11758459/52059609-4787f700-2538-11e9-881b-2fa666855655.png)

**Comment by h-michael** [comment]
See https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L343

**Comment by sdemura** [comment]
thanks.

**Comment by arclabs561** [comment]
Can this issue confirm the solution with a permalink or the config name?

**Comment by martskins** [comment]
@henrywallace I think this is what you are looking for https://github.com/autozimu/LanguageClient-neovim/blob/a42594c9c320b1283e9b9058b85a8097d8325fed/doc/LanguageClient.txt#L435

If you set that to `No` it won't use virtual texts at all. `CodeLens` will use it only for code lens and not for diagnostics.
