### ISSUE TITLE
LanguageClient-neovim + deoplete won't show completion

### ISSUE THREAD

**Issue by topecongiro** [autozimu/LanguageClient-neovim#721]
- Did you upgrade to latest plugin version?
    - Yes (0.1.136)
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
    - Yes (`languageclient 0.1.136`) 
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
    - Yes
- Did you check [troubleshooting]?
    - Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

I am trying to use LanguageClient-neovim and deoplete together with rust support, however I get no completion when I start writing code: e.g. `use std::io::`.

My apologies if I am missing something obvious.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
- This plugin version (`git rev-parse --short HEAD`): `NVIM v0.3.4`
- This plugin's binary version (`bin/languageclient --version`):  `languageclient 0.1.136`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh',
        \ }

call plug#end()

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('sources', {
        \ 'rust': ['LanguageClient'],
        \ })

set hidden

let g:LanguageClient_ServerCommands = {
        \ 'rust': ['rustup', 'run', 'stable', 'rls'],
        \ }
```
- Language server link and version: `rls-preview 1.31.6 (bfa1371 2018-12-07)`

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## Current behavior

No completion appears after I start typing.

## Expected behavior

deoplete show completion based on rls.

**Comment by autozimu** [comment]
This is a regression on rls side. Please file an issue to their repo.

Thanks.
