### ISSUE TITLE
c++ deoplete doesn't list LC matches until manually doing 'set filetype=cpp'

### ISSUE THREAD

**Issue by ryan0270** [autozimu/LanguageClient-neovim#723]
- Did you upgrade to latest plugin version?
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
When I open a .cpp file I can use omnicomplete to get matches from the LC but the deoplete menu doesn't not show them (it only shows buffer, around, etc. matches). If I do ":set filetype=cpp" I then start to get LC matches in the deoplete menu.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5

- This plugin version (`git rev-parse --short HEAD`): 
668b996

- This plugin's binary version (`bin/languageclient --version`): 
0.1.136

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.local/share/dein')
  call dein#begin('~/.local/share/dein')
  call dein#add('~/.local/share/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('autozimu/LanguageClient-neovim',{'rev':'next','build':'bash install.sh'})
  call dein#end()
  call dein#save_state()
endif

let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = []
let g:LanguageClient_serverCommands = {'cpp': ['clangd'] }

let g:deoplete#enable_at_startup=1
call deoplete#enable_logging('DEBUG','/tmp/deoplete.log')
call deoplete#custom#source('LanguageClient','mark', 'LC')
call deoplete#custom#source('LanguageClient','rank', 600)
call deoplete#custom#source('LanguageClient','min_pattern_length', 1)

```
- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

1. edit cpp file
2. :set filetype? (confirm it's at cpp)
3. start typing code that should have completions provided by deoplete
       (no completions provided by LC)
4. <c-x><c-o> to confirm that omnicomplete gets LC completions
5. :set filetype=cpp
6. try again: deoplete now shows completions by LC

## Context
I'm newly configuring both LC and deoplete so very likely have a configuration error on my part. I'm also not sure if this problem is with LC or deoplete so just trying here first.

**Comment by Shougo** [comment]
Please read dein.vim documentation.
It is dein.vim feature.

You need to write vimrc like this.

```vim
if dein#load_state({path to plugin base path directory})
...
endif

filetype plugin indent on
syntax enable
```

**Comment by ryan0270** [comment]
whoops, stripped too much down from main main vimrc to the minimal. 

Even with those lines added to the minimal vimrc I get the same behavior though.

**Comment by Shougo** [comment]
Hm.
Please use the latest version of deoplete.
Old deoplete has bugs.

**Comment by ryan0270** [comment]
That fixed it, thanks!
