### ISSUE TITLE
Code Action is editing the text twice

### ISSUE THREAD

**Issue by sriharshachilakapati** [autozimu/LanguageClient-neovim#724]
- Did you upgrade to latest plugin version? **YES**
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. **YES: Version 0.1.137**
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **YES, OK in GREEN**
- Did you check [troubleshooting]? **YES**

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
When doing a code action, it is being added twice. Same is being happened when adding imports.

It is being done twice, as pressing undo once after code action is giving the correct result.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): **NVIM 0.3.4**
- This plugin version (`git rev-parse --short HEAD`): **1db273f**
- This plugin's binary version (`bin/languageclient --version`): **languageclient 0.1.137 0325b78584f36c001c93a1465855de5e1deba3fe**
- Minimal vimrc content

~~~viml
scriptencoding utf8
set hidden

call plug#begin('~/.local/share/nvim/bundle/')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'purescript-contrib/purescript-vim'

call plug#end()

let g:deoplete#enable_at_startup = 1

let g:LanguageClient_autoStart=1
let g:LanguageClient_autoStop=1
let g:LanguageClient_serverCommands={}
let g:LanguageClient_windowLogMessageLevel="Log"
let g:LanguageClient_loggingLevel="INFO"
let g:LanguageClient_loggingFile=expand("~/LanguageClient.log")

if executable("purescript-language-server")
    " See https://github.com/nwolverson/vscode-ide-purescript/blob/master/package.json#L80-L246 for list of properties to use
    let config =
        \ { 'purescript.autoStartPscIde': v:true
        \ , 'purescript.pscIdePort': v:null
        \ , 'purescript.autocompleteAddImport': v:true
        \ , 'purescript.pursExe': 'purs'
        \ , 'purescript.trace.server': 'verbose'
        \ }
	
    " Define the LanguageServer in the LanguageClient
    let g:LanguageClient_serverCommands.purescript = ['purescript-language-server', '--stdio', '--config', json_encode(config)]
    autocmd filetype purescript setlocal omnifunc=LanguageClient#complete
	
    " Commands for ease of use
    autocmd filetype purescript nm <buffer> <silent> <leader>a :call LanguageClient_textDocument_codeAction()<CR>
    autocmd filetype purescript nm <buffer> <silent> <leader>i :call LanguageClient_workspace_executeCommand(
        \ 'purescript.addCompletionImport', [ expand('<cword>'), v:null, v:null, 'file://' . expand('%:p') ])<CR>
    autocmd filetype purescript nm <buffer> <silent> <leader>g :call LanguageClient_textDocument_definition()<CR>
    autocmd filetype purescript nm <buffer> <silent> <leader>h :call LanguageClient_textDocument_hover()<CR>
    autocmd filetype purescript nm <buffer> <silent> <leader>l :call LanguageClient_workspace_executeCommand('purescript.build', [])<CR>
endif
~~~

- Language server link and version:

https://www.npmjs.com/package/purescript-language-server/v/0.12.6

## To Reproduce

1. Create/Fetch example project (use pulp init to create one)
2. Fetch all dependencies using bower i
3. Build the project using pulp build
4. Start vim, `nvim -u min-vimrc.vim`
5. Create file src/Test.purs to following content.

~~~purescript
module Test where

import Prelude
import Data.Array

a :: Array Int
a = [ 1, 2, 3, 9, 2, 3, 4 ]

b :: Array Int
b = nub a
~~~

6. Save file.
7. There should be warning on `import Data.Array` line.
8. Call codeAction on it.
9. Select makeImportExplicit. It should replace it to `import Data.Array (nub) (nub)`
10. Press `u` to undo. It should now be `import Data.Array (nub)`

## Current behavior
It adds the import lists twice. However, undo once fixes it.

## Expected behavior
It should add the import list only once.

## Screenshots

![codeaction_twice](https://user-images.githubusercontent.com/4593204/52230217-d8662600-28dc-11e9-9834-5938a1f0fb14.gif)

**Comment by sriharshachilakapati** [comment]
Updated the new cargo release and edited the issue to reflect it, but still having the same issue. Also now when I run, getting

![image](https://user-images.githubusercontent.com/4593204/52258583-b05edd00-2945-11e9-8049-db3efae2d184.png)

**Comment by autozimu** [comment]
Could you attach file `~/LanguageClient.log`?

Also, what's the steps to the screenshot error? Is it the same reproduction step?

**Comment by sriharshachilakapati** [comment]
Yeah sure. The steps in the screenshot show the codeAction. I've remapped it to leader a in the minimal configuration.

Also attaching the sample project as pure12.zip. You need PureScript 0.12 + NodeJS atleast 9.5.0 to run this project.

[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2834835/LanguageClient.log)
[pure12.zip](https://github.com/autozimu/LanguageClient-neovim/files/2834844/pure12.zip)

**Comment by sriharshachilakapati** [comment]
The too many arguments error is only coming under a production project I work in our company, and is not there in this log. I unfortunately don't have permission to give out the log for that project without anonymising. I think it is to do with the number of warnings, it had like 70 warnings in that same file, and is 1012 lines long.

**Comment by sriharshachilakapati** [comment]
@autozimu Any update on this? Please let me know if you need any more information.

**Comment by sriharshachilakapati** [comment]
Just updated the plugin, and it is now working! Thank you so much!!
