### ISSUE TITLE
Filter diagnostics messages

### ISSUE THREAD

**Issue by cheuk-fung** [autozimu/LanguageClient-neovim#726]
## Is your feature request related to a problem? Please describe.
I am working on a Java project that have many TODOs in the comments. I am using [Eclipse JDT Language Server](https://github.com/eclipse/eclipse.jdt.ls) as the backend which will send the TODOs as `Information` level diagnostics messages. This is distracting when I need to fix errors or warnings.

## Describe the solution you'd like
Could you add the functionality to filter diagnostics messages? I think we have two options,
1. Filter by level, like Logging levels
2. Filter by text, for example, only add a message to the diagnostics list if it matches a regular expression.

## Describe alternatives you've considered
I tried to add an `autocmd` for the `LanguageClientDiagnosticsChanged` event to filter the messages by text, however, the quickfix list changed back to the non-filtered list very soon.

## Additional context
Let me know if you need more information. Thanks.

**Comment by martsa1** [comment]
I'd quite like a feature along these lines as well

**Comment by cheuk-fung** [comment]
Fixes by 0f4a1fcae7faacec1c7438c48b22645f2fd88369
