### ISSUE TITLE
Consider adding release notes

### ISSUE THREAD

**Issue by funbringer** [autozimu/LanguageClient-neovim#728]
Thanks for a nice plugin!

Unfortunately, currently there's no easy way to list release changes. One has to look through commit log in order to get the idea. I wonder if you could at least write a brief changelog from time to time.

**Comment by autozimu** [comment]
I will comment under https://github.com/autozimu/LanguageClient-neovim/issues/35 for new feature and any breaking changes. Is it sufficient?

**Comment by funbringer** [comment]
@autozimu Sure, also it would be nice if you added an explicit reference (e.g. "changelog") to #35 to the README.md.
