### ISSUE TITLE
code completion with omnifunc not working with vim 8.1 - didChange event gets emitted removing identifier before completion request? 

### ISSUE THREAD

**Issue by TysonAndre** [autozimu/LanguageClient-neovim#729]
This has occurred for roughly a month. Older versions of vim/the language client used to work(haven't figured out which is the cause, yet). (I haven't checked yet with neovim or older vim 8.1 patch versions)

- Did you upgrade to latest plugin version? yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number. `0.1.139`
- Did you check [troubleshooting]? yes

## Describe the bug
As a consequence of vim's omnifunc running, the document will change, removing the identifier prior to the cursor. The cursor position being sent to the language client is also for the original document contents without the deleted word, not the new contents with the deleted word.

- The didChange event (with the removed identifier (prefix) `ca`) gets sent to the language server before the textDocument/completion event

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): vim 8.1 patches 1-885
- This plugin version (`git rev-parse --short HEAD`):
- This plugin's binary version (`bin/languageclient --version`): 0.1.139
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): - TODO: (This occurs with omnifunc. This still occurred after disabling other plugins)
- Language server link and version: https://github.com/tysonandre/languageserver-phan-neovim (latest, with dev-master of phan from composer)

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Create/Fetch example project ...
1. Start vim
1. Edit ...
1. Request code completions with `C-x C-o`. Observe no completions are sent back, and that the input to the language server was different from what I'd expect.
1. See error

## Current behavior
Completions fail because

1. the document is unexpectedly modified before sending the completion request to the language server, and
2. the character position is out of sync with the state of the document from didChange

## Expected behavior

1. The unmodified document is sent to the language server when requesting completion (modifying the document before requesting completions is not a standard part of the language server protocol)

   e.g. if that can be done by skipping/delaying/not causing didChange events caused as a side effect of omnifunc, that would be one way to do that
2. The textDocument/completion position is in sync with the most recent call to didChange on the same document.

## Screenshots

![omni_completion_request](https://user-images.githubusercontent.com/1904430/52536444-aadc0b00-2d28-11e9-9185-6c86bc9af040.png)

## Additional context

These raw events (mixed with logs to stderr) were seen with the following command

```sh
/path/to/phan/phan --require-config-exists --language-server-on-stdin --project-root-directory /path/to/phan_example_project --quick --language-server-allow-missing-pcntl --use-fallback-parser --allow-polyfill-parser --memory-limit 1G --language-server-enable-go-to-definition --language-server-enable-hover --language-server-enable-completion --language-server-hide-category --language-server-verbose --plugin InvokePHPNativeSyntaxCheckPlugin
```

```
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"<?php\ncall_user_func(function ($some_arg) {\n    \n});\n"}],"textDocument":{"uri":"file:///path/to/phan_example_project/src/filter.php","version":8}}}


Received message in coroutine: {"method":"textDocument\/didChange","params":{"contentChanges":[{"text":"<?php\ncall_user_func(function ($so
me_arg) {\n    \n});\n"}],"textDocument":{"uri":"file:\/\/\/path\/to\/phan_example_project\/src\/filter.php","version":8}},
"jsonrpc":"2.0"}
Called textDocument/didChange, uri=file:///path/to/phan_example_project/src/filter.php version=8
Called analyzeURIAsync, uri=file:///path/to/phan_example_project/src/filter.php, path=/path/to/phan_example_project/src/filter.php
Request:
{"Content-Length":"..."}
Data:
{"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":6,"line":2},"textDocument":{"uri":"file:///home/tyson
/programming/phan_example_project/src/filter.php"}},"id":3}


Received message in coroutine: {"id":3,"method":"textDocument\/completion","params":{"position":{"character":6,"line":2},"textDocument":{"uri":"file:\/\/\/path\/to\/phan_example_project\/src\/filter.php"}},"jsonrpc":"2.0"}
Shifting position 2:6 to handle issues
```

Note the unexpected didChange from the document from the above raw JSON: I expected the third line to contain `ca`, but it didn't.

```patch
 <?php
 call_user_func(function ($some_arg) {
-     ca
+    
 });
```

This language server does not use threading - it is definitely using the contents from didChange.

**Comment by autozimu** [comment]
I remembered this has been an issue in the first beginning. Partially due to described vim completion limitation.

For the time being, I'd recommend using completion framework like deoplete to work around this.

I will also introduce a user setting to control whether to send didChange before completion.

**Comment by autozimu** [comment]
I removed the didChange notification instead of introducing another setting. Let's see how it goes.

**Comment by TysonAndre** [comment]
Thanks, completion is working now with omnifunc

**Comment by pickfire** [comment]
I believe that I still experience this issue when completing html end tag. (`_` is the cursor)

### Input
```html
<div>
  </_
```

With <kbd>ctrl</kbd> <kbd>x</kbd> + <kbd>o</kbd>.

### Expected
```html
<div>
  </div>_
```

### Output
```html
<div>
  </v>_
```

Same goes for other html tag where the first 2 characters got lost. I am using deoplete here.
