### ISSUE TITLE
Node.js: Error 2307 cannot find module 'url'

### ISSUE THREAD

**Issue by anchnk** [autozimu/LanguageClient-neovim#732]
- Did you upgrade to latest plugin version? **yes**
- Did you upgrade to/compile latest binary? **yes** (version `0.1.140`)
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? **yes**

> health#LanguageClient#check
> ========================================================================
>   - OK: binary found: /home/anchnk/.local/share/nvim/plugged/LanguageClient-neovim/bin/languageclient
>   - OK: languageclient 0.1.140 

- Did you check [troubleshooting]? **yes**

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

> Disclaimer: First of all, I must say I am not fully aware of all the LSP protocol. I mainly use the plugin as an abstraction so I apologize if the problem I am facing isn't related to this repo. Maybe it has to do with the server, if that's the case I will report there.

Adding a `jsconfig.json` at the root of my repository which sets `checkJs` property to `true` throws errors such as `[Error][2307]Cannot find module 'url'`.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): **NVIM v0.3.1**
- This plugin version (`git rev-parse --short HEAD`): **5685989**
- This plugin's binary version (`bin/languageclient --version`): **0.1.140**
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
- Language server link and version: https://github.com/sourcegraph/javascript-typescript-langserver version 2.11.2

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

- I added a `jsconfig.json` file at the root of my repository. Here's the content of this file:

```json
{
    "compilerOptions": {
        "target": "es6",
        "checkJs": true,
        "module": "commonjs"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ],
    "include": [
      "src/**/*"
    ]
}
```
I am not sure **LanguageClient-neovim** makes use of it but I think it does somehow as it changed the behavior. If i get rid of this file I don't have any error in my repository. If do add this file I have certains errors showing up related to not being able to locate node's core module (such as url). 

- I set up a minimal example to isolate the problem:

```js
'use strict'

const { URL } = require('url');

const url = new URL('https://www.google.fr');
console.log(url);
```

When I do start the LangageClient  (either automatically by opening the file either with `:LanguageClientStart`, the following error shows up  `[Error][2307]Cannot find module 'url'`. As it's a node core module I am not sure it's complaining about some TypeScript definitions missing, if it's a bug from the LSP Server or something else. 

## Current behavior
It complains about not finding module reference

## Expected behavior
It shouldn't throw false errors.

## Screenshots

![bug-lsp](https://user-images.githubusercontent.com/515506/52795383-f6b4ea00-3071-11e9-93b1-cc5ac96a178c.png)

## Additional context

Extract of the logs

```
15:37:23 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","method":"s:command","params":["sign place 75008 line=3 name=LanguageClientError file=/tmp/empty-project/index.js"]}
15:37:23 DEBUG unnamed src/language_client.rs:41 state.highlights_placed./tmp/empty-project/index.js: [] ==> [{"character_end":29,"character_start":24,"group":"ALEError","line":2,"text":"('url"}]
15:37:23 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","method":"nvim_buf_clear_highlight","params":[0,1,0,5]}
15:37:23 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","method":"s:AddHighlights","params":[1,[{"character_end":29,"character_start":24,"group":"ALEError","line":2,"text":"('url"}]]}
15:37:23 INFO unnamed src/language_server_protocol.rs:2518 End languageClient/handleCursorMoved
15:37:23 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","method":"s:ExecuteAutocmd","params":["LanguageClientDiagnosticsChanged"]}
15:37:23 INFO unnamed src/language_server_protocol.rs:1982 End textDocument/publishDiagnostics
15:37:23 INFO reader-None src/rpcclient.rs:83 <= None {"id": 632, "jsonrpc": "2.0", "method": "languageClient/getState", "params": {"bufnr": 1, "viewport": {"end": 6, "start": 0}, "languageId": "javascript"}}
15:37:23 INFO unnamed src/language_server_protocol.rs:2118 Begin languageClient/getState
15:37:23 INFO unnamed src/language_server_protocol.rs:2120 End languageClient/getState
15:37:23 INFO unnamed src/rpcclient.rs:137 => None {"jsonrpc":"2.0","result":"{\"capabilities\":{\"javascript\":{\"capabilities\":{\"codeActionProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\"]},\"definitionProvider\":true,\"documentSymbolProvider\":true,\"executeCommandProvider\":{\"commands\":[]},\"hoverProvider\":true,\"referencesProvider\":true,\"renameProvider\":true,\"signatureHelpProvider\":{\"triggerCharacters\":[\"(\",\",\"]},\"textDocumentSync\":1,\"typeDefinitionProvider\":true,\"workspaceSymbolProvider\":true,\"xdefinitionProvider\":true,\"xdependenciesProvider\":true,\"xpackagesProvider\":true,\"xworkspaceReferencesProvider\":true}}},\"registrations\":[],\"roots\":{\"javascript\":\"/tmp/empty-project\"},\"text_documents\":{\"/tmp/empty-project/index.js\":{\"uri\":\"file:///tmp/empty-project/index.js\",\"languageId\":\"javascript\",\"version\":0,\"text\":\"'use strict'\\n\\nconst { URL } = require('url');\\n\\nconst url = new URL('https://www.google.fr');\\nconsole.log(url);\\n\"}},\"text_documents_metadata\":{},\"diagnostics\":{\"/tmp/empty-project/index.js\":[{\"range\":{\"start\":{\"line\":2,\"character\":24},\"end\":{\"line\":2,\"character\":29}},\"severity\":1,\"code\":2307,\"source\":\"ts\",\"message\":\"Cannot find module 'url'.\"}]},\"signs\":{\"/tmp/empty-project/index.js\":[{\"id\":75008,\"line\":3,\"text\":\"const { URL } = require('url');\",\"severity\":1}]},\"signs_placed\":{\"/tmp/empty-project/index.js\":[{\"id\":75008,\"line\":3,\"text\":\"const { URL } = require('url');\",\"severity\":1}]},\"namespace_id\":null,\"highlight_source\":1,\"highlights\":{\"/tmp/empty-project/index.js\":[{\"line\":2,\"character_start\":24,\"character_end\":29,\"group\":\"ALEError\",\"text\":\"('url\"}]},\"highlights_placed\":{\"/tmp/empty-project/index.js\":[{\"line\":2,\"character_start\":24,\"character_end\":29,\"group\":\"ALEError\",\"text\":\"('url\"}]},\"highlight_match_ids\":[],\"document_highlight_source\":null,\"user_handlers\":{},\"is_nvim\":true,\"last_cursor_line\":2,\"last_line_diagnostic\":\"[Error][2307]Cannot find module 'url'.\",\"stashed_codeAction_commands\":[],\"viewport\":{\"start\":0,\"end\":6},\"serverCommands\":{\"javascript\":[\"javascript-typescript-stdio\"],\"rust\":[\"rustup\",\"run\",\"stable\",\"rls\"]},\"autoStart\":true,\"selectionUI\":\"FZF\",\"selectionUI_autoOpen\":true,\"trace\":\"verbose\",\"diagnosticsEnable\":true,\"diagnosticsList\":\"Quickfix\",\"diagnosticsDisplay\":{\"2\":{\"name\":\"Warning\",\"texthl\":\"ALEWarning\",\"signText\":\"⚠\",\"signTexthl\":\"ALEWarningSign\",\"virtualTexthl\":\"Todo\"},\"1\":{\"name\":\"Error\",\"texthl\":\"ALEError\",\"signText\":\"✖\",\"signTexthl\":\"ALEErrorSign\",\"virtualTexthl\":\"Error\"},\"3\":{\"name\":\"Information\",\"texthl\":\"ALEInfo\",\"signText\":\"ℹ\",\"signTexthl\":\"ALEInfoSign\",\"virtualTexthl\":\"Todo\"},\"4\":{\"name\":\"Hint\",\"texthl\":\"ALEInfo\",\"signText\":\"➤\",\"signTexthl\":\"ALEInfoSign\",\"virtualTexthl\":\"Todo\"}},\"diagnosticsSignsMax\":null,\"documentHighlightDisplay\":{\"1\":{\"name\":\"Text\",\"texthl\":\"SpellCap\"},\"3\":{\"name\":\"Write\",\"texthl\":\"SpellRare\"},\"2\":{\"name\":\"Read\",\"texthl\":\"SpellLocal\"}},\"windowLogMessageLevel\":2,\"settingsPath\":\".vim/settings.json\",\"loadSettings\":true,\"rootMarkers\":null,\"change_throttle\":null,\"wait_output_timeout\":{\"secs\":10,\"nanos\":0},\"hoverPreview\":\"Auto\",\"completionPreferTextEdit\":false,\"use_virtual_text\":false,\"loggingFile\":\"/tmp/LanguageClient.log\",\"loggingLevel\":\"DEBUG\",\"serverStderr\":\"/tmp/LanguageClient-err.log\"}","id":632}
15:37:26 INFO reader-None src/rpcclient.rs:83 <= None {"method": "languageClient/handleCursorMoved", "jsonrpc": "2.0", "params": {"bufnr": 1, "languageId": "javascript", "line": 1, "LSP#visible_line_start()": 0, "LSP#visible_line_end()": 5, "buftype": "", "filename": "/tmp/empty-project/index.js"}}
```

**Comment by Anrock** [comment]
Do you have typings for node.js installed? Otherwise TS wouldn't know if you're writing a browser or node.js script. Also i think you have to change your `compilerOptions.module` option to `node` otherwise modules won't work properly.

**Comment by anchnk** [comment]
> Do you have typings for node.js installed?

I am assuming you are refering to [this package](https://www.npmjs.com/package/@types/node) ?
If that assertion is true, then no I don't have those installed. 

I try to install the node typings and to add the `module` option and it seems that the errors is gone.
So that mitght be it. Thanks already.

I keep the issue open while I am checking that everything is solved then I will close it.
