### ISSUE TITLE
remove "Language server is not running for "

### ISSUE THREAD

**Issue by teto** [autozimu/LanguageClient-neovim#738]
## Is your feature request related to a problem? Please describe.
When I enable LanguageClient-neovim, I get
`"Language server is not running for "` with a big red background which is distracting.

## Describe the solution you'd like
I'd like for it to be removed as it is distracting and I know that I haven't configured any lsp server for these filetypes.

## Describe alternatives you've considered
The status of lsp servers might be better checked via `:checkhealth` or :LanguageClientInfo/Debug (like the very good `:NeomakeInfo`)

**Comment by autozimu** [comment]
This error is only displayed when you specified the language server for filetype and it isn't able to launch the server successfully.

I'd argue that it is useful to have  the message displayed to indicate something is wrong, instead of fail silently and left user wondering why the plugin doesn't work when it suppose to.

**Comment by teto** [comment]
except it displays even for filetypes that don't have an lsp server configured: mail, commit etc.

**Comment by autozimu** [comment]
Are you sure that's the case?

Can you verify again?  If it is still reproducible, please follow bug report template to provide reproduction steps.

**Comment by RobbieMcKinstry** [comment]
I'm experiencing this. 
```
[LC] Language server is not running for: vim
```

**Comment by RobbieMcKinstry** [comment]
Hah! In my case, I had been running
```
autocmd BufWritePre * :call LanguageClient#textDocument_formatting_sync()
```
instead of 
```
autocmd BufWritePre *.rs :call LanguageClient#textDocument_formatting_sync()
```
