### ISSUE TITLE
how to disable autocomplete opening a split pane

### ISSUE THREAD

**Issue by meganaut** [autozimu/LanguageClient-neovim#740]
When using autocomplete (fzf + deoplete) I keep getting a split pane showing up whenever I select an option.  I use tab to select the option from the completions.

See gif 
![autocomplete-issue](https://user-images.githubusercontent.com/2966929/53007017-23a63a00-3482-11e9-8c66-2bb4d5ec73ac.gif)

Is there a way to disable this?
I am running on the latest version of this package.

**Comment by autozimu** [comment]
That's completion preview window provided by vim. Not controlled inside this plugin.

`:h completeopt`, then check `preview` option.
