### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ym1234** [autozimu/LanguageClient-neovim#744]
I haven't found a better place to ask these questions, so please tell me if there is.

1. Is there is a way to lint on save and only on save?
2. is there is a way to toggle Virtual text at runtime? resetting it to 1 doesn't work
3. Is there is a way to align the virtual text to the end of the window instead of right next to the text?

**Comment by autozimu** [comment]
1. You could use throttle to achieve the behaviour. Just set it to a large number. https://github.com/autozimu/LanguageClient-neovim/blob/14dafc186c9c96053336f20dbf59ba14b767034f/doc/LanguageClient.txt#L135
2. Right now, no. But should be possible without too much work. Please file a feature request if you want to have this functionality.
3. It has to be supported from neovim side. Please file issue at neovim.

**Comment by ym1234** [comment]
Thanks!
