### ISSUE TITLE
How Do I add include directories

### ISSUE THREAD

**Issue by DSUK** [autozimu/LanguageClient-neovim#746]
suppose I'm working on a project with a non-standard library (let's say its in `/foo/randomlib/`) and using clangd as the language server

how to I communicate to the language server that `/foo/randomlib/` is also a directory to look for header files in etc?

**Comment by theHamsta** [comment]
Create a compilation database (compile_commanda.jsons) at project root. For instance with CMake (https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html)

**Comment by DSUK** [comment]
Thank you, that's what I was looking for.
