### ISSUE TITLE
js omni completion not working

### ISSUE THREAD

**Issue by terkelg** [autozimu/LanguageClient-neovim#747]
## Describe the bug
I cannot get omni function completion working for some reason.
I have tried `setlocal omnifunc=LanguageClient#complete`. 
All other language server features are working.

## Environment
- neovim/vim version: NVIM v0.3.4
- This plugin version: 14dafc1
- This plugin's binary version: `languageclient 0.1.140 56859896904347856f6491d143dd447bc05c3df0`
- Language server link and version: 2.11.2

Minimal vimrc content
```vim
filetype plugin indent on
call plug#begin('~/.vim/plugged')
Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh',
        \ }
call plug#end()

    let g:LanguageClient_autoStart = 1
    let g:LanguageClient_serverCommands = {}
    if executable('javascript-typescript-stdio')
      let g:LanguageClient_serverCommands = extend(g:LanguageClient_serverCommands, {
            \ 'javascript': ['javascript-typescript-stdio'],
            \ 'typescript': ['javascript-typescript-stdio'],
            \ 'javascript.jsx': ['javascript-typescript-stdio'],
            \ 'typescript.tsx': ['javascript-typescript-stdio'],
            \ })

      setlocal omnifunc=LanguageClient#complete
    endif
```

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Configure vimrc
2. Open JavaScript or TypeScript file
3. Complete with `<C-x><C-o>`

## Current behavior
Hitting `<C-x><C-o>` does only complete with words from the current buffer.

## Expected behavior
Completion of built-in JavaScript and TypeScript methods like `Math.sin` and custom methods from the current project.

**Comment by Shougo** [comment]
`<C-x><C-o>` is for omnifunc.

**Comment by terkelg** [comment]
Sorry for the typo. I have updated the issue.

**Comment by LoveSponge** [comment]
I've just spent a couple of hours trying to fiddle and get this working; I read the help docs and it looks like the name of the _complete_  function may have changed: 

```
LanguageClient#textDocument_completion
```

Ref: doc/LanguageClient.txt (section 4: functions) - sorry not actual line number - can't see it on mobile...

I've thrown In the towell for the night, myself, will update tomorrow with status.

**Comment by dwhitney** [comment]
I get the popup menu with suggestions, but when a selection is chosen, the import is not added to my file. Is this the same issue you are having? If not I will submit a new issue

**Comment by terkelg** [comment]
Thank you for looking into this @LoveSponge.
@dwhitney I haven't tried with  `LanguageClient#textDocument_completion` but I don't get any completion, not even the popup menu.

**Comment by dwhitney** [comment]
Are you using a OSX? I had a brew installed version of neovim and had the
same problem as you. When I uninstalled that and installed the binary from
neovims website, it started working

**Comment by autozimu** [comment]
`LanguageClient#textDocument_completion` is an LSP method and is used by other wrapper functions inside this plugin.

If you're trying omni completion, then `LanguageClient#complete` is the correct answer.

For javascript project, because there are so many different ways to setup and consume modules, the language server might not understand what modules are available to consume, thus producing no completions outside the current file.

Try with simple project and basic completion, like `console.err`.

Alternatively, put the project in an accessible place if it is possible so I can take a look. But it's not guaranteed I can find out something due to reasons mentioned above.

**Comment by martskins** [comment]
Closing this as it seems to be stale and still lacking info to reproduce.
