### ISSUE TITLE
The sign is not displayed

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#753]
## Describe the bug
The sign is not displayed.

## Environment
- neovim/vim version v0.3.4
- This plugin version 0b17a7a978bc7bc11d654c21db623995966b0ac8
- Minimal vimrc content 
```
set hidden
set completeopt=menu
set signcolumn=yes
let g:LanguageClient_useVirtualText = 0
let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ }
```

## To Reproduce
1. Open a Rust file with an error.

**Comment by autozimu** [comment]
You are using the latest commit, which is not always a tagged release.

I cannot guarantee the latest can always compile and function properly. If you're an user, please always use a tagged release.

With that said, I just pushed a few more commits. Signs issue should been resolved by now.

**Comment by nabezokodaikon** [comment]
I confirmed that it has been corrected.
Thank you.
