### ISSUE TITLE
Limit diognostics to onsave

### ISSUE THREAD

**Issue by UlisseMini** [autozimu/LanguageClient-neovim#754]
## Is your feature request related to a problem? Please describe.
Yes, i'm learning haskell and using haskell-ide-engine and i run into a lot of errors (lint syntax bad imports etc) they tend to overwhelm me since they are always happening (say i type out a function signature then pause to think, then i instantly i get bombarded with red errors)

## Describe the solution you'd like
Instead of diagnostics being displayed on screen automatically all the time have an option (or function) that can be called to display them,
another good thing to have would be to integrate with syntastic for the people who have a setup and don't want to learn to configure a new plugin that does the same thing.

## Describe alternatives you've considered
Limiting how often diagnostics are sent to the server (bad workaround)

Love your plugin btw :smile:

**Comment by urandom** [comment]
It would also be preferable to do the diagnostics when you exit insert mode. Quite a few language servers wil spam you with errors while you are typing, because you obviously didn;t finish the statement.

**Comment by martskins** [comment]
I'm assuming you are talking about virtual texts. Virtual texts can now be hidden while on insert mode by setting `let g:LanguageClient_hideVirtualTextsOnInsert = 1`, so I guess that solves this issue. I'll close this as it's been solved to my knowledge, but feel free to re-open if that's not what you wanted.
