### ISSUE TITLE
Final newline is dropped from text sent to servers, causing bogus warnings

### ISSUE THREAD

**Issue by dimbleby** [autozimu/LanguageClient-neovim#757]
Since 0.1.141, buffer contents as reported eg in `textDocument/didOpen` drop the final newline in the file.

This causes some linters to complain eg the python language server (via flake8) then starts reporting "W292 no newline at end of file" - even though there is a newline at the end of the file.

At 0.1.140, text for `textDocument/didOpen` was gathered via LSP#text, which added `['']` to the lines that it gets from `getbufline()`.  But at 0.1.141, `textDocument_didOpen()` just calls `getbufline()` directly, which apparently loses the final newline.

**Comment by dimbleby** [comment]
I got to wondering how other plugins did it - [here](https://github.com/prabirshrestha/vim-lsp/blob/0310241af11adc6c3a7ba93955bc27b15744c957/autoload/lsp/utils/buffer.vim) is an example that's even more elaborate - checking all of `fixendofline`, `endofline` and `binary` to decide what to do.

License for that code is MIT, maybe just copy it?

**Comment by autozimu** [comment]
This plugin actually has something very similar, https://github.com/autozimu/LanguageClient-neovim/blob/b9f19e8ffac4633f886f70a6dcb0e057b8e0ed7c/autoload/LSP.vim#L12-L20

Not sure which part went wrong. Need time to investigate.

**Comment by autozimu** [comment]
What you described is totally correct. We should use the wrapped up `LSP#text()` instead of raw `getbufline()`.

**Comment by mkoura** [comment]
I have 0.1.141 and up-to-date plugin (last commit 2b1350cd3be21c8b8fa2f52a62e7b8bdeca3cf7f) and still see this issue (pyls complains about "W292 no newline at end of file").

**Comment by autozimu** [comment]
The fix hasn't been included in binary release yet.

You will need to build the latest yourself or wait for next binary release.

Sorry for this inconvenience.

**Comment by theHamsta** [comment]
There is not a release of the binary after every commit. Does the issue persist after building the binary yourself with cargo in the plug-in directory and replacing the automatically downloaded one in the `bin` directory?
