### ISSUE TITLE
Regression: Signs do not disappear in gutter after line shifts.

### ISSUE THREAD

**Issue by mhuttner** [autozimu/LanguageClient-neovim#758]
## Description
Warning signs in gutter do not get deleted properly after deleting or inserting a line. 
This was reintroduced in 0.1.141, 0.1.140 does not have this issue

## To Reproduce
- Open a valid python file, using python-language-server 
- Delete a line causing multiple syntax errors
- Undo the change, reinserting the line

## Current behavior
- Warning signs in the gutter will remain

## Expected behavior
- Resolved warnings are cleared

## Possible Cause
I think the problem was introduced by
https://github.com/autozimu/LanguageClient-neovim/blob/788e91931b9397cad047fed4c74811a62fdac1eb/src/sign.rs#L20-L23

Since the line number changes and causes the Equality check to fail.

**Comment by AdaShoelace** [comment]
In addition to signs not disappearing when inserting or deleting a line, they also persist after correcting the error in question. This in turn forces me to call `signs unplace *` after correcting an error in order for the signs to reflect the correct state of my code.

**Comment by kierun** [comment]
If anyone wants to see how it looks, this is it:

![screenshot](https://user-images.githubusercontent.com/3079575/54273496-e82cf600-457d-11e9-8593-a7180563050c.png)

Just wrote a simple script, making many errors along the way.

**Comment by autozimu** [comment]
Should be resolved by https://github.com/autozimu/LanguageClient-neovim/pull/769
