### ISSUE TITLE
Strange text in completions

### ISSUE THREAD

**Issue by ANtlord** [autozimu/LanguageClient-neovim#759]
- Did you upgrade to latest plugin version?
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.3.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-P1bWuS/neovim-0.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-P1bWuS/neovim-0.3.1/build/config -I/build/neovim-P1bWuS/neovim-0.3.1/src -I/usr/include -I/build/neovim-P1bWuS/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-P1bWuS/neovim-0.3.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- This plugin version (`git rev-parse --short HEAD`):
`aa91c56`
- This plugin's binary version (`bin/languageclient --version`):
`languageclient 0.1.141`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()

augroup filetype_rust
    autocmd!
    autocmd BufReadPost *.rs setlocal filetype=rust
augroup END

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'stable', 'rls'],
    \ 'python': ['/endlessos/develop/buf/.venv/bin/pyls'],
    \ }
let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```
- Language server link and version:
[python-language-server 0.24.0](https://github.com/palantir/python-language-server)
[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Create/Fetch example project ...
1. Start vim, `nvim -u min-vimrc.vim` ...
1. Edit ...
1. Execute ....
1. See error

## Current behavior
The selected completion appears with placeholders. It looks like a snippet but it's not a snippet.

## Expected behavior
The selected completion should be without the placeholders.

## Screenshots
![screenshot from 2019-03-07 19-29-46](https://user-images.githubusercontent.com/2972483/53953857-813bb700-410f-11e9-8cc5-0090e7b6c214.png)

## Additional context
I just installed neovim, the Language Client, Python Language server. The issue is reproduced on the sample python project from the code repository. The nvim.init that is pointed in the description is the whole nvim.init

**Comment by pvdrz** [comment]
I'm having the same problem, however this is a duplicate or is related to: https://github.com/autozimu/LanguageClient-neovim/issues/737#issuecomment-465089402. Downgrading python-language-server as stated in https://github.com/tigersoldier/company-lsp/issues/85#issuecomment-470197923 is a partial fix

**Comment by ANtlord** [comment]
Can it be fixed this way for every language or only for python?

**Comment by pvdrz** [comment]
I'm just experiencing this in the latest version of pyls, are you having this behavior in any other language?

**Comment by autozimu** [comment]
Please see my comment https://github.com/autozimu/LanguageClient-neovim/issues/737#issuecomment-469791907

And the issue for pyls https://github.com/palantir/python-language-server/issues/515
