### ISSUE TITLE
Setup for  C/C++  and  Python 

### ISSUE THREAD

**Issue by bones97** [autozimu/LanguageClient-neovim#76]
I really love this plugin and would like to know how I can set up the serverCommands for python and C/C++.

**Comment by autozimu** [comment]
Please follow setups on their corresponding project websites:
- https://github.com/palantir/python-language-server
- https://clang.llvm.org/get_started.html

After setting language servers properly, neovim side setting is pretty straight-forward,
```
let g:LanguageClient_serverCommands = {
            \ 'python': ['pyls'],
            \ 'cpp': ['clangd']
            \ }
```
(Given those commands are available from your PATH.)

**Comment by bones97** [comment]
Thank You

**Comment by DerWeh** [comment]
Is there by chance an easier way to get `clangd` instead of checking out the huge svn repository? It takes ages.

**Comment by autozimu** [comment]
At the moment, I think the answer is no.
