### ISSUE TITLE
Mention MUcomplete compatibility

### ISSUE THREAD

**Issue by lifepillar** [autozimu/LanguageClient-neovim#760]
Hi,
[MUcomplete](https://github.com/lifepillar/vim-mucomplete)'s author here (MUcomplete is an autocompletion plugin).

Recently, I have had the opportunity to try your plugin with a couple of languages (C, F#). It seems to go along well together with MUcomplete (for F#, and possibly some other languages, minimal configuration is needed in MUcomplete, but I have documented that). Perhaps, as more people get using both, other issues may emerge, but I am positive that full compatibility may be achieved.

So, how about mentioning MUcomplete in the Readme as another option for autocompletion?

Pinging @jordwalke, who has used both and might be interested.

**Comment by autozimu** [comment]
Thanks for bring this up.

Glad to mention it inside the README.
