### ISSUE TITLE
Is it possible to auto-discover where declarations are?

### ISSUE THREAD

**Issue by nkakouros** [autozimu/LanguageClient-neovim#762]
## Is your feature request related to a problem? Please describe.
I do not know if this is a limitation of vim, this plugin or the language server. I am using bash-language-server. In one script I call a function that is defined in another file ("library"). When I call `LanguageClient#textDocument_defintion()` on the function's name in the first script, I get an error:

```
[LC] Not found!
```

If I then open the library file and try the same thing, the definition is correctly located. 

If I then close the library file, the definition is still correctly found and the library file is reopened. 

## Describe the solution you'd like
The solution I describe is an uneducated one and comes from my perception of how things work. It would be nice to have some option that would feed to the language server all script files that are contained in the current working directory (ie the current project). This way, declarations would be known to the language server and jumping to them would not require the user to first manually open the files that contain them.

## Describe alternatives you've considered
None.

## Additional context
None.

**Comment by autozimu** [comment]
This is not an issue of this plugin. Please file it to the language server side.

Language server itself should be able to discover related files in repo.
