### ISSUE TITLE
Option to suppress virtual text on current line

### ISSUE THREAD

**Issue by theHamsta** [autozimu/LanguageClient-neovim#764]
## Is your feature request related to a problem? Please describe.
I like Neovim's virtual text feature. However, there is currently no way to give certain virtual text namespaces preference over others. This can result in conflict if two plug-ins try to display text in the same line.

If I want to use echodoc's virtual text feature [1] in conjunction with this plug-in, echodoc's diagnostics are overwritten by LanguageClient-neovim's diagnostic since a unfinished line is likely to provoke a LSP diagnostic message. Also, those diagnostics for lines I'm currently typing are kind of irritating.

## Describe the solution you'd like

I personnaly applied a hard-coded patch to this plug-in in order to not display diagnostics for current line.

`autoload/LanguageClient:156`
```viml
    for vt in a:virtual_texts
        if line('.') !=#  vt['line'] + 1
            call nvim_buf_set_virtual_text(a:buf_id, a:ns_id, vt['line'], [[vt['text'], vt['hl_group']]], {})
        endif
    endfor
```
It would be nice to have an option to choose above behavior. Maybe only for insert mode or maybe only if echodoc uses the `virtual` option. It would be nice if echodoc and the language client would play nicely together. Probably the clearest configuration would be to offer an option to suppress diagnostic for current line while in insert mode as these line can be considered unfinished.

## Describe alternatives you've considered
Since for me, I prefer diagnostics for the current line not to show up I have the patch above in my fork of this plug-in. An alternative would also if echodoc could use floating windows for showing the signature help.

## Additional context
This is kind of related to #603. A no diagnostic for insert mode would also solve this issue. 

[1]:
```
 let g:echodoc#enable_at_startup = 1
 let g:echodoc#type = 'virtual'
```

**Comment by martskins** [comment]
This is now supported by setting `let g:LanguageClient_hideVirtualTextsOnInsert = 1`.

Closing as it's solved, but feel free to re-open if it's not what you're looking for.
