### ISSUE TITLE
Regression: Signs are displayed with diagnosticsSignsMax set to zero

### ISSUE THREAD

**Issue by mburakov** [autozimu/LanguageClient-neovim#765]
## Description
Up to 0.1.140 it was possible to disable signs (and gutter) entirely by setting diagnosticsSignsMax to zero. This feature was introduced with bb733ef. Unfortunately, this does not work anymore since 0.1.141.

## To Reproduce
1. Set diagnosticsSignsMax to zero (`let g:LanguageClient_diagnosticsSignsMax = 0`)
2. Open any source file with warnings/errors
3. Observe gutter with corresponding signs

## Current behavior
Gutter and diagnostic signs are visible after setting diagnosticsSignsMax to zero.

## Expected behavior
Gutter and diagnostic signs must not be visible after setting diagnosticsSignsMax to zero.

## Additional context
I assume that since 0.1.141 **zero** value is mistakenly reinterpreted as **null** value. And displaying all the signs is a documented behavior for null value.

**Comment by autozimu** [comment]
Resolved by https://github.com/autozimu/LanguageClient-neovim/pull/769
