### ISSUE TITLE
Some LSPs can't handle neovim being backgrounded

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#768]
*I'm not sure if it's a bug or not so I'm erring on the side of saying it's not LanguageClient's fault and this would be a request for some sort of compatibility method.*

## Is your feature request related to a problem? Please describe.

Some LSPs seem to be unable to handle the backgrounding of neovim (ctrl+z/SIGSTOP), which for many developers like myself is a common part of the edit-build-debug cycle. I don't use `:terminal` and I've come to prefer `ctrl+z` followed by building/linting/testing at the terminal rather than using `!make` or `:make` because it's one less ide-specific step or configuration hassle.

Unfortunately, while I've had no problems doing this with most LSPs, I've run into an issue with [sourcegraph's JS/TS LSP](https://github.com/sourcegraph/javascript-typescript-langserver/) in `--stdio` mode which seems to irrecoverably fail (without any errors) when neovim is suspended for more than a moment or two. Briefly suspending neovim and then resuming is OK, but if I suspend neovim, build/test/whatever for some time and then `fg` neovim again, there are no completions at all. I've tried running `:LanguageClientStop <CR> :LanguageClientStart` afterwards, but that has no effect.

## Describe the solution you'd like
I am wondering if there is something this plugin can do to keep LSP channels alive/functioning across SIGSTOP/SIGCONT cycles. Obviously the majority of LSP clients are for graphical editors/IDEs where this isn't an issue (and probably not even for emacs users that use it in client mode), but for many (neo)vim developers `SIGSTOP` is a normal part of their routine, everyday usage.

## Describe alternatives you've considered
Restarting the language client doesn't help, otherwise I was planning on adding a hook to automatically restart the language client after resume.

**Comment by autozimu** [comment]
Is it still the case?

I cannot reproduce this locally. I'm using macOS with zsh 5.7.1, neovim 0.4.0-dev, javascript-typescript-langserver 2.11.3

**Comment by autozimu** [comment]
BTW, if the issue is only reproducible on a single language server, do you think it makes more sense fix it up at the language server side?

**Comment by mqudsi** [comment]
@autozimu I'll try to run it behind a network proxy instead of over stdio to see if it dumps any messages while neovim is suspended (although it might suddenly keep working all on its own if I do that).

Although I have been going through my git logs and `package.log` files and it seems like it was this language server: https://github.com/theia-ide/typescript-language-server

I guess if the context of this changes from feature request to bug report then I need to put together a full repro for you! Thank you for your patience. If I close this can I reopen it when that info is available?

**Comment by autozimu** [comment]
Sounds good to me.
