### ISSUE TITLE
LanguageClient breaks folding

### ISSUE THREAD

**Issue by nkakouros** [autozimu/LanguageClient-neovim#771]
- Did you upgrade to latest plugin version? yes
- Did you upgrade to/compile latest binary? yes
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yes
- Did you check [troubleshooting]? yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
I have found the following line in `~/.local/share/nvim/rplugin.vim` to break folding:

```
      \ {'sync': v:false, 'name': 'TextChanged', 'type': 'autocmd', 'opts': {'pattern': '*', 'eval': '[{''filename'': expand(''%:p''), ''buftype'': &buftype}]'}},
```

What happens is that when in a fold, some actions such as pressiong `o` make the fold close.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
`NVIM v0.4.0-381-g7fcf2f926`
- This plugin version (`git rev-parse --short HEAD`): 1459d24
- This plugin's binary version (`bin/languageclient --version`): languageclient 0.1.142
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): Just install this plugin
- Language server link and version: -

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Create the following file:
```
" vim:foldmethod=marker:foldlevel=0:
" sdfsdf {{{
df
" }}}
```
2. `\nvim -u NORC path/to/file`
3. Press `jlo`

## Current behavior
The fold closes on pressing `o`.

## Expected behavior
The fold should not close.

## Screenshots
https://www.youtube.com/watch?v=Pd1C5rjCw88

## Additional context
Removing the line I mentioned above resolves the issue when calling `nvim -u NORC`.

**Comment by autozimu** [comment]
The `rplugin.vim` line was added when this plugin was implemented as neovim remote plugin and that was deprecated long time ago. Please run `:UpdateRemotePlugins` command to clean it up, and follow the current plugin setup steps if you still intent to use this plugin.

Besides, not sure what's the expected outcome in this case. Even for the original remote plugin, neovim's intended use case is that whenever there is change to remote plugin, run `:UpdateRemotePlugins` first to update the registration, where here you're using an empty VIMRC which means there is absolutely no remote plugins can be found.
