### ISSUE TITLE
How to fetch the LSP symbols only?

### ISSUE THREAD

**Issue by liuchengxu** [autozimu/LanguageClient-neovim#775]
## Is your feature request related to a problem? Please describe.
I'm adding LCN support to [vista.vim](https://github.com/liuchengxu/vista.vim) which is a tagbar like plugin, but with async and LSP symbols support.

What I need is an approach to merely fetch the document/workspace symbols without further processing. 

I tried this:

```vim
function! LCNHandler(output) abort
" vista logic
...
endfunction

function! vista#executive#lcn#Execute() abort
  let l:params = {
              \ 'filename': LSP#filename(),
              \ 'text': LSP#text(),
              \ 'handle': v:true
              \ }
  call LanguageClient#Call('textDocument/documentSymbol', l:params, function('LCNHandler'))
endfunction
```

But LCN still automatically display these symbols for me via fzf(or sth else), which is not what I want.

## Describe the solution you'd like

A way to fetch the symbols only.

**Comment by autozimu** [comment]
If you don't want this plugin to handle the response from language server and provide your own handler, you can set the parameter `'handle': v:false`.

Also, you can simply call the wrapped function,
```vim
 call LanguageClient#workspace_symbol({'handle': v:false}, 'LCNHandler')
```

The missing parameters (like `filename`) will be filled out by this plugin.

**Comment by liuchengxu** [comment]
Good. I have finished the initial support in https://github.com/liuchengxu/vista.vim/pull/25:

<img width="1680" alt="屏幕快照 2019-03-20 上午8 26 31" src="https://user-images.githubusercontent.com/8850248/54650599-43b13380-4aea-11e9-8693-0ab890a798b3.png">

The two more questions are:

1. Could LCN return the symbol instead of the number of kind? So I don't have to transform them in vista.vim. coc.nvim did this. What's more, coc.nvim provides some kinds that do not exist in `s:symbol_kinds`, e.g., `TypeParameter` in rust, I guess that benefits from the vscode extension?

```vim
let s:symbol_kinds = {
    \ '1': 'File',
    \ '2': 'Module',
    \ '3': 'Namespace',
    \ '4': 'Package',
    \ '5': 'Class',
    \ '6': 'Method',
    \ '7': 'Property',
    \ '8': 'Field',
    \ '9': 'Constructor',
    \ '10': 'Enum',
    \ '11': 'Interface',
    \ '12': 'Function',
    \ '13': 'Variable',
    \ '14': 'Constant',
    \ '15': 'String',
    \ '16': 'Number',
    \ '17': 'Boolean',
    \ '18': 'Array',
    \ }
```

2. I believe that I have just done the `RunAsync` part, then how to fetch the symbols synchronously in LCN?

**Comment by autozimu** [comment]
For item 1, this plugin is serializing the same way language server and client is communicating. I'm not sure if there is a way to serialize things differently for one specific type in one specific request.

Regarding item 2, you can use another wrapper
https://github.com/autozimu/LanguageClient-neovim/blob/next/autoload/LanguageClient.vim#L801

to call the function synchronously. But I don't recommend it since it will block the vim process.

**Comment by liuchengxu** [comment]
It makes more sense to have a real `runSync` similar to `CocAction` instead of the sleep and wait strategy IMHO. Any way, the async version could also be enough for now.

**Comment by liuchengxu** [comment]
Update for my first question: the missing kinds are found in the latest LSP spec https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol.

**Comment by autozimu** [comment]
There is really no way to support async operations in vim without callbacks.

With neovim rpc API, the sync call will block neovim until the response is returned, which is effectively the same as sleeping and waiting strategy in this plugin. Hence I would recommend using the async version wherever possible.
