### ISSUE TITLE
Logging File Not showing up

### ISSUE THREAD

**Issue by vito-c** [autozimu/LanguageClient-neovim#776]
I'm trying to find the log file. I don't have `$TMP` or `$TEMP` variables set, but nothing is showing up in my `/tmp` dir.

I have this in my vimrc
```
let $LANGUAGECLIENT_DEBUG=1
let g:LanguageClient_loggingLevel='DEBUG'
let g:LanguageClient_autoStart=0
```

then after I open the file I do:
```
:call LanguageClient_setLoggingLevel('DEBUG')
:call LanguageClient#startServer()
```

I highly recommend you add steps to get debug logging in the troubleshooting section so it's on the front page. Thanks!

**Comment by autozimu** [comment]
You haven't specify the log path,

https://github.com/autozimu/LanguageClient-neovim/blob/15cc7c72eea9e7128daa17298e2dc0eec07fef27/min-vimrc.vim#L23

**Comment by vito-c** [comment]
Thank you can you add this to trouble shooting?
