### ISSUE TITLE
error caught in async handler rplugin/python3/LanguageClient:     autocmd:TextChanged:* []  

### ISSUE THREAD

**Issue by teto** [autozimu/LanguageClient-neovim#78]
> If you are reporting a bug, please read following FAQ first.

If not, please try follow the instructions there first.

# If you are still seeing an error or other types of error, please create ticket with
- neovim version NVIM v0.2.1-dev
- Plugin version (git SHA) 98f558e335f8af7f12ecafa332c8685a99d2b5d0

CheckHealth is fine, I am running latest python clients.
I regularly have this error popping out:
```
    40 || error caught in async handler '/home/teto/.local/share/nvim/site/pack/LanguageClient-neovim/rplugin/python3/LanguageClient:   
       ↳ autocmd:TextChanged:* []'                                                                                                      
    41 || TypeError: handleTextChanged() missing 1 required positional argument: 'filename'  
```

This seems to be related to the latest commit https://github.com/autozimu/LanguageClient-neovim/commit/98f558e335f8af7f12ecafa332c8685a99d2b5d0

**Comment by autozimu** [comment]
Did you run `:UpdateRemotePlugins` after update?

**Comment by teto** [comment]
hum that seems to fix it thanks. I have UpdateRemotePlugin autorun on update by vim-plug for other plugins but not this one. Fixed :)
