### ISSUE TITLE
Any possibility to add vscode-json-languageserver?

### ISSUE THREAD

**Issue by sevaho** [autozimu/LanguageClient-neovim#782]
Is there any possibility to add vscode-json-languageserver or any other json language server?

**Comment by h-michael** [comment]
You can use any language server which  satisfies the lsp specification.

```
let g:LanguageClient_serverCommands = {
    \ 'json': ['vscode-json-languageserver', '--stdio']
    \ }
```

**Comment by autozimu** [comment]
It should work with any language server implementing the LSP protocol.
