### ISSUE TITLE
workspace_symbol() is limited to 50 results

### ISSUE THREAD

**Issue by muni-corn** [autozimu/LanguageClient-neovim#784]
When I call LanguageClient#workspace_symbol(), it's limited to 50 results. I can't access symbols that start with any letter towards the end of the alphabet.

This isn't limited to any single language server. Seems to be a language-wide problem.

I'm using FZF with the plugin. Latest commit I'm working with for LanguageClient-neovim is `c33c45dd: (cargo-release) version 0.1.144`.

**Comment by autozimu** [comment]
I don't recall there is such an restriction in this plugin. Are you sure it is limited from plugin side, not server side? Can you follow template to provide concrete reproduction steps?

I tried the operation on this project, and got 450 symbols.

<img width="1392" alt="Screen Shot 2019-04-05 at 5 13 14 PM" src="https://user-images.githubusercontent.com/1453551/55662233-75065080-57c6-11e9-87ed-59aea071d0e7.png">

**Comment by autozimu** [comment]
Not reproducible and no response.
