### ISSUE TITLE
LanguageClient_windowLogMessageLevel does not work for python

### ISSUE THREAD

**Issue by ipod825** [autozimu/LanguageClient-neovim#787]
With newest version of lsp, `let g:LanguageClient_windowLogMessageLevel='Warning'` still shows Info message in dianostic with pyls.

The Info messages shown is "[missing-docstring] Missing module docstring". For e.g, the following snippet shows this info.
```python
import os
os.path.isabs('/')
```

**Comment by teto** [comment]
I confirm.

**Comment by autozimu** [comment]
Sorry for the late response.

This particular setting (`g:LanguageClient_windowLogMessageLevel`) is used to filter out messages requested to display by language servers. In vim scenario, the messages will be displayed in echo area. https://microsoft.github.io/language-server-protocol/specification#window_logMessage

It's totally different than the diagnostics information of your code. Usually the diagnostics are configurable from language server side. e.g., pyls uses pycodestyle/pyflakes for various style checking and error detection, which supports customization of the rules applied on. Please refer to their (pyls/pycodestyle/pyflakes) corresponding documentations to find how to properly customize them.
