### ISSUE TITLE
ccls: Error handling message: sending on a disconnected channel

### ISSUE THREAD

**Issue by sumnerevans** [autozimu/LanguageClient-neovim#788]
## Describe the bug

When using `ccls`, performing any action results in an error similar to:

```
ERROR unnamed src/rpchandler.rs:13 Error handling message: sending on a disconnected channel

Message: {"jsonrpc":"2.0","method":"languageClient/findLocations","params":{"bufnr":1,"filename":"/home/sumner/school/csci564/projects/CacheSim/cache.cpp","gotoCmd":null,"handle":true,"languageId":"cpp","method":"textDocument/definition","position":{"character":40,"line":118}},"id":11}

Error: "SendError(..)"
```

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): **NVIM v0.3.4**
- This plugin version (`git rev-parse --short HEAD`): **c33c45d**
- This plugin's binary version (`bin/languageclient --version`): **0.1.144**
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): the `min-vimrc.vim` exhibits this problem when the following line is added to the `serverCommands` list:

   ```
   \ 'c': ['ccls'],
   ```
- Language server link and version: `ccls` and the output of `ccls --version`

    ```
    $ ccls --version
    ccls version 0.20190314-2-g64f9dbdc
    clang version 8.0.0 (tags/RELEASE_800/final)
    ```

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Open `main.cpp` in the `sample-cpp` project with the `min-vimrc.vim` (using the single modification described above).
1. Run `:call LanguageClient#textDocument_definition()`
1. See error `[LC] sending on a disconnected channel`

## Current behavior

An error is thrown. Example trace for `textDocument_definition`:

```
13:04:07 ERROR unnamed src/rpchandler.rs:13 Error handling message: sending on a disconnected channel

Message: {"jsonrpc":"2.0","method":"languageClient/findLocations","params":{"bufnr":1,"filename":"/home/sumner/tmp/LanguageClient-neovim/tests/data/sample-cpp/main.cpp","gotoCmd":null,"handle":true,"languageId":"cpp","method":"textDocument/definition","position":{"character":4,"line":8}},"id":2}

Error: "SendError(..)"

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new::ha91ac4f5f3650864 (0x70145f)
   1: <failure::backtrace::Backtrace as core::default::Default>::default::h387a9561621288e0 (0x7016ff)
   2: languageclient::rpcclient::RpcClient::call::h9ed3f3715be49405 (0x4d4765)
   3: languageclient::language_server_protocol::<impl languageclient::language_client::LanguageClient>::find_locations::h8bedfc1f9ab62121 (0x423736)
   4: languageclient::rpchandler::<impl languageclient::language_client::LanguageClient>::handle_method_call::h3f4b27abfdbad8ca (0x44f071)
   5: languageclient::rpchandler::<impl languageclient::language_client::LanguageClient>::handle_call::h981926dbf9871969 (0x4497cc)
   6: std::sys_common::backtrace::__rust_begin_short_backtrace::hc05776c37b3fa9a8 (0x52e6ab)
   7: std::panicking::try::do_call::hed24a25e6d3d3d29 (0x55e4e5)
   8: __rust_maybe_catch_panic (0x72f529)
             at src/libpanic_unwind/lib.rs:92
   9: <F as alloc::boxed::FnBox<A>>::call_box::h21724160cc250217 (0x56de87)
  10: <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hb820b7bb4e871f91 (0x72efbd)
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/liballoc/boxed.rs:744
      std::sys_common::thread::start_thread::h52b7919ca202bbe2
             at src/libstd/sys_common/thread.rs:14
      std::sys::unix::thread::Thread::new::thread_start::h561dd350a6a5bdaa
             at src/libstd/sys/unix/thread.rs:81
```

## Expected behavior

No error.

**Comment by przemkovv** [comment]
I've recently had similar problem on Arch after instalation of either `aur/ccls` or `aur/ccls-git` package. 
The issue was that ccls indexer was crashing after upgrading to LLVM 8 (you can check it by running `ccls -index .` command in project root).

I've solved it by recompiling ccls with clang compiler (I have gcc set by default), e.g. before installing package export `CC=clang` and `CXX=clang++` environment variables.

**Comment by martskins** [comment]
Closing as stale
