### ISSUE TITLE
LanguageClient-neovim is duplicating lines with rls

### ISSUE THREAD

**Issue by pvdrz** [autozimu/LanguageClient-neovim#789]
- Did you upgrade to latest plugin version? Yes.
- Did you upgrade to/compile latest binary? Yes.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? Yes.
- Did you check [troubleshooting]? Yes.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
On Rust nightly with RLS, LanguageClient is adding lines of code next to the old ones instead of replacing them.

I've tested `rustfmt` from the terminal and this does not happen.

## Environment
- neovim/vim version: `0.3.4`.
- This plugin version: `c33c45d`.
- This plugin's binary version: `0.1.144`.
- Minimal vimrc content: this [example][min-vimrc.vim] with `nightly` instead of `stable`.
- Language server link and version: [`rls 1.35.0 (49efc06 2019-04-06)`][rls].

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim
[rls]: https://github.com/rust-lang/rls
## To Reproduce
1. Create a new project with `cargo new my_project`
2. Start vim, `nvim -u min-vimrc.vim`
3. Edit `src/main.rs` or `src/lib.rs`
4. Write a `match` expression without a trailing comma in its last pattern:
```rust
match Some(4) {
    _ => println!("something")
}
```
5. Run `:call LanguageClient#textDocument_formatting()`

## Current behavior
Formatting is adding lines of code without removing the old ones.

## Expected behavior
Formatting should replace text instead of adding more.

## Screenshots
https://asciinema.org/a/BFnufgJp1PRaQIPnGc3yyNyUg.

**Comment by Tobi4161** [comment]
Had the same problem, fixed it by updating rls to version 1.35.0 (b202e14 2019-04-11)

**Comment by pvdrz** [comment]
Thank you @Tobi4161, I updated RLS and everything is ok now :)
