### ISSUE TITLE
Display diagnostic for current line in floating window

### ISSUE THREAD

**Issue by teto** [autozimu/LanguageClient-neovim#792]
## Is your feature request related to a problem? Please describe.
Haskell diagnostics are (very) verbose (multiple lines, up to 3/4). This makes virtualtext solutions useless since no screen is wide enough to display everything.

## Describe the solution you'd like
I would like to be able to see the diagnostic in a floating window instead of virtualtext (for the current line). Ideally I would like to keep virtualtext for other lines than the current but if it's too complex to do I wouldn't mind having the diagnostic just for the current line.

**Comment by mb720** [comment]
Having the diagnostics messages in a [separate buffer](https://github.com/haskell/haskell-ide-engine/issues/1332) would be fine for me, too.

**Comment by teto** [comment]
using neovim lsp now.
