### ISSUE TITLE
roxma/nvim-completion-manager source?

### ISSUE THREAD

**Issue by autozimu** [autozimu/LanguageClient-neovim#8]
As deoplete does not support async source, right now completion function is implemented as sync calls.

Might even better support async completion.

roxma/nvim-completion-manager looks cool and actively maintained/developed.

@roxma

**Comment by Shougo** [comment]
> As deoplete does not support async source, right now completion function is implemented as sync calls.

Of course it is on the todo list.
But I must refactor the implementation to support the feature.
And I have denite.nvim and neovim supports...

**Comment by autozimu** [comment]
@Shougo Thanks for the info.

I know you might be busy with other stuff, but could you given a rough estimation of when the work will start?

You can let me know if you need some more hand on that.

**Comment by Shougo** [comment]
> I know you might be busy with other stuff, but could you give a rough estimation of when the work will start?

https://github.com/Shougo/deoplete.nvim/issues/407

Hm.

Current loadmap:

* Split the gather candidates and the completion popup
* Add the async support
* Change option API like denite.nvim
* completefunc support?
* Parallel support?
* Vim8 support?

The async support is not so far, but it depends on the other works.

**Comment by autozimu** [comment]
Great. Thanks for sharing.

**Comment by Shougo** [comment]
I will start the implementation ASAP.

**Comment by Shougo** [comment]
> As deoplete does not support async source, right now completion function is implemented as sync calls.

I have implemented the feature.

**Comment by autozimu** [comment]
Cool! I will start upgrading the integration.

**Comment by Shougo** [comment]
Thanks.
I will test it.
