### ISSUE TITLE
Support TexLab language server

### ISSUE THREAD

**Issue by krishnakumarg1984** [autozimu/LanguageClient-neovim#804]
The officially supported language server for LaTeX is [TexLab](https://texlab.netlify.com/) which also supports BibTeX.  I have had a positive experience using it in VSCode for which the same author provides a client plugin bearing the same name. 

Can you please provide support for the `TexLab` language server?

**Comment by autozimu** [comment]
What extra support needed for this language server?

LSP exists to eliminate the need to accommodate particular as long as server and client adhere to the protocol.

**Comment by autozimu** [comment]
No response.
