### ISSUE TITLE
CodeAction: Error handling message: missing field `command`

### ISSUE THREAD

**Issue by schmidma** [autozimu/LanguageClient-neovim#805]
- Did you upgrade to latest plugin version?
yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
languageclient 0.1.146 
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
ok
- Did you check [troubleshooting]?
yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
Language Server Specification [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) states  

> *A CodeAction must set either `edit` and/or a `command`. If both are supplied, the `edit` is applied first, then the `command` is executed.*

If no command is given calling `call LanguageClient#textDocument_codeAction()` results in a the following:

```
18:23:32 INFO reader-Some("cpp") src/rpcclient.rs:169 <= Some("cpp") {"jsonrpc":"2.0","id":3,"result":[{"title":"FixIt: use of undeclared identifier 'ballls'; did you mean 'balls'?\n\nBallDetectionNeuralNet.cpp:41:30: note: 'balls' declared here","kind":"quickfix","edit":{"documentChanges":[{"textDocument":{"uri":"file:///home/schmidma/worktree/hulks/nao/src/vision/Modules/BallDetection/BallDetectionNeuralNet.cpp","version":0},"edits":[{"range":{"start":{"line":42,"character":4},"end":{"line":42,"character":10}},"newText":"balls"}]}]}}]}
18:23:32 ERROR unnamed src/rpchandler.rs:13 Error handling message: missing field `command`
```

This call should fix a misspelled member variable `ballls` to `balls`.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): v0.3.4
- This plugin version (`git rev-parse --short HEAD`): f71ab82
- This plugin's binary version (`bin/languageclient --version`): 0.1.146
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): troubleshooting version
- Language server link and version: [ccls](https://github.com/MaskRay/ccls)

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Open C++ project with ccls as language server
1. misspell a member variable
1. you should get a response like `[...] did you mean [...]`
1. calling `call LanguageClient#textDocument_codeAction()` results in a call like the one mentioned above

## Current behavior
A quick fix exits with error `missing field command`

## Expected behavior
The suggested quick fix should be applied

## Screenshots
not applicable

## Additional context
not applicable

**Comment by dimbleby** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/d7988a89a68bbac2a9f4a08dfbbb7981720c8f7f/src/language_server_protocol.rs#L1245

Assumes that the response to a CodeActionRequest is a list of commands, but the type should be CodeActionResponse.

Decoding correctly should be trivial; more work needed to actually implement any edits...
