### ISSUE TITLE
support rust-analyzer

### ISSUE THREAD

**Issue by quanlou** [autozimu/LanguageClient-neovim#808]
When I use `rust-analyzer` instead of `rls`, the 
```
:call LanguageClient#textDocument_definition()
```
will result 
```
[LC] Definition links are not supported!
```
But the `rust-analyzer` actually is supporting  `go to definition` feature

**Comment by ngortheone** [comment]
I have this issue with latest `rust-analyzer` and language client.
Do I need to do some special configuration?

My config is:
```
let g:LanguageClient_serverCommands = {
   \ 'rust': ['~/.cargo/bin/ra_lsp_server'],
   \ 'python': ['~/.local/bin/pyls'],
   \ }

```
