### ISSUE TITLE
[next] gopls: completion includes full function signature

### ISSUE THREAD

**Issue by sebastianst** [autozimu/LanguageClient-neovim#813]
## Describe the bug
As already mentioned in #795, the recent fix of that bug now introduced a new bug: `gopls` Go completion now completes a function/method by writing out the full function's signature. E.g., typing `fmt.Print<tab>` and selecting the `fmt.Println` completion actually now completes not only to `fmt.Println` but to `fmt.Println(a ...interface{})`.

## Environment
- neovim/vim version:
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```
- This plugin version: 6ee4c89
- This plugin's binary version: `languageclient 0.1.146 6ee4c8994ee84609f8370aa4766b66c7cbad1424`
- Minimal vimrc content:
```vim
" deoplete and LanguageClient-neovim via vim-plug and the follow config for LC
let g:LanguageClient_serverCommands = {
      \ 'go': ['~/go/bin/gopls'],
      \ }

```
- Language server link and version: most recent [gopls](golang.org/x/tools/cmd/gopls)

## To Reproduce
1. Open any file in a Go project
2. Type e.g. `fmt.Print<tab>`

## Current behavior
Completion includes full function signature: `fmt.Println(a ...interface{})`

## Expected behavior
Completion to `fmt.Println` and the signature being shown somewhere else in vim

## Additional context
Bug caused by recent fix of #795, see discussion there at the bottom.

**Comment by butterflyfish** [comment]
hope someone can fix this issue.

**Comment by dimbleby** [comment]
`g:LanguageClient_completionPreferTextEdit`, probably.

**Comment by 0xC0FFEE** [comment]
> `g:LanguageClient_completionPreferTextEdit`, probably.

This doesn't fix the issue for me.

**Comment by kid** [comment]
I had the same issue, I just fixed it by installing the latest version of `gopls`:
`GO111MODULE=on go get golang.org/x/tools/gopls@latest`

**Comment by autozimu** [comment]
No longer reproducible with latest gopls.
```
19:32 ➜  ~lcn git:(next) ✗ gopls version
golang.org/x/tools/gopls v0.1.2
    golang.org/x/tools/gopls@v0.1.3 h1:CB5ECiPysqZrwxcyRjN+exyZpY0gODTZvNiqQi3lpeo=
```

**Comment by butterflyfish** [comment]
@autozimu  it works well. But function parameter expansion  is lost. it works well w/ go-langserver. Do you know why ?

**Comment by autozimu** [comment]
It could be gopls doesn't support snippet. But I didn't find any documentation to confirm.

**Comment by Furkanzmc** [comment]
In case someone gets here with the same problem, I'm using `ccls` and had the same problem. `g:LanguageClient_completionPreferTextEdit = 1` fixed the problem. And that setting is on by default. I had it turned off because of a bug a couple of months ago and forgot about it.
