### ISSUE TITLE
Feature Request: an option to disable notifications in insert mode

### ISSUE THREAD

**Issue by luochen1990** [autozimu/LanguageClient-neovim#816]
## Is your feature request related to a problem? Please describe.
I am disturbed by the error messages and hints when I'm editing my code and not finished yet.

## Describe the solution you'd like
Provide an option to disable these notifications in insert mode, and when I'm switching to normal mode, display them again.

## Describe alternatives you've considered
Consider to make the above being default behavior.

**Comment by proxict** [comment]
I would also like to see that. This behaviour can be seen in YouCompleteMe, for example.
There, the validation wouldn't trigger until returned into the normal mode after some change is made. That way we wouldn't get false-positive errors during typing of our code :)

**Comment by martskins** [comment]
Are we talking about the diagnostics shown in virtual text here?
If that's the case I also found that a little distracting while typing, so I've been looking at LanguageClient-neovim's source code and I think I found a way to hide all virtual texts for the buffer you are editing while in insert mode.
Should I open a PR? Or are there any other plans for this?

**Comment by martskins** [comment]
Fixed by #982
