### ISSUE TITLE
Feature Request: add option to control signText level

### ISSUE THREAD

**Issue by luochen1990** [autozimu/LanguageClient-neovim#817]
## Is your feature request related to a problem? Please describe.
I am disturbed by the gutter when editing and scrolling through the code, I think there are enough notifications for these warnings and hints, But error is important enough to use the gutter, I think there should be some way to control this.

## Describe the solution you'd like
Provide an option to control which level of signText should be displayed in the gutter.

## Describe alternatives you've considered
set `signText = 0` or `""` in `g:LanguageClient_diagnosticsDisplay` to disable it

**Comment by autozimu** [comment]
Should be addressed in https://github.com/autozimu/LanguageClient-neovim/commit/0f4a1fcae7faacec1c7438c48b22645f2fd88369
