### ISSUE TITLE
Customize floating window

### ISSUE THREAD

**Issue by teto** [autozimu/LanguageClient-neovim#818]
## Describe the solution you'd like
I would like to customize the floating window on hover (background color, changing filetype as python's doc appears as markdown which ends up ). I could use an autocmd  like BufEnter but I am not sure how to identify LC-neovim floating windows ?

## Describe alternatives you've considered
Maybe name the buffer to something identifyable or trigger an autocommand on floating window opening.

https://github.com/autozimu/LanguageClient-neovim/blob/0ed9b69dca49c415390a8317b19149f97ae093fa/autoload/LanguageClient.vim#L356

**Comment by rhysd** [comment]
I think you can check the popup by checking bufname is `"__LanguageClient__"`. 

I guess

```
autocmd BufEnter __LanguageClient__ echo 'hello'
```

would work.

**Comment by teto** [comment]
cool thanks !

**Comment by cultab** [comment]
Incase someone else is trying to do this, I think the bufname changed to "__LCNHover__"

`autocmd BufEnter __LCNHover__ echo 'hello'`

Is what I had to use now.
