### ISSUE TITLE
Unexpected behavior in handleTextDocumentFormatting

### ISSUE THREAD

**Issue by cnt0** [autozimu/LanguageClient-neovim#82]
Hello. I'm trying to format my `.go` files using [go-langserver](https://github.com/sourcegraph/go-langserver). It produces JSON like this:   
```javascript
[
  {"range":{"start":{"line":0,"character":0},"end":{"line":8,"character":0}},"newText":""},
  {"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"newText":"formatted_code"}
]
```  

which I believe is ugly but still correct `textDocument/formatting` response.  

However, function [handleTextDocumentFormatting](https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/LanguageClient/LanguageClient.py#L1087) explicitly rejects responses with more than one textEdit. Why? Shouldn't it process all textEdits one by one?

**Comment by autozimu** [comment]
Yes, the response is legit.

I will address this issue shortly.
