### ISSUE TITLE
gopls suggestions missing first letter

### ISSUE THREAD

**Issue by delfick** [autozimu/LanguageClient-neovim#823]
- Did you upgrade to latest plugin version? yeap
- Did you upgrade to/compile latest binary? yeap
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yeap
- Did you check [troubleshooting]? yeap

## Describe the bug
When I select suggestions that appear in the completion menu from gopls, vim leaves out the first letter of the suggestion.

So say I start typing "f" and the first suggestion is "fmt", when I choose that suggestion the "f" changes to "mt"

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Features: +acl +iconv +jemalloc +tui
```
- This plugin version (`git rev-parse --short HEAD`):

```
(stephenmoore) ~/.vim/plugged/LanguageClient-neovim
 8:10 ──   git rev-parse HEAD
41c948e05532a92b27c9ef0509cea651592d6bb5
```

- This plugin's binary version (`bin/languageclient --version`):

```
(stephenmoore) ~/.vim/plugged/LanguageClient-neovim
 8:11 ──   bin/languageclient --version
languageclient 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93
```

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

```
call plug#begin('~/.vim/plugged')
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2'

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }

call plug#end()
autocmd BufEnter  *  call ncm2#enable_for_buffer()

set shortmess+=c
set completeopt=noinsert,menuone,noselect
set pumheight=6

" Always draw sign column. Prevent buffer moving when adding/deleting sign.
set signcolumn=yes

let g:LanguageClient_serverCommands = {
    \ 'go': ['gopls'],
    \ }
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```

- Language server link and version:

https://github.com/golang/go/wiki/gopls

gopls 1.16.0

`GOFLAGS="" GO111MODULE=on go get golang.org/x/tools/cmd/gopls@1.16.0`

## To Reproduce

install gopls and get min vimrc specified in this issue

Create a main.go with 

```
package main

import "fmt"

func main() {
}
```

in main() start typing "f", wait for it to suggest "fmt" and choose it.

## Current behavior
The suggestion gets filled without the first letter

## Expected behavior
The whole suggestion gets filled. I noticed that if I use golang-server instead of gopls then it works correctly.

**Comment by butterflyfish** [comment]
@delfick , does snippet(Function parameter expansion) works at your side w/ ncm2/gopls?

**Comment by delfick** [comment]
I forgot to update this issue, I updated gopls a few weeks ago and the problem seemed to go away.
