### ISSUE TITLE
Add Support for Elixir-LS

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#824]
## Is your feature request related to a problem? Please describe.
I would like to be able to use elixir-ls in LanguageClient-neovim

## Describe alternatives you've considered
I considered using ALE but there are so many problems with interoperation of these two that after a while it became unmanagable.  I tried to add it to my LanguageClient config with no luck 

```
let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
    \ 'elixir': ['~/.elixirls/language_server.sh'],
    \ }
```

This didn't work despite all the paths being quadruple checked.

**Comment by nfode** [comment]
For me elixir-ls works perfectly fine with the following config:
```
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ 'elixir': ['~/elixir-ls/rel/language_server.sh'],
    \ }
```

**Comment by autozimu** [comment]
What does `didn't work` mean in this case?

This plugin is striving for and should be language server agnostic (in most case). Please specify details if it didn't work for elixir language server.
