### ISSUE TITLE
How to get a list of classes that inherit from the base class?

### ISSUE THREAD

**Issue by chiphell123** [autozimu/LanguageClient-neovim#826]
How to get a list of classes that inherit from the base class ?

Can LanguageClient-neovim support this function?

- LspCqueryDerived - when used on function, get a list of functions that override this one. When used on a class, get a list of classes that inherit from this one.
- LspCqueryBase - get a base class (or a list of base classes) of this class.

**Comment by autozimu** [comment]
Please see https://github.com/MaskRay/ccls/wiki/LanguageClient-neovim#cross-reference-extensions for reference and replace the corresponding methods to onces provided by cquery.
