### ISSUE TITLE
additionalTextEdits above the cursor don't move the cursor down to the line where it used to be

### ISSUE THREAD

**Issue by tbodt** [autozimu/LanguageClient-neovim#827]
## Describe the bug
When clangd inserts a header automatically, the cursor will stay on the same line number, even though all the text above the cursor has shifted down. So it feels like the cursor suddenly moved up.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): NVIM 0.3.3
- This plugin version (`git rev-parse --short HEAD`): 41c948e
- This plugin's binary version (`bin/languageclient --version`): 0.1.146
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
    ```vim
    call plug#begin()

    " I use this for python, you probably don't need it
    Plug 'roxma/python-support.nvim'

    Plug 'autozimu/LanguageClient-neovim', {
        \ 'branch': 'next',
        \ 'do': 'bash install.sh',
        \ }
    let g:LanguageClient_serverCommands = {
        \ 'c': ['clangd'],
        \ 'cpp': ['clangd'],
        \ }
    let g:LanguageClient_loggingLevel = 'INFO'
    let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
    let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')

    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    let g:deoplete#enable_at_startup = 1

    call plug#end()

    set number
    ```

- Language server link and version: clangd trunk

## To Reproduce
1. Start vim with clangd
1. Trigger clangd automatic header insertion

## Current behavior
The cursor stays on the same line number, which makes it feel like it moved it up a line.

## Expected behavior
The cursor should move to the next line number because the text above it has shifted down a line.

**Comment by calewis** [comment]
I have the same issue.

**Comment by tbodt** [comment]
@calewis In case you haven't figured this out, there's a clangd flag to disable it.

**Comment by calewis** [comment]
@tbodt Thanks!  I found it earlier and edited my comment, but not before it sent the notification I guess.

**Comment by autozimu** [comment]
Duplicate https://github.com/autozimu/LanguageClient-neovim/issues/914
