### ISSUE TITLE
LanguageClient panics when I write a few lines of Rust with rls on linux.

### ISSUE THREAD

**Issue by TheSandvichMaker** [autozimu/LanguageClient-neovim#828]
## Describe the bug
On Ubuntu via WSL, LanguageClient quickly panics when I write a little bit of Rust with rls.
When I open files without editing them, LanguageClient works fine. The moment I write a little bit of code, it quickly panics:
```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:997:5```

This doesn't happen on Windows.

## Environment
- neovim version:
```
NVIM v0.4.0-dev
Build type: RelWithDebInfo
```

- This plugin version:
41c948e

- This plugin's binary version (`bin/languageclient --version`):
`languageclient 0.1.146`

- Minimal vimrc content:
```
call plug#begin('~/.local/share/nvim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
                        \ 'branch': 'next',
                        \ 'do': 'bash install.sh'
                        \ }

call plug#end()

" LanguageClient
set hidden

let g:LanguageClient_serverCommands = {
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
    \ }

let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_loggingFile  = expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```

- Language server link and version:
[rls](https://github.com/rust-lang/rls) 1.35.0 (49efc06 2019-04-06)

## To Reproduce
1. Use any rust project as a base.
2. Write some code for a bit, whether it be proper code or just gibberish.

## Current behavior
LanguageClient (or perhaps more accurately, LanguageServer) panics with the following trace:
[LanguageServer.log](https://github.com/autozimu/LanguageClient-neovim/files/3234692/LanguageServer.log)

## Additional context
Client log: [LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/3234699/LanguageClient.log)

**Comment by autozimu** [comment]
This seems very like an issue of rls.

Please report on rls repo if you can. Thanks.
