### ISSUE TITLE
How do I use scalameta/metals?

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#829]
Metals's site says LanguageClient-neovim is compatible.
[metals/vim](http://scalameta.org/metals/docs/editors/vim.html#docsNav)

**Comment by autozimu** [comment]
Using any language server shall be as easy as adding the language server if you already installed this plugin.

Is there any particular issue when you're using it that way?

**Comment by nabezokodaikon** [comment]
It was done in the following way.
```
let g:LanguageClient_serverCommands = {	
    \ 'scala': ['metals-vim']
    \ }	
```
But, the display position of the error symbol is incorrect.

**Comment by autozimu** [comment]
Can you follow the bug report template to provide reproduction steps?

**Comment by NightWhistler** [comment]
I can confirm that metals works.
This is my config:

```
let g:LanguageClient_serverCommands = {
    \ 'scala': ['/home/alex/bin/metals-vim']
    \ }

let g:LanguageClient_windowLogMessageLevel = 'Log'

" Having LogMessageLevel set to Log interferes with non-preview
" displaying of Hover
let g:LanguageClient_hoverPreview = 'Always'
```

Setting the windowLevelMessageLevel to 'Log' helps to see things like "compiling 32%".

**Comment by nabezokodaikon** [comment]
- Did you upgrade to latest plugin version?
> Yes

- Did you upgrade to/compile latest binary? Run shell command
> Yes

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
> OK

## Describe the bug
The display position of the error symbol is incorrect by metals/vim

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
> NVIM v0.3.7

- This plugin version (`git rev-parse --short HEAD`):
> `languageclient 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93`

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
```
set hidden	
set completeopt=menu	
set signcolumn=yes	

let g:LanguageClient_useVirtualText = 0	
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1

let g:LanguageClient_serverCommands = {	
    \ 'scala': ['metals-vim']
    \ }	
```

## To Reproduce
Steps to reproduce the behavior:
##### 1. Install Metals
```
$ curl -L -o coursier https://git.io/coursier
$ chmod +x coursier
$ ./coursier bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=LanguageClient-neovim \
  org.scalameta:metals_2.12:0.5.2 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o /usr/local/bin/metals-vim -f
```
##### 2. Create Scala project
```
$ sbt new nabezokodaikon/scala-basic.g8
```
##### 3. Run sbt
```
$ cd my-something-project
$ sbt
```
##### 4. Start Neovim
##### 5. Open Main.scala File
##### 6. Start Metals
##### 7. Edit Main.scala

**Comment by autozimu** [comment]
I followed the steps and no obvious issues found.

![Screen Shot 2019-06-19 at 4 11 49 PM](https://user-images.githubusercontent.com/1453551/59807596-787d8400-92ad-11e9-8126-9444402cd23f.png)

Please be more specific if you are still having issue.

**Comment by nabezokodaikon** [comment]
Is that so. it can not be helped. Thank you.
