### ISSUE TITLE
Preview windows does not continuously work

### ISSUE THREAD

**Issue by Huxpro** [autozimu/LanguageClient-neovim#835]
If the preview windows has already opened. Further `hover()` would display a empty preview windows. (Close preview windows first then call `hover()` works fine)

- neovim/vim version (`nvim --version` or `vim --version`):

nvim --version
NVIM v0.3.7

- This plugin version (`git rev-parse --short HEAD`):

41c948e

- This plugin's binary version (`bin/languageclient --version`):

languageclient 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93

- Language server link and version:

any

**Comment by Huxpro** [comment]
Hmm... I found https://github.com/autozimu/LanguageClient-neovim/pull/615 was proposed but does not get merged. Isn't auto-closing a good idea?

**Comment by DerWeh** [comment]
I have the same problem, I think the issue got introduce with the support for hover windows, but I am not sure. It was just around the same time that I noticed the problem.

**Comment by YaLTeR** [comment]
Same issue, I also believe it broke along with the floating window support.

**Comment by YaLTeR** [comment]
Confirming that it broke in 53ce2fee7d24dd9262ea783908e2edebc71635dc.
