### ISSUE TITLE
Completion contains JSON-ish placeholders

### ISSUE THREAD

**Issue by Z-Shang** [autozimu/LanguageClient-neovim#837]
## Describe the bug
The completion contains undesired strings of form: `$1{typename argname}`

## Environment
- neovim 0.3.7
- This plugin version (`git rev-parse --short HEAD`): 3e31d01
- This plugin's binary version (`bin/languageclient --version`): 0.1.146
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
let g:deoplete#sources = {}
let g:deoplete#sources.cpp = ['LanguageClient']

let g:LanguageClient_serverCommands = {
     \ 'cpp': ['ccls', '--log-file=/tmp/cc.log'],
     \ 'c': ['ccls', '--log-file=/tmp/cc.log'],
     \ 'clj': ['clojure-lsp'],
     \ 'clojure': ['clojure-lsp'],
     \ }
set completefunc=LanguageClient#complete
```

- Language server link and version: ccls,  `git rev-parse --short HEAD`: d3808de2, with prebuilt clang+llvm-8.0.0

## To Reproduce
Open up a C++ file, and trigger the completion, select any of the `[LC]` candidates that takes at least 1 argument.

## Current behavior
![Screenshot_2019-06-13_16-41-50](https://user-images.githubusercontent.com/859939/59410679-cbae8d00-8dfc-11e9-99ac-f8d0bedcbfaa.png)

**Comment by autozimu** [comment]
That is snippet returned by language server.

If you don't want it to show up, set the following config to `0`,
https://github.com/autozimu/LanguageClient-neovim/blob/3e31d01da54aaad3905da813cf7d3564bc8d98d7/doc/LanguageClient.txt#L274-L284
