### ISSUE TITLE
setup example

### ISSUE THREAD

**Issue by zhoupro** [autozimu/LanguageClient-neovim#838]
### purpose

I try your plugin with fail at first try.  I found useful  information from  vim-lsp.  So I try it , and It works perfect. Please add more instruction about how to setup language server and configure.

#### java

* Install Eclipse JDT Language Server

```bash
mkdir -p ~/lsp/eclipse.jdt.ls
cd ~/lsp/eclipse.jdt.ls
curl -L https://download.eclipse.org/jdtls/milestones/0.35.0/jdt-language-server-0.35.0-201903142358.tar.gz -O
tar xf jdt-language-server-0.35.0-201903142358.tar.gz
```
* Create executable jdtls in path (e.g., /usr/local/bin/jdtls), with content

```bash
#!/usr/bin/env sh

server="/root/lsp"

java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -noverify \
    -Xms1G \
    -jar $server/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.*.jar \
    -configuration $server/eclipse.jdt.ls/config_linux/ \
    "$@"
```
* Add to your vim config:

```viml
let g:LanguageClient_serverCommands = {
    \ 'java': ['/usr/local/bin/jdtls', '-data', getcwd()],
    \ }
```
#### php
* install intelephense
```bash
npm -g install intelephense
```
* add to your bashrc
```viml
let g:LanguageClient_serverCommands = {
\ 'php': ['node', '/usr/local/lib/node_modules/intelephense/lib/intelephense.js', '--stdio'],
    \ }
```
### python
* install python language server
```bash
pip install python-language-server
```

* add to your bashrc
```viml
let g:LanguageClient_serverCommands = {
\ 'python': ['pyls'],
    \ }
```
### lua
* install lua language server
```bash
apt install  lua5.3-dev luarocks
luarocks install --server=http://luarocks.org/dev lua-lsp
```
* add to config
```viml
let g:LanguageClient_serverCommands = {
\ 'lua': ['lua-lsp'],
    \ }
```
### fe
* install css js typescript language server
```bash
npm install -g typescript typescript-language-server
npm install -g vscode-css-languageserver-bin
```

* add to config
```viml
let g:LanguageClient_serverCommands = {
\ 'css': ['css-languageserver',  '--stdio'],
\ 'less': ['css-languageserver',  '--stdio'],
\ 'sass': ['css-languageserver',  '--stdio'],
\ 'javascript': ['typescript-language-server',  '--stdio'],
\ 'javascript.jsx': ['typescript-language-server',  '--stdio'],
\ 'typescript': ['typescript-language-server',  '--stdio'],
\ 'typescript.tsx': ['typescript-language-server',  '--stdio'],
\ }
```

**Comment by autozimu** [comment]
Sorry for the confusion.

The concern with proposed approach is that those instructions to install language servers are very hard to be comprehensive and kept up to date. e.g., how to keep the java language server version number up to date, and what if user OS don't apt support.

That's why I prefer the end user would go the language server specific page to following the corresponding install steps, as linked in https://github.com/autozimu/LanguageClient-neovim#language-servers

It's welcome to improve if redirection is not clear enough.
