### ISSUE TITLE
Do not insert parentheses when completing function

### ISSUE THREAD

**Issue by cdelledonne** [autozimu/LanguageClient-neovim#839]
## Is your feature request related to a problem? Please describe.

I'm using LanguageClient as a source for completion items for **deoplete** for C files (using **ccls**). Say that we have this C file:

![Screenshot from 2019-06-14 18-41-49](https://user-images.githubusercontent.com/24732205/59524495-5f9f5800-8ed4-11e9-8d3b-605b15661e33.png)

If I start typing `foo`, the completion menu presents me with the options `foo_noarg`, which is a function that takes no arguments, and `foo_witharg`, a function that takes one argument.

The completion word of `foo_noarg` is `foo_noarg()`, with both parentheses inserted

![Screenshot from 2019-06-14 18-43-38](https://user-images.githubusercontent.com/24732205/59524636-bb69e100-8ed4-11e9-9250-4a195df6167e.png)

The completion word of `foo_witharg` is `foo_witharg(`, with only the left parenthesis inserted

![Screenshot from 2019-06-14 18-42-59](https://user-images.githubusercontent.com/24732205/59524675-cde41a80-8ed4-11e9-8852-72bb2e4e132c.png)

## Describe the solution you'd like

Though I understand the rationale for this design choice, I would like to be given the option of LanguageClient not automatically inserting parentheses.

The first reason is that parentheses are not needed when assigning to a function pointer, e.g.:
```C
typedef void (* fp)();
fp foo = foo_noarg;
```

The second reason is that I use a Vim plugin that, when pressing `)`, brings the cursor to the next closing parenthesis in the buffer, rather than inserting a parenthesis. This requires that all opening parentheses have a matching closing parenthesis, which, in the case of `foo_witharg(`, is not true.

The first reason is more generic, the second more personal, but I think it would be great to at least give the user the option to choose whether to autoinsert parentheses or not.

## Describe alternatives you've considered

Pressing backspace upon completion is what I'm doing, but it's not very neat :).

**Comment by DerWeh** [comment]
A bit off-topic, but may I ask which plugin you use the maps `)`  to going to the next parenthesis?

**Comment by cdelledonne** [comment]
@DerWeh that's [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs) with [Fly Mode](https://github.com/jiangmiao/auto-pairs#fly-mode) enabled.

**Comment by dimbleby** [comment]
What makes you think that this is a client decision?  

I bet the client is just making the completion that the server tells it to make, I don't recall seeing any special code for parentheses.  

If that's right, this feature request would want to go to your language server.

**Comment by cdelledonne** [comment]
@dimbleby actually you're right, I had tried to do some debugging but I was not careful enough. Closing the issue.
