### ISSUE TITLE
How do I disable snippet completion suggestions?

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#841]
## Is your feature request related to a problem? Please describe.
The completion candidate contains a snippet.

## Describe the solution you'd like
Exclude snippets from completions.

**Comment by Shougo** [comment]
https://github.com/autozimu/LanguageClient-neovim/blob/53ce2fee7d24dd9262ea783908e2edebc71635dc/doc/LanguageClient.txt#L274

**Comment by nabezokodaikon** [comment]
I already tried it, but there was no change.

**Comment by Shougo** [comment]
What LSP are you use?
Some LSP may ignore the configuration like old pyls.

**Comment by nabezokodaikon** [comment]
I am using AAA.
[haxe-language-server](https://github.com/vshaxe/haxe-language-server)

**Comment by nabezokodaikon** [comment]
I am using [haxe-language-server](https://github.com/vshaxe/haxe-language-server)

**Comment by Shougo** [comment]
Please upload the minimal vimrc using g:LanguageClient_hasSnippetSupport.
I will test it later.

**Comment by nabezokodaikon** [comment]
### vimrc
```
set hidden	
set completeopt=menu	
set signcolumn=yes	

let g:LanguageClient_useVirtualText = 0	
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_hasSnippetSupport = 0

if &ft=="haxe"
    let g:LanguageClient_settingsPath = '~/dotfiles/.config/nvim/haxelsp/settings.json'
endif

let g:LanguageClient_serverCommands = {	
    \ 'haxe': ['node', '~/dotfiles/.config/nvim/haxelsp/server.js']
    \ }	

let g:LanguageClient_rootMarkers = {
    \ 'haxe': ['build.hxml']
    \ }
```

### settings.json
```
{
  "initializationOptions": {
    "displayServerConfig": {
      "env": {},
      "path": "haxe",
      "arguments": []
    },
    "displayArguments": ["build.hxml"]
  }
}
```

### server.js
See how to build [haxe-language-server](https://github.com/vshaxe/haxe-language-server).
```
$ git clone https://github.com/vshaxe/haxe-language-server.git --recursive
$ cd haxe-languageserver
$ npm install
$ npx lix run vshaxe-build -t language-server 

bin
└── server.js
```

**Comment by Shougo** [comment]
Please wait.
It takes time to test the problem.

**Comment by Shougo** [comment]
@nabezokodaikon And please upload the reproduce instructions with sample project.
I have installed haxe and language server.  But I cannot find the instruction.

The problem must be reproducible by other people.
If not, the issue will be ignored.

Note:  I have read the source code of LanguageClient-neovim and haxe-language-server.
It should work.

**Comment by nabezokodaikon** [comment]
I created a project. please confirm.

[issue-haxe](https://github.com/nabezokodaikon/issue-haxe)

**Comment by nabezokodaikon** [comment]
1. Open the Main.hx file.
1. Type a dot after the msg variable.
1. Make sure that the snippet exists in the displayed completion.

**Comment by nabezokodaikon** [comment]
I confirmed this on a Mac, but it worked fine on Linux (Ubuntu).

**Comment by nabezokodaikon** [comment]
Mac
![image](https://user-images.githubusercontent.com/3197942/60310647-d6395c80-998e-11e9-9a95-c96ab4890d20.png)

**Comment by nabezokodaikon** [comment]
Linux
![001](https://user-images.githubusercontent.com/3197942/60310748-2c0e0480-998f-11e9-8e7e-a77c5f66ac4e.png)

**Comment by Shougo** [comment]
OK.  If so, you can filter snippet kind from candidates by using deoplete filter feature.

**Comment by Shougo** [comment]
`:help deoplete-filter-converter_reorder_attr`

```
		Additionally, you can filter out unwanted candidates by
		prefixing an attribute value with '!'. This character is only
		a flag and will be stripped out before compiling the
		expression.

>
		call deoplete#custom#filter('attrs_order', {
		\ 'ruby': {
		\    		'kind': [
		\			'!Class',
		\			],
		\
		\		'abbr': [
		\			'ExtensionClass'
		\			]
		\ },
		\})
<
```

**Comment by nabezokodaikon** [comment]
I set it as below, but it does not work.
Is something wrong?
```
call deoplete#custom#filter('attrs_order', {
    \ 'haxe': {
    \    'kind': [
    \      '!Snippet'
    \    ]
    \ }
    \})
```

**Comment by Shougo** [comment]
You need to set `converter_reorder_attr` for LanguageClient-neovim source.

**Comment by Shougo** [comment]
The source name is here.
https://github.com/autozimu/LanguageClient-neovim/blob/next/rplugin/python3/deoplete/sources/LanguageClientSource.py#L11

**Comment by nabezokodaikon** [comment]
I'm sorry.
It seems too difficult for me.
Please provide specific examples if possible.

**Comment by Shougo** [comment]
Really?  Oh no.

```vim
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])
```

**Comment by nabezokodaikon** [comment]
Nothing changed. . .
```
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])

call deoplete#custom#filter('attrs_order', {
    \ 'haxe': {
    \    'kind': [
    \      '!Snippet'
    \    ]
    \ }
    \})
```

**Comment by Shougo** [comment]
Please check `converter_reorder_attr` is called.

**Comment by Shougo** [comment]
Oh, the documentation is wrong.

```vim
call deoplete#custom#filter('converter_reorder_attr', 'attrs_order', {
    \ 'haxe': {
    \    'kind': [
    \      '!Snippet'
    \    ]
    \ }
    \})

```

**Comment by nabezokodaikon** [comment]
It seems that converter_reorder_attr is being called.
But it does not work...
```
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])

call deoplete#custom#filter('converter_reorder_attr', 'attrs_order', {
    \ 'haxe': {
    \    'kind': [
    \      '!Snippet'
    \    ]
    \ }
    \})
```

**Comment by nabezokodaikon** [comment]
```
2019-06-30 21:13:31,917 DEBUG    [69500] (deoplete.child) Profile Start: converter_reorder_attr
2019-06-30 21:13:31,917 DEBUG    [69500] (deoplete.child) Profile End  : converter_reorder_attr    time=0.0002190000

2019-06-30 21:18:32,087 DEBUG    [70781] (deoplete.child) Attribute: converters (['converter_reorder_attr'])
2019-06-30 21:18:32,087 DEBUG    [70782] (deoplete.child) Attribute: converters (['converter_remove_paren', 'converter_remove_overlap', 'matcher_length', 'converter_truncate_abbr', 'converter_truncate_info', 'converter_truncate_menu', 'converter_auto_delimiter'])
```

**Comment by Shougo** [comment]
deoplete is open source and you are programmer.
You can find the reason in the source code.

https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/filter/converter_reorder_attr.py#L60

**Comment by Shougo** [comment]
You should check `preferred_order_attrs` value in the code.

**Comment by Shougo** [comment]
Oh, `converter_reorder_attr` implementation is broken.
Please test the latest version of deoplete.

**Comment by nabezokodaikon** [comment]
Finally done!
Thank you very much.
