### ISSUE TITLE
Allow virtual only for certain loglevel (eg errors only)

### ISSUE THREAD

**Issue by BlueDrink9** [autozimu/LanguageClient-neovim#846]
## Problem:

If you are loading an old codebase, codestyles can often differ wildly from best practise, meaning a buffer filled with warning and info messages in the virtualtext. This is very distracting.

## Solution

A better option would be to provide an option to enable the virtualtext for only errors.

##  Alternatives considered

Disabling  virtualtext entirely is a poor option, because for actual errors that need to be fixed, it is still useful to have that salient error text present.

**Comment by BlueDrink9** [comment]
Is `g:LanguageClient_diagnosticsMaxSeverity` meant to apply to virtualtext? I have set it to "warning" but still see virtualtext for 'information'

**Comment by autozimu** [comment]
The fix hasn't been released yet. You have to either build from source yourself or wait for next binary release.

**Comment by BlueDrink9** [comment]
Oh, of course. My mistake, sorry. I hadn't realised it was a binary, I just saw the option in `:h` and assumed it was in
