### ISSUE TITLE
Add function/method + args signature to completion

### ISSUE THREAD

**Issue by daedric** [autozimu/LanguageClient-neovim#847]
## Is your feature request related to a problem? Please describe.
vim-lsp, coc and vscode, upon accepting a completion proposition will also write the signature of the function so that the developer has to fill in the potential parameters.

LanguageClient-neovim only writes the function name without the parens nor any args.

I've the issue on python and C++. I did not test other languages.

## Describe the solution you'd like
I'd like a vim-lsp/vscode style completion so that I don't have to remember the type of the arguments nor do I have to insert the parens myself.

## Describe alternatives you've considered
vim-lsp or coc

## Additional context
I am not sure whether it is a bug or a missing feature.
I use mucomplete and clangd as a language server.

**Comment by daedric** [comment]
Actually, playing around with lsp server, I think the problem might be related to what field LanguageClient-neovim choose to replace the completion.

For instance, I'm giving a go at ccls and this time, it is the complete opposite, it selects the whole signature

![2019-07-10-183952_1495x168_scrot](https://user-images.githubusercontent.com/298311/60987560-22e34700-a342-11e9-9b75-72ce4ee0ec6b.png)


This is an example of what ccls returns:

```
      {
        "label": "ReadImage(const std::string &in_filename, ImageT &image) -> void",
        "kind": 3,
        "detail": "carla::image::ImageIO",
        "sortText": "   !",
        "filterText": "ReadImage",
        "insertTextFormat": 1,
        "textEdit": {
          "range": {
            "start": {
              "line": 57,
              "character": 13
            },
            "end": {
              "line": 57,
              "character": 13
            }
          },
          "newText": "ReadImage("
        }
      },
      {
        "label": "ReadImage(const std::string &in_filename, ImageT &image, IO = IO()) -> void",
        "kind": 3,
        "detail": "carla::image::ImageIO",
        "sortText": "   \"",
        "filterText": "ReadImage",
        "insertTextFormat": 1,
        "textEdit": {
          "range": {
            "start": {
              "line": 57,
              "character": 13
            },
            "end": {
              "line": 57,
              "character": 13
            }
          },
          "newText": "ReadImage("
        }
      },
```

Here with clangd as a server:

![2019-07-10-184147_1160x220_scrot](https://user-images.githubusercontent.com/298311/60987676-6b026980-a342-11e9-85fe-ee5d82a42ff8.png)

And this is what clangd seems to answer.
```  {
        "detail": "void",
        "filterText": "ReadImage",
        "insertText": "ReadImage",
        "insertTextFormat": 1,
        "kind": 2,
        "label": " ReadImage(const std::string &in_filename, ImageT &image)",
        "sortText": "3f651eb8ReadImage",
        "textEdit": {
          "newText": "ReadImage",
          "range": {
            "end": {
              "character": 13,
              "line": 60
            },
            "start": {
              "character": 13,
              "line": 60
            }
          }
        }
      },
      {
        "detail": "std::string",
        "filterText": "WriteView",
        "insertText": "WriteView",
        "insertTextFormat": 1,
        "kind": 2,
        "label": " WriteView(std::string out_filename, const ViewT &image_view)",
        "sortText": "3f651eb8WriteView",
        "textEdit": {
          "newText": "WriteView",
          "range": {
            "end": {
              "character": 13,
              "line": 60
            },
            "start": {
              "character": 13,
              "line": 60
            }
          }
        }
      },
```


So maybe LanguageClient-neovim uses the `label` instead of the `textEdit.newText` when there is no top level `insertText`. I've tried to enable the option to prefer the textEdit without success.

**Comment by dimbleby** [comment]
prefer-text-edit ought to be the right answer here, at least to your update - though it is buggy per #858 etc.

**Comment by martskins** [comment]
I take it this is already fixed? I definitely get proper completions with placeholders with both ncm2 and deoplete, so I asumme this is safe to close. Please re-open if that's not the case.
