### ISSUE TITLE
LocationLink not working

### ISSUE THREAD

**Issue by ngortheone** [autozimu/LanguageClient-neovim#848]
LocationLinks still do not work even after https://github.com/autozimu/LanguageClient-neovim/commit/6ee4c8994ee84609f8370aa4766b66c7cbad1424

- Did you upgrade to latest plugin version? - Yes
- Did you upgrade to/compile latest binary?
```
./languageclient --version
languageclient 0.1.146 f3b2210c19b8ae4186ef66abfd75fd8f0323e955
```

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
```
health#LanguageClient#check
========================================================================
  - OK: binary found: /home/ngor/.nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.146 f3b2210c19b8ae4186ef66abfd75fd8f0323e955
  - OK: Floating window is supported and will be used for hover
```

## Environment
- Minimal vimrc content:
```
let g:LanguageClient_serverCommands = {
   \ 'rust': ['~/.cargo/bin/ra_lsp_server'],
   \ }
```

- Language server link and version:
`rust-analyzer` before https://github.com/rust-analyzer/rust-analyzer/pull/1511
@matklad, `rust-alalyzer` maintainer added support for old style links as a workaround https://github.com/rust-analyzer/rust-analyzer/pull/1511

The issue is discussed here
https://github.com/rust-analyzer/rust-analyzer/issues/1474

## To Reproduce
Open any rust code and try jumping to definition or getting symbol's documentation

## Current behavior
`[LC] Not found!` or just silence

## Expected behavior
Jumping to definition and showing documentation

I am interested in helping, but I need some initial hand-holding/directions to get started. I am struggling to come up with a productive dev-testing setup. Any advice is appreciated.

**Comment by matklad** [comment]
One needs to set a client capability for location links to work, rust-analyzer no longer sends them unconditionally :-)

**Comment by dimbleby** [comment]
Not clear that there'd be very much point in this client advertising support for location links - it treats them only as locations, making no use of the additional information.  And if the client doesn't advertise this support then the server should send locations anyway.

(And indeed that's what rust-analyzer does now, per rust-analyzer/rust-analyzer#1511).

So we should now be at the point where advertising support for location links makes no difference to the user-visible behaviour.

Having said that, it should also be harmless for the client to advertise support for location links.

@ngortheone if you're still interested in doing this then I reckon the change wants to go [here](https://github.com/autozimu/LanguageClient-neovim/blob/0f171f5cef4f611bce3efc217fd83b021adbb3aa/src/language_server_protocol.rs#L912-L939)-ish.
