### ISSUE TITLE
ALE-like underscore/wavy for diagnostics 

### ISSUE THREAD

**Issue by Huxpro** [autozimu/LanguageClient-neovim#852]
## Is your feature request related to a problem? Please describe.

Currently, if [ALE](https://github.com/w0rp/ale) is not running along with this extension. The diagnostics from LSP only display sign in column and virtual texts but ignore the `Range`.

![Screen Shot 2019-07-12 at 1 12 06 PM](https://user-images.githubusercontent.com/5563315/61155834-bd5c9b00-a4a6-11e9-80b1-84ab42331b46.png)

## Describe the solution you'd like

Have native supports on that. 
Btw, it seems like ALE itself is intended to evolve into a full-fledged language clients as well.
Do we want to depend on it?

## Alternative

As `CoC.vim`? [Show diagnostics via ALE](https://github.com/autozimu/LanguageClient-neovim/issues/800).

## Additional context

I am confusing by the fact that [Updates - Diagnostics](https://github.com/autozimu/LanguageClient-neovim/issues/35#issuecomment-288732042) does show the underline. Does it come from ALE or this extension?

**Comment by autozimu** [comment]
There is no intention for this plugin to depend on other plugins regarding LSP as it is positioned to be the lowest level to talk to language servers.

The underline of GIF showing in Updates is indeed displayed by this plugin.

The styles for highlighting ranges of text are defined as https://github.com/autozimu/LanguageClient-neovim/blob/5491a64a07b259568e26981e5ec0d78ba8cec756/doc/LanguageClient.txt#L95-L125. More specifically, it is `texthl`. You might want to make sure your theme display those highlight groups prominently or customize this setting to different highlight groups.
