### ISSUE TITLE
Constant width of error column on the left-hand side

### ISSUE THREAD

**Issue by gruberb** [autozimu/LanguageClient-neovim#853]
## Is your feature request related to a problem? Please describe.
When the LanguageClient is detecting an error, the left-hand bar jumps a few pixels to the right (as also seen in the GIF in the README.md). It is a bit frustrating to have a constant jumping editor when I fix errors and when the pop up. 

## Describe the solution you'd like
I would like to have a fixed width of the vertical-error line (where the "x" for error shows up) so just the "x" appears on the line where the error is, without increasing the width of the column.

Maybe there is a styling or a feature out, however I couldn't find any solution.

**Comment by theHamsta** [comment]
I think that is not an issue specific to this plugin since all kind of plugins can set signs.
Does `set signcolumn=yes` in your .vimrc/init.vim solve your problem?

**Comment by gruberb** [comment]
Sorry, my bad! Yes, this solves my "problem". Thank you!
