### ISSUE TITLE
ccls diagnostics can't disappear in some case

### ISSUE THREAD

**Issue by fcying** [autozimu/LanguageClient-neovim#861]
## Describe the bug
after I fix error, diagnostics can't disappear.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):vim 8.1 1-1750
- This plugin version (`git rev-parse --short HEAD`):e4478a4
- This plugin's binary version (`bin/languageclient --version`):0.1.147
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

`test_vimrc`
```
set nocompatible
set encoding=utf-8
set runtimepath+=~/.vim/plugged/ncm2
set runtimepath+=~/.vim/plugged/vim-hug-neovim-rpc
set runtimepath+=~/.vim/plugged/LanguageClient-neovim
set hidden
set number
set laststatus=2

inoremap {<CR> {}<ESC>i<CR><c-o><s-o> 

let g:LanguageClient_serverCommands = {
      \ 'c': ['ccls'],
      \ 'cpp': ['ccls'],
      \ }
filetype plugin indent on
syntax enable
```
## To Reproduce
1. vim -u ~/test_vimrc main.c
2. insert:   if (rc == ) { , click`<CR>`
3. save file
4. fix error: if (rc == 0), save
5. diagnostics can't disappear

[![asciicast](https://asciinema.org/a/O9Is1CaXHgMiJ46YrZKscVIpQ.svg)](https://asciinema.org/a/O9Is1CaXHgMiJ46YrZKscVIpQ)

## Screenshots
![图片](https://user-images.githubusercontent.com/106934/62435679-a3de0480-b76f-11e9-8aab-7b177f8f1f0a.png)
![图片](https://user-images.githubusercontent.com/106934/62435691-ad676c80-b76f-11e9-824e-34e7b6b8a715.png)

**Comment by autozimu** [comment]
Is this still reproducible?

I'm not able to reproduce it locally with
- neovim: 0.3.8
- ccls: stable 0.20190314.1

**Comment by autozimu** [comment]
No longer reproducible and no response during 7 days.

**Comment by fcying** [comment]
@autozimu  reproducible with vim 8.1 Included patches: 1-1950. 
Tested 5 times reproduce once
```
$ccls --version
ccls version <unknown> (install from brew)
clang version 8.0.0 (tags/RELEASE_800/final)

LanguageClient-neovim ‹next›$git rev-parse --short HEAD
baea090

LanguageClient-neovim ‹next›$bin/languageclient --version
languageclient 0.1.147
```
