### ISSUE TITLE
Hover floating window auto-close breaks visual selection

### ISSUE THREAD

**Issue by YaLTeR** [autozimu/LanguageClient-neovim#864]
## Describe the bug
Starting a visual selection while the floating window hover is active and then moving the cursor stops the visual selection. This is especially annoying when using any kind of automatic hover—in this case you must actively attempt to start the selection with the floating window closed.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`): `NVIM v0.4.0-1587-g1d6e36815`
- This plugin version (`git rev-parse --short HEAD`): 2c9c091
- This plugin's binary version (`bin/languageclient --version`): `languageclient 0.1.147`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]): `min-vimrc.vim`
- Language server link and version: RLS or `rust-analyzer` or whatever

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. `cargo new test-project`
1. `nvim -u min-vimrc.vim test-project/src/main.rs`
1. Add `/// a` above `fn main()` so that it gives more than one line of hover.
1. `:call LanguageClient_textDocument_hover()` while on `main`.
1. <kbd>v</kbd> or <kbd>V</kbd> or <kbd>Ctrl</kbd>+<kbd>v</kbd> to start the visual selection and try to move the cursor.
1. Observe how the hover window disappeared and the visual selection was cleared.

## Current behavior
The visual selection is cleared.

## Expected behavior
The visual selection is not cleared.

**Comment by autozimu** [comment]
Shall fixed by #866

**Comment by YaLTeR** [comment]
Huh? That's related?

**Comment by autozimu** [comment]
Oops, #865
