### ISSUE TITLE
question: no abbreviation of preview

### ISSUE THREAD

**Issue by DerWeh** [autozimu/LanguageClient-neovim#866]
If I complete a function with, it's documentation is automatically shown in the preview window. In contrast to using `hover`, however, the documentation is abbreviated. This constantly forces me to manually use `hover`.
I didn't find any documentation on this, can someone tell me how to change this behavior and show everything?

See screenshot: 
![languageclient_preview](https://user-images.githubusercontent.com/22542812/62943634-3a976a80-bddb-11e9-86e6-d5d03a64fa4b.jpg)

**Comment by autozimu** [comment]
It looks like the truncating behavior is coming from deoplete, https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L1096

You can use following config to disable the truncating,
```
call deoplete#custom#source('LanguageClient', 'max_info_width', 0)
```
