### ISSUE TITLE
Support for a customizable virtual text prefix string

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#871]
## Is your feature request related to a problem? Please describe.
While working on files having multiple errors, warnings and hints (etc.) with virtual text enabled, it can sometimes get difficult to read and focus on the code. Striking the balance between applying a subtle highlight to virtual text and still keeping it visible enough to be really useful can be challenging.

## Describe the solution you'd like
I propose that an option for a customizable virtual text prefix should be added to the plugin.

## Describe alternatives you've considered
Customizing the highlighting for the virtual text can make the readability better, adding white space between normal text and virtual text further improves it, especially if you have weak eyesight.

## Additional context
Blow are some examples of what it can look like:

Image with no virtual text prefix:
![no-prefix](https://user-images.githubusercontent.com/36127183/63550580-68ec1700-c54c-11e9-91bb-e76301ba1d97.png)

Image with virtual text prefix set to `'    •••➜ '`
![prefix](https://user-images.githubusercontent.com/36127183/63550630-77d2c980-c54c-11e9-91d8-ba28c1ddb046.png)
Adding symbols to the prefix with or without white space makes it very clear where the text ends and the virtual text begins.

There is pull request accompanying this issue which implements the proposed solution.
Thank you.

**Comment by autozimu** [comment]
Already addressed in #872
