### ISSUE TITLE
Add support for calling LSP completionItem/resolve implementation when completion items are selected

### ISSUE THREAD

**Issue by wincent** [autozimu/LanguageClient-neovim#875]
(I originally posted this over in [the deoplete repo](https://github.com/Shougo/deoplete.nvim) ([\#1004](https://github.com/Shougo/deoplete.nvim/issues/1004)) because I thought that might be the right place for it, but @Shougo seems to think this is best handled inside LanguageClient-neovim, so I'm creating this ticket to see if that's correct.)

> Looking at the LSP spec, I see [this](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) (emphasis added):
>
>>  If computing full completion items is expensive, servers can additionally provide a handler for the completion item resolve request (‘completionItem/resolve’). This request is sent when a completion item is selected in the user interface. **A typical use case is for example: the ‘textDocument/completion’ request doesn’t fill in the documentation property** for returned completion items since it is expensive to compute. **When the item is selected in the user interface then a ‘completionItem/resolve’ request is sent** with the selected completion item as a parameter. The returned completion item should have the documentation property filled in.
>
> To this effect, LanguageClient-neovim [implemented](https://github.com/autozimu/LanguageClient-neovim/pull/514) a `LanguageClient#completionItem_resolve()` function that can be called to get additional information about a completion. The obvious use-case here is to show info about the selection completing in a preview window (or floating window).
>
> As far as I can tell, LanguageClient-neovim sets its `LanguageClient#complete()` function as the `'omnifunc'`, and deoplete calls that to get completions. But when you move through completions, deoplete doesn't call `LanguageClient#completionItem_resolve()` and so doesn't get the extra info that an LSP server might provide. One such example server would be [typescript-language-server](https://github.com/theia-ide/typescript-language-server), which doesn't provide extended information for `textDocument/completion` requests, but does implement `completionItem/resolve`.
>
> So this is really a feature request. Could we have an option to make deoplete call an LSP `completionItem/resolve` function when completion items are selected? This means that `'completopt=preview'` would be more useful, because it would have information to show about selected completions in more cases. coc.nvim [implements this](https://github.com/neoclide/coc.nvim/blob/3e0eec9c4f08003304ba4d50bb0866dbaf7cc707/src/provider/index.ts#L40-L52), in case you wanted to check out what they're doing.

Looking into `:h CompleteChanged`, I see that support for it was added to Neovim [here](https://github.com/neovim/neovim/pull/9616) by @chemzqm (the [Coc](https://github.com/neoclide/coc.nvim/issues/441) maintainer).

It's still not clear to me exactly where the responsibility for this functionality should lie (that's why I opened the issue in deoplete; but it may be here), but the end goal is to have something like what you can see in the GIF in the Coc README:

https://user-images.githubusercontent.com/251450/55285193-400a9000-53b9-11e9-8cff-ffe4983c5947.gif

You can see how the completion menu appears, and then, asynchronously, a floating preview appears to the side with additional information about the selected completion:

<img width="1262" alt="Screen_Shot_2019-08-24_at_21_10_47_png" src="https://user-images.githubusercontent.com/7074/63641761-06158f80-c6b4-11e9-9bf4-2236179a7c6c.png">

Thoughts?

**Comment by hasufell** [comment]
Has anyone started working on this already?

**Comment by take** [comment]
@wincent just out of curiosity but did https://github.com/wincent/wincent/commit/8888453d9b96ca36fd441936c9209b546690184b work? :eyes:

**Comment by wincent** [comment]
Yeah it works fine, although I haven't found a way to get it to show previews like this yet.

**Comment by take** [comment]
@wincent nice! how is the previews shown? 🤔 in the preview window? :eyes:

**Comment by wincent** [comment]
@take I made [a short screencast on it](https://youtu.be/3jl8a5Wo2l0) a few weeks ago. Since then I tweaked a few things (mostly color related) to make it look nicer, but you can get a sense of the basics behavior from that.

**Comment by martskins** [comment]
Opened #1043 to try and kicks things off here. Appreciate the extra eyes if someone can take a look and try it out.

**Comment by martskins** [comment]
Just updated that PR to properly work in neovim 0.4.X+ and vim8. I'll give it a ride for a few days and merge if all is working correctly.

**Comment by martskins** [comment]
Closing via #1043
