### ISSUE TITLE
[LC] LanguageClient exited with: 143

### ISSUE THREAD

**Issue by c02y** [autozimu/LanguageClient-neovim#877]
- Did you upgrade to latest plugin version?
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
- Did you check [troubleshooting]?

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

Everytime I open nvim (nightly version), even without open any file, after exiting, there will one line after the prompt:
~~~
[LC] LanguageClient exited with: 143
~~~

I've used several different nightly versions(NOTE: I use https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage), all of them have this bug.

Currently the latest version if `NVIM v0.4.0-1958-gd7aea13f`

But there is a version I used a month ago(`NVIM v0.4.0-1504-g87140f234`), it is fine.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
~~~
NVIM v0.4.0-1504-g87140f234
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-4fc584c6-5eea-41b5-9767-c743ed0b6d08

Features: +acl+iconv +tui   
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
~~~
- This plugin version (`git rev-parse --short HEAD`):
~~~
baea090
~~~
- This plugin's binary version (`bin/languageclient --version`):
~~~
languageclient 0.1.147
~~~
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):

Normally I'm using [space-vim](https://github.com/liuchengxu/space-vim) + lsp layer, It has the `[LC] LanguageClient exited with: 143` bug

Then I tried to use [min-vimrc.vim](https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim) as `~/.config/nvim/init.vim`, it has this bug too.

So I'm guessing it is the bug of [LC] LanguageClient exited with: 143 or the new version of neovim.

- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Download the latest neovim binary from https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage, rename it as `nvim` 
2. download [min-vimrc.vim](https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim), rename it as `~/.config/nvim/init.vim`
3. open ./nvim
4. `:q` to exit nvim
5. there is one error line `[LC] LanguageClient exited with: 143` after the command line prompt

## Current behavior
A clear and concise description of what's the current behavior.

Like I said:

Everytime I open nvim (nightly version), even without open any file, after exiting, there will one line after the prompt:
~~~
[LC] LanguageClient exited with: 143
~~~

## Expected behavior

No `[LC] LanguageClient exited with: 143` after the command line prompt.

**Comment by autozimu** [comment]
Thanks for reporting!
