### ISSUE TITLE
Support skim as an alternative to fzf

### ISSUE THREAD

**Issue by pickfire** [autozimu/LanguageClient-neovim#879]
## Is your feature request related to a problem? Please describe.
[Skim](https://github.com/lotabout/skim) is a fuzzy finder similar to fzf. It can be integrated to Vim using the [Skim.vim](https://github.com/lotabout/skim.vim) plugin. It would be nice to make Vista.vim compliant with skim to not have to install fzf in addition.
By the way, skim is also written in rust, related PR solved in https://github.com/liuchengxu/vista.vim/issues/129

## Describe the solution you'd like
skim is an alternative to FZF, and skim.vim and fzf.vim does not differs much from the look.

## Describe alternatives you've considered
skim.vim is the alternative to fzf.vim

**Comment by ghost** [comment]
I created a shim function [1] to call skim instead of fzf in vim. It should 'just work'. The PR hasent been merged thou.
[1]: https://github.com/lotabout/skim.vim/pull/7

**Comment by pickfire** [comment]
Looks interesting how short that patch is, I don't get how it works though. I know `skim` does provide both `fzf#wrap()` and `fzf#run()`.

**Comment by ghost** [comment]
>  I know `skim` does provide both `fzf#wrap()` and `fzf#run()`.

No, it doesnt. Thats what the patch adds, and it just reuses the arguments with `skim#run/wrap`

edit: obviously it wouldnt work well if fzf-vim is also present.

**Comment by martskins** [comment]
@pickfire now that #1059 has been merged to dev, I think you should be able to configure `skim` as your selection UI. Let me know if that fixes this for you.

**Comment by pickfire** [comment]
> @pickfire now that #1059 has been merged to dev, I think you should be able to configure skim as your selection UI. Let me know if that fixes this for you.

Looks like I was already using skim before that since fzf stuff are already present even though I didn't install it, most likely because skim is a drop-in replace for fzf, it didn't even change the naming and the plugin still call it fzf.
