### ISSUE TITLE
Can't use LanguageClient#explainErrorAtPoint() in CursorHold autocmd

### ISSUE THREAD

**Issue by foonathan** [autozimu/LanguageClient-neovim#884]
## Is your feature request related to a problem? Please describe.

I have the following autocmd:

```
au CursorHold * sil call LanguageClient#explainErrorAtPoint()
```

It works greater and displays the diagnostic in a floating window with the newest neovim. However, when I'm on a line without error, it outputs the error message "No diagnostic found: ...". This is annoying.

## Describe the solution you'd like

I'd like that calling `explainErrorAtPoint()` on a line without error does nothing.

## Describe alternatives you've considered

I've tried rasing the log level, but this doesn't seem to work.

**Comment by wincent** [comment]
Probably related: https://github.com/autozimu/LanguageClient-neovim/issues/792

**Comment by martskins** [comment]
@foonathan Sorry for the massive delay, but I've finally found a nice enough way to solve this. If you want to give it a try you can check #1143 and build from source. I'll be testing it out in these next few days and merging some time next week.

**Comment by foonathan** [comment]
I've since switched to nvim's built in LSP... :D

**Comment by martskins** [comment]
Fair enough! I'll close this one as I've merged the linked PR now. 😁
