### ISSUE TITLE
How do I fzf project wide Symbols? What about limiting it to Classes?

### ISSUE THREAD

**Issue by Plotnus** [autozimu/LanguageClient-neovim#890]
First off thanks for LanguageClient-neovim!

This isn't a bug, but a help request.

I'm working with a large C++ project and would like to FZF through the project's classes or structs.

I expected `LanguageClient_workspace_symbols` to be the fn I needed for the magic to happen but I run into a few snafu.

1) fzf has 0 symbols when I run this in a cpp.
2) I don't understand what a "query" is and how I would go about limiting the search?

I have read a but about LSP that there is a thing called `SymbolKind`.
What I'd like to accomplish is being able to do an FZF of lets say all the Classes?

Can you point me toward some resources to better understand the what's happening and how to get something like ProjectsClassSymbols->Fzf->gotoSelectedSymbol?

**Comment by TamaMcGlinn** [comment]
Perhaps by now you can provide the information? Or did you find this somewhere in the documentation?
