### ISSUE TITLE
Language Server does not start when using fzf to open first file

### ISSUE THREAD

**Issue by Plotnus** [autozimu/LanguageClient-neovim#891]
- Did you upgrade to latest plugin version?
Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
0.1.154
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
Yes, all green
- Did you check [troubleshooting]?
I had to add `Plug 'junegunn/fzf.vim'` to test the behaviour.

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
If I open the file with fzf.vim the language server is not started.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
NVIM v0.4.2
- This plugin version (`git rev-parse --short HEAD`):
4fd272b
- This plugin's binary version (`bin/languageclient --version`):
languageclient 0.1.154 4fd272b0dbf96d7a4fd5d9d840780638f514aa7c
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
Add `'Plug junegunn/fzf.vim` to the min-vimrc.vim.
- Language server link and version:
rls 1.37.0

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
0. `cd into the LanguageClient-neovim home directory
1. Add `Plug 'junegunn/fzf.vim'` to line 2 in `LanguageClient-neovim/min-vimrc.vim`
2. `cd ./tests/data/sample-rs/`
3. `nvim` - here we just open nvim at the root directory
4. Use an fzf.vim command to open `sample-rs/src/main.rs. I used `:GFiles`
5. Type `:call LanguageClient_workspace_symbol()`

## Current behavior
You will get an error "[LC] Language server is not running for rust."

## Expected behavior
I expected the Language Server to be running.
I expect this because the language server starts if I had used an ex command to edit, `:e ./src/main.rs`. 

## Screenshots
Not applicable

## Additional context
I looked at fzf.vim a bit and if I'm not mistaken it defaults to using `e` on enter when you select a file. I believe it is sending an edit command. Unfortunately I don't know enough about fzf, or LanguageClient-neovim to understand why a server is not starting.

edit: added versions

**Comment by PhilT** [comment]
I'm not seeing this issue on Windows but I'm on Neovim 0.4.3. Might be worth updating Neovim, FZF and LanguageClient and checking again.

**Comment by martskins** [comment]
This seems stale and I also wasn't able to reproduce (that's actually how I use nvim usually), so I'm gonna close this, but feel free to re-open if it's still an issue for you.
