### ISSUE TITLE
Run language server command from project directory

### ISSUE THREAD

**Issue by Samsinite** [autozimu/LanguageClient-neovim#894]
## Is your feature request related to a problem? Please describe.
I'd like to be able to run the solorgraph command using bundler from my project directory, as recommended by their [documentation](https://github.com/castwide/solargraph#solargraph-and-bundler).
## Describe the solution you'd like
When I open a project in vim (I currently run `vim .` from the root directory of the project), I would like the language client to be able to launch the appropriate language server from that project's directory using a command like `bundle exec solargraph stdio`.

## Describe alternatives you've considered
I'm not sure of the best way to implement this, so I've tried to just explain what I'd like the feature to be able to do. If there is a better alternative, or this is already supported, I apologize.

Thanks for the great plugin, I use it every day!

**Comment by runiq** [comment]
Isn't that the default behavior with`let g:LanguageClient_serverCommands = { 'ruby': ['bundle', 'exec', 'solargraph', 'stdio'] }`?

**Comment by martskins** [comment]
@Samsinite I'm not sure I understood the issue but.. does the above comment solve it for you?

**Comment by martskins** [comment]
Closing this as it seems to be stale
