### ISSUE TITLE
is it possible to search a definition not under cursor?

### ISSUE THREAD

**Issue by quink-black** [autozimu/LanguageClient-neovim#897]
Just like `:tselect`

**Comment by TamaMcGlinn** [comment]
there is LanguageClient#textDocument_documentSymbol(), but it only works within the file. E.g. mapping:

```
nnoremap <silent> gs :call LanguageClient#textDocument_documentSymbol()<CR>
```

There is also `LanguageClient#workspace_symbol()` but that ~~seems to be not implemented~~ happens to not work with my current languageserver.

**Comment by PhilT** [comment]
Depends on your language I think. For example when using F# `LanguageClient#workspace_symbol()` does work at least if you FZF installed. If you're not using FZF you may need to configure one of the other options.

**Comment by martskins** [comment]
Closing this as it's stale and unclear. If you feel like you still need this please elaborate a little more on what exactly is that you're looking for.
