### ISSUE TITLE
Disable auto compile

### ISSUE THREAD

**Issue by UlisseMini** [autozimu/LanguageClient-neovim#898]
## Is your feature request related to a problem? Please describe.
My computer is a bit old, and it can't handle auto compiling rust code

## Describe the solution you'd like
A way to disable auto compilation with `rls` (and hopefully other lang-servers)
## Describe alternatives you've considered
Not using language-client for rust

**Comment by autozimu** [comment]
Use
```vim
let g:LanguageClient_autoStart = 0
```

See doc https://github.com/autozimu/LanguageClient-neovim/blob/b4de07929d6c03b49595902d44e9f8b29e0882b2/doc/LanguageClient.txt#L147-L152
