### ISSUE TITLE
[rust] Check examples and tests

### ISSUE THREAD

**Issue by Ploppz** [autozimu/LanguageClient-neovim#902]
One can see errors and warnings from tests and examples with: `cargo check --tests --examples`.
When I `:w` a .rs file, it never shows errors in examples.
Maybe there is a way to enable this that I have not yet found?

**Comment by autozimu** [comment]
Not sure if rls `cfg_test` option would do that, https://github.com/rust-lang/rls/blame/master/README.md#L145

You can try the option following example of https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/data/sample-rs/.vim/settings.json

If it didn't work out, please file issue at rls repo.

**Comment by Ploppz** [comment]
Thanks
