### ISSUE TITLE
[go] function params is omit

### ISSUE THREAD

**Issue by JoveYu** [autozimu/LanguageClient-neovim#910]
when I use `gopls` ,the params of function in completion is omit with `...`, if it is too long
how to show all of the params?

![image](https://user-images.githubusercontent.com/1973603/67930964-e17dec80-fbfb-11e9-9d3a-11d7208b9eb5.png)

and my `echodoc` get wrong result 
![image](https://user-images.githubusercontent.com/1973603/67931034-083c2300-fbfc-11e9-95aa-7de385656791.png)

**Comment by JoveYu** [comment]
i found it is limited by `deoplete` 
```vim
call deoplete#custom#source('LanguageClient', 'max_menu_width', 150)
```

**Comment by autozimu** [comment]
Seems like you addressed it by yourself.
