### ISSUE TITLE
LanguageClient#textDocument_rename isn't working correctly

### ISSUE THREAD

**Issue by timfeirg** [autozimu/LanguageClient-neovim#912]
- Did you upgrade to latest plugin version? 
Using https://github.com/autozimu/LanguageClient-neovim/commit/53f59715a5ce2c6d600b3c258bd23cbf9fc023b2
- Did you upgrade to/compile latest binary? Run shell command
```
 bin/languageclient --version
languageclient 0.1.155 1ffab7ef19e2acae6f32c6f3a27581429d28e47b
```

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yes, all green.
- Did you check [troubleshooting]? I did.

## Describe the bug

Upon execution, `LanguageClient#textDocument_rename` will replace the current buffer content with another file.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
```
NVIM v0.5.0-nightly-1368-g568900806
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191110-4894-p24zs4/build/config -I/tmp/neovim-20191110-4894-p24zs4/src -I/usr/local/include -I/tmp/neovim-20191110-4894-p24zs4/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191110-4894-p24zs4/build/src/nvim/auto -I/tmp/neovim-20191110-4894-p24zs4/build/include
Compiled by timfeirg@timfeirg-mba-7.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-5689008/share/nvim"
```
- This plugin version (`git rev-parse --short HEAD`): https://github.com/autozimu/LanguageClient-neovim/commit/53f59715a5ce2c6d600b3c258bd23cbf9fc023b2
- This plugin's binary version (`bin/languageclient --version`):  `languageclient 0.1.155 1ffab7ef19e2acae6f32c6f3a27581429d28e47b`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
            \ 'branch': 'next',
            \ 'do': 'bash install.sh',
            \ }

call plug#end()
let g:LanguageClient_loadSettings = 1
let g:LanguageClient_serverCommands = {
            \ 'python': ['pyls'],
            \ }
let g:LanguageClient_diagnosticsList = "Disabled"
nnoremap <silent> <C-c>rr :call LanguageClient#textDocument_rename()<CR>
```
- Language server link and version: https://github.com/palantir/python-language-server/releases/tag/0.30.0

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce

```
# create these two python files
$ cat a.py
from b import func_b

func_b
$ cat b.py
def func_b():
    pass
$ nvim b.py
# Using LanguageClient#textDocument_rename on func_b
# the buffer content of b.py will be replaced by a.py, but with func_b renamed
```

## Current behavior

The buffer content of `b.py` will be replaced by `a.py`. but with `func_b` renamed.

...This is really tricky to describe, better just view the asciinema below.

## Expected behavior

current buffer content should be the same as before, except with `func_b` renamed, also, the renaming should happen in the same fashion with a.py

## Screenshots

The following screen is made by asciinema, and will be removed in 7 days, if that happens I can upload it again.

https://asciinema.org/a/6egAGD7boxwvaimx2N8JfRbNm

## Additional context

Not sure yet if this is a languageclient-neovim problem or pyls', I'll move this issue if it's the latter.

**Comment by martskins** [comment]
Are you still seeing this issue? If so, could you provide another asciinema, as it's not clear to me what the issue is.

**Comment by timfeirg** [comment]
I've switched to nvim-lsp, hence unable to follow up with this issue
