### ISSUE TITLE
TexLab configuration

### ISSUE THREAD

**Issue by kwon-young** [autozimu/LanguageClient-neovim#923]
## Is your feature request related to a problem? Please describe.

In order to [configure the texlab language server](https://texlab.netlify.com/docs/reference/configuration):

* texlab only use the `workspace/configuration` request to fetch the configuration from the client.
* LanguageClient-Neovim only use the `workspace/didChangeConfiguration` request to push the configuration to the server.

## Describe the solution you'd like

It would be nice if LanguageClient-neovim could support the  `workspace/configuration` request so that all features of texlab can be used together with LanguageClient-Neovim!

## Additional context

Here is the mirrored feature request made on the TexLab repo: https://github.com/latex-lsp/texlab/issues/123

**Comment by martskins** [comment]
Closing via #1090
