### ISSUE TITLE
The display of complement candidates is strange on scala

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#939]
- Did you upgrade to latest plugin version?
>Yes

- Did you upgrade to/compile latest binary? Run shell command
>Yes

  `bin/languageclient --version` to get its version number.
>`languageclient 0.1.155 1ffab7ef19e2acae6f32c6f3a27581429d28e47b`

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
>OK

## Describe the bug
The display of complement candidates is strange on scala.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
>`0.4.3`

- This plugin version (`git rev-parse --short HEAD`):
>`0394fbaa2def5a5e304f7f4c08def4de4cb9e689`

- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
```
set hidden	
set completeopt=menu	
set signcolumn=yes	

let g:LanguageClient_useVirtualText = 0	
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1

let g:LanguageClient_serverCommands = {	
    \ 'scala': ['metals-vim']
    \ }	
```

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

##### 1. Install Metals
```
// ~/.sbt/1.0/plugins/plugins.sbt
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.3.4")
```
##### 2. Create Scala project
```
$ sbt new nabezokodaikon/scala-basic.g8
```
##### 3. Run sbt
```
$ cd my-something-project
$ sbt
```
##### 7. Edit Main.scala

<img width="797" alt="スクリーンショット 2020-01-02 2 08 10" src="https://user-images.githubusercontent.com/3197942/71644072-11ce2e00-2d06-11ea-8a6e-18fd291987a5.png">

For example, the character `scala` after` Int` is entered by completion. Therefore, it will not be code that can be compiled.

**Comment by tssm** [comment]
I'm seeing the same issue with the latest version of Metals. People using it in conjunction with Emacs don't have the problem.

**Comment by nabezokodaikon** [comment]
So that's it. It may be a problem of metals. However, VSCODE did not have this problem.

**Comment by tssm** [comment]
I wonder the same thing. Maybe Visual Studio Code and Emacs handle Metals as a special case. I saw that [you also found the issue with the new Neovim native client](https://github.com/neovim/nvim-lsp/pull/75#issuecomment-575875068). @autozimu what can we do to help debugging this?

**Comment by tssm** [comment]
[This seems relevant](https://twitter.com/mattn_jp/status/1221067443839258626?s=21)

**Comment by tssm** [comment]
@nabezokodaikon FYI I updated Metals to 0.8.1 and LanguageClient to the `next` branch's head and I don't see the issue anymore

**Comment by martskins** [comment]
@nabezokodaikon I'm gonna close this issue on the assumption that updating metals and LanguageClient worked for you too, as it did for @tssm, but feel free to re-open if that's not the case.
