### ISSUE TITLE
Multiline virtual text diagnostics

### ISSUE THREAD

**Issue by googleson78** [autozimu/LanguageClient-neovim#942]
## Is your feature request related to a problem? Please describe.
Some servers would greatly benefit from having diagnostics on multiple lines.

An example of this is [ghcide](https://github.com/digital-asset/ghcide). If I have a type error that is slightly longer it easily doesn't fit without putting it on multiple lines.

## Describe the solution you'd like
I imagine this happening via virtual text, but seeing as how it's usually attached to one line, I'm not sure how hard this would be to implement?

This is what I'm imagining(dreaming of): https://twitter.com/tritlo/status/1206604868733014022

Ideally also some way for diagnostics to remain hidden until you hover the item that they are "attached" to.

## Describe alternatives you've considered
Using pop up windows to instead have the same functionality is another idea.

However I particularly don't like pop up windows, because they obscure code around where I am currently at, and usually it is just as important as what is in the pop up window.

##
Thanks for the client! It seems to be working great so far <3

**Comment by martskins** [comment]
Unfortunately I don't think this is possible with virtual text. There's a middle-ground solution for your request though which is use `explanErrorAtPoint`. If you call `LanguageClient#explainErrorAtPoint` while standing on the region (line [+ character range]) you get a floating window with the explained error.

You probably want to map that to something easy to use, like `E`. If you want to do that you add this to your config:

`nmap <silent>E            <Plug>(lcn-explain-error)`

Hopefully that's close enough to what you wanted.

I will close this one as there is no way for us to display multiline virtual texts as of today, and the solution above I think fits your needs pretty closely. Do re-open if you feel that's not what you wanted or think it can be done better.
