### ISSUE TITLE
invalid type: integer `0`, expected string or map

### ISSUE THREAD

**Issue by nabezokodaikon** [autozimu/LanguageClient-neovim#947]
- Did you upgrade to latest plugin version?
Yes

- Did you upgrade to/compile latest binary? Run shell command
Yes

  `bin/languageclient --version` to get its version number.
languageclient 0.1.156 90e49e587fc700c81cd21529e773b7f863dfc958

- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
OK

- Did you check [troubleshooting]?
Yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
After updating to the latest version in dein.vim, the title error occurred.

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
  - `NVIM v0.4.3`
- This plugin version (`git rev-parse --short HEAD`):
  - `90e49e5`
- This plugin's binary version (`bin/languageclient --version`):
  - languageclient 0.1.156 90e49e587fc700c81cd21529e773b7f863dfc958
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
```
set hidden	
set completeopt=menu	
set signcolumn=yes	

let g:LanguageClient_useVirtualText = 0	
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1

let g:LanguageClient_serverCommands = {	
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],	
    \ }	

let $RUST_BACKTRACE = 1
let g:LanguageClient_loggingLevel = 'INFO'
let g:LanguageClient_virtualTextPrefix = ''
let g:LanguageClient_loggingFile =  expand('~/.local/share/nvim/LanguageClient.log')
let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
```
- Language server link and version:

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. `$ git clone -b getting-started https://github.com/nabezokodaikon/rust-study.git`
1. `$ cd rust-study/ch03/bitonic-sorter`
1. `$ nvim src/first.rs`
1. See error
1. `23:50:15 WARN unnamed src/language_server_protocol.rs:2389 Failed to start language server automatically. invalid type: integer `0`, expected string or map
`

## Current behavior
LanguageClient does not start.

## Expected behavior
LanguageClient starts.

## Additional context
It worked with tag `v0.1.153`.

**Comment by zekzekus** [comment]
I was just about to click new issue button :) Same problem here. I rolled back one commit back (d273439c1c05a599423c278fcad95df6564d7b8a) language server starts without any problem.

**Comment by martskins** [comment]
There was a breaking change regarding the `LanguageClient_useVirtualText` option, it now takes a string instead of a number. See https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L343 for the accepted values.

**Comment by nabezokodaikon** [comment]
> There was a breaking change regarding the `LanguageClient_useVirtualText` option, it now takes a string instead of a number. See https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L343 for the accepted values.

Thank you! Confirmed to work!

**Comment by ReggieMarr** [comment]
> There was a breaking change regarding the `LanguageClient_useVirtualText` option, it now takes a string instead of a number. See https://github.com/autozimu/LanguageClient-neovim/blob/next/doc/LanguageClient.txt#L343 for the accepted values.

This also broke for me. If we broke backwards compatibility shouldn't there be more transparency (in the changelog or error code)?
