### ISSUE TITLE
[Question/probably not a bug] Abbreviated function signatures

### ISSUE THREAD

**Issue by donotnoot** [autozimu/LanguageClient-neovim#957]
- Did you upgrade to latest plugin version? yes
- Did you upgrade to/compile latest binary? 0.1.156
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? yes
- Did you check [troubleshooting]? yes

## Describe the bug
When trying to get the function signature of the function that I'm currently typing, I expect to see the full function signature, instead I see just an abbreviated version of it.

I've had a look at the relevant `:h`'s for LC, deoplete and echodoc and could not find any settings related to this, is there any way to see the entire signature?

See screenshot:

![Screenshot from 2020-01-20 10-05-47](https://user-images.githubusercontent.com/6237457/72717917-d7b9b480-3b6c-11ea-896d-a7bfa8256ed1.png)

**Comment by PetarMetodiev** [comment]
I had the same problem and the only solution I found was to set `max_abbr_width` and `max_menu_width` to `0`:
```vim
call deoplete#custom#source('LanguageClient', {
			\ 'max_abbr_width': 0,
			\ 'max_menu_width': 0
			\ })

```
With these set, the limit is the screen width.

**Comment by martskins** [comment]
@donotnoot I'm gonna assume the proposed solution here worked and close this, but feel free to reopen if that isn't the case.
About the solution, I'm hesitant to add this config to our registering logic, as it sounds better to keep deoplete's defaults, but if more people complain about this then it might be worth considering.
