### ISSUE TITLE
Either select "rename to" value by default or add option to do so

### ISSUE THREAD

**Issue by mqudsi** [autozimu/LanguageClient-neovim#96]
I'm loving the refactoring options that LanguageClient provides, but a constant "inefficiency" for me is to have to delete the existing value of the `rename to` prompt. Would it be possible to have the rename prompt's initial value selected by default so that typing overrides its value?

**Comment by autozimu** [comment]
<https://stackoverflow.com/questions/2075569/how-can-i-move-around-in-the-vim-command-line>
