### ISSUE TITLE
vim 8.2 nvim_create_namespace

### ISSUE THREAD

**Issue by gnattishness** [autozimu/LanguageClient-neovim#967]
- Did you upgrade to latest plugin version?
  - Yes
- Did you upgrade to/compile latest binary? Run shell command
  `bin/languageclient --version` to get its version number.
  - `languageclient 0.1.156`
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`?
  - I use vim
- Did you check [troubleshooting]?
  - Yes, replicable in minimal environment

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug

In vim 8.2, after recent LanguageClient-neovim update, on cursor movement within a lsp-relevant file, the following error is emitted `[LC] 'Vim(let):E117: Unknown function: nvim_create_namespace'`

## Environment
- neovim/vim version (`nvim --version` or `vim --version`):
  - `vim 8.2` see [vim_version.txt](https://github.com/autozimu/LanguageClient-neovim/files/4133335/vim_version.txt) for full output

- This plugin version (`git rev-parse --short HEAD`):
  - `51fa22f`
- This plugin's binary version (`bin/languageclient --version`):
  - `languageclient 0.1.156`
- Minimal vimrc content (A minimal vimrc is the smallest vimrc that could
  reproduce the issue. Refer to an example [here][min-vimrc.vim]):
  - As in the minimal example, but I have my `vim-plug` in `~/.vim/plugged` and need to ensure the log directory exists before use
- Language server link and version:
  - `rls 1.38.0 (7b0a20b 2019-08-11)`

[min-vimrc.vim]: https://github.com/autozimu/LanguageClient-neovim/blob/next/min-vimrc.vim

## To Reproduce
1. Create/Fetch example project ...
1. Start vim with minimal vimrc
1. Open `tests/data/sample-rs/src/main.rs`
1 Move cursor
1. See error

## Current behavior
A clear and concise description of what's the current behavior.

Error appears on every cursor movement, and other lsp functionality doesn't work?

## Expected behavior

Error isn't logged and I can use lsp.

## Additional context

See error log:
[lsp_error.txt](https://github.com/autozimu/LanguageClient-neovim/files/4133285/lsp_error.txt)

I think this may have been introduced by 1c7a3b0d629f213457cd8f19b6000fc0223c3240, where `get_or_create_namespace()` is called unconditionally
https://github.com/autozimu/LanguageClient-neovim/commit/1c7a3b0d629f213457cd8f19b6000fc0223c3240#diff-27ebfa082188b80aa07414ddf00c884eR2644

Thanks for your work and let me know if I can assist further!

**Comment by autozimu** [comment]
Thanks a lot for taking time reporting!
