### ISSUE TITLE
Support windows os

### ISSUE THREAD

**Issue by wsdjeg** [autozimu/LanguageClient-neovim#971]
in the readme, it use bash to install this plugin, but it is not supported in windows os.

```
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
```

**Comment by aravind2612krishna** [comment]
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'powershell -executionpolicy bypass -File install.ps1',
    \ }

Equivalent windows script

**Comment by aravind2612krishna** [comment]
It is mentioned in the install section of Wiki

> For Windows users, replace bash install.sh with powershell -executionpolicy bypass -File install.ps1 in following snippets.

**Comment by wsdjeg** [comment]
thanks.
