### ISSUE TITLE
Lightline with LanguageClient_serverStatus()

### ISSUE THREAD

**Issue by dylanirlbeck** [autozimu/LanguageClient-neovim#975]
Is there a way to display the current status of the Language Server inside of my lightline status bar? I see a few functions like `LanguageClient_serverStatus` and `LanguageClient_statusLine` but I'm unable to configure lightline properly to use these functions. If someone could explain how to use these functions or send me their own status bar configuration I'd greatly appreciate it.

Thanks in advance!

**Comment by Kotaro7750** [comment]
`LanguageClient_serverStatus` returns whether language server is idle or busy, so if you want display information like error count, you should not use this function.
Altanatively, you can display error count by count quickfix list, like below.

```vim
function! LangugeServerStatus() abort
  let l:errors = 0
        let l:warnings = 0
        for item in getqflist()
            if item["type"] == "E"
                let l:errors += 1
            else 
              if item["type"] == "W"
                let l:warnings += 1
              endif
            endif
        endfor
        return l:errors + l:warnings == 0 ? "✔ " : "✖ :" . l:errors . " " . "⚠ :" . l:warnings
endfunction
```

But this script displays all errors of opening buffer, so when cpp file containing errors and txt file exist in buffer and you open txt file buffer, status line displays errors.

Ideal behavior is that no errors is displayed when you open txt file, so I create pull-request( #1003 ) which enables this.

I'm glad if I can help you.

**Comment by martskins** [comment]
I'll close this as it seems to be stale.
