### ISSUE TITLE
Have `completionPreferTextEdit` toggle the handling of `additional text edit`s.

### ISSUE THREAD

**Issue by martskins** [autozimu/LanguageClient-neovim#977]
This is more of a question than a feature request or a bug report. Currently, `additional text edits` from a `completionItem/resolve` call are being processed even though the `LanguageClient_completionPreferTextEdit` option is set to `0`. I think it would make sense for those text edits not to happen if the user has the option set to `0`.
Another alternative would be to add an option specifically for this, but I think it makes sense to handle that under the same flag.

So the question is, should we move [this line](https://github.com/autozimu/LanguageClient-neovim/blob/next/src/language_server_protocol.rs#L3101) inside the `if block` where we check the value of `LanguageClient_completionPreferTextEdit`?

This would be a fairly straight forward change, so if this is something that we want to see I can open a PR for it.

**Comment by autozimu** [comment]
Yes, current behavior is not expected. PR is always welcomed.

BTW, the line link has been outdated due to a recent merge. Actually GitHub support [permalink](https://help.github.com/en/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet) if you haven't aware of.

**Comment by autozimu** [comment]
Actually the original behavior is expected.

The flag is there due to completion have two different styles, insertText and TextEdit. The flag is there to allow user specify which has higher precedence when both appears.

While for additionalTextEdits, it's usually import statements due to completion. We want to apply those changes no matter which completion style is being applied. We can make this customizable if there is any valid use case, but until now none exists.

Sorry for the wrong statement I made earlier.

**Comment by martskins** [comment]
That's ok.

I would definitely appreciate being able to disable those additional text edits, I find it a little obtrusive to have vim insert import lines above me while I'm typing (usually I find it triggers on `.` after a package name), even if I need that import. This might be a due to some missing NCM2 config though, but I haven't been able to find how to stop NCM2 from doing that.

I would also argue that being able to disable user-specified LSP functions would also be nice, for the ones who want to tune it in some very specific way, but I don't know how involved this would be or what other issues it could raise.

**Comment by autozimu** [comment]
For this particular use case, maybe one flag `LanguageClient_applyCompletionAdditionalTextEdits` shall be sufficient.

**Comment by martskins** [comment]
Sounds good :+1:! Updated #978 to add that flag and use that instead to decide whether or not to apply the edits.
