### ISSUE TITLE
Disable compile checks when in insert mode or before writes

### ISSUE THREAD

**Issue by ghost** [autozimu/LanguageClient-neovim#980]
## Is your feature request related to a problem? Please describe.

I am frustrated when I am trying to write code and the language server complains that the code does not compile while I am typing. It creates a lot of visual noise that will not exist once I finish inserting my code or once I write the file.

## Describe the solution you'd like

I would like to disable the compile portions of the language server messages either while in insert mode or before a write occurs, but still get completions.

## Describe alternatives you've considered

I have yet to consider any alternatives.

## Additional context

Here is all the errors that flash across my screen as I write two lines of trivial code:

![Captura de pantalla 2020-03-04 a las 15 12 57](https://user-images.githubusercontent.com/60761092/75931921-0b098780-5e2b-11ea-80de-c1190ce15470.png)
![Captura de pantalla 2020-03-04 a las 15 13 15](https://user-images.githubusercontent.com/60761092/75931923-0c3ab480-5e2b-11ea-9388-05a339d22c3c.png)
![Captura de pantalla 2020-03-04 a las 15 13 23](https://user-images.githubusercontent.com/60761092/75931925-0cd34b00-5e2b-11ea-9ee7-f7d5a75fcef0.png)
![Captura de pantalla 2020-03-04 a las 15 13 30](https://user-images.githubusercontent.com/60761092/75931926-0d6be180-5e2b-11ea-8c53-99cc1f75ddfe.png)
![Captura de pantalla 2020-03-04 a las 15 13 37](https://user-images.githubusercontent.com/60761092/75931930-0e047800-5e2b-11ea-95ca-dc77aa4af94f.png)
![Captura de pantalla 2020-03-04 a las 15 13 48](https://user-images.githubusercontent.com/60761092/75931932-0e047800-5e2b-11ea-9aeb-69b974bdd52a.png)
![Captura de pantalla 2020-03-04 a las 15 13 54](https://user-images.githubusercontent.com/60761092/75931934-0e9d0e80-5e2b-11ea-8f10-315b8329095a.png)
![Captura de pantalla 2020-03-04 a las 15 14 02](https://user-images.githubusercontent.com/60761092/75931936-0e9d0e80-5e2b-11ea-9638-36d5620e745e.png)
![Captura de pantalla 2020-03-04 a las 15 14 10](https://user-images.githubusercontent.com/60761092/75931938-0f35a500-5e2b-11ea-8460-0e8601f83aeb.png)
![Captura de pantalla 2020-03-04 a las 15 14 15](https://user-images.githubusercontent.com/60761092/75931939-0f35a500-5e2b-11ea-86aa-0c677104babe.png)
![Captura de pantalla 2020-03-04 a las 15 14 21](https://user-images.githubusercontent.com/60761092/75931941-0f35a500-5e2b-11ea-9ea1-e03a1a35dbe8.png)
![Captura de pantalla 2020-03-04 a las 15 14 29](https://user-images.githubusercontent.com/60761092/75931942-0fce3b80-5e2b-11ea-9c78-5ae198eff28b.png)
![Captura de pantalla 2020-03-04 a las 15 14 35](https://user-images.githubusercontent.com/60761092/75931944-0fce3b80-5e2b-11ea-92dd-5b5187cfd659.png)
![Captura de pantalla 2020-03-04 a las 15 14 43](https://user-images.githubusercontent.com/60761092/75931945-0fce3b80-5e2b-11ea-9b73-f7a0ab42d1a2.png)
![Captura de pantalla 2020-03-04 a las 15 14 48](https://user-images.githubusercontent.com/60761092/75931947-1066d200-5e2b-11ea-8fdc-7d87fa8005fd.png)
![Captura de pantalla 2020-03-04 a las 15 14 57](https://user-images.githubusercontent.com/60761092/75931948-1066d200-5e2b-11ea-9cf4-2a90dab6f61e.png)

**Comment by martskins** [comment]
This should be solved by #896.

**Comment by ghost** [comment]
Closing as a duplicate of #816.

**Comment by ghost** [comment]
@martskins thanks for the patch. Is there any particular reason it is not up to date with the next branch?

**Comment by martskins** [comment]
@u24b6 not really, I haven't updated it because it has been stale for a while now, but I can rebase it if there's interest to merge it.
