### ISSUE TITLE
LS settings degugging

### ISSUE THREAD

**Issue by mkatychev** [autozimu/LanguageClient-neovim#983]
I'm having issues telling if my client settings are being picked up by the language server (`rust-analyzer`) in this case.

I was wondering if there way any sort of reflection or some way to see if my settings are being picked up by the language server.

I'm trying to get this setting to work in particular: [`rust-analyzer.rustfmtArgs`](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/package.json#L238)

Perhaps there's a setting in the documentation I missed but I'd like to see a way to debug settings that I pass to the language server itself.

With this `init.vim`:

```vim
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rust-analyzer'],
    \ }
let g:LanguageClient_settingsPath = "~/.config/nvim/settings.json"
```
I cannot get either of the `settings.json` variants below to work since `rustfmt` is not picking up my project's `rustfmt.toml` when I use `LanguageClient#textDocument_formatting_sync()`:

```json
{
  "rust-analyzer.trace.server": "verbose",
  "rust-analyzer.rustfmtArgs": [
    "+nightly"
  ]
}
```

```json
{
  "rust-analyzer": {
    "trace": {
      "server": "verbose"
    },
    "rustfmtArgs": [
      "+nightly"
    ]
  }
}
```

If I can be pointed to additional reading or possible solutions to this that would be a great help, particularly in how do I manage to tease out the settings structure for different language servers.

**Comment by martskins** [comment]
I think what you want for your `.vim/settings.json` is something like this

```
{
    "initializationOptions": {
        "trace": {
            "server": "verbose"
         }
    }
}
```

**Comment by mkatychev** [comment]
@martskins  how did you derive that setting for rust-analyzer?

**Comment by martskins** [comment]
Honestly, trial and error 😁 

I'll close this issue now since so much time has passed but feel free to re-open if you are still having issues with it.
