### ISSUE TITLE
Completion does not work since 0.1.156

### ISSUE THREAD

**Issue by liushapku** [autozimu/LanguageClient-neovim#990]
- Did you upgrade to latest plugin version? YES
- Did you upgrade to/compile latest binary? 0.1.156  Run shell command 
  `bin/languageclient --version` to get its version number.
- (Neovim users only) Did you check output of `:checkhealth LanguageClient`? YES
- Did you check [troubleshooting]? yes

[troubleshooting]: https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#6-troubleshooting

## Describe the bug
Completion does not work since commit `90e49e5` (binary version 0.1.156). I did `bash install.sh` whenever I changed commit. I uses `deoplete.nvim` as the completion engine.

There was warn message in the log: 

     WARN unnamed src/language_server_protocol.rs:2389 Failed to start language server automatically. invalid type: integer `0`, expected string or map

With the same configuration, if I checkout commit `d273439` (binary version 0.1.155, the parent of `90e49e5`) and do `bash install.sh`, the problem is gone.

PS: may I know how can I compile the binary from the src?

**Comment by martskins** [comment]
Can you share your config? I suspect this might be a dupe of #947.

To compile the binary from source just step on the folder and run `make release`, that should compile the binary in `release` mode and place the binary in the `LanguageClient-neovim/bin` folder.

**Comment by liushapku** [comment]
Thanks @martskins you are right it is the same issue. I fixed it by following [https://github.com/autozimu/LanguageClient-neovim/issues/947#issuecomment-572111189]() and setting `LanguageClient_useVirtualText` to `"No"`.

**Comment by astrolemonade** [comment]
I experience the same issue and I have no clue for solving this, I did `let LanguageClient_useVirtualText="No"` in my configuration and it does not work. I only see errors! Any help on this would be very appreciated

**Comment by martskins** [comment]
@cata0309  could you share your vimrc and maybe LCN's log output after you launch it?
