### ISSUE TITLE
Add ability to check language server status per filetype

### ISSUE THREAD

**Issue by nkakouros** [autozimu/LanguageClient-neovim#993]
## Is your feature request related to a problem? Please describe.

I want to have an icon in my status line when a language server is running
(not just idle/busy) for the file that I am currently editing.

## Describe the solution you'd like

A function or a variable that I can use to check if a language server for the
current filetype is running. Sth like `LanguageClient#status('python')`.

## Describe alternatives you've considered

I tried using what is already there but I couldn't make it work. Do you have
any tips to share?

**Comment by martskins** [comment]
This is already possible via the `b:LanguageClient_isServerRunning` variable. See #1003
