### ISSUE TITLE
Do not send textDocument/codeLens while textDocument/didOpen is still in process

### ISSUE THREAD

**Issue by cannorin** [autozimu/LanguageClient-neovim#994]
## Describe the bug

Some language servers such as [fsautocomplete](https://github.com/fsharp/FsAutoComplete/) take some time to parse the source after `textDocument/didOpen` is called.

LC-neovim tries to call `textDocument/codeLens` right after calling `textDocument/didOpen` [here](https://github.com/autozimu/LanguageClient-neovim/blob/next/src/language_server_protocol.rs#L2109) and if the server is not fast enough the code lens information is not yet available and it will return an error.

If that was the first time `textDocument/didOpen` is called, LC-neovim considers the error as that the server has failed to start. This means LC-neovim cannot be used with this kind of servers at all.

```
18:44:47 INFO unnamed src/language_server_protocol.rs:2015 Begin textDocument/codeLens
18:44:47 INFO writer-Some("fsharp") src/rpcclient.rs:215 => Some("fsharp") {"jsonrpc":"2.0","method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///private/tmp/foo/Program.fs"}},"id":2}
18:44:47 INFO reader-Some("fsharp") src/rpcclient.rs:169 <= Some("fsharp") {"jsonrpc":"2.0","id":2,"error":{"code":-32603,"message":"File '/private/tmp/foo/Program.fs' not parsed"}}
18:44:47 WARN unnamed src/language_server_protocol.rs:2794 Failed to start language server automatically. Error: Failure { jsonrpc: Some(V2), error: Error { code: InternalError, message: "File \'/private/tmp/foo/Program.fs\' not parsed", data: None }, id: Num(2) }
```

My suggestion is LC-neovim should not send `textDocument/codeLens` there and instead should do so once (LC-neovim believes) the server has finished loading the source (for example, wait until the server sends `textDocument/publishDiagnostics`).

## Environment

- neovim/vim version: arbitrary
- This plugin version: tag 0.1.156
- Language server link and version: [fsautocomplete](https://github.com/fsharp/FsAutoComplete/), latest (for example)

## To Reproduce

Open an document with a "slow" language server.

## Current behavior

LC-neovim fails to start the server.

## Expected behavior

LC-neovim starts the server successfully.

## Additional context

Ionide-vim, F# plugin for (neo)vim using LC-neovim under the hood, has stopped working after version 0.1.156 (https://github.com/ionide/Ionide-vim/issues/22).

It is confirmed that https://github.com/autozimu/LanguageClient-neovim/commit/1c7a3b0d6 is the very commit causing the issue, and it introduces a call to `self.textDocument_codeLens` into the `textDocument_didOpen` functions.

**Comment by martskins** [comment]
First of all apologies for the very very late response. I've seen this before but I wasn't as involved in the project as I am now and I didn't have a way (or didn't know how to) test this to confirm, but those things have changed now so happy to pick this up again.

Sadly, I don't think waiting for a `publishDiagnostics` event is gonna cut it, as there might be servers which don't have support for that notification and we'd be left waiting forever for it. Of course we could wait for a different one, but same logic applies.

I'm honestly not sure what the protocol says about this type of scenario, but considering how the protocol is async I would be surprised if the server was supposed to finish processing anything before receiving another request. As I said, I'm not sure if this is correct, and I'm not sure what the correct way of dealing with this would be, but I don't think the client should be tracking ordering or timing of the requests.

Maybe it's worth opening an issue on the LSP repo to see if anyone had to deal with a similar situation before?

**Comment by cannorin** [comment]
I think you can just ignore the result of `textDocument/codeLens`. The problem is that LC-neovim is assuming `textDocument/didOpen` has failed even when the server is just too slow to respond to `textDocument/codeLens`.

**Comment by martskins** [comment]
Oh I see the confusion now. The message you are getting there is because the `codeLens` request fails, but the language start has actually been successful. The fact that we're calling `text_document_did_open` and `text_document_did_change` inside `server_start` makes that message a little misleading, as one of those two may have failed and we show that the server hasn't started correctly. Which I believe is what's happening here.

I was able to correctly use `fsautocomplete` with a fix I'm about to PR here and this settings.json:

```json
{
  "initializationOptions": {
    "AutomaticWorkspaceInit": true
  }
}
```

**Comment by martskins** [comment]
@cannorin #1124 should fix that warning message.

**Comment by martskins** [comment]
Closing via #1124
